-- This file is generated by tdr. 

Ds_ResDataOperate = {} --数据操作类型
Ds_ResDataOperate.ResDataOperate_INT = 1 --固定数值
Ds_ResDataOperate.ResDataOperate_10K = 2 --万分比

Ds_ResDataSet = {} --数据操作类型
Ds_ResDataSet.RESDATASET_SET = 0 --数据覆盖
Ds_ResDataSet.RESDATASET_ADD = 1 --数据加法
Ds_ResDataSet.RESDATASET_SUB = 2 --数据减法

Ds_ATTRADDTYPE = {} --属性加成类型
Ds_ATTRADDTYPE.ATTRADD_BASE = 1 --基础属性
Ds_ATTRADDTYPE.ATTRADD_UPADD = 2 --加成属性(固定数值)
Ds_ATTRADDTYPE.ATTRADD_BASEMUL = 3 --基础属性乘法(万分比)
Ds_ATTRADDTYPE.ATTRADD_UPADDMUL = 4 --加成属性乘法(万分比)
Ds_ATTRADDTYPE.ATTRADD_ALLMUL = 5 --所有属性乘法(万分比)

Ds_ATTRDATATYPE = {} --属性数值类型
Ds_ATTRDATATYPE.ATTRDATA_HPMAX = 1 --当前最大生命值(固定值)
Ds_ATTRDATATYPE.ATTRHPDATA_HPCUR = 2 --当前生命值(固定值)
Ds_ATTRDATATYPE.ATTRHPDATA_HPLOSE = 3 --损失生命值(固定值)
Ds_ATTRDATATYPE.ATTRHPDATA_HPLOSEPRECENT = 4 --损失生命值万分比
Ds_ATTRDATATYPE.ATTRDATA_MMAX = 5 --当前最大法术值(固定值)
Ds_ATTRDATATYPE.ATTRHPDATA_MCUR = 6 --当前法术值(固定值)
Ds_ATTRDATATYPE.ATTRHPDATA_MLOSE = 7 --损失法术值(固定值)

Ds_LOGICOPTTYPE = {} --逻辑运算符
Ds_LOGICOPTTYPE.LOGICOPT_LESS = 0 --小于
Ds_LOGICOPTTYPE.LOGICOPT_LESS_EQ = 1 --小于等于
Ds_LOGICOPTTYPE.LOGICOPT_GREAT = 2 --大于
Ds_LOGICOPTTYPE.LOGICOPT_GREAT_EQ = 3 --大于等于
Ds_LOGICOPTTYPE.LOGICOPT_EQUAL = 4 --等于
Ds_LOGICOPTTYPE.LOGICOPT_NOT_EQUAL = 5 --不等于
Ds_LOGICOPTTYPE.LOGICOPT_AND = 6 --逻辑与
Ds_LOGICOPTTYPE.LOGICOPT_OR = 7 --逻辑或

Ds_RaceType = {} --种族
Ds_RaceType.RACE_NEUTRAL = 0 --中立种族
Ds_RaceType.RACE_HUMAN = 1 --人族
Ds_RaceType.RACE_ORC = 2 --兽族
Ds_RaceType.RACE_GHOST = 3 --亡灵
Ds_RaceType.RACE_ELF = 4 --精灵
Ds_RaceType.RACE_MAX = 5 --种族最大值

Ds_LegionType = {} --军团类型
Ds_LegionType.LEGION_NEUTRAL = 0 --中立军团
Ds_LegionType.LEGION_JUSTICE = 1 --正义军团
Ds_LegionType.LEGION_EVIL = 2 --邪恶军团
Ds_LegionType.LEGION_MAX = 3 --军团最大值

Ds_ResHeroCapacityType = {} --英雄能力类别
Ds_ResHeroCapacityType.ResHeroCapatyType_FIGHTER = 1 --战士
Ds_ResHeroCapacityType.ResHeroAttrType_MAGE = 2 --法师
Ds_ResHeroCapacityType.ResHeroAttrType_SUP = 3 --辅助
Ds_ResHeroCapacityType.ResHeroAttrType_SHOOTER = 4 --射手
Ds_ResHeroCapacityType.ResHeroAttrType_TANK = 5 --坦克
Ds_ResHeroCapacityType.ResHeroAttrType_MAX = 6 --Max

Ds_ResWeaponType = {} --武器类型
Ds_ResWeaponType.RESWEAPONTYPE_DISTANCE = 0 --
Ds_ResWeaponType.RESWEAPONTYPE_LONGDISTANCE = 1 --

Ds_BattleTeamType = {} --队伍类型
Ds_BattleTeamType.WHITE = 0 --白方队伍
Ds_BattleTeamType.RED = 1 --红方队伍
Ds_BattleTeamType.BLUE = 2 --蓝方队伍
Ds_BattleTeamType.PURPLE = 3 --紫方队伍
Ds_BattleTeamType.GREEN = 4 --绿方队伍
Ds_BattleTeamType.PINK = 5 --粉方队伍
Ds_BattleTeamType.YELLOW = 6 --黄方队伍
Ds_BattleTeamType.TEAM_MAX = 7 --队伍数量

Ds_TeamLegionType = {} --阵营类型
Ds_TeamLegionType.LEGION_FRIEND = 0 --阵营友军
Ds_TeamLegionType.LEGION_ENEMY = 1 --阵营敌军
Ds_TeamLegionType.LEGION_ALLL = 2 --所有阵营单位

Ds_BattleActorType = {} --单位类型
Ds_BattleActorType.COMMON = 0 --普通单位
Ds_BattleActorType.HERO = 1 --英雄
Ds_BattleActorType.DOGFACE = 2 --士兵
Ds_BattleActorType.MONSTER = 3 --野怪
Ds_BattleActorType.TOWER = 4 --防御塔
Ds_BattleActorType.GOLDMINE = 5 --金矿
Ds_BattleActorType.BASE = 6 --基地
Ds_BattleActorType.SUBBASE = 7 --副基地
Ds_BattleActorType.STASISTRAP = 8 --静止陷阱
Ds_BattleActorType.SCENEOBJECT = 9 --场景物件
Ds_BattleActorType.ACTORPET = 10 --跟宠
Ds_BattleActorType.MECHINE = 11 --机械单位
Ds_BattleActorType.TRANSFERDOOR = 12 --场景传送门
Ds_BattleActorType.ACTORTYPE_MAX = 13 --MAX

Ds_BattleActorSubType = {} --单位子类型
Ds_BattleActorSubType.SUBTYPE_NONE = 0 --无类型
Ds_BattleActorSubType.SUBTYPE_TECHDOGFACE = 1 --科技建造士兵
Ds_BattleActorSubType.SUBTYPE_CHARMDOGFACE = 2 --魅惑符咒士兵
Ds_BattleActorSubType.SUBTYPE_WILD_SPRING = 3 --野外泉水
Ds_BattleActorSubType.SUBTYPE_HPMP_RUNE = 4 --回血蓝符
Ds_BattleActorSubType.SUBTYPE_BIGDRAGON = 5 --野怪精英_大龙
Ds_BattleActorSubType.SUBTYPE_SMALLDRAGON = 6 --野怪精英_小龙
Ds_BattleActorSubType.SUBTYPE_WARD = 7 --侦查守卫
Ds_BattleActorSubType.SUBTYPE_RELIFE = 8 --治疗守卫
Ds_BattleActorSubType.SUBTYPE_SUMMONEDBIGDRAGON = 9 --大龙召唤物
Ds_BattleActorSubType.SUBTYPE_HEROTRAP = 10 --英雄技能陷阱
Ds_BattleActorSubType.SUBTYPE_TEAMGROUPGHOST = 11 --队伍灵魂控制者
Ds_BattleActorSubType.SUBTYPE_BIGTITAN = 12 --野怪精英_泰坦
Ds_BattleActorSubType.SUBTYPE_SMALLTITAN = 13 --野怪精英_小泰坦

Ds_BattleActorSummonedType = {} --召唤物类型
Ds_BattleActorSummonedType.BATTLEACTORSUMMONEDTYPE_NONE = 0 --非召唤物
Ds_BattleActorSummonedType.BATTLEACTORSUMMONEDTYPE_CREATURES = 1 --生物召唤物
Ds_BattleActorSummonedType.BATTLEACTORSUMMONEDTYPE_STILL = 2 --静止召唤物
Ds_BattleActorSummonedType.BATTLEACTORSUMMONEDTYPE_CHARM = 3 --魅惑符咒召唤物(不可驱散)

Ds_BattleDeadBodyType = {} --尸体类型
Ds_BattleDeadBodyType.BATTLEDEADBODYTYOE_ACTOR = 0 --单位死亡尸体
Ds_BattleDeadBodyType.BATTLEDEADBODYTYOE_CARRY = 1 --载具召唤尸体
Ds_BattleDeadBodyType.BATTLEDEADBODYTYOE_UDSPAWN = 2 --腐地召唤尸体

Ds_BattleRusult = {} --战斗结果类型
Ds_BattleRusult.RESULT_NONE = 0 --无结果
Ds_BattleRusult.JUSTICE_WIN = 1 --正义胜利
Ds_BattleRusult.EVIL_WIN = 2 --邪恶胜利
Ds_BattleRusult.NO_WIN = 3 --平局

Ds_ArmorType = {} --护甲类型
Ds_ArmorType.ARMORTYPE_LIGHT = 0 --轻型护甲
Ds_ArmorType.ARMORTYPE_MIDDLE = 1 --中型护甲
Ds_ArmorType.ARMORTYPE_HEAVY = 2 --重型护甲
Ds_ArmorType.ARMORTYPE_CITY = 3 --城型护甲
Ds_ArmorType.ARMORTYPE_HERO = 4 --英雄护甲
Ds_ArmorType.ARMORTYPE_BUILDING = 5 --建筑建造中护甲

Ds_SkillAttackType = {} --攻击类型
Ds_SkillAttackType.ATTACK_TYPR_NONE = 0 --攻击类型_无
Ds_SkillAttackType.ATTACK_TYPR_NORMAL = 1 --攻击类型_普通
Ds_SkillAttackType.ATTACK_TYPR_INSERT = 2 --攻击类型_穿刺
Ds_SkillAttackType.ATTACK_TYPR_ENERGY = 3 --攻击类型_能量
Ds_SkillAttackType.ATTACK_TYPR_CITY = 4 --攻击类型_攻城
Ds_SkillAttackType.ATTACK_TYPR_HERO = 5 --攻击类型_英雄
Ds_SkillAttackType.ATTACK_TYPR_GOD = 6 --攻击类型_神圣
Ds_SkillAttackType.ATTACK_TYPR_MAX = 7 --攻击类型_max

Ds_SpeedType = {} --速度类型
Ds_SpeedType.SPEED_NONE = 0 --无速度
Ds_SpeedType.SPEED_FAST = 1 --快
Ds_SpeedType.SPEED_MIDDLE = 2 --中
Ds_SpeedType.SPEED_SLOW = 3 --慢

Ds_ResFogViewType = {} --迷雾视野类型
Ds_ResFogViewType.RESFOGVIEWTYPE_GROUND = 0 --迷雾视野_地面
Ds_ResFogViewType.RESFOGVIEWTYPE_AIR = 1 --迷雾视野_高空

Ds_AIAttackType = {} --AI攻击类型
Ds_AIAttackType.AIATKTYPE_AUTO = 0 --主动攻击AI
Ds_AIAttackType.AIATKTYPE_PASSIVE = 1 --被动攻击AI
Ds_AIAttackType.AIATKTYPE_STATICAUTO = 2 --静止攻击AI,视野小半径，触发打开AI

Ds_ActorDeadTrigEventType = {} --死亡触发事件类型
Ds_ActorDeadTrigEventType.ACTORDEADTRIGEVENT_SPAWNDOGFACE = 1 --死亡基地刷小兵
Ds_ActorDeadTrigEventType.ACTORDEADTRIGEVENT_MAPSPAWNGROUP = 2 --地图孵化一组怪物
Ds_ActorDeadTrigEventType.ACTORDEADTRIGEVENT_KILLERADDBUFF = 3 --死亡给目标方增加BUFF

Ds_KillerTargetType = {} --击杀者作用对象类型
Ds_KillerTargetType.SKILLERTARGETTYPE_SELF = 1 --击杀者自身
Ds_KillerTargetType.SKILLERTARGETTYPE_TEAMHERO = 2 --击杀者队伍所有英雄
Ds_KillerTargetType.SKILLERTARGETTYPE_LEGIONHERO = 3 --击杀者阵营所有英雄
Ds_KillerTargetType.SKILLERTARGETTYPE_LEGIONALL = 4 --击杀者阵营所有英雄和士兵

Ds_ResActorMoveType = {} --单位移动类型
Ds_ResActorMoveType.ACTORMOVETYPE_GROUND = 0 --地面移动单位
Ds_ResActorMoveType.ACTORMOVETYPE_AIR = 1 --空中移动单位

Ds_ResActrorAITargetType = {} --AI优先攻击目标类型
Ds_ResActrorAITargetType.ACTORAITARGETTYPE_ALL = 0 --AI目标_任意单位
Ds_ResActrorAITargetType.ACTORAITARGETTYPE_NONE = 1 --AI目标_无单位
Ds_ResActrorAITargetType.ACTORAITARGETTYPE_ENEMYHERO = 2 --AI目标_敌方英雄
Ds_ResActrorAITargetType.ACTORAITARGETTYPE_ENEMYDOGFACE = 3 --AI目标_敌方士兵
Ds_ResActrorAITargetType.ACTORAITARGETTYPE_ENEMYBUILD = 4 --AI目标_敌方建筑,统称
Ds_ResActrorAITargetType.ACTORAITARGETTYPE_MONSTER = 5 --AI目标_野怪
Ds_ResActrorAITargetType.ACTORAITARGETTYPE_SUMMONED = 6 --AI目标_召唤生物
Ds_ResActrorAITargetType.ACTORAITARGETTYPE_MAX = 7 --AI目标_最大值

Ds_ResAttrType = {} --属性类型
Ds_ResAttrType.EN_ATTR_MIN = 0 --属性最小值
Ds_ResAttrType.EN_ATTR_HP = 1 --生命值(计算后)
Ds_ResAttrType.EN_ATTR_MAX_HP = 2 --最大生命值
Ds_ResAttrType.EN_ATTR_HP_RECOVERY = 3 --生命回复/5s
Ds_ResAttrType.EN_ATTR_HP_RECOVERY_RATE = 4 --生命回复率(万分比/5s)
Ds_ResAttrType.EN_ATTR_MAX_MP = 5 --最大法术值
Ds_ResAttrType.EN_ATTR_MP = 6 --法术值(计算后)
Ds_ResAttrType.EN_ATTR_MP_RECOVER = 7 --法术回复/5s
Ds_ResAttrType.EN_ATTR_ATK = 8 --攻击力
Ds_ResAttrType.EN_ATTR_ARMOR = 9 --护甲值
Ds_ResAttrType.EN_ATTR_ARMOR_PIERCE = 10 --护甲穿透
Ds_ResAttrType.EN_ATTR_ARMOR_PIERCE_RATE = 11 --护甲穿透率(万分比)
Ds_ResAttrType.EN_ATTR_ATK_SPEED = 12 --攻击速度(1万代表1s)
Ds_ResAttrType.EN_ATTR_ATK_STEAL_RATE = 13 --生命偷取率(万分比)
Ds_ResAttrType.EN_ATTR_CRI_RATE = 14 --暴击率(万分比)
Ds_ResAttrType.EN_ATTR_CRI_DAM_RATE = 15 --暴击伤害率(万分比)
Ds_ResAttrType.EN_ATTR_MAGIC = 16 --法术强度
Ds_ResAttrType.EN_ATTR_MAGIC_DEF = 17 --法术抗性
Ds_ResAttrType.EN_ATTR_MD_PIERCE = 18 --法术穿透
Ds_ResAttrType.EN_ATTR_MD_PIERCE_RATE = 19 --法术穿透率(万分比)
Ds_ResAttrType.EN_ATTR_AP_STEAL_RATE = 20 --法术吸血率(万分比)
Ds_ResAttrType.EN_ATTR_TENACITY_RATE = 21 --韧性率(万分比)
Ds_ResAttrType.EN_ATTR_CD_REDUCTION = 22 --冷却缩减(万分比)
Ds_ResAttrType.EN_ATTR_MOVE_SPEED = 23 --移动速度(1万代表1M)
Ds_ResAttrType.EN_ATTR_EVASION_RATE = 24 --闪避值(万分比)
Ds_ResAttrType.EN_ATTR_MAX_HP_LV = 25 --生命值成长
Ds_ResAttrType.EN_ATTR_HP_RECOVER_LV = 26 --生命回复成长(/5s)
Ds_ResAttrType.EN_ATTR_ATK_LV = 27 --攻击力成长
Ds_ResAttrType.EN_ATTR_MAGIC_LV = 28 --法术强度成长
Ds_ResAttrType.EN_ATTR_ARMOR_LV = 29 --护甲成长
Ds_ResAttrType.EN_ATTR_MAGIC_DEF_LV = 30 --法术抗性成长
Ds_ResAttrType.EN_ATTR_MAX_MP_LV = 31 --法术值成长
Ds_ResAttrType.EN_ATTR_MP_RECOVER_LV = 32 --法术值回复成长(/5s)
Ds_ResAttrType.EN_ATTR_REB_DAMAGE = 33 --反弹值
Ds_ResAttrType.EN_ATTR_REB_DAMAGE_RATE = 34 --反伤率(万分比)
Ds_ResAttrType.EN_ATTR_ATKMISS_RATE = 35 --攻击丢失率(万分比)
Ds_ResAttrType.EN_ATTR_COLLIDERRADIUS = 36 --碰撞体积
Ds_ResAttrType.EN_ATTR_VISIONRADIUS = 37 --视野半径
Ds_ResAttrType.EN_ATTR_WARNRADIUS = 38 --警戒半径
Ds_ResAttrType.EN_ATTR_FOWRADIUS = 39 --迷雾半径
Ds_ResAttrType.EN_ATTR_MAGIC_ATK_IMM = 40 --物理伤害减免
Ds_ResAttrType.EN_ATTR_MAGIC_MGIC_IMM = 41 --法术伤害减免
Ds_ResAttrType.EN_ATTR_ATK_DMG_RATE = 42 --物理伤害百分比(万分比,计算完后)
Ds_ResAttrType.EN_ATTR_AP_DMG_RATE = 43 --法术伤害百分比(万分比,计算完后)
Ds_ResAttrType.EN_ATTR_ATK_GET_DMG_RATE = 44 --受到物理伤害率(万分比,计算完后)
Ds_ResAttrType.EN_ATTR_AP_GET_DMG_RATE = 45 --受到法术伤害率(万分比,计算完后)
Ds_ResAttrType.EN_ATTR_NORMALDMG_IMM = 46 --被普通攻击伤害减免值
Ds_ResAttrType.EN_ATTR_NORMALDMG_IMM_RATE = 47 --被普通攻击伤害减免率(万分比)
Ds_ResAttrType.EN_ATTR_FARNORMALDMG_IMM_RATE = 48 --被远程普通攻击伤害减免率(万分比)
Ds_ResAttrType.EN_ATTR_MONSTERDMG_ADD = 49 --对野怪伤害加成值
Ds_ResAttrType.EN_ATTR_MONSTERDMG_ADD_COE = 50 --对野怪伤害加成系数(万分比)
Ds_ResAttrType.EN_ATTR_AI_ATKDMG_COE = 51 --AI攻击伤害系数
Ds_ResAttrType.EN_ATTR_AI_DEFDMG_COE = 52 --AI防御伤害系数
Ds_ResAttrType.EN_ATTR_BUILDING_COE = 53 --对建筑伤害系数(万分比,计算完后)
Ds_ResAttrType.EN_ATTR_BUILDING_BECOE = 54 --被建筑伤害系数(万分比,计算完后)
Ds_ResAttrType.EN_ATTR_BUFFRESTADD_CORE = 55 --BUFF回属性加成系数
Ds_ResAttrType.EN_ATTR_BASERECOVERYADD_CORE = 56 --基础回复加成系数
Ds_ResAttrType.EN_ATTR_NSATKDIS_ADD = 57 --普攻半径加成
Ds_ResAttrType.EN_ATTR_MAX = 58 --最大值

Ds_BuffPropertyType = {} --BUFF属性类型
Ds_BuffPropertyType.BUFFPROPERTYTYPE_TALENT = 1 --天赋BUFF
Ds_BuffPropertyType.BUFFPROPERTYTYPE_SYSTEM = 2 --系统BUFF
Ds_BuffPropertyType.BUFFPROPERTYTYPE_USEFUL = 3 --数值增益BUFF
Ds_BuffPropertyType.BUFFPROPERTYTYPE_UNUSEFUL = 4 --数值减益BUFF
Ds_BuffPropertyType.BUFFPROPERTYTYPE_HARMFUL = 5 --控制BUFF
Ds_BuffPropertyType.BUFFPROPERTYTYPE_UNHARMFUL = 6 --免疫控制BUFF
Ds_BuffPropertyType.BUFFPROPERTYTYPE_TRIGSKILL = 7 --触发技能BUFF
Ds_BuffPropertyType.BUFFPROPERTYTYPE_TRIGBUFF = 8 --触发BUFF
Ds_BuffPropertyType.BUFFPROPERTYTYPE_GODBUFF = 9 --上帝BUFF

Ds_BuffPropertySubType = {} --BUFF属性子类型
Ds_BuffPropertySubType.BUFFPROPERTYSUBTYPE_SWIM = 1 --眩晕类子类型
Ds_BuffPropertySubType.BUFFPROPERTYSUBTYPE_DELSPEED = 2 --减速类子类型
Ds_BuffPropertySubType.BUFFPROPERTYSUBTYPE_SILENT = 3 --沉默类子类型
Ds_BuffPropertySubType.BUFFPROPERTYSUBTYPE_BEATBACK = 4 --击飞击退类子类型
Ds_BuffPropertySubType.BUFFPROPERTYSUBTYPE_XSPACE = 5 --X空间类子类型
Ds_BuffPropertySubType.BUFFPROPERTYSUBTYPE_MPOP = 6 --法术值增减益子类型

Ds_BuffMergeType = {} --BUFF叠加规则
Ds_BuffMergeType.BUFFERMERGRES_NONE = 0 --无法合并
Ds_BuffMergeType.BUFFERMERGRES_CASTERSTACK = 1 --BUFF堆叠(施法者)
Ds_BuffMergeType.BUFFERMERGRES_GROUPSTACK = 2 --BUFF堆叠(组ID)
Ds_BuffMergeType.BUFFERMERGRES_CASTERREPLACE = 3 --替换旧的BUFF（同一施法者，高等级替换低等级，同等级刷数据）
Ds_BuffMergeType.BUFFERMERGRES_CASTERMUTEX = 4 --新Buff被排斥(施法者)
Ds_BuffMergeType.BUFFERMERGRES_GROUPIDMUTEX = 5 --新Buff被排斥(组ID)
Ds_BuffMergeType.BUFFERMERGRES_GROUPIDREPLACE = 6 --替换旧的BUFF（只按组ID）
Ds_BuffMergeType.BUFFERMERGRES_UNCASTERREPLACE = 7 --不同施法者并行BUFF,同一施法者替换旧的BUFF,不同施法者无法合并但是生效

Ds_BuffOp = {} --BUFF操作类型
Ds_BuffOp.BUFF_OP_ADD = 1 --添加buff操作
Ds_BuffOp.BUFF_OP_DEL = 2 --移除buff操作
Ds_BuffOp.BUFF_OP_OVERLAY = 3 --覆盖buff操作
Ds_BuffOp.BUFF_OP_INTERRUPT = 4 --中断buff操作

Ds_BuffRemoveType = {} --BUFF外部移除类型
Ds_BuffRemoveType.BUFFREMOVETYPE_DEFUALT = 0 --任意移除Buff
Ds_BuffRemoveType.BUFFREMOVETYPE_DEAD = 1 --死亡移除Buff
Ds_BuffRemoveType.BUFFREMOVETYPE_GOD = 2 --上帝移除Buff

Ds_BuffEndType = {} --BUFF结束类型
Ds_BuffEndType.BUFFENDTYPE_ENC = 0 --Buff自然结束
Ds_BuffEndType.BUFFENDTYPE_BECLEAR = 1 --Buff被动清除
Ds_BuffEndType.BUFFENDTYPE_DEADCLEAR = 2 --Buff死亡清除

Ds_BuffEffectType = {} --Buff效果类型
Ds_BuffEffectType.BUFFEFFECTTYPE_ATTROPE = 1 --属性修改
Ds_BuffEffectType.BUFFEFFECTTYPE_SETATTR = 2 --回属性
Ds_BuffEffectType.BUFFEFFECTTYPE_SPRINGSETATTR = 3 --泉水回属性
Ds_BuffEffectType.BUFFEFFECTTYPE_DMGABSORB = 4 --吸收伤害
Ds_BuffEffectType.BUFFEFFECTTYPE_SWIM = 5 --眩晕
Ds_BuffEffectType.BUFFEFFECTTYPE_SILENT = 6 --沉默
Ds_BuffEffectType.BUFFEFFECTTYPE_DRAG = 7 --拉扯
Ds_BuffEffectType.BUFFEFFECTTYPE_BEATBACK = 8 --击飞击退
Ds_BuffEffectType.BUFFEFFECTTYPE_SNEER = 9 --嘲讽
Ds_BuffEffectType.BUFFEFFECTTYPE_FEAR = 10 --恐惧效果
Ds_BuffEffectType.BUFFEFFECTTYPE_CYCLONE = 11 --龙卷风效果
Ds_BuffEffectType.BUFFEFFECTTYPE_PHYIMM = 12 --物理免疫
Ds_BuffEffectType.BUFFEFFECTTYPE_MGCIMM = 13 --魔法免疫
Ds_BuffEffectType.BUFFEFFECTTYPE_GOD = 14 --无敌
Ds_BuffEffectType.BUFFEFFECTTYPE_DELBUFF = 15 --清除BUFF
Ds_BuffEffectType.BUFFEFFECTTYPE_IMMDELBUFF = 16 --免疫DEBUFF
Ds_BuffEffectType.BUFFEFFECTTYPE_SUPERBODY = 17 --霸体BUFF
Ds_BuffEffectType.BUFFEFFECTTYPE_XSPACE = 18 --进入X空间
Ds_BuffEffectType.BUFFEFFECTTYPE_GOLDENBODY = 19 --BUFF金身
Ds_BuffEffectType.BUFFEFFECTTYPE_ADDAVATARSKILL = 20 --触发变体技能
Ds_BuffEffectType.BUFFEFFECTTYPE_DELAVATARSKILL = 21 --解除变体技能
Ds_BuffEffectType.BUFFEFFECTTYPE_FOEVERATTROPE = 22 --永久修改属性
Ds_BuffEffectType.BUFFEFFECTTYPE_CLEARSKILCASTCNT = 23 --清空技能释放次数
Ds_BuffEffectType.BUFFEFFECTTYPE_ADDSKILL = 24 --触发添加技能
Ds_BuffEffectType.BUFFEFFECTTYPE_TRIGSKILLPHASE_EFFECT = 25 --触发技能阶段效果
Ds_BuffEffectType.BUFFEFFECTTYPE_TRIGSKILLPHASE_SERACHEFFECT = 26 --触发技能阶段搜索和效果
Ds_BuffEffectType.BUFFEFFECTTYPE_ADDGOLD = 27 --BUFF增加金钱
Ds_BuffEffectType.BUFFEFFECTTYPE_ADDEXP = 28 --BUFF增加经验
Ds_BuffEffectType.BUFFEFFECTTYPE_BLINDNESS = 29 --烟幕失明效果
Ds_BuffEffectType.BUFFEFFECTTYPE_SUMMONEDLIFETIME = 30 --BUFF修改召唤物存活时间
Ds_BuffEffectType.BUFFEFFECTTYPE_SOULFETTER = 31 --灵魂锁链
Ds_BuffEffectType.BUFFEFFECTTYPE_NETTRAP = 32 --撒网诱捕
Ds_BuffEffectType.BUFFEFFECTTYPE_TPCHAT = 33 --回城吟唱
Ds_BuffEffectType.BUFFEFFECTTYPE_STEALTH = 34 --BUFF隐身
Ds_BuffEffectType.BUFFEFFECTTYPE_ANTISTEALTH = 35 --BUFF反隐身
Ds_BuffEffectType.BUFFEFFECTTYPE_TARGETVISION = 36 --BUFF目标视野
Ds_BuffEffectType.BUFFEFFECTTYPE_CHANGEAVATAR = 37 --BUFF变身
Ds_BuffEffectType.BUFFEFFECTTYPE_ATKCRI = 38 --BUFF普攻暴击
Ds_BuffEffectType.BUFFEFFECTTYPE_FLIMSYBURYING = 39 --BUFF薄葬
Ds_BuffEffectType.BUFFEFFECTTYPE_POLYMORPH = 40 --BUFF变形术
Ds_BuffEffectType.BUFFEFFECTTYPE_IMPRISON = 41 --BUFF禁锢
Ds_BuffEffectType.BUFFEFFECTTYPE_LIGHTGIRLFRIEND = 42 --BUFF光之女圈内友军(定制)
Ds_BuffEffectType.BUFFEFFECTTYPE_LIGHTGIRLENEMY = 43 --BUFF光之女圈内敌军(定制)
Ds_BuffEffectType.BUFFEFFECTTYPE_DMGTOTRANSFER = 44 --BUFF伤害转移
Ds_BuffEffectType.BUFFEFFECTTYPE_DMGNUMB = 45 --BUFF伤害麻木(船长船游)
Ds_BuffEffectType.BUFFEFFECTTYPE_DIVINESHIELD = 46 --圣盾(无敌但能被选中)
Ds_BuffEffectType.BUFFEFFECTTYPE_SPELLSHIELD = 47 --BUFF魔法护盾
Ds_BuffEffectType.BUFFEFFECTTYPE_MAX = 48 --Buff效果最大值

Ds_BuffEffectAddExpGoldType = {} --BUFF增加经验金钱类型
Ds_BuffEffectAddExpGoldType.BUFFEFFADDEXPMONEYTYPE_DEFAULT = 0 --BUFF固定数值增加
Ds_BuffEffectAddExpGoldType.BUFFEFFADDEXPMONEYTYPE_GAMETIME = 1 --BUFF游戏时间增加

Ds_BuffEffectRemoveBuffType = {} --BUFF效果清除BUFF类型
Ds_BuffEffectRemoveBuffType.BUFFEFFCTREMOVEBUFFTYPE_GROUPID = 0 --根据BUFF组清除BUFF
Ds_BuffEffectRemoveBuffType.BUFFEFFCTREMOVEBUFFTYPE_BUFFTYPE = 1 --根据BUFF类型清除BUFF
Ds_BuffEffectRemoveBuffType.BUFFEFFCTREMOVEBUFFTYPE_SUBBUFFTYPE = 2 --根据BUFF子类型清除BUFF

Ds_BuffEftSetAttrType = {} --BUFF回属性参数
Ds_BuffEftSetAttrType.BUFFSETATTRPARAM_HP = 1 --回属性HP
Ds_BuffEftSetAttrType.BUFFSETATTRPARAM_MP = 2 --回属性MP
Ds_BuffEftSetAttrType.BUFFSETATTRPARAM_ENERGY = 3 --回属性怒气

Ds_BuffEffectCoefType = {} --BUFF效果作用系数类型
Ds_BuffEffectCoefType.BUFFEFFECTCOEFTYPE_DEFAULT = 0 --BUFF效默认效果系数
Ds_BuffEffectCoefType.BUFFEFFECTCOEFTYPE_HEROLEVEL = 1 --BUFF效果施法者等级系数

Ds_BuffEftBeatBackType = {} --BUFF效果击飞击退类型
Ds_BuffEftBeatBackType.BUFFBEATBACKTYPE_CASTER = 0 --击飞击退_施法者
Ds_BuffEftBeatBackType.BUFFBEATBACKTYPE_SKILLPOS = 1 --击飞击退_技能目标点(对点释放)
Ds_BuffEftBeatBackType.BUFFBEATBACKTYPE_CASTERFIXEDDISTANCE = 2 --击飞击退_施法者固定距离(动态计算VEC/ACC)

Ds_BuffEffectTrigType = {} --BUFF效果生效条件
Ds_BuffEffectTrigType.BUFFTRIGTYPE_TIME = 0 --BUFF效果时间周期生效
Ds_BuffEffectTrigType.BUFFTRIGTYPE_DEAD = 1 --死亡生效
Ds_BuffEffectTrigType.BUFFTRIGTYPE_NORMALEACHHIT = 2 --普通攻击命中单个生效
Ds_BuffEffectTrigType.BUFFTRIGTYPE_CASTSKILL = 3 --释放技能生效
Ds_BuffEffectTrigType.BUFFTRIGTYPE_CASTNORMALSKILL = 4 --释放普攻技能生效
Ds_BuffEffectTrigType.BUFFTRIGTYPE_CASTSKILLROLLEND = 5 --释放技能前摇结束生效
Ds_BuffEffectTrigType.BUFFTRIGTYPE_BEHIT = 6 --被伤害生效
Ds_BuffEffectTrigType.BUFFTRIGTYPE_BEHITCRI = 7 --被伤害暴击生效
Ds_BuffEffectTrigType.BUFFTRIGTYPE_KILLACTOR = 8 --击杀单位生效
Ds_BuffEffectTrigType.BUFFTRIGTYPE_CASTSKILLCNT = 9 --指定技能释放次数生效(技能前摇完)
Ds_BuffEffectTrigType.BUFFTRIGTYPE_BECRITHIT = 10 --被致命一击生效
Ds_BuffEffectTrigType.BUFFTRIGTYPE_NORMALHIT = 11 --普通攻击命中生效
Ds_BuffEffectTrigType.BUFFTRIGTYPE_SPECQWERSKILLHIT = 12 --被特定单位QWER伤害生效
Ds_BuffEffectTrigType.BUFFTRIGTYPE_SPECACTORNORMALSKILLHIT = 13 --被特定单位普攻伤害生效
Ds_BuffEffectTrigType.BUFFTRIGTYPE_BUFFOVERLAY = 14 --当前Buff堆叠生效

Ds_BuffEventType = {} --BUFF事件类型
Ds_BuffEventType.BUFFEVENTTYPE_REMOVESELF = 1 --当前BUFF移除
Ds_BuffEventType.BUFFEVENTTYPE_LAYERCHANGE = 2 --当前BUFF层级改变
Ds_BuffEventType.BUFFEVENTTYPE_LAYERRESET = 3 --当前BUFF层级重置
Ds_BuffEventType.BUFFEVENTTYPE_CASTBUFF = 4 --当前BUFF释放BUFF
Ds_BuffEventType.BUFFEVENTTYPE_REDAMAGE = 5 --当前BUFF反弹伤害
Ds_BuffEventType.BUFFEVENTTYPE_DMGNUMBEND = 6 --当前BUFF伤害麻木触发
Ds_BuffEventType.BUFFEVENTTYPE_FEEDBACKCASTER = 7 --当前BUFF反馈施法者

Ds_BuffEventTrigType = {} --BUFF事件触发类型
Ds_BuffEventTrigType.BUFFEVENTTRIGTYPE_BEDAMAGE = 1 --受到伤害触发BUFF事件
Ds_BuffEventTrigType.BUFFEVENTTRIGTYPE_DMGTARGET = 2 --对目标造成伤害触发BUFF事件
Ds_BuffEventTrigType.BUFFEVENTTRIGTYPE_SKILLCASTCNT = 3 --技能释放次数触发BUFF事件
Ds_BuffEventTrigType.BUFFEVENTTRIGTYPE_NORMALSKILLHIT = 4 --普通攻击命中触发BUFF事件
Ds_BuffEventTrigType.BUFFEVENTTRIGTYPE_ATTRHPCHANGE = 5 --生命值改变触发BUFF事件
Ds_BuffEventTrigType.BUFFEVENTTRIGTYPE_BENORMALSKILLDAMAGE = 6 --受到普攻伤害触发BUFF事件
Ds_BuffEventTrigType.BUFFEVENTTRIGTYPE_BENOPHYDAMAGE = 7 --受到物理伤害触发BUFF事件
Ds_BuffEventTrigType.BUFFEVENTTRIGTYPE_STEALUNIONS = 8 --隐身移除事件集合事件,攻击,被伤害，建造，使用道具
Ds_BuffEventTrigType.BUFFEVENTTRIGTYPE_BMSTEALUNIONS = 9 --剑圣隐身移除事件集合事件,攻击,建造，使用道具
Ds_BuffEventTrigType.BUFFEVENTTRIGTYPE_NORMALSKILLREDAMGE = 10 --受普通攻击触发反弹BUFF事件
Ds_BuffEventTrigType.BUFFEVENTTRIGTYPE_CHANGEDAY = 11 --切换到白天触发BUFF事件
Ds_BuffEventTrigType.BUFFEVENTTRIGTYPE_ELFTALENTBUFFREMOVE = 12 --精灵族通用天赋BUFF移除事件
Ds_BuffEventTrigType.BUFFEVENTTRIGTYPE_SPELLFIELDDO = 13 --魔法护盾抵消触发BUFF事件
Ds_BuffEventTrigType.BUFFEVENTTRIGTYPE_CASTQWERSKILL = 14 --释放QWER技能触发BUFF事件
Ds_BuffEventTrigType.BUFFEVENTTRIGTYPE_BUFFTRIG = 15 --当前BUFF生效触发BUFF事件
Ds_BuffEventTrigType.BUFFEVENTTRIGTYPE_BUFFEND = 16 --当前BUFF结束触发BUFF事件

Ds_BuffEventEffectType = {} --BUFF事件效果系数
Ds_BuffEventEffectType.BUFFEVENTEFFECTTYPE_HP = 1 --BUFF事件生命值效果系数

Ds_BuffEventFeedBackCaterType = {} --BUFF反馈施法者类型
Ds_BuffEventFeedBackCaterType.BUFFEVENTFEEDBACKCATERTYPE_MANAFLARE = 1 --BUFF事件反馈施法者_技能魔法闪耀
Ds_BuffEventFeedBackCaterType.BUFFEVENTFEEDBACKCATERTYPE_ADDBUFF = 2 --BUFF事件反馈施法者_添加BUFF
Ds_BuffEventFeedBackCaterType.BUFFEVENTFEEDBACKCATERTYPE_SKILL = 3 --BUFF事件反馈施法者_技能反馈

Ds_SkillType = {} --技能类型
Ds_SkillType.SKILLTYPE_NORMAL = 1 --普通攻击
Ds_SkillType.SKILLTYPE_AUTO = 2 --主动技能
Ds_SkillType.SKILLTYPE_AUTO2 = 3 --主动二段技能
Ds_SkillType.SKILLTYPE_AUTO3 = 4 --主动三段技能
Ds_SkillType.SKILLTYPE_SWITCH = 5 --主动开关技能(一个需设置技能栏一个无)
Ds_SkillType.SKILLTYPE_PASSIVE = 6 --被动技能

Ds_SkillSubType = {} --技能子类型
Ds_SkillSubType.SKILLSUBTYPE_NORMALATTACK = 1 --普通技能
Ds_SkillSubType.SKILLSUBTYPE_ATTACK = 2 --攻击技能
Ds_SkillSubType.SKILLSUBTYPE_SUBBUFF = 3 --辅助BUFF技能
Ds_SkillSubType.SKILLSUBTYPE_SUBRESHP = 4 --辅助回血技能
Ds_SkillSubType.SKILLSUBTYPE_RESHP = 5 --基础回血技能
Ds_SkillSubType.SKILLSUBTYPE_TP = 6 --基础回程技能
Ds_SkillSubType.SKILLSUBTYPE_AVATAR = 7 --变体技能
Ds_SkillSubType.SKILLSUBTYPE_SUMMONED = 8 --召唤师技能
Ds_SkillSubType.SKILLSUBTYPE_POSTRANSFORM = 9 --基础传送技能
Ds_SkillSubType.SKILLSUBTYPE_SELFREVIVAL = 10 --重生复活技能，复活自身
Ds_SkillSubType.SKILLSUBTYPE_SUMMONREVIVAL = 11 --召唤复活技能，复活他人
Ds_SkillSubType.SKILLSUBTYPE_ENERGY = 12 --充能技能

Ds_SkillAICastType = {} --AI释放技能类型
Ds_SkillAICastType.SKILLAICASTTYPE_REHP = 1 --AI技能类型_治疗
Ds_SkillAICastType.SKILLSUBTYPE_CTR = 2 --AI技能类型_控制
Ds_SkillAICastType.SKILLSUBTYPE_USEFUL = 3 --AI技能类型_增益
Ds_SkillAICastType.SKILLSUBTYPE_UNUSEFUL = 4 --AI技能类型_减益
Ds_SkillAICastType.SKILLSUBTYPE_DMG = 5 --AI技能类型_伤害

Ds_SkillBarType = {} --技能栏位类型
Ds_SkillBarType.SKILLBARTYPE_NONE = 0 --技能栏无
Ds_SkillBarType.SKILLBARTYPE_Q = 1 --技能栏Q
Ds_SkillBarType.SKILLBARTYPE_W = 2 --技能栏W
Ds_SkillBarType.SKILLBARTYPE_E = 3 --技能栏E
Ds_SkillBarType.SKILLBARTYPE_R = 4 --技能栏R
Ds_SkillBarType.SKILLBARTYPE_A = 5 --技能栏A
Ds_SkillBarType.SKILLBARTYPE_F1 = 6 --技能栏F1
Ds_SkillBarType.SKILLBARTYPE_F2 = 7 --技能栏F2
Ds_SkillBarType.SKILLBARTYPE_F3 = 8 --技能栏F3
Ds_SkillBarType.SKILLBARTYPE_F4 = 9 --技能栏F4
Ds_SkillBarType.SKILLBARTYPE_NORMAL1 = 10 --技能栏普攻1
Ds_SkillBarType.SKILLBARTYPE_NORMAL2 = 11 --技能栏普攻2
Ds_SkillBarType.SKILLBARTYPE_TALENT = 12 --技能栏天赋
Ds_SkillBarType.SKILLBARTYPE_RANCEEYE = 13 --技能栏种族眼
Ds_SkillBarType.SKILLBARTYPE_MAX = 14 --技能栏最大值

Ds_SkillTrigCastType = {} --技能触发释放类型
Ds_SkillTrigCastType.SKILLTRIGTYPE_AUTOCAST = 0 --主动释放触发
Ds_SkillTrigCastType.SKILLTRIGTYPE_TALENT = 1 --技能天赋触发
Ds_SkillTrigCastType.SKILLTRIGTYPE_NOOTHER = 2 --被动无触发
Ds_SkillTrigCastType.SKILLTRIGTYPE_DEAD = 3 --单位死亡触发
Ds_SkillTrigCastType.SKILLTRIGTYPE_TIMEDURA = 4 --时间周期触发
Ds_SkillTrigCastType.SKILLTRIGTYPE_NORMALHIT = 5 --普通攻击命中锁定目标触发(第一个目标)
Ds_SkillTrigCastType.SKILLTRIGTYPE_BENORMALHIT = 6 --被普通攻击命中触发
Ds_SkillTrigCastType.SKILLTRIGTYPE_CASTNORMALSKILL = 7 --释放普攻技能触发
Ds_SkillTrigCastType.SKILLTRIGTYPE_CASTAUTOSKILL = 8 --释放QWER技能触发
Ds_SkillTrigCastType.SKILLTRIGTYPE_CASTSKILLROLLEND = 9 --释放技能前摇结束触发
Ds_SkillTrigCastType.SKILLTRIGTYPE_BEHIT = 10 --被任意伤害触发
Ds_SkillTrigCastType.SKILLTRIGTYPE_NORMALSKILLBEHIT = 11 --被普攻伤害触发
Ds_SkillTrigCastType.SKILLTRIGTYPE_AUTOSKILLBEHIT = 12 --被主动技能伤害触发
Ds_SkillTrigCastType.SKILLTRIGTYPE_PHYDMGHIT = 13 --被物理攻击伤害触发
Ds_SkillTrigCastType.SKILLTRIGTYPE_INSERTDMGHIT = 14 --被穿刺类攻击伤害触发
Ds_SkillTrigCastType.SKILLTRIGTYPE_BECRITHIT = 15 --被致命一击伤害触发
Ds_SkillTrigCastType.SKILLTRIGTYPE_UNPASSIVESKILLDAMAGE = 16 --非被动技能造成伤害触发
Ds_SkillTrigCastType.SKILLTRIGTYPE_QWERSKILLDAMAGE = 17 --QWER技能造成伤害触发
Ds_SkillTrigCastType.SKILLTRIGTYPE_NORMALEACHHIT = 18 --普通攻击伤害目标触发（AOE）
Ds_SkillTrigCastType.SKILLTRIGTYPE_KILLTARGET = 19 --击杀目标触发
Ds_SkillTrigCastType.SKILLTRIGTYPE_BUFFEFFECTMANAFLARE = 20 --Buff效果魔法闪耀触发
Ds_SkillTrigCastType.SKILLTRIGTYPE_LEVELUP = 21 --角色等级提升触发
Ds_SkillTrigCastType.SKILLTRIGTYPE_Day2NIGHT = 22 --切换到夜晚触发
Ds_SkillTrigCastType.SKILLTRIGTYPE_NIGHT2DAY = 23 --切换到白天触发
Ds_SkillTrigCastType.SKILLTRIGTYPE_CALLSUMMONED = 24 --召唤召唤物触发
Ds_SkillTrigCastType.SKILLTRIGTYPE_SUMMONEDDEAD = 25 --召唤物死亡触发

Ds_SkillTrigCastCondType = {} --技能释放条件类型
Ds_SkillTrigCastCondType.SKILLTRIGCONDTYPE_DURANOTDAMAGE = 1 --一定时间内未受伤害
Ds_SkillTrigCastCondType.SKILLTRIGCONDTYPE_DURANOTNORMALSKILL = 2 --一定时间内未释放普攻(包括变体普攻)
Ds_SkillTrigCastCondType.SKILLTRIGCONDTYPE_DURANOTBEDAMAGEANDNORMALSKILL = 3 --一定时间内未受伤害和未释放普攻
Ds_SkillTrigCastCondType.SKILLTRIGCONDTYPE_RANDOM = 4 --一定随机概率
Ds_SkillTrigCastCondType.SKILLTRIGCONDTYPE_LESSHP = 5 --生命值低于一定值
Ds_SkillTrigCastCondType.SKILLTRIGCONDTYPE_SELECTSKILLGROUPID = 6 --指定一个技能组ID(主动技能不支持)
Ds_SkillTrigCastCondType.SKILLTRIGCONDTYPE_SELECTACTORTYPE = 7 --指定一个目标类型(主动技能不支持)
Ds_SkillTrigCastCondType.SKILLTRIGCONDTYPE_RANGEEXITTEAMDEADBODY = 8 --技能攻击范围内存在友军尸体
Ds_SkillTrigCastCondType.SKILLTRIGCONDTYPE_RANGEEXITANYDEADBODY = 9 --技能攻击范围内存在任意尸体(被动技能不支持)
Ds_SkillTrigCastCondType.SKILLTRIGCONDTYPE_RANGEEXITANYDEADBODYANDACTORNUMLIMIT = 10 --技能攻击范围内存在尸体且召唤数目限制(被动技能不支持)
Ds_SkillTrigCastCondType.SKILLTRIGCONDTYPE_TEAMACTORNUMMAXLIMIT = 11 --队伍指定单位数量上限限制(被动技能不支持)
Ds_SkillTrigCastCondType.SKILLTRIGCONDTYPE_NIGHT = 12 --技能条件所需夜晚
Ds_SkillTrigCastCondType.SKILLTRIGCONDTYPE_NOREVIVAL = 13 --无复活技能或道具
Ds_SkillTrigCastCondType.SKILLTRIGCONDTYPE_ELFNIGHTTALENTTIRG = 14 --精灵族夜晚天赋效果触发条件
Ds_SkillTrigCastCondType.SKILLTRIGCONDTYPE_SKILLXPOSMARKDIS = 15 --技能X标记点距离条件
Ds_SkillTrigCastCondType.SKILLTRIGCONDTYPE_SELECTSUMMONRESID = 16 --指定召唤召唤物怪物ID条件
Ds_SkillTrigCastCondType.SKILLTRIGCONDTYPE_UDDEADBODYNOTFULL = 17 --不死灵魂战车尸体未满条件

Ds_SkillTrigRevivalParamType = {} --技能复活参数类型
Ds_SkillTrigRevivalParamType.SKILLTRIGREVIVALTYPE_INT = 0 --技能复活血蓝固定值
Ds_SkillTrigRevivalParamType.SKILLTRIGPARAMTYPE_10K = 1 --技能复活血蓝万分比
Ds_SkillTrigRevivalParamType.SKILLTRIGPARAMTYPE_LEVEL = 2 --技能复活血蓝等级系数

Ds_SkillTargetType = {} --技能作用对象类型
Ds_SkillTargetType.SKILL_TARGETTYPE_ALL = 0 --所有单位
Ds_SkillTargetType.SKILL_TARGETTYPE_SELF = 1 --自身
Ds_SkillTargetType.SKILL_TARGETTYPE_ALLENEMY = 2 --所有敌方
Ds_SkillTargetType.SKILL_TARGETTYPE_ALLSELF = 3 --所有己方
Ds_SkillTargetType.SKILL_TARGETTYPE_MYHERO = 4 --我方英雄
Ds_SkillTargetType.SKILL_TARGETTYPE_MYDOGFACE = 5 --我方士兵
Ds_SkillTargetType.SKILL_TARGETTYPE_MYBUILD = 6 --我方建筑
Ds_SkillTargetType.SKILL_TARGETTYPE_ENEMYHERO = 7 --敌方英雄
Ds_SkillTargetType.SKILL_TARGETTYPE_ENEMYDOGFACE = 8 --敌方士兵
Ds_SkillTargetType.SKILL_TARGETTYPE_ENEMYBUILD = 9 --敌方建筑
Ds_SkillTargetType.SKILL_TARGETTYPE_MYTEAMCALLER = 10 --自身队伍召唤物
Ds_SkillTargetType.SKILL_TARGETTYPE_ENEMYCALLER = 11 --敌方召唤物
Ds_SkillTargetType.SKILL_TARGETTYPE_MYALLNOTBUILD = 12 --所有己方除建筑
Ds_SkillTargetType.SKILL_TARGETTYPE_MYALLNOTBUILDANDME = 13 --所有己方除建筑除施法者
Ds_SkillTargetType.SKILL_TARGETTYPE_ALLENEMTNOTBUILD = 14 --所有敌方除建筑
Ds_SkillTargetType.SKILL_TARGETTYPE_ALLENEMTNOTHEROANDBUILD = 15 --所有敌方除英雄和建筑
Ds_SkillTargetType.SKILL_TARGETTYPE_MYLONGACTORNOTBUILD = 16 --所有己方远程除建筑
Ds_SkillTargetType.SKILL_TARGETTYPE_MYNEARACTORNOTBUILD = 17 --所有己方近战除建筑
Ds_SkillTargetType.SKILL_TARGETTYPE_ALLENEMTNOTBUILDANDMONSTER = 18 --所有敌方除建筑和野怪
Ds_SkillTargetType.SKILL_TARGETTYPE_MYTEAMALLNOTBUILD = 19 --所有己方队伍除建筑
Ds_SkillTargetType.SKILL_TARGETTYPE_MYTEAMLONGACTORNOTBUILD = 20 --所有己方队伍远程除建筑
Ds_SkillTargetType.SKILL_TARGETTYPE_ALLDOGFACEANDMONSTRENOTSUMM = 21 --所有士兵及野怪除召唤物
Ds_SkillTargetType.SKILL_TARGETTYPE_ALLTARGETLEGIONACTOR = 22 --目标阵营单位
Ds_SkillTargetType.SKILL_TARGETTYPE_ALLTARGETLEGIONHERO = 23 --目标阵营所有英雄(无范围搜索)
Ds_SkillTargetType.SKILL_TARGETTYPE_ALLTARGETLEGIONHERODOGFACE = 24 --目标阵营所有英雄和士兵(无范围搜索)
Ds_SkillTargetType.SKILL_TARGETTYPE_ALLTARGETTEAMHERO = 25 --目标队伍所有英雄(无范围搜索)
Ds_SkillTargetType.SKILL_TARGETTYPE_CASTERHOLEGIONALLHERO = 26 --施法者敌对阵营所有英雄(无范围搜索)
Ds_SkillTargetType.SKILL_TARGETTYPE_ALLMONSTER = 27 --所有野怪
Ds_SkillTargetType.SKILL_TARGETTYPE_MYTEAMHERO = 28 --我方队伍英雄

Ds_SkillDeadbodyTargetType = {} --技能作用尸体对象类型
Ds_SkillDeadbodyTargetType.SKILLDEADBODYTARGETTYPE_ALLACTOR = 0 --所有单位尸体
Ds_SkillDeadbodyTargetType.SKILLDEADBODYTARGETTYPE_MYTEAM = 1 --所有己方队伍尸体
Ds_SkillDeadbodyTargetType.SKILLDEADBODYTARGETTYPE_MYLEGION = 2 --所有己方阵营尸体
Ds_SkillDeadbodyTargetType.SKILLDEADBODYTARGETTYPE_ALLACTORADNCARRDY = 3 --所有单位和载具尸体

Ds_SkillDmgType = {} --技能伤害类型
Ds_SkillDmgType.SKILLDMGTYPE_PHY = 1 --物理伤害
Ds_SkillDmgType.SKILLDMGTYPE_MGC = 2 --法术伤害
Ds_SkillDmgType.SKILLDMGTYPE_ALL = 3 --全额伤害

Ds_SkillDistanceType = {} --技能距离类型
Ds_SkillDistanceType.SKILLDISTANCETYPE_NEARA = 0 --近战技能
Ds_SkillDistanceType.SKILLDISTANCETYPE_FAR = 1 --远程技能

Ds_SkillAtkActorType = {} --技能攻击单位类型
Ds_SkillAtkActorType.SKILLATKACTORTYPE_GROUND = 0 --攻击地面单位
Ds_SkillAtkActorType.SKILLATKACTORTYPE_AIR = 1 --攻击空中单位
Ds_SkillAtkActorType.SKILLATKACTORTYPE_AIRANDGROUND = 2 --攻击空地单位

Ds_SkillPassiveBreakType = {} --技能被动打断类型(向下包含)
Ds_SkillPassiveBreakType.SKILLPASSIVEBREAKTYPE_ALL = 1 --任意打断(1.受攻击)
Ds_SkillPassiveBreakType.SKILLPASSIVEBREAKTYPE_SOFTBUFF = 2 --软控Buff打断
Ds_SkillPassiveBreakType.SKILLPASSIVEBREAKTYPE_DEBUFF = 3 --硬控Buff打断
Ds_SkillPassiveBreakType.SKILLPASSIVEBREAKTYPE_DEAD = 4 --死亡打断
Ds_SkillPassiveBreakType.SKILLPASSIVEBREAKTYPE_GOD = 5 --上帝模式，能够打断所有(程序保护用)

Ds_SkillAutoBreakBehaviType = {} --技能主动打断行为类型(不填表)
Ds_SkillAutoBreakBehaviType.SKILLAUTOBREAKBEHAVITYPE_SKILLBEFOREROLL = 1 --技能前摇打断
Ds_SkillAutoBreakBehaviType.SKILLAUTOBREAKBEHAVITYPE_AUTOCASTSKILL = 2 --主动释放技能打断
Ds_SkillAutoBreakBehaviType.SKILLAUTOBREAKBEHAVITYPE_USEITEM = 3 --使用道具打断
Ds_SkillAutoBreakBehaviType.SKILLAUTOBREAKBEHAVITYPE_BUILD = 4 --建造打断
Ds_SkillAutoBreakBehaviType.SKILLAUTOBREAKBEHAVITYPE_MOVE = 5 --移动打断

Ds_SkillAutoBreakType = {} --技能主动打断类型(无优先级)
Ds_SkillAutoBreakType.SKILLAUTOBREAKTYPE_LV1 = 1 --技能前摇打断
Ds_SkillAutoBreakType.SKILLAUTOBREAKTYPE_LV2 = 2 --建造和使用道具打断
Ds_SkillAutoBreakType.SKILLAUTOBREAKTYPE_LV3 = 3 --技能前摇和移动打断
Ds_SkillAutoBreakType.SKILLAUTOBREAKTYPE_LV4 = 4 --建造和使用道具和移动打断
Ds_SkillAutoBreakType.SKILLAUTOBREAKTYPE_LV5 = 5 --主动使用技能打断
Ds_SkillAutoBreakType.SKILLAUTOBREAKTYPE_LV6 = 6 --主动使用技能和使用道具和移动打断

Ds_SkillInputOpType = {} --技能释放操控类型
Ds_SkillInputOpType.SKILLINPUTOPTYPE_NONE = 0 --操控类型_无
Ds_SkillInputOpType.SKILLINPUTOPTYPE_DIR = 1 --操控类型_控制朝向

Ds_SkillCooldownType = {} --技能冷却类型
Ds_SkillCooldownType.SKILLCOOLDOWNTYPE_NONE = 0 --无冷却
Ds_SkillCooldownType.SKILLCOOLDOWNTYPE_TIME = 1 --时间冷却

Ds_SkillCDStartType = {} --技能CD启动类型
Ds_SkillCDStartType.SKILLCDSTARTTYPE_CASTSKILL = 0 --释放技能启动
Ds_SkillCDStartType.SKILLCDSTARTTYPE_SKILLROLLEND = 1 --技能前摇结束启动
Ds_SkillCDStartType.SKILLCDSTARTTYPE_SKILATKEND = 2 --技能后摇结束启动

Ds_SkillCostType = {} --技能消耗类型
Ds_SkillCostType.SKILLCOSTYPE_NONE = 0 --无消耗
Ds_SkillCostType.SKILLCOSTYPE_MP = 1 --法术值消耗
Ds_SkillCostType.SKILLCOSTYPE_ENERGY = 2 --计数能量点
Ds_SkillCostType.SKILLCOSTYPE_SKILLPT = 3 --技能充能点
Ds_SkillCostType.SKILLCOSTYPE_ITEM = 4 --道具

Ds_SkillPointType = {} --技能指向类型
Ds_SkillPointType.SKILLPOINTTYPE_SLFE = 0 --自身
Ds_SkillPointType.SKILLPOINTTYPE_SLFEPOS = 1 --自身位置
Ds_SkillPointType.SKILLPOINTTYPE_TARGET = 2 --选择目标
Ds_SkillPointType.SKILLPOINTTYPE_DIRECTION = 3 --选择朝向
Ds_SkillPointType.SKILLPOINTTYPE_AREA = 4 --选择区域
Ds_SkillPointType.SKILLPOINTTYPE_AREATARGET = 5 --选择区域目标
Ds_SkillPointType.SKILLPOINTTYPE_MAPAREA = 6 --选择地图区域
Ds_SkillPointType.SKILLPOINTTYPE_MAPTARGET = 7 --选择地图目标
Ds_SkillPointType.SKILLPOINTTYPE_AREACAMERAFOLLOW = 8 --选择区域并镜头跟随

Ds_SkillPointAreaType = {} --技能指向区域类型
Ds_SkillPointAreaType.SKILLPOINTAREA_NONE = 0 --无区域
Ds_SkillPointAreaType.ASKILLPOINTAREA_RECTANGLE = 1 --矩形
Ds_SkillPointAreaType.SKILLPOINTAREA_CIRCLE = 2 --圆形
Ds_SkillPointAreaType.SKILLPOINTAREA_CIRCULAR = 3 --扇形

Ds_SkillAttkRollBuffType = {} --技能前摇效果类型
Ds_SkillAttkRollBuffType.SKILLATKROLLBUFFTYPE_NONE = 0 --前摇效果_无
Ds_SkillAttkRollBuffType.SKILLATKROLLBUFFTYPE_MOVE = 1 --前摇效果_移动
Ds_SkillAttkRollBuffType.SKILLATKROLLBUFFTYPE_SWIM = 2 --前摇效果_眩晕
Ds_SkillAttkRollBuffType.SKILLATKROLLBUFFTYPE_SILENT = 3 --前摇效果_沉默
Ds_SkillAttkRollBuffType.SKILLATKROLLBUFFTYPE_SNEER = 4 --前摇效果_嘲讽
Ds_SkillAttkRollBuffType.SKILLATKROLLBUFFTYPE_PASSIVEMOVE = 5 --前摇效果_被动位移
Ds_SkillAttkRollBuffType.SKILLATKROLLBUFFTYPE_PHYIMM = 6 --前摇效果_物理免疫
Ds_SkillAttkRollBuffType.SKILLATKROLLBUFFTYPE_MGCIMM = 7 --前摇效果_魔法免疫
Ds_SkillAttkRollBuffType.SKILLATKROLLBUFFTYPE_GOD = 8 --前摇效果_无敌
Ds_SkillAttkRollBuffType.SKILLATKROLLBUFFTYPE_TYPEMAX = 9 --前摇效果_Max

Ds_SkillCtrCastType = {} --技能受控制释放类型
Ds_SkillCtrCastType.SKILLCTRCASTTYPE_AIATKROLLCAST = 0 --有前摇通过AI释放
Ds_SkillCtrCastType.SKILLCTRCASTTYPE_AINOTATKCASTCAST = 1 --无前摇通过AI释放
Ds_SkillCtrCastType.SKILLCTRCASTTYPE_DIRECT = 2 --无前摇不通过AI受控制释放
Ds_SkillCtrCastType.SKILLCTRCASTTYPE_GOD = 3 --上帝释放(不通过AI,任何状态可放，无前摇)
Ds_SkillCtrCastType.SKILLCTRCASTTYPE_PASSIVECAST = 4 --被动技能直接释放

Ds_SkillBeforeRollType = {} --技能前摇类型
Ds_SkillBeforeRollType.SKILLBEFOREROLLTYPE_FIXTIME = 0 --固定时间前摇
Ds_SkillBeforeRollType.SKILLBEFOREROLLTYPE_DYNTIME = 1 --动态时间前摇

Ds_SkillBeforeRollMoveFaceType = {} --技能前摇移动朝向类型
Ds_SkillBeforeRollMoveFaceType.SKILLBEFOREROLLMOVEFACETYPE_NONE = 0 --技能前摇移动任意朝向
Ds_SkillBeforeRollMoveFaceType.SKILLBEFOREROLLMOVEFACETYPE_CAST = 1 --技能前摇移动释放朝向

Ds_SkillBattleCastType = {} --技能战斗释放类型
Ds_SkillBattleCastType.SKILLBATTLECASTTYPE_IN = 0 --战斗状态释放
Ds_SkillBattleCastType.SKILLBATTLECASTTYPE_ALL = 1 --任意状态释放

Ds_SkillCastMutexType = {} --技能释放互斥类型
Ds_SkillCastMutexType.SKILLCASTMUTEX_NONE = 0 --无目标互斥
Ds_SkillCastMutexType.SKILLCASTMUTEX_SAMETARGET = 1 --对同一目标互斥
Ds_SkillCastMutexType.SKILLCASTMUTEX_SAMETEAM = 2 --对同一队伍排斥

Ds_SkillLastTargetCondType = {} --技能上次目标有效条件
Ds_SkillLastTargetCondType.SKILLLASTTARGETCONDTYPE_SKLLAREA = 1 --技能目标仍在技能范围内

Ds_SkillTargetStatusCullType = {} --技能目标状态排除条件
Ds_SkillTargetStatusCullType.SKILLTTARGETSTATUSCULLYPE_BUFFGROUP = 1 --技能目标命中BUFF组ID
Ds_SkillTargetStatusCullType.SKILLTTARGETSTATUSCULLYPE_FULLHP = 2 --技能目标血量满
Ds_SkillTargetStatusCullType.SKILLTTARGETSTATUSCULLYPE_SKILLFIELD = 3 --技能目标命中法术场组ID

Ds_SkillTargetFilterType = {} --技能目标筛选条件类型
Ds_SkillTargetFilterType.SKILLTARGETFILTERTYPE_ACTORTYPE = 1 --技能目标筛选_目标类型
Ds_SkillTargetFilterType.SKILLTARGETFILTERTYPE_HP = 2 --技能目标筛选_血量
Ds_SkillTargetFilterType.SKILLTARGETFILTERTYPE_DISTANCE = 3 --技能目标筛选_距离
Ds_SkillTargetFilterType.SKILLTARGETFILTERTYPE_SPELLSTEAL = 4 --技能目标筛选_魔法盗取
Ds_SkillTargetFilterType.SKILLTARGETFILTERTYPE_DISPELMAGIC = 5 --技能目标筛选_驱散魔法
Ds_SkillTargetFilterType.SKILLTARGETFILTERTYPE_CYCLONE = 6 --技能目标筛选_龙卷风

Ds_SkillTargetFilterActorType = {} --技能目标筛选目标类型
Ds_SkillTargetFilterActorType.SKILLTARGETFILTERACTORTYPE_HERO = 1 --目标筛选_英雄
Ds_SkillTargetFilterActorType.SKILLTARGETFILTERACTORTYPE_DOGFACE = 2 --目标筛选_小兵
Ds_SkillTargetFilterActorType.SKILLTARGETFILTERACTORTYPE_BUILD = 3 --目标筛选_建筑
Ds_SkillTargetFilterActorType.SKILLTARGETFILTERACTORTYPE_WEAPONTYPENEAR = 4 --目标筛选_近战单位
Ds_SkillTargetFilterActorType.SKILLTARGETFILTERACTORTYPE_WEAPONTYPEFAR = 5 --目标筛选_远程单位

Ds_SkillTargetFilterDispelMagicType = {} --驱散魔法参数优先级
Ds_SkillTargetFilterDispelMagicType.SKILLTARGETFILTERDISPELMAGICTYPE_ENEMYUSEFULBUFF = 0 --驱散优先_敌方增益BUFF
Ds_SkillTargetFilterDispelMagicType.SKILLTARGETFILTERDISPELMAGICTYPE_MYUNUSEFUL = 1 --驱散优先_我方减益BUFF
Ds_SkillTargetFilterDispelMagicType.SKILLTARGETFILTERDISPELMAGICTYPE_SUMMONED = 2 --驱散优先_召唤物

Ds_SkillEffectType = {} --技能效果类型
Ds_SkillEffectType.SKILLEFFECT_NONE = 0 --无特殊效果
Ds_SkillEffectType.SET_ADD_BUFF = 1 --添加buff
Ds_SkillEffectType.REMOVE_BUFF = 2 --移除buff
Ds_SkillEffectType.CHANGE_BUFFLAYER = 3 --修改buff层数
Ds_SkillEffectType.SET_HURT = 4 --造成伤害
Ds_SkillEffectType.SET_KILLHURT = 5 --造成致命伤害
Ds_SkillEffectType.SKILL_ADDFIELD = 6 --召唤法术场
Ds_SkillEffectType.SKILL_REMOVEFIELD = 7 --技能移除法术场
Ds_SkillEffectType.SPAWN_SUMMONED = 8 --召唤怪物
Ds_SkillEffectType.SKILL_TP = 9 --技能回城
Ds_SkillEffectType.SET_REBHURT = 10 --造成反弹伤害
Ds_SkillEffectType.SKILL_DISPEL = 11 --技能驱散
Ds_SkillEffectType.SpellSteal = 12 --魔法盗取阶段效果
Ds_SkillEffectType.RESETHP = 13 --技能阶段加血
Ds_SkillEffectType.OPDEADBODY = 14 --技能操控尸体
Ds_SkillEffectType.CHANGESKILLENERGY = 15 --修改计数能量点
Ds_SkillEffectType.BREAKSKILL = 16 --中断释放中技能
Ds_SkillEffectType.SKILLSPAWNDEADBODY = 17 --技能产生尸体
Ds_SkillEffectType.SKILLMANABREAK = 18 --技能法力损毁
Ds_SkillEffectType.OPCASTSKILLCD = 19 --修改当前释放技能CD
Ds_SkillEffectType.EXORCISMSUCKHP = 20 --驱使恶灵吸血
Ds_SkillEffectType.SUMMONEDLIFETIME = 21 --技能修改召唤物存活时间
Ds_SkillEffectType.DEVOUR_MAGIC = 22 --吞噬魔法
Ds_SkillEffectType.SKILL_CHARM = 23 --魅惑符咒
Ds_SkillEffectType.SKILL_XPOSMARK = 24 --技能X位置标记
Ds_SkillEffectType.SKILLBACK_XPOSMARK = 25 --技能X标记返回
Ds_SkillEffectType.SPYFOWPOSITION = 26 --技能侦查迷雾位置
Ds_SkillEffectType.RESETITEMCD = 27 --重置道具CD
Ds_SkillEffectType.UDGROUNDSPAWNDEADBODY = 28 --腐地生成尸体
Ds_SkillEffectType.NETREESTANDBY = 29 --精灵树坐地
Ds_SkillEffectType.ATKPLUNDERGOLD = 30 --攻击掠夺金钱
Ds_SkillEffectType.SET_MAX = 31 --技能效果类型最大值

Ds_SkillEffectTargetType = {} --技能效果目标类型
Ds_SkillEffectTargetType.SKILLEFFECTTARGET_SELFTEAM = 0 --己方单位
Ds_SkillEffectTargetType.SKILLEFFECTTARGET_OPPTEAM = 1 --敌方单位

Ds_SkillEffectDamageType = {} --技能阶段伤害系数类型
Ds_SkillEffectDamageType.SKILLEFFECTDAMGETYPE_DEFAULT = 0 --技能阶段默认效果系数
Ds_SkillEffectDamageType.SKILLEFFECTDAMGETYPE_DISTANCE = 1 --距离效果系数
Ds_SkillEffectDamageType.SKILLEFFECTDAMGETYPE_HP = 2 --生命值效果固定值
Ds_SkillEffectDamageType.SKILLEFFECTDAMGETYPE_MP = 3 --法术值效果固定值
Ds_SkillEffectDamageType.SKILLEFFECTDAMGETYPE_SKILLENERGY = 4 --计数能量点系数
Ds_SkillEffectDamageType.SKILLEFFECTDAMGETYPE_HEROLEVEL = 5 --角色等级系数
Ds_SkillEffectDamageType.SKILLEFFECTDAMGETYPE_BUFFLAYER = 6 --BUFF层级系数
Ds_SkillEffectDamageType.SKILLEFFECTDAMGETYPE_ATTRARMOR = 7 --护甲数值系数
Ds_SkillEffectDamageType.SKILLEFFECTDAMGETYPE_HITINDEX = 8 --技能受击排序系数
Ds_SkillEffectDamageType.SKILLEFFECTDAMGETYPE_HITTARGETCNT_OP = 9 --技能击中目标数目操作数系数
Ds_SkillEffectDamageType.SKILLEFFECTDAMGETYPE_HITTARGETCNT_ATTR = 10 --技能击中目标数目属性系数
Ds_SkillEffectDamageType.SKILLEFFECTDAMGETYPE_HPANDBLOOM = 11 --生命值效果固定值附带吸血效果
Ds_SkillEffectDamageType.SKILLEFFECTDAMGETYPE_MAX = 12 --技能阶段效果系数最大值

Ds_SkillEffectSummonedType = {} --技能阶段召唤物召唤类型
Ds_SkillEffectSummonedType.SKILLEFFECTSUMMON_TARGETPOS = 0 --当前目标位置召唤
Ds_SkillEffectSummonedType.SKILLEFFECTSUMMON_FRONTPOS = 1 --当前目标朝向位置召唤

Ds_SkillEffectAddBuffCondType = {} --技能阶段BUFF添加条件和效果
Ds_SkillEffectAddBuffCondType.SKILLEFFECTADDBUFFCOND_SKILLENGRGYCNT = 1 --技能阶段所需计数能量点数目,条件
Ds_SkillEffectAddBuffCondType.SKILLEFFECTADDBUFFCOND_HITTARGETCNTBUFFLAYER = 2 --技能阶段击中目标数添加BUFF层,添加层级
Ds_SkillEffectAddBuffCondType.SKILLEFFECTADDBUFFCOND_GIVERLEVELBUFFLAYER = 3 --技能阶段施法者等级添加BUFF层,添加层级
Ds_SkillEffectAddBuffCondType.SKILLEFFECTADDBUFFCOND_REGIONFREINDACTORCNTBUFFLAYER = 4 --技能阶段范围内特定友军单位数目添加BUFF层,添加层级

Ds_SkillEffectTPType = {} --技能阶段回城类型
Ds_SkillEffectTPType.SKILLEFFECTTPTYPE_MAPTPPOS = 0 --回城到地图传送点
Ds_SkillEffectTPType.SKILLEFFECTTPTYPE_TEAM = 1 --群体传送到单位位置

Ds_SkillEffectOpDeadBodyType = {} --技能阶段操控尸体类型
Ds_SkillEffectOpDeadBodyType.SKILLEFFECTOPDEADBODYTYPE_REVIVAL = 0 --操控尸体复活
Ds_SkillEffectOpDeadBodyType.SKILLEFFECTOPDEADBODYTYPE_CALLER = 1 --操控尸体召唤

Ds_SkillEffectDispelType = {} --技能阶段驱散类型
Ds_SkillEffectDispelType.SKILLEFFECTDISPELTYPE_ALL = 0 --技能驱散_所有
Ds_SkillEffectDispelType.SKILLEFFECTDISPELTYPE_LEGION = 1 --技能驱散_阵营优先

Ds_SkillEffectDoDamageType = {} --技能造成伤害类型
Ds_SkillEffectDoDamageType.SKILLEFFECTDODAMAGE_DIRECT = 0 --直接造成伤害
Ds_SkillEffectDoDamageType.SKILLEFFECTDODAMAGE_REBORT = 1 --反弹造成伤害

Ds_SkillEffectSkillCdOpType = {} --技能阶段技能CD操作类型
Ds_SkillEffectSkillCdOpType.SKILLEFFECTSKILLCDOPTYPE_SKILLCD = 0 --技能阶段效果_修改技能CD,分子时间
Ds_SkillEffectSkillCdOpType.SKILLEFFECTSKILLCDOPTYPE_INSKILLCD = 1 --技能阶段效果_技能进入CD

Ds_SkillEffectHitLimitType = {} --技能阶段受击数目上限类型
Ds_SkillEffectHitLimitType.SKILLEFFECTHITLIMITTYPE_ALL = 0 --累计受击数目上限
Ds_SkillEffectHitLimitType.SKILLEFFECTHITLIMITTYPE_ONCE = 1 --单次受击数目上限

Ds_ResExpType = {} --经验类型
Ds_ResExpType.RESEXPTYPE_SYSTEM = 0 --系统经验
Ds_ResExpType.RESEXPTYPE_MONSTER = 1 --野怪经验
Ds_ResExpType.RESEXPTYPE_LEGION = 2 --英雄士兵经验

Ds_ResMoneyAddType = {} --金钱获取类型
Ds_ResMoneyAddType.RESMONEYADDTYPE_SYSTEM = 0 --系统奖励金钱
Ds_ResMoneyAddType.RESMONEYADDTYPE_GOLDMINE = 1 --金矿开采金钱
Ds_ResMoneyAddType.RESMONEYADDTYPE_KILLACTOR = 2 --击杀战斗单位金钱
Ds_ResMoneyAddType.RESMONEYADDTYPE_KILLMONSTER = 3 --击杀野怪金钱
Ds_ResMoneyAddType.RESMONEYADDTYPE_REPLAIRCOST = 4 --维修费消耗
Ds_ResMoneyAddType.RESMONEYADDTYPE_BUILDACTORCOST = 5 --造兵消耗
Ds_ResMoneyAddType.RESMONEYADDTYPE_BUILDOTHERCOST = 6 --造塔或金矿消耗
Ds_ResMoneyAddType.RESMONEYADDTYPE_TECHUPCOST = 7 --科技升级消耗
Ds_ResMoneyAddType.RESMONEYADDTYPE_SELLEQUIP = 8 --出售装备
Ds_ResMoneyAddType.RESMONEYADDTYPE_GM = 10 --GM命令

Ds_ResRepairCostType = {} --维修费用类型
Ds_ResRepairCostType.RESREPAIRCOSTTYPE_NONE = 0 --无维修费用
Ds_ResRepairCostType.RESREPAIRCOSTTYPE_LOW = 1 --低维修费用
Ds_ResRepairCostType.RESREPAIRCOSTTYPE_HIGHT = 2 --高维修费用

Ds_SkillFieldType = {} --法术场类型
Ds_SkillFieldType.SKILLFIELD_TYPE_TRIGGER_ONCE = 0 --触碰消失放技能
Ds_SkillFieldType.SKILLFIELD_TYPE_COMMON_FIELD = 1 --进加出减法术场
Ds_SkillFieldType.SKILLFIELD_ONLY_ADD = 2 --进加出不减法术场
Ds_SkillFieldType.SKILLFIELD_TRIGGER_HP = 3 --血瓶触碰法术场
Ds_SkillFieldType.SKILLFIELD_TYPE_MAX = 4 --法术场类型最大值

Ds_SkillFieldShape = {} --法术场形状
Ds_SkillFieldShape.SKILLFIELD_SHAPE_CIRCLE = 0 --圆形场
Ds_SkillFieldShape.SKILLFIELD_SHAPE_RECT = 1 --矩形场

Ds_SkillFieldShapeChangeType = {} --法术场形状变化类型
Ds_SkillFieldShapeChangeType.SKILLFIELDSHAPECHANGETYPE_NONE = 0 --范围内法术场无变化
Ds_SkillFieldShapeChangeType.SKILLFIELDSHAPECHANGETYPE_RECTWIDTH = 1 --范围内矩形长度变化
Ds_SkillFieldShapeChangeType.SKILLFIELDSHAPECHANGETYPE_RECTHEIGHT = 2 --范围内矩形宽度变化
Ds_SkillFieldShapeChangeType.SKILLFIELDSHAPECHANGETYPE_CIRCLE = 3 --范围内圆形半径变化

Ds_SkillFieldParamType = {} --法术场触发参数类型
Ds_SkillFieldParamType.SKILLFIELD_PARAM_TYPE_BUFF = 1 --法术场触发Buff
Ds_SkillFieldParamType.SKILLFIELD_PARAM_TYPE_SKILL_PHASE = 2 --法术场触发技能阶段

Ds_SkillFieldTargetFilterType = {} --法术场目标筛选类型
Ds_SkillFieldTargetFilterType.SKILLFIELD_FILTER_DURADAMAGE = 1 --法术场_一定时间内未受伤害筛选
Ds_SkillFieldTargetFilterType.SKILLFIELD_FILTER_DURADAMAGEORATTACK = 2 --法术场_一定时间内未受到伤害或主动攻击筛选
Ds_SkillFieldTargetFilterType.SKILLFIELD_FILTER_NEAR = 3 --法术场_最近距离的几个
Ds_SkillFieldTargetFilterType.SKILLFIELD_FILTER_NOBUFF = 4 --法术场_无指定BUFF组ID
Ds_SkillFieldTargetFilterType.SKILLFIELD_FILTER_TRIGERRECTACTOR = 5 --法术场_触发者范围内搜寻

Ds_SkillFieldRemoveEventType = {} --法术场移除事件类型
Ds_SkillFieldRemoveEventType.SKILLFIELDREMOVEEVENTTYPE_NONE = 0 --法术场移除事件_NONE
Ds_SkillFieldRemoveEventType.SKILLFIELDREMOVEEVENTTYPE_CASTERCASTSKILL = 1 --法术场施法者使用技能移除
Ds_SkillFieldRemoveEventType.SKILLFIELDREMOVEEVENTTYPE_CASTERBEHIT = 2 --法术场施法者受到伤害移除
Ds_SkillFieldRemoveEventType.SKILLFIELDREMOVEEVENTTYPE_BESKILLNODEHIT = 3 --法术场被技能子弹碰撞移除

Ds_BattleModeType = {} --战场模式类型
Ds_BattleModeType.BATTLEMODETYPE_DEFUALT = 0 --默认模式战场局
Ds_BattleModeType.BATTLEMODETYPE_GUIDE = 1 --新手模式战场局

Ds_BuildAIType = {} --建造AI类型
Ds_BuildAIType.BUILDAI_ACTOR = 1 --建造AI_建造单位
Ds_BuildAIType.BUILDAI_ACTOR_TECH = 2 --建造AI_升级单位科技
Ds_BuildAIType.BUILDAI_TEAM_TECH = 3 --建造AI_升级队伍科技
Ds_BuildAIType.BUILDAI_BUILDGOLDMINEGOLD = 4 --建造AI_建造分矿攒钱
Ds_BuildAIType.BUILDAI_CANCELGOLDMINEGOLD = 5 --建造AI_取消分矿攒钱

Ds_BuildAITargetType = {} --建造AI目标类型
Ds_BuildAITargetType.BUILDAITARGET_NONE = 0 --建造AI_无目标
Ds_BuildAITargetType.BUILDAITARGET_CONST = 1 --建造AI_常量
Ds_BuildAITargetType.BUILDAITARGET_VAR = 2 --建造AI_条件变量
Ds_BuildAITargetType.BUILDAITARGET_SUB_COND = 3 --建造AI_子条件
Ds_BuildAITargetType.BUILDAITARGET_ACTOR_CNT = 4 --建造AI_单位数量
Ds_BuildAITargetType.BUILDAITARGET_BUILDING_ACTOR_CNT = 5 --建造AI_建造中单位数量
Ds_BuildAITargetType.BUILDAITARGET_BASE_LVL = 6 --建造AI_基地等级
Ds_BuildAITargetType.BUILDAITARGET_FOOD_CNT = 7 --建造AI_人口数量
Ds_BuildAITargetType.BUILDAITARGET_MAX_FOOD_CNT = 8 --建造AI_最大人口数量
Ds_BuildAITargetType.BUILDAITARGET_NEED_GOLD_MINE_CNT = 9 --建造AI_待开采金矿数
Ds_BuildAITargetType.BUILDAITARGET_NEED_TOWER_CNT = 10 --建造AI_待建造防御塔数
Ds_BuildAITargetType.BUILDAITARGET_TECH_LVL = 11 --建造AI_科技等级
Ds_BuildAITargetType.BUILDAITARGET_MAX = 12 --建造AI目标类型最大值

Ds_BaseTechLevelType = {} --基地科技等级类型
Ds_BaseTechLevelType.BASETECHLEVEL_LEVEL0 = 0 --无科技基地
Ds_BaseTechLevelType.BASETECHLEVEL_LEVEL1 = 1 --一本科技基地
Ds_BaseTechLevelType.BASETECHLEVEL_LEVEL2 = 2 --二本科技基地
Ds_BaseTechLevelType.BASETECHLEVEL_LEVEL3 = 3 --三本科技基地

Ds_TechLevelType = {} --科技类型
Ds_TechLevelType.TECHTYPE_ACTOR = 0 --单位科技
Ds_TechLevelType.TECHTYPE_TEAM = 1 --团队科技

Ds_TechLevelSubType = {} --科技子类型
Ds_TechLevelSubType.TECHSUBTYPE_NONE = 0 --科技子类型_NONE
Ds_TechLevelSubType.TECHSUBTYPE_BASEUP = 1 --单位基地升级科技
Ds_TechLevelSubType.TECHSUBTYPE_ACTORAVATAR = 2 --单位变身科技
Ds_TechLevelSubType.TECHSUBTYPE_BUILDGOLDMINE = 3 --单位金矿建造科技
Ds_TechLevelSubType.TECHSUBTYPE_BUILDTOWER = 4 --单位防御塔建造科技
Ds_TechLevelSubType.TECHSUBTYPE_CONSTRUCTARMY = 5 --单位训练科技
Ds_TechLevelSubType.TECHSUBTYPE_ATKUP = 6 --团队攻击升级科技
Ds_TechLevelSubType.TECHSUBTYPE_DEFENCEUP = 7 --团队防御升级科技
Ds_TechLevelSubType.TECHSUBTYPE_FOODUP = 8 --团队人口升级科技

Ds_TechEffectType = {} --科技效果类型
Ds_TechEffectType.TECHEFFECTTYPE_UNLOCKUNITSKILL = 1 --科技效果_解锁单位技能
Ds_TechEffectType.TECHEFFECTTYPE_UPDATEMAXFOOD = 2 --科技效果_提升最大人口
Ds_TechEffectType.TECHEFFECTTYPE_UPDATEUNITATTR = 3 --科技效果_提升单位攻防属性
Ds_TechEffectType.TECHEFFECTTYPE_UPDATEBASE = 4 --科技效果_基地科技升级
Ds_TechEffectType.TECHEFFECTTYPE_SPAWNACTOR = 5 --科技效果_孵化单位
Ds_TechEffectType.TECHEFFECTTYPE_ADDHEROSKILL = 6 --科技效果_增加英雄技能

Ds_TechStatusType = {} --科技状态类型
Ds_TechStatusType.TECHSTATUSTYPE_INVALID = 0 --科技状态_不可用
Ds_TechStatusType.TECHSTATUSTYPE_LOCK = 1 --科技状态_不可用
Ds_TechStatusType.TECHSTATUSTYPE_READY = 2 --科技状态_可研究
Ds_TechStatusType.TECHSTATUSTYPE_RESEARCHING = 3 --科技状态_研究中
Ds_TechStatusType.TECHSTATUSTYPE_FINISH = 4 --科技状态_研究完成

Ds_TechTreeType = {} --科技树类型
Ds_TechTreeType.TECHTREETYPE_LEVEL1 = 1 --科技树类型1
Ds_TechTreeType.TECHTREETYPE_LEVEL2 = 2 --科技树类型2
Ds_TechTreeType.TECHTREETYPE_LEVEL3 = 3 --科技树类型3
Ds_TechTreeType.TECHTREETYPE_LEVEL4 = 4 --科技树类型3
Ds_TechTreeType.TECHTREETYPE_LEVEL5 = 5 --科技树类型4
Ds_TechTreeType.TECHTREETYPE_MAX = 10 --科技树类型MAX

Ds_BattleGoodsItemType = {} --物品道具类型
Ds_BattleGoodsItemType.BATTLEGOODSITEMTYPE_NONE = 0 --物品道具无类型
Ds_BattleGoodsItemType.BATTLEGOODSITEMTYPE_RETURNTOBASE = 1 --回程类物品道具
Ds_BattleGoodsItemType.BATTLEGOODSITEMTYPE_GOLD = 2 --金币类物品道具
Ds_BattleGoodsItemType.BATTLEGOODSITEMTYPE_ATTRBOOK = 3 --书籍类物品道具
Ds_BattleGoodsItemType.BATTLEGOODSITEMTYPE_SCROLLS = 4 --卷轴类物品道具
Ds_BattleGoodsItemType.BATTLEGOODSITEMTYPE_POTION = 5 --药剂类物品道具
Ds_BattleGoodsItemType.BATTLEGOODSITEMTYPE_RUNE = 6 --神符类物品道具
Ds_BattleGoodsItemType.BATTLEGOODSITEMTYPE_WARD = 7 --侦查类物品道具
Ds_BattleGoodsItemType.BATTLEGOODSITEMTYPE_EQUIP = 8 --装备类物品道具
Ds_BattleGoodsItemType.BATTLEGOODSITEMTYPE_SUMMONEDACTOR = 9 --召唤单位类物品道具
Ds_BattleGoodsItemType.BATTLEGOODSITEMTYPE_MAX = 10 --物品道具类型最大值

Ds_ItemQualityType = {} --道具品质类型
Ds_ItemQualityType.ITEMQUALITYTYPE_WHITE = 0 --道具品质_白
Ds_ItemQualityType.ITEMQUALITYTYPE_GREEN = 1 --道具品质_绿
Ds_ItemQualityType.ITEMQUALITYTYPE_BLUE = 2 --道具品质_蓝
Ds_ItemQualityType.ITEMQUALITYTYPE_PURPLE = 3 --道具品质_紫
Ds_ItemQualityType.ITEMQUALITYTYPE_ORANGE = 4 --道具品质_橙

Ds_ItemPickType = {} --道具拾取类型
Ds_ItemPickType.ITEMPICKTYPE_AUTO = 0 --道具自动拾取
Ds_ItemPickType.ITEMPICKTYPE_MANUAL = 1 --道具点击拾取
Ds_ItemPickType.ITEMPICKTYPE_CHAT = 2 --道具吟唱拾取

Ds_ItemUseType = {} --道具使用类型
Ds_ItemUseType.ITEMUSETYPE_NONE = 0 --道具不可使用
Ds_ItemUseType.ITEMUSETYPE_MANUAL = 1 --道具点击使用
Ds_ItemUseType.ITEMUSETYPE_AUTO = 2 --道具自动使用

Ds_ItemCostType = {} --道具消耗类型
Ds_ItemCostType.ITEMCOSTTYPE_IMM = 0 --道具使用立即消耗
Ds_ItemCostType.ITEMCOSTTYPE_SKILLROLL = 1 --道具技能前摇结束消耗，技能必须配置前摇和道具消耗

Ds_EquipBarType = {} --装备栏位类型
Ds_EquipBarType.EQUIPBARTYPE_1 = 0 --装备栏位1
Ds_EquipBarType.EQUIPBARTYPE_2 = 1 --装备栏位2
Ds_EquipBarType.EQUIPBARTYPE_3 = 2 --装备栏位3
Ds_EquipBarType.EQUIPBARTYPE_4 = 3 --装备栏位4
Ds_EquipBarType.EQUIPBARTYPE_5 = 4 --装备栏位5
Ds_EquipBarType.EQUIPBARTYPE_6 = 5 --装备栏位6
Ds_EquipBarType.EQUIPBARTYPE_MAX = 6 --装备栏位最大值

Ds_BattleItemEffectType = {} --道具效果类型
Ds_BattleItemEffectType.BATTLEITEMEFFECTTYPE_CASTSKILL = 1 --道具触发释放技能
Ds_BattleItemEffectType.BATTLEITEMEFFECTTYPE_ADDBUFF = 2 --道具触发添加BUFF
Ds_BattleItemEffectType.BATTLEITEMEFFECTTYPE_ADDGOLD = 3 --道具使用增加金币
Ds_BattleItemEffectType.BATTLEITEMEFFECTTYPE_ADDEQUIP = 4 --道具使用穿戴装备

Ds_ItemMapTpPosType = {} --道具回城点类型
Ds_ItemMapTpPosType.ITEMMAPTPPOSTYPE_MYLEGION = 0 --我方阵营所有回城点
Ds_ItemMapTpPosType.ITEMMAPTPPOSTYPE_MYBASE = 1 --我方队伍基地回城点

Ds_BaseProtectType = {} --基地保护类型
Ds_BaseProtectType.BASEPROTECTTYPE_LEGION = 0 --主基地团队保护
Ds_BaseProtectType.BASEPROTECTTYPE_TEAM = 1 --主基地队伍保护

Ds_BattleEndJudgeType = {} --战斗比赛结束判定类型
Ds_BattleEndJudgeType.BATTLEENDJUDGETYPE_KILLALLBASE = 0 --摧毁所有主基地定战斗胜负
Ds_BattleEndJudgeType.BATTLEENDJUDGETYPE_OTHERCMD = 1 --外部判定定战斗胜负

Ds_BattleCongfigType = {} --战场设置表
Ds_BattleCongfigType.BATTLECONFIGTYPE_BUILDTOWERDIS = 1 --建造塔最少满足距离
Ds_BattleCongfigType.BATTLECONFIGTYPE_ACTORDEADBODY_TIME = 2 --单位死亡变成尸体时间
Ds_BattleCongfigType.BATTLECONFIGTYPE_OP_TIME = 3 --队伍操作时间集
Ds_BattleCongfigType.BATTLECONFIGTYPE_TEAM_REGION = 4 --队伍区域距离范围
Ds_BattleCongfigType.BATTLECONFIGTYPE_TEAMLOCKOPTIME = 5 --队伍英雄死亡锁定操作时间
Ds_BattleCongfigType.BATTLECONFIGTYPE_HEROFOLLOWTEAMGOURO = 6 --队伍英雄复活归队距离
Ds_BattleCongfigType.BATTLECONFIGTYPE_BACKTEAM_MOVEBUFF = 7 --单位归队加速BUFF
Ds_BattleCongfigType.BATTLECONFIGTYPE_DROPPICKUP_RANGE = 8 --掉落拾取半径范围
Ds_BattleCongfigType.BATTLECONFIGTYPE_REPATRI_RANGE = 9 --遣散士兵有效范围
Ds_BattleCongfigType.BATTLECONFIGTYPE_STEALWARN_RANGE = 10 --隐身提示检测范围
Ds_BattleCongfigType.BATTLECONFIGTYPE_GRASSPARAM = 11 --草丛渐隐参数
Ds_BattleCongfigType.BATTLECONFIGTYPE_EQUIPPICKUP = 12 --装备拾取参数
Ds_BattleCongfigType.BATTLECONFIGTYPE_AIFLLOWPARAM = 13 --AI跟随参数
Ds_BattleCongfigType.BATTLECONFIGTYPE_GANKKILLEVENTPARAM = 14 --Gank击杀事件参数
Ds_BattleCongfigType.BATTLECONFIGTYPE_KILLDOGFACEEVENTPARAM = 15 --击杀小兵事件参数
Ds_BattleCongfigType.BATTLECONFIGTYPE_HOSTPARAM = 16 --挂机托管参数
Ds_BattleCongfigType.BATTLECONFIGTYPE_NETPARAM = 17 --网络延迟参数

Ds_NightDayType = {} --昼夜类型
Ds_NightDayType.NIGHTDAYTYPE_DAYTIME = 0 --昼夜_白天
Ds_NightDayType.NIGHTDAYTYPE_NIGHT = 1 --昼夜_晚上

Ds_AiConfigType = {} --AI难度
Ds_AiConfigType.AICONFIGTYPE_ASSIT = 0 --AI难度_托管
Ds_AiConfigType.AICONFIGTYPE_PASSIVE = 1 --AI难度_消极
Ds_AiConfigType.AICONFIGTYPE_EASY = 2 --AI难度_简单
Ds_AiConfigType.AICONFIGTYPE_NORMAL = 3 --AI难度_中等
Ds_AiConfigType.AICONFIGTYPE_HARD = 4 --AI难度_困难
Ds_AiConfigType.AICONFIGTYPE_CRAZY = 5 --AI难度_疯狂
Ds_AiConfigType.AICONFIGTYPE_GUIDE = 6 --AI难度_弱引导
Ds_AiConfigType.AICONFIGTYPE_NEWBEE = 7 --AI难度_新手
Ds_AiConfigType.AICONFIGTYPE_MAX = 8 --AI难度_MAX

Ds_BattleSceneType = {} --战斗场景模式
Ds_BattleSceneType.BATTLESCENETYPE_COMMON = 0 --战斗场景_通用
Ds_BattleSceneType.BATTLESCENETYPE_COMMON1V1 = 1 --战斗场景_通用1V1
Ds_BattleSceneType.BATTLESCENETYPE_COMMON2V2 = 2 --战斗场景_通用2V2
Ds_BattleSceneType.BATTLESCENETYPE_COMMON3V3 = 3 --战斗场景_通用3V3
Ds_BattleSceneType.BATTLESCENETYPE_GUIDEPVE1 = 4 --战斗场景_新手PVE1
Ds_BattleSceneType.BATTLESCENETYPE_GUIDEPVE2 = 5 --战斗场景_新手PVE2
Ds_BattleSceneType.BATTLESCENETYPE_GUIDEPVE3 = 6 --战斗场景_新手PVE3
Ds_BattleSceneType.BATTLESCENETYPE_GUIDEPVE4 = 7 --战斗场景_新手PVE4

Ds_LODType = {} --LOD类型
Ds_LODType.LODTYPE_LOW = 0 --LOD低配
Ds_LODType.LODTYPE_MID = 1 --LOD中配
Ds_LODType.LODTYPE_HIGHT = 2 --LOD高配
Ds_LODType.LODTYPE_MAX = 3 --LOD_MAX

Ds_LODTargetType = {} --LOD对象类型
Ds_LODTargetType.LODTARGETTYPE_SELF = 0 --LOD对象_自身
Ds_LODTargetType.LODTARGETTYPE_FRIENDD = 1 --LOD对象_友军
Ds_LODTargetType.LODTARGETTYPE_ENEMY = 2 --LOD对象_敌军
Ds_LODTargetType.LODTARGETTYPE_MAX = 3 --LOD对象_MAX

Ds_LODEffectType = {} --LOD特效类型
Ds_LODEffectType.LODEFFECTTYPE_ATTACKEFFECT_NEAR = 0 --LOD近战攻击特效
Ds_LODEffectType.LODEFFECTTYPE_ATTACKEFFECT_FLY = 1 --LOD飞行攻击特效
Ds_LODEffectType.LODEFFECTTYPE_HITEFFECT = 2 --LOD受击特效
Ds_LODEffectType.LODEFFECTTYPE_SKILLHITRING = 3 --LOD技能识别圈特效
Ds_LODEffectType.LODEFFECTTYPE_SKILLOTHER = 4 --LOD技能辅助特效
Ds_LODEffectType.LODEFFECTTYPE_BUFF = 5 --LODBUFF特效
Ds_LODEffectType.LODEFFECTTYPE_ITEM = 6 --LOD道具特效
Ds_LODEffectType.LODEFFECTTYPE_SKILLFIELD = 7 --LOD法术场特效
Ds_LODEffectType.LODEFFECTTYPE_ACTOR = 8 --LOD角色特效
Ds_LODEffectType.LODEFFECTTYPE_SCENE = 9 --LOD场景特效
Ds_LODEffectType.LODEFFECTTYPE_MAX = 10 --LOD特效MAX

Ds_LODEffectSetType = {} --LOD设置项
Ds_LODEffectSetType.LODEFFECTSETTYPE_ENEMYCNT = 1 --敌方单位LOD数目
Ds_LODEffectSetType.LODEFFECTSETTYPE_FRIENDCNT = 2 --友方单位LOD数目

Ds_LanguageDefine = {} --语言类型
Ds_LanguageDefine.NONE = 0 --无
Ds_LanguageDefine.SIM_CHINESE = 1 --简体中文
Ds_LanguageDefine.FON_CHINESE = 2 --繁体中文
Ds_LanguageDefine.ENGLISH = 3 --英文

Ds_SystemItemType = {} --系统道具类型
Ds_SystemItemType.SYSYTEMITEMTYPE_HIDDES = 0 --隐藏道具
Ds_SystemItemType.SYSYTEMITEMTYPE_ITEM = 1 --系统道具_道具
Ds_SystemItemType.SYSYTEMITEMTYPE_EXPERIENCE = 2 --系统道具_体验卡
Ds_SystemItemType.SYSYTEMITEMTYPE_RUNE = 3 --系统道具_符文

Ds_SystemItemSubType = {} --系统道具子类型
Ds_SystemItemSubType.SYSYTEMITEMSUBTYPE_EXP = 1 --道具子类型_EXP
Ds_SystemItemSubType.SYSYTEMITEMSUBTYPE_RMB = 2 --道具子类型_点券
Ds_SystemItemSubType.SYSYTEMITEMSUBTYPE_GOLD = 3 --道具子类型_金币
Ds_SystemItemSubType.SYSYTEMITEMSUBTYPE_DIAM = 4 --道具子类型_钻石
Ds_SystemItemSubType.SYSYTEMITEMSUBTYPE_SPEAK = 5 --道具子类型_喇叭
Ds_SystemItemSubType.SYSYTEMITEMSUBTYPE_PACKAGE = 6 --道具子类型_礼包
Ds_SystemItemSubType.SYSYTEMITEMSUBTYPE_EXPCARD = 7 --道具子类型_经验卡
Ds_SystemItemSubType.SYSYTEMITEMSUBTYPE_GOLDCARD = 8 --道具子类型_金币卡
Ds_SystemItemSubType.SYSYTEMITEMSUBTYPE_NAMECARD = 9 --道具子类型_改名卡
Ds_SystemItemSubType.SYSYTEMITEMSUBTYPE_HEROPIECE = 10 --道具子类型_英雄碎片
Ds_SystemItemSubType.SYSYTEMITEMSUBTYPE_SKINPIECE = 11 --道具子类型_皮肤碎片
Ds_SystemItemSubType.SYSYTEMITEMSUBTYPE_HEROEXP = 12 --道具子类型_英雄体验卡
Ds_SystemItemSubType.SYSYTEMITEMSUBTYPE_SKINEXP = 13 --道具子类型_皮肤体验卡
Ds_SystemItemSubType.SYSYTEMITEMSUBTYPE_RUNE = 14 --道具子类型_符文
Ds_SystemItemSubType.SYSYTEMITEMSUBTYPE_ACTIVE = 15 --道具子类型_活跃
Ds_SystemItemSubType.SYSYTEMITEMSUBTYPE_RUNES = 16 --道具子类型_纹章
Ds_SystemItemSubType.SYSYTEMITEMSUBTYPE_HERO = 17 --道具子类型_英雄
Ds_SystemItemSubType.SYSYTEMITEMSUBTYPE_SKIN = 18 --道具子类型_皮肤
Ds_SystemItemSubType.SYSYTEMITEMSUBTYPE_ACHPOINT = 19 --道具子类型_成就点数
Ds_SystemItemSubType.SYSYTEMITEMSUBTYPE_HEAD = 20 --道具子类型_头像
Ds_SystemItemSubType.SYSYTEMITEMSUBTYPE_HEADFRAME = 21 --道具子类型_头像框
Ds_SystemItemSubType.SYSYTEMITEMSUBTYPE_RAFFLE = 22 --道具子类型_抽奖
Ds_SystemItemSubType.SYSYTEMITEMSUBTYPE_MEDAL = 23 --道具子类型_勋章商店
Ds_SystemItemSubType.SYSYTEMITEMSUBTYPE_ARENA = 24 --道具子类型_竞技场积分
Ds_SystemItemSubType.SYSYTEMITEMSUBTYPE_ACTIVITY = 25 --道具子类型_活动道具
Ds_SystemItemSubType.SYSYTEMITEMSUBTYPE_HERO_RUNE_FRAGMENT = 26 --道具子类型_英雄符文碎片
Ds_SystemItemSubType.SYSYTEMITEMSUBTYPE_RACE_RUNE_FRAGMENT = 27 --道具子类型_种族符文碎片

Ds_SystemItemEffectType = {} --系统道具效果
Ds_SystemItemEffectType.SYSYTEFFECTTYPE_ADDEXP = 1 --增加召唤师经验
Ds_SystemItemEffectType.SYSYTEFFECTTYPE_ADDCOUPON = 2 --增加召唤师点券
Ds_SystemItemEffectType.SYSYTEFFECTTYPE_ADDGOLD = 3 --增加召唤师金币
Ds_SystemItemEffectType.SYSYTEFFECTTYPE_ADDDIAM = 4 --增加召唤师钻石
Ds_SystemItemEffectType.SYSYTEFFECTTYPE_ACTIVE = 5 --增加召唤师活跃
Ds_SystemItemEffectType.SYSYTEFFECTTYPE_HERO = 6 --增加英雄
Ds_SystemItemEffectType.SYSYTEFFECTTYPE_SKIN = 7 --增加皮肤
Ds_SystemItemEffectType.SYSYTEFFECTTYPE_ADDACHPOINT = 8 --增加召唤师成就点数
Ds_SystemItemEffectType.SYSYTEFFECTTYPE_ADD_DOUBLEEXP_TIME = 9 --增加双倍经验时间
Ds_SystemItemEffectType.SYSYTEFFECTTYPE_ADD_DOUBLEGOLD_TIME = 10 --增加双倍金币时间
Ds_SystemItemEffectType.SYSYTEFFECTTYPE_EXPER_HERO = 11 --增加体验英雄
Ds_SystemItemEffectType.SYSYTEFFECTTYPE_EXPER_SKIN = 12 --增加体验皮肤
Ds_SystemItemEffectType.SYSYTEFFECTTYPE_ADD_DOUBLEEXP_WIN_NUM = 13 --增加胜利获得双倍经验次数
Ds_SystemItemEffectType.SYSYTEFFECTTYPE_ADD_DOUBLEGOLD_WIN_NUM = 14 --增加胜利获得双倍金币次数
Ds_SystemItemEffectType.SYSYTEFFECTTYPE_UNLOCKHEAD = 15 --解锁系统头像
Ds_SystemItemEffectType.SYSYTEFFECTTYPE_UNLOCKHEADFRAME = 16 --解锁系统头像框
Ds_SystemItemEffectType.SYSYTEFFECTTYPE_ADD_RACE_RUNE_FRAGMENT = 17 --增加召唤师种族符文碎片
Ds_SystemItemEffectType.SYSYTEFFECTTYPE_ADD_HERO_RUNE_FRAGMENT = 18 --增加召唤师英雄符文碎片

Ds_SystemTaskType = {} --系统任务类型
Ds_SystemTaskType.SYSYTEMTASKTYPE_DAY = 1 --每日任务
Ds_SystemTaskType.SYSYTEMTASKTYPE_LEVEL = 2 --成长任务
Ds_SystemTaskType.SYSYTEMTASKTYPE_WEEK = 3 --任务_每周任务
Ds_SystemTaskType.SYSYTEMTASKTYPE_NEWGUIDE = 4 --任务_新手引导任务
Ds_SystemTaskType.SYSYTEMTASKTYPE_BASIC = 5 --任务_基础任务
Ds_SystemTaskType.SYSYTEMTASKTYPE_CONDITION = 6 --任务_条件任务

Ds_SystemTaskCountType = {} --系统任务计数类型
Ds_SystemTaskCountType.SYSYTEMTASKCOUNTTYPE_SINGLE = 1 --任务_单局
Ds_SystemTaskCountType.SYSYTEMTASKCOUNTTYPE_DAY = 2 --任务_日累计
Ds_SystemTaskCountType.SYSYTEMTASKCOUNTTYPE_WEEK = 3 --任务_周累计
Ds_SystemTaskCountType.SYSYTEMTASKCOUNTTYPE_FOREVER = 4 --任务_永久

Ds_SystemTaskNeedActType = {} --系统任务行为需求类型
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_LOGIN = 1 --登陆游戏
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_KILLHERO = 2 --单局击杀英雄数量
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_KILLMOS = 3 --单局击杀野怪数量
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_KILLSOLDIER = 4 --单局击杀小兵数量
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_CONTINWININT = 5 --连续赢得积分赛场次
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_CONTINWIN = 6 --连续赢得对战比赛场次
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_GOLD = 7 --当日累计花费金币
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_JOINBATTLE = 8 --当日参加对战比赛场次
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_TOWER = 9 --当日对战中累计造塔数量
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_MINE = 10 --单局内开分矿次数
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_KILLDRAGEON = 11 --当日对战中杀龙次数
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_WINNUM = 12 --当日对战胜利场次
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_DAY = 13 --日活跃度点数
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_WEEK = 14 --周活跃度点数
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_BUYHERO = 15 --购买一个英雄
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_SOLDIERLEVELUP = 16 --小兵升级一次
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_BUYSKIN = 17 --购买任意一个皮肤
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_SKILLLEVELUP = 18 --召唤师技能升级一次
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_NEWGUIDEBASICS = 19 --任务_新手通关基础教学
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_BUILD_INFANTRY_NUM = 20 --任务_单局建造步兵数量
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_BUILD_CROSSBOWMAN = 21 --任务_单局建造弩兵数量
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_LEVEL_UP_FARM = 22 --任务_单局升级人口次数
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_LEVEL_UP_BASE = 23 --任务_单局升级基地次数
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_USE_SUMMON_SKILL = 24 --任务_单局使用召唤师技能次数
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_DESTORY_TOWER = 25 --任务_单局摧毁防御塔数量
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_MOVE_TARGET = 26 --任务_单局移动目标
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_BUILD_NUN_NUM = 27 --任务_单局建造修女数量
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_WATCHANYVIDEO = 28 --任务_观看任意技巧教学
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_COMPLETE_GUIDESKILL = 51 --任务_完成单个技能教学
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_COMPLETE_ALL_GUIDESKILL = 52 --任务_完成全部技能教学
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_PLAY_RANK = 53 --任务_参加排位赛
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_INVITE_FRIEND_START_GAME = 54 --任务_邀请好友上线
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_DAILY_SHARE_GAME = 55 --任务_每日分享
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_KILL_BOSS = 56 --任务_击杀黑暗泰坦或烈焰战神
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_ARENA_LEVEL_UP = 57 --任务_竞技场升级
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_PAY = 58 --任务_充值
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_DIAMOND_LOTTERY = 59 --任务_抽钻石宝箱
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_TICKET_LOTTERY = 60 --任务_抽点券宝箱
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_KILL_SMALL_BOSS = 61 --任务_击杀烈焰战神
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_KILL_BIG_BOSS = 62 --任务_击杀黑暗泰坦
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_JOINBATTLE_BYHERO = 63 --任务_当日使用某英雄参加对战比赛场次
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_BUY_APPOINT_ITEM = 64 --任务_购买指定物品
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_BUY_APPOINT_HERO = 65 --任务_购买指定英雄
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_SHARE_GAME = 66 --任务_分享游戏
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_PLAYER_LEVEL = 101 --成就_玩家等级
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_MVP = 102 --成就_MVP
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_RACE_TYPE = 103 --成就_种族
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_MULTI_MODE = 104 --成就_多人模式
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_DOGFACE_STAT = 105 --成就_训练小兵
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_RANK_LEVEL = 106 --成就_段位
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_ICON_EDGE = 107 --成就_头像框
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_ADD_HERO = 108 --成就_获得英雄
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_ADD_SKIN = 109 --成就_获得皮肤
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_ADD_MONEY = 110 --成就_获得货币
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_HERO_LEGEND = 111 --成就_英雄传说
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_TEAM_GAME = 112 --成就_组队游戏
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_KILL_BIG_DRAGON = 113 --成就_击杀大龙
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_KILL_SMALL_DRAGON = 114 --成就_击杀小龙
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_ACH_CONTINWIN = 115 --连续赢得对战比赛场次
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_ACH_KILLHERO = 116 --单局击杀英雄数量
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_ACH_KILLSOLDIER = 117 --单局击杀小兵数量
Ds_SystemTaskNeedActType.SYSTEMTASKNEEDACTTYPE_MAX_RANK_LEVEL = 118 --成就_最高段位

Ds_AchievementCounterType = {} --成就计数类型
Ds_AchievementCounterType.ACHCOUNTERTYPE_INC = 0 --成就计数类型_累加
Ds_AchievementCounterType.ACHCOUNTERTYPE_MAXUPDATE = 1 --成就计数类型_最大更新

Ds_UIInterfaceSkipType = {} --系统界面跳转类型
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_NONE = 0 --界面跳转_无
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_RACE = 1 --界面跳转_种族
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_RACE_HUMAN_PROFILE = 2 --界面跳转_人族概况
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_RACE_HUMAN_DOGFACE = 3 --界面跳转_人族小兵
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_RACE_HUMAN_TALENT = 4 --界面跳转_人族天赋
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_RACE_ORC_PROFILE = 5 --界面跳转_兽族概况
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_RACE_ORC_DOGFACE = 6 --界面跳转_兽族小兵
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_RACE_ORC_TALENT = 7 --界面跳转_兽族天赋
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_RACE_GHOST_PROFILE = 8 --界面跳转_亡灵概况
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_RACE_GHOST_DOGFACE = 9 --界面跳转_亡灵小兵
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_RACE_GHOST_TALENT = 10 --界面跳转_亡灵天赋
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_RACE_ELF_PROFILE = 11 --界面跳转_精灵概况
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_RACE_ELF_DOGFACE = 12 --界面跳转_精灵小兵
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_RACE_ELF_TALENT = 13 --界面跳转_精灵天赋
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_STRATEGY = 14 --界面跳转_种族攻略
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_HERO = 20 --界面跳转_英雄
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_HERO_FIGHTER = 21 --界面跳转_英雄战士
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_HERO_TANK = 22 --界面跳转_英雄坦克
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_HERO_MASTER = 23 --界面跳转_英雄法师
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_HERO_SHOOTER = 24 --界面跳转_英雄射手
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_HERO_SUPPORTER = 25 --界面跳转_英雄辅助
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_DOGFACESETTING = 31 --界面跳转_快捷出兵
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_MESSAGESETTING = 32 --界面跳转_快捷消息
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_ACHIEVE = 40 --界面跳转_成就
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_ACHIEVE_UNREACHED = 41 --界面跳转_成就未达成
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_BAG = 50 --界面跳转_背包
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_BAG_PROP = 51 --界面跳转_背包道具
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_BAG_CARD = 52 --界面跳转_背包体验卡
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_TASK = 60 --界面跳转_任务
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_TASK_GROWUP = 61 --界面跳转_成长任务
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_TASK_STRONGER = 62 --界面跳转_我要变强
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_BATTLE = 70 --界面跳转_对战
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_FORFUN = 71 --界面跳转_娱乐模式
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_PVC = 72 --界面跳转_人机练习
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_CUSTOM = 73 --界面跳转_开房间
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_RANK1V1 = 80 --界面跳转_排位1V1
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_RANK2V2 = 81 --界面跳转_排位2V2
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_TRAINING = 90 --界面跳转_训练营
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_TECHNIC = 91 --界面跳转_技巧教学
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_SHOP = 100 --界面跳转_商城
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_SHOPSKIN = 101 --界面跳转_皮肤商城
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_SHOPSKINFARGMENT = 102 --界面跳转_皮肤碎片商城
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_SHOPPROP = 103 --界面跳转_道具商城
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_SHOPCARD = 104 --界面跳转_特权卡
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_SHOPRAFFLE = 105 --界面跳转_战争祭坛
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_SHOPMEDALWAR = 106 --界面跳转_战争勋章商店
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_SHOPMEDALROAR = 107 --界面跳转_怒吼勋章商店
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_SHOPHEROFARGMENT = 108 --界面跳转_英雄碎片商城
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_LIVE = 110 --界面跳转_直播
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_REPLAY = 120 --界面跳转_回看录像
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_GREATREPLAY = 121 --界面跳转_高手观战
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_ACTIVITY = 130 --界面跳转_活动
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_SEVENDAYLOGIN = 131 --界面跳转_七日登录
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_SETTING = 140 --界面跳转_设置
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_OPERATESETTING = 141 --界面跳转_操做设置
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_VOICESETTING = 142 --界面跳转_声音设置
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_NETWORKSETTING = 143 --界面跳转_网络诊断
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_FRIEND = 150 --界面跳转_好友
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_ADDFRIEND = 151 --界面跳转_添加好友
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_FRIENDAPPLY = 152 --界面跳转_好友申请
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_RECHARGE = 160 --界面跳转_充值
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_FIRSTRECHARGE = 161 --界面跳转_首冲
Ds_UIInterfaceSkipType.UIINTERFACESKIPTYPE_RUNE = 162 --界面跳转_战旗

Ds_SystemGrowthGuidanceType = {} --系统成长指导类型
Ds_SystemGrowthGuidanceType.SYSTEMGROWTHGUID_GOLD = 1 --指导_获取金币
Ds_SystemGrowthGuidanceType.SYSTEMGROWTHGUID_HERO = 2 --指导_获取英雄
Ds_SystemGrowthGuidanceType.SYSTEMGROWTHGUID_STRONG = 3 --指导_我要变强

Ds_MainGuideID = {} --新手教学主流程
Ds_MainGuideID.MAINGUIDEID_PVE1 = 1 --新手_PVE关卡1
Ds_MainGuideID.MAINGUIDEID_PVE2 = 2 --新手_PVE关卡2
Ds_MainGuideID.MAINGUIDEID_PVE3 = 3 --新手_PVE关卡3
Ds_MainGuideID.MAINGUIDEID_PVE4 = 4 --新手_PVE关卡4
Ds_MainGuideID.MAINGUIDEID_MATCH = 5 --新手_解锁匹配
Ds_MainGuideID.MAINGUIDEID_TEACH_MATCH = 6 --新手_匹配教学
Ds_MainGuideID.MAINGUIDEID_SEVENDAYLOGIN = 7 --新手_解锁七日登录
Ds_MainGuideID.MAINGUIDEID_FIRSTRECHARGE = 8 --新手_解锁首冲
Ds_MainGuideID.MAINGUIDEID_ACTIVITY = 9 --新手_解锁活动
Ds_MainGuideID.MAINGUIDEID_TASK = 10 --新手_解锁任务
Ds_MainGuideID.MAINGUIDEID_TRAIN = 11 --新手_解锁训练营
Ds_MainGuideID.MAINGUIDEID_SHOP = 12 --新手_解锁商城
Ds_MainGuideID.MAINGUIDEID_ACHIEVE = 13 --新手_解锁成就
Ds_MainGuideID.MAINGUIDEID_ARMYSETTING = 14 --新手_解锁快捷出兵
Ds_MainGuideID.MAINGUIDEID_RUNE = 15 --新手_解锁战旗
Ds_MainGuideID.MAINGUIDEID_MAX = 18 --新手_最大值

Ds_NewGuideEventType = {} --新手教学事件定义
Ds_NewGuideEventType.NEWGUIDE_CLICK_NONE = 0 --
Ds_NewGuideEventType.NEWGUIDE_MOVE_JOYSTICK = 1 --新手教学转动转盘
Ds_NewGuideEventType.NEWGUIDE_CLICK_CONVERGE = 2 --新手教学点击集火
Ds_NewGuideEventType.NEWGUIDE_CLICK_RETREAT = 3 --新手教学点击撤退
Ds_NewGuideEventType.NEWGUIDE_CLICK_NORMALSKILL = 4 --新手教学点击攻击
Ds_NewGuideEventType.NEWGUIDE_COVER = 5 --新手教学透明蒙板
Ds_NewGuideEventType.NEWGUIDE_SHOW_CONVERGE_EFFECT = 6 --显示集火特效
Ds_NewGuideEventType.NEWGUIDE_SHOW_RETREAT_EFFECT = 7 --显示撤退特效
Ds_NewGuideEventType.NEWGUIDE_RETREAT_INTRODUCE = 8 --撤退说明
Ds_NewGuideEventType.NEWGUIDE_MOVE_JOYSTICK_RETREAT = 9 --转动轮盘撤退
Ds_NewGuideEventType.NEWGUIDE_RETREAT_NOTICE = 10 --撤退提示
Ds_NewGuideEventType.NEWGUIDE_CLICK_TECH_VIEW = 11 --点击科技界面
Ds_NewGuideEventType.NEWGUIDE_CLICK_ARM = 12 --点击士兵头像
Ds_NewGuideEventType.NEWGUIDE_CLICK_TRAIN_DWARFINFANTRY = 13 --点击训练矮人步兵
Ds_NewGuideEventType.NEWGUIDE_SHOW_TRAIN_PROGRESS = 14 --显示训练进度
Ds_NewGuideEventType.NEWGUIDE_CLICK_TECH_TOGGLE = 15 --点击科技页签
Ds_NewGuideEventType.NEWGUIDE_CLICK_FOOD_ICON = 16 --点击人口图标
Ds_NewGuideEventType.NEWGUIDE_CLICK_LEVEL_UP_BTN = 17 --点击升级按钮
Ds_NewGuideEventType.NEWGUIDE_SHOW_FOOD_CHANGE = 18 --显示人口变化
Ds_NewGuideEventType.NEWGUIDE_CLICK_TRAIN_TOGGLE = 19 --点击训练页签
Ds_NewGuideEventType.NEWGUIDE_CLICK_TRAIN_CROSSBOWMAN = 20 --点击训练弩手
Ds_NewGuideEventType.NEWGUIDE_CLICK_CLOSE_TRAIN_VIEW = 21 --点击关闭训练界面
Ds_NewGuideEventType.NEWGUIDE_CLICK_NORMAL_ATTACK = 31 --点击普攻(弱引导)
Ds_NewGuideEventType.NEWGUIDE_BUILD_GOLD_MINE = 32 --点击金矿建造
Ds_NewGuideEventType.NEWGUIDE_GOLD_MINE_STATE = 33 --金矿建造状态
Ds_NewGuideEventType.NEWGUIDE_CLICK_TOWER_BAR = 34 --点击防御塔栏
Ds_NewGuideEventType.NEWGUIDE_CLICK_BUILD_TOWER = 35 --点击建造防御塔
Ds_NewGuideEventType.NEWGUIDE_CLICK_REPAIR_BTN = 36 --点击维修按钮
Ds_NewGuideEventType.NEWGUIDE_CLICK_CASTLE = 41 --点击城堡图标
Ds_NewGuideEventType.NEWGUIDE_CLICK_CASTLE_LEVELUP = 42 --点击城堡升级按钮
Ds_NewGuideEventType.NEWGUIDE_CLICK_TRAIN_CURE = 43 --点击修女训练图标
Ds_NewGuideEventType.NEWGUIDE_CLICK_CURE_TRAIN_BTN = 44 --点击训练修女
Ds_NewGuideEventType.NEWGUIDE_SHOW_SMALL_DRAGON = 45 --标注小龙位置
Ds_NewGuideEventType.NEWGUIDE_CLICK_EQUIP = 46 --点击装备拾取栏
Ds_NewGuideEventType.NEWGUIDE_SHOW_ENEMY_BASE = 47 --标注敌方基地
Ds_NewGuideEventType.NEWGUIDE_GET_BIG_DRAGON_NOTIFY = 48 --获取统帅之刃提示
Ds_NewGuideEventType.NEWGUIDE_GET_BIG_DRAGON = 49 --获取统帅之刃
Ds_NewGuideEventType.NEWGUIDE_SHOW_MATCH_DESC = 120 --显示匹配描述
Ds_NewGuideEventType.NEWGUIDE_CLICK_MATCH_BUTTON = 121 --点击匹配按钮
Ds_NewGuideEventType.NEWGUIDE_SHOW_ARENA_DESC = 122 --显示竞技场描述
Ds_NewGuideEventType.NEWGUIDE_CLICK_ARENA_BUTTON = 123 --点击竞技场按钮
Ds_NewGuideEventType.NEWGUIDE_CLICK_TASK_BUTTON = 130 --点击任务按钮
Ds_NewGuideEventType.NEWGUIDE_SHOW_LEVEL_UNLOCK = 131 --标注等级解锁新功能
Ds_NewGuideEventType.NEWGUIDE_CLICK_LEVEL_REWARD_BUTTON = 132 --点击等级奖励领取按钮
Ds_NewGuideEventType.NEWGUIDE_CLICK_TRAINCAMP_BUTTON = 140 --点击训练营按钮
Ds_NewGuideEventType.NEWGUIDE_CLICK_GUIDE_SKILL_BUTTON = 141 --点击技巧教学按钮
Ds_NewGuideEventType.NEWGUIDE_CLICK_GUIDE_SKILL_PLAY_BUTTON = 142 --点击开始播放按钮
Ds_NewGuideEventType.NEWGUIDE_CLICK_SHOP_BUTTON = 150 --点击商城按钮
Ds_NewGuideEventType.NEWGUIDE_SHOW_SHOP_DESC = 151 --显示商城描述
Ds_NewGuideEventType.NEWGUIDE_SHOW_ACHIEVE_DESC = 160 --显示成就描述
Ds_NewGuideEventType.NEWGUIDE_CLICK_ACHIEVE_BUTTON = 161 --点击成就按钮
Ds_NewGuideEventType.NEWGUIDE_CLICK_ACHIEVE_REWARD_BUTTON = 162 --点击成就奖励领取按钮
Ds_NewGuideEventType.NEWGUIDE_CLICK_PREPAREFORWAR_BUTTON = 170 --点击备战按钮
Ds_NewGuideEventType.NEWGUIDE_CLICK_ARMYSETTING_BUTTON = 171 --点击快捷出兵按钮
Ds_NewGuideEventType.NEWGUIDE_PLAY_ARMYSETTING_VIDEO = 172 --播放快捷出兵视频
Ds_NewGuideEventType.NEWGUIDE_SHOW_SEVENDAYLOGIN = 180 --显示七日登录界面
Ds_NewGuideEventType.NEWGUIDE_HIDE_SEVENDAYLOGIN = 181 --关闭七日登录界面
Ds_NewGuideEventType.NEWGUIDE_SHOW_FIRSTRECHARGE = 190 --显示首冲界面
Ds_NewGuideEventType.NEWGUIDE_HIDE_FIRSTRECHARGE = 191 --关闭首冲界面
Ds_NewGuideEventType.NEWGUIDE_SHOW_ACTIVITY = 200 --显示活动界面
Ds_NewGuideEventType.NEWGUIDE_HIDE_ACTIVITY = 201 --关闭活动界面
Ds_NewGuideEventType.NEWGUIDE_CLICK_BEGIN_BUTTON = 210 --点击开始匹配按钮
Ds_NewGuideEventType.NEWGUIDE_CLICK_READY_BUTTON = 211 --点击准备按钮
Ds_NewGuideEventType.NEWGUIDE_CLICK_RACE_BUTTON = 212 --点击种族
Ds_NewGuideEventType.NEWGUIDE_CLICK_RACE_SKILL = 213 --点击种族技能
Ds_NewGuideEventType.NEWGUIDE_SELECT_HERO_NOTIFY = 214 --英雄选择提示
Ds_NewGuideEventType.NEWGUIDE_CLICK_HERO_BUTTON = 215 --点击英雄
Ds_NewGuideEventType.NEWGUIDE_CLICK_HERO_SKILL = 216 --点击英雄技能
Ds_NewGuideEventType.NEWGUIDE_HERO_SURE_NOTIFY = 217 --英雄确定提示
Ds_NewGuideEventType.NEWGUIDE_CLICK_HERO_SURE = 218 --确定英雄
Ds_NewGuideEventType.NEWGUIDE_VICTORY_CONDITION = 219 --胜利条件提示
Ds_NewGuideEventType.NEWGUIDE_MAP_INTRODUCE = 220 --地图介绍
Ds_NewGuideEventType.NEWGUIDE_FIGHT_WILD_NOTIFY = 221 --打野路线提示
Ds_NewGuideEventType.NEWGUIDE_PICK_EQUIPMENT = 222 --拾取装备提示
Ds_NewGuideEventType.NEWGUIDE_ATTACK_GOLDMINE = 223 --进攻金矿提示
Ds_NewGuideEventType.NEWGUIDE_TRAIN_DOGFACE = 224 --训练小兵提示
Ds_NewGuideEventType.NEWGUIDE_CLICK_OPEN_TECH_BUTTON = 225 --点击打开科技界面按钮
Ds_NewGuideEventType.NEWGUIDE_CLICK_DOGFACE = 226 --点击小兵
Ds_NewGuideEventType.NEWGUIDE_CLICK_TRAIN_BUTTON = 227 --点击训练按钮
Ds_NewGuideEventType.NEWGUIDE_REPAIR_COST_NOTIFY = 228 --高维修费用通知
Ds_NewGuideEventType.NEWGUIDE_GOLDMINE_INTRODUCE = 229 --金矿介绍
Ds_NewGuideEventType.NEWGUIDE_CLICK_GOLDMINE_BUTTON = 230 --点击金矿建造按钮
Ds_NewGuideEventType.NEWGUIDE_CLICK_TOWERBAR_BUTTON = 231 --点击防御塔栏
Ds_NewGuideEventType.NEWGUIDE_BIG_DRAGON_SPAWN = 232 --大龙出生提示
Ds_NewGuideEventType.NEWGUIDE_BIG_DRAGON_INTRODUCE = 233 --大龙介绍
Ds_NewGuideEventType.NEWGUIDE_USE_BIG_DRAGON = 234 --召唤大龙
Ds_NewGuideEventType.NEWGUIDE_CLICK_TP_BUTTON = 235 --点击回城按钮
Ds_NewGuideEventType.NEWGUIDE_SMALL_DRAGON_SPAWN = 236 --小龙出生提示
Ds_NewGuideEventType.NEWGUIDE_SMALL_DRAGON_INTRODUCE = 237 --小龙介绍
Ds_NewGuideEventType.NEWGUIDE_ATTACK_BASE_NOTIFY = 238 --进攻敌方基地
Ds_NewGuideEventType.NEWGUIDE_PICK_DRAGON_EGG = 239 --拾取统帅之刃
Ds_NewGuideEventType.NEWGUIDE_CAST_DRAGON_EGG = 240 --使用统帅之刃
Ds_NewGuideEventType.NEWGUIDE_UPGRADE_FOOD = 241 --升级人口提示
Ds_NewGuideEventType.NEWGUIDE_UPGRADE_BASE = 242 --升级基地提示
Ds_NewGuideEventType.NEWGUIDE_WELCOME_TO_GAME = 243 --欢迎来到战争怒吼
Ds_NewGuideEventType.NEWGUIDE_MONSTER_INTRODUCE = 244 --野怪介绍
Ds_NewGuideEventType.NEWGUIDE_BASE_PROTECT = 245 --主基地保护机制
Ds_NewGuideEventType.NEWGUIDE_CLICK_RUNE = 260 --点击战旗按钮
Ds_NewGuideEventType.NEWGUIDE_CLICK_RUNE_SHOP = 261 --点击战旗室按钮
Ds_NewGuideEventType.NEWGUIDE_CLICK_RUNE_ICON = 262 --点击战旗图标
Ds_NewGuideEventType.NEWGUIDE_CLICK_RUNE_BUY = 263 --点击战旗购买按钮
Ds_NewGuideEventType.NEWGUIDE_CLICK_RUNE_SURE = 264 --点击战旗确定按钮
Ds_NewGuideEventType.NEWGUIDE_CLICK_RUNE_FIT = 265 --点击战旗装配按钮
Ds_NewGuideEventType.NEWGUIDE_CLICK_RUNE_SLOT = 266 --点击战旗插槽
Ds_NewGuideEventType.NEWGUIDE_CLICK_RUNE_SET = 267 --点击镶嵌战旗
Ds_NewGuideEventType.NEWGUIDE_SHOW_RUNE_DESC = 268 --展示战旗描述

Ds_SystemVoicer = {} --播报者
Ds_SystemVoicer.SystemVoicer_HERO = 0 --播报者_英雄
Ds_SystemVoicer.SystemVoicer_ACTOR = 1 --播报者_声优

Ds_ResTastType = {} --任务系统类型
Ds_ResTastType.RESTASKTYPE_BRANCH = 0 --支线任务
Ds_ResTastType.RESTASKTYPE_TRUNK = 1 --主线任务

Ds_ResGuideBattleTastActiveType = {} --新手战斗任务激活类型
Ds_ResGuideBattleTastActiveType.RESGUIDEBATTLETASTACTIVETYPE_ENTERBATTLE = 1 --新手战斗任务激活类型_进入战斗
Ds_ResGuideBattleTastActiveType.RESGUIDEBATTLETASTACTIVETYPE_BFTASKCOMPLETE = 2 --新手战斗任务激活类型_前置任务完成
Ds_ResGuideBattleTastActiveType.RESGUIDEBATTLETASTACTIVETYPE_GOD = 10 --新手战斗任务激活类型_GOD,默认激活

Ds_ResGuideBattleTastCompleteType = {} --新手战斗任务完成类型
Ds_ResGuideBattleTastCompleteType.RESGUIDEBATTLETASTCOMPLETETYPE_KILLACTOR = 1 --新手战斗任务完成类型_击杀指定怪物
Ds_ResGuideBattleTastCompleteType.RESGUIDEBATTLETASTCOMPLETETYPE_TRAINACTOR = 2 --新手战斗任务完成类型_训练指定单位
Ds_ResGuideBattleTastCompleteType.RESGUIDEBATTLETASTCOMPLETETYPE_KILLACTORGROUP = 3 --新手战斗任务完成类型_击杀指定怪物组
Ds_ResGuideBattleTastCompleteType.RESGUIDEBATTLETASTCOMPLETETYPE_STUDYACTORTECH = 4 --新手战斗任务完成类型_研究指定科技
Ds_ResGuideBattleTastCompleteType.RESGUIDEBATTLETASTCOMPLETETYPE_BUILDCOMPLETE = 5 --新手战斗任务完成类型_建筑建造完成
Ds_ResGuideBattleTastCompleteType.RESGUIDEBATTLETASTCOMPLETETYPE_REPAIR = 6 --新手战斗任务完成类型_维修指定单位
Ds_ResGuideBattleTastCompleteType.RESGUIDEBATTLETASTCOMPLETETYPE_MISSKILATK = 7 --新手战斗任务完成类型_躲避技能攻击
Ds_ResGuideBattleTastCompleteType.RESGUIDEBATTLETASTCOMPLETETYPE_BUILD_ORE_GOLDNUM = 8 --新手战斗任务完成类型_金矿开采数量
Ds_ResGuideBattleTastCompleteType.RESGUIDEBATTLETASTCOMPLETETYPE_GOLD = 10 --新手战斗任务完成类型_GOD,默认激活

Ds_StoryBreakType = {} --新手剧情终止类型
Ds_StoryBreakType.RESSTORYBREAKTYPE_NOTSKIP = 0 --不可跳过
Ds_StoryBreakType.RESSTORYBREAKTYPE_SKIPGROUP = 1 --跳过剧情组

Ds_ResGuideUnLockSystemType = {} --新手解锁系统类型
Ds_ResGuideUnLockSystemType.RESGUIDEUNLOCKSYSTEMTYPE_NONE = 0 --新手解锁系统_无
Ds_ResGuideUnLockSystemType.RESGUIDEUNLOCKSYSTEMTYPE_TASK = 1 --新手解锁系统_任务
Ds_ResGuideUnLockSystemType.RESGUIDEUNLOCKSYSTEMTYPE_TRAIN = 2 --新手解锁系统_训练营
Ds_ResGuideUnLockSystemType.RESGUIDEUNLOCKSYSTEMTYPE_SHOP = 3 --新手解锁系统_商城
Ds_ResGuideUnLockSystemType.RESGUIDEUNLOCKSYSTEMTYPE_ACHIEVE = 4 --新手解锁系统_成就
Ds_ResGuideUnLockSystemType.RESGUIDEUNLOCKSYSTEMTYPE_ARMYSETTING = 5 --新手解锁系统_快捷出兵
Ds_ResGuideUnLockSystemType.RESGUIDEUNLOCKSYSTEMTYPE_RANK = 6 --新手解锁系统_排位
Ds_ResGuideUnLockSystemType.RESGUIDEUNLOCKSYSTEMTYPE_RANK1V1 = 7 --新手解锁系统_排位1V1
Ds_ResGuideUnLockSystemType.RESGUIDEUNLOCKSYSTEMTYPE_RANK2V2 = 8 --新手解锁系统_排位2V2
Ds_ResGuideUnLockSystemType.RESGUIDEUNLOCKSYSTEMTYPE_MATCH = 9 --新手解锁系统_匹配
Ds_ResGuideUnLockSystemType.RESGUIDEUNLOCKSYSTEMTYPE_MATCH1V1 = 10 --新手解锁系统_匹配1V1
Ds_ResGuideUnLockSystemType.RESGUIDEUNLOCKSYSTEMTYPE_MATCH2V2 = 11 --新手解锁系统_匹配2V2
Ds_ResGuideUnLockSystemType.RESGUIDEUNLOCKSYSTEMTYPE_PVC = 12 --新手解锁系统_人机
Ds_ResGuideUnLockSystemType.RESGUIDEUNLOCKSYSTEMTYPE_PVC1V1 = 13 --新手解锁系统_人机1V1
Ds_ResGuideUnLockSystemType.RESGUIDEUNLOCKSYSTEMTYPE_PVC2V2 = 14 --新手解锁系统_人机2V2
Ds_ResGuideUnLockSystemType.RESGUIDEUNLOCKSYSTEMTYPE_FORFUN = 15 --新手解锁系统_娱乐
Ds_ResGuideUnLockSystemType.RESGUIDEUNLOCKSYSTEMTYPE_FORFUN1V1 = 16 --新手解锁系统_娱乐1V1
Ds_ResGuideUnLockSystemType.RESGUIDEUNLOCKSYSTEMTYPE_FORFUN2V2 = 17 --新手解锁系统_娱乐2V2
Ds_ResGuideUnLockSystemType.RESGUIDEUNLOCKSYSTEMTYPE_FORFUN3V3 = 18 --新手解锁系统_娱乐2V2
Ds_ResGuideUnLockSystemType.RESGUIDEUNLOCKSYSTEMTYPE_CUSTOM = 19 --新手解锁系统_开房间
Ds_ResGuideUnLockSystemType.RESGUIDEUNLOCKSYSTEMTYPE_CUSTOM1V1 = 20 --新手解锁系统_开房间1V1
Ds_ResGuideUnLockSystemType.RESGUIDEUNLOCKSYSTEMTYPE_CUSTOM2V2 = 21 --新手解锁系统_开房间2V2
Ds_ResGuideUnLockSystemType.RESGUIDEUNLOCKSYSTEMTYPE_SEVENDAYLOGIN = 22 --新手解锁系统_七日登录
Ds_ResGuideUnLockSystemType.RESGUIDEUNLOCKSYSTEMTYPE_FIRSTRECHARGE = 23 --新手解锁系统_首冲
Ds_ResGuideUnLockSystemType.RESGUIDEUNLOCKSYSTEMTYPE_ACTIVITY = 24 --新手解锁系统_活动
Ds_ResGuideUnLockSystemType.RESGUIDEUNLOCKSYSTEMTYPE_FALLRUINS = 25 --新手解锁系统_陨落遗迹
Ds_ResGuideUnLockSystemType.RESGUIDEUNLOCKSYSTEMTYPE_LOSTDESERT = 26 --新手解锁系统_迷失沙漠
Ds_ResGuideUnLockSystemType.RESGUIDEUNLOCKSYSTEMTYPE_RUNE = 27 --新手解锁系统_战旗

Ds_ShopBuyGoodsCostType = {} --购买方式
Ds_ShopBuyGoodsCostType.Coupon = 1 --消耗_点券
Ds_ShopBuyGoodsCostType.GoldOrDiamond = 2 --消耗_金币或钻石
Ds_ShopBuyGoodsCostType.CouponOrGold = 3 --消耗_点券或金币
Ds_ShopBuyGoodsCostType.Activity = 4 --消耗_活动获取
Ds_ShopBuyGoodsCostType.None = 5 --消耗_无

Ds_GiftOpenWay = {} --礼包打开方式
Ds_GiftOpenWay.GiftOpenWay_OnlyItem = 1 --礼包_道具
Ds_GiftOpenWay.GiftOpenWay_IncludeHero = 2 --礼包_英雄
Ds_GiftOpenWay.GiftOpenWay_Other = 3 --礼包_其他

Ds_MoneyType = {} --货币类型
Ds_MoneyType.MONEYTYPE_GOLD = 1 --金币
Ds_MoneyType.MONEYTYPE_DIAMOND = 2 --钻石
Ds_MoneyType.MONEYTYPE_TICKET = 3 --点券
Ds_MoneyType.MONEYTYPE_DAY_ACTIVE_POINT = 4 --日活跃度
Ds_MoneyType.MONEYTYPE_WEEK_ACTIVE_POINT = 5 --周活跃度
Ds_MoneyType.MONEYTYPE_SIGNET_FRAGMENT = 6 --纹章碎片
Ds_MoneyType.MONEYTYPE_HERO_FRAGMENT = 7 --英雄碎片(道具)
Ds_MoneyType.MONEYTYPE_SKIN_FRAGMENT = 8 --皮肤碎片(道具)
Ds_MoneyType.MONEYTYPE_WAR_MEDAL = 9 --战争勋章
Ds_MoneyType.MONEYTYPE_ROAR_MEDAL = 10 --怒吼勋章
Ds_MoneyType.MONEYTYPE_HERO_RUNE_FRAGMENT = 11 --英雄符文碎片
Ds_MoneyType.MONEYTYPE_RACE_RUNE_FRAGMENT = 12 --种族符文碎片

Ds_ChatChannelType = {} --聊天频道
Ds_ChatChannelType.CHATCHANNEL_BIG_HORN = 1 --聊天频道_大喇叭
Ds_ChatChannelType.CHATCHANNEL_SMALL_HORN = 2 --聊天频道_小喇叭
Ds_ChatChannelType.CHATCHANNEL_HALL = 3 --聊天频道_大厅频道
Ds_ChatChannelType.CHATCHANNEL_FRIENDS = 4 --聊天频道_好友频道
Ds_ChatChannelType.CHATCHANNEL_TONG = 5 --聊天频道_公会频道
Ds_ChatChannelType.CHATCHANNEL_BATTLE_TEAM = 6 --聊天频道_战斗队伍频道
Ds_ChatChannelType.CHATCHANNEL_BATTLE_ALL = 7 --聊天频道_战斗全局频道
Ds_ChatChannelType.CHATCHANNEL_SYSTEM = 8 --聊天频道_系统公告
Ds_ChatChannelType.CHATCHANNEL_MATCH_TEAM = 9 --聊天频道_匹配队伍频道
Ds_ChatChannelType.CHATCHANNEL_CUSTOM_ROOM = 10 --聊天频道_开房间频道

Ds_GlobalParameterType = {} --游戏全局参数类型
Ds_GlobalParameterType.GLOBALPARAMETERE_WEEK_BATTLE_GOLD_TOPLIMIT = 1 --每周通过对战获得金币初始上限
Ds_GlobalParameterType.GLOBALPARAMETERE_WEEK_ALL_GOLD_TOPLIMIT = 2 --每周金币绝对上限
Ds_GlobalParameterType.GLOBALPARAMETERE_WEEK_ALL_EXP_TOPLIMIT = 3 --每周经验绝对上限
Ds_GlobalParameterType.GLOBALPARAMETERE_CREDIT_ADD_WEEK_BATTLE_GOLD_TOPLIMIT = 4 --对战信用奖励对战获得金币上限
Ds_GlobalParameterType.GLOBALPARAMETERE_CREDIT_REDUCE_WEEK_BATTLE_GOLD_TOPLIMIT = 5 --对战信用降低对战获得金币上限
Ds_GlobalParameterType.GLOBALPARAMETERE_BIG_HORN = 6 --大喇叭
Ds_GlobalParameterType.GLOBALPARAMETERE_SMALL_HORN = 7 --小喇叭
Ds_GlobalParameterType.GLOBALPARAMETERE_CHAT_HALL_CD = 8 --大厅聊天冷却CD
Ds_GlobalParameterType.GLOBALPARAMETERE_HERO_MASTERY_TOPLIMIT = 9 --英雄熟练度上限
Ds_GlobalParameterType.GLOBALPARAMETERE_REAL_AUTH_REWARD = 10 --英雄熟练度上限
Ds_GlobalParameterType.GLOBALPARAMETERE_FIRST_PAY = 11 --首充奖励
Ds_GlobalParameterType.GLOBALPARAMETERE_NEWBIE_TIME = 12 --新手活动时间
Ds_GlobalParameterType.GLOBALPARAMETERE_WARMGAME_1ST = 13 --新号第一把温暖局
Ds_GlobalParameterType.GLOBALPARAMETERE_WARMGAME_2ND = 14 --新号第二把温暖局
Ds_GlobalParameterType.GLOBALPARAMETERE_RUNE_PRICE = 15 --购买战旗价格

Ds_ServerParameterType = {} --服务器参数类型
Ds_ServerParameterType.SERVERPARAMETERE_IOS_CLIENT_VERSION = 1 --客户端苹果版本号
Ds_ServerParameterType.SERVERPARAMETERE_ANDROID_CLIENT_VERSION = 2 --客户端安卓版本号

Ds_BasicState = {} --玩家基础状态
Ds_BasicState.BASICSTATE_LOBBY = 0 --大厅中
Ds_BasicState.BASICSTATE_QUEUE = 1 --组队中
Ds_BasicState.BASICSTATE_ROOM = 2 --选人中
Ds_BasicState.BASICSTATE_BATTLE = 3 --游戏中
Ds_BasicState.BASICSTATE_BATTLE_AWARD = 4 --游戏结算中
Ds_BasicState.BASICSTATE_NEW_GUIDE = 5 --新手教学中
Ds_BasicState.BASICSTATE_NONET_BATTLE = 6 --无网络游戏中
Ds_BasicState.BASICSTATE_WATCH_RECORD = 7 --观看录像中
Ds_BasicState.BASICSTATE_BATTLE_GROUPING = 8 --开黑中

Ds_GameType = {} --比赛类型
Ds_GameType.GAMETYPE_MATCH = 0 --匹配比赛
Ds_GameType.GAMETYPE_RANK = 1 --排位比赛

Ds_SystemVsMode = {} --对战模式
Ds_SystemVsMode.SYSTEMVSMODE_ALL = 0 --对战模式_所有
Ds_SystemVsMode.SYSTEMVSMODE_RANK = 1 --对战模式_排位
Ds_SystemVsMode.SYSTEMVSMODE_MATCH = 2 --对战模式_匹配
Ds_SystemVsMode.SYSTEMVSMODE_PVC = 3 --对战模式_人机
Ds_SystemVsMode.SYSTEMVSMODE_CUSTOM = 4 --对战模式_自定义
Ds_SystemVsMode.SYSTEMVSMODE_FORFUN = 5 --对战模式_娱乐模式

Ds_SystemMutiPlayMode = {} --对战人数模式
Ds_SystemMutiPlayMode.SYTEMVSMUTIPLAYMODE_ALL = 0 --对战人数模式_所有
Ds_SystemMutiPlayMode.SYTEMVSMUTIPLAYMODE_1V1 = 1 --对战人数模式_1V1
Ds_SystemMutiPlayMode.SYTEMVSMUTIPLAYMODE_2V2 = 2 --对战人数模式_2V2
Ds_SystemMutiPlayMode.SYTEMVSMUTIPLAYMODE_3V3 = 3 --对战人数模式_3V3

Ds_CustomRoomMode = {} --开房间模式
Ds_CustomRoomMode.CUSTOMROOMMODE_1v1 = 1 --1v1
Ds_CustomRoomMode.CUSTOMROOMMODE_2v2 = 2 --2v2
Ds_CustomRoomMode.CUSTOMROOMMODE_3v3 = 3 --3v3

Ds_FriendSyncType = {} --好友状态同步类型
Ds_FriendSyncType.FRIENDSYNCTYPE_ONLINE = 1 --在线状态
Ds_FriendSyncType.FRIENDSYNCTYPE_STATE = 2 --游戏状态
Ds_FriendSyncType.FRIENDSYNCTYPE_ICON = 3 --头像
Ds_FriendSyncType.FRIENDSYNCTYPE_ICON_EDGE = 4 --头像框
Ds_FriendSyncType.FRIENDSYNCTYPE_COUNTRY = 5 --国籍
Ds_FriendSyncType.FRIENDSYNCTYPE_RANK_LEVEL = 6 --段位
Ds_FriendSyncType.FRIENDSYNCTYPE_LOGOUT_TIME = 7 --登出时间
Ds_FriendSyncType.FRIENDSYNCTYPE_LEVEL = 8 --等级

Ds_RoleType = {} --角色类型
Ds_RoleType.ROLETYPE_PLAYER = 1 --角色类型_玩家
Ds_RoleType.ROLETYPE_COMPUTER = 2 --角色类型_电脑
Ds_RoleType.ROLETYPE_VIRTUAL = 3 --角色类型_虚拟人

Ds_SystemPackageUseType = {} --礼包使用类型
Ds_SystemPackageUseType.SYSTEMPACKAGE_MANUALUSE = 0 --手动使用
Ds_SystemPackageUseType.SYSTEMPACKAGE_AUTOUSE = 1 --自动使用

Ds_SystemPackageRandomType = {} --礼包随机类型
Ds_SystemPackageRandomType.SYSTEMPACKAGE_RANDOM_ALL = 0 --全概率抽取
Ds_SystemPackageRandomType.SYSTEMPACKAGE_RANDOM_SINGLE = 1 --独立概率抽取

Ds_CreditReportType = {} --信用投票类型
Ds_CreditReportType.CREDITREPORTTYPE_HANGUP = 1 --信用投票类型_恶意挂机
Ds_CreditReportType.CREDITREPORTTYPE_PASSIVE = 2 --信用投票类型_消极游戏
Ds_CreditReportType.CREDITREPORTTYPE_ABUSE = 4 --信用投票类型_言语辱骂
Ds_CreditReportType.CREDITREPORTTYPE_CHEAT = 8 --信用投票类型_使用外挂

Ds_MailMainType = {} --邮件主类型
Ds_MailMainType.MAILMAINTYPE_SYSTEM = 1 --邮件主类型_系统
Ds_MailMainType.MAILMAINTYPE_SOCIATY = 2 --邮件主类型_公会
Ds_MailMainType.MAILMAINTYPE_FRIEND = 3 --邮件主类型_好友
Ds_MailMainType.MAILMAINTYPE_QUALIFIER = 4 --邮件主类型_排位赛
Ds_MailMainType.MAILMAINTYPE_MESSAGE = 5 --邮件主类型_消息

Ds_MailSubType = {} --邮件子类型
Ds_MailSubType.MAILSUBTYPE_SERVERNOTIFY = 1 --邮件子类型_服务器通知
Ds_MailSubType.MAILSUBTYPE_FESTIVALAWARDS = 2 --邮件子类型_节日奖励
Ds_MailSubType.MAILSUBTYPE_VIPRITESPACKAGE = 3 --邮件子类型_VIP周礼包
Ds_MailSubType.MAILSUBTYPE_VIPONETIMEREWARD = 4 --邮件子类型_VIP一次性奖励
Ds_MailSubType.MAILSUBTYPE_HEROCARDFAILS = 5 --邮件子类型_英雄体验卡失效
Ds_MailSubType.MAILSUBTYPE_SKINCARDFAILS = 6 --邮件子类型_皮肤体验卡失效
Ds_MailSubType.MAILSUBTYPE_CREDITSCORE = 7 --邮件子类型_对战信用扣分
Ds_MailSubType.MAILSUBTYPE_SUSPENDNOTICE = 8 --邮件子类型_禁赛通知
Ds_MailSubType.MAILSUBTYPE_REPORTSUCCESS = 9 --邮件子类型_成功举报
Ds_MailSubType.MAILSUBTYPE_REPORTFEEDBACK = 10 --邮件子类型_举报反馈
Ds_MailSubType.MAILSUBTYPE_GUILDREWARD = 11 --邮件子类型_公会奖励
Ds_MailSubType.MAILSUBTYPE_GUILDWEEKLY = 12 --邮件子类型_公会周报
Ds_MailSubType.MAILSUBTYPE_FRIENDSGIVEGOLD = 13 --邮件子类型_好友赠送金币
Ds_MailSubType.MAILSUBTYPE_RECEIVEQUALIFIERAWARD = 14 --邮件子类型_排位赛奖励领取
Ds_MailSubType.MAILSUBTYPE_SQUADINVITE = 15 --邮件子类型_邀请组队

Ds_RankType = {} --排行榜类型
Ds_RankType.RANKTYPE_QUALIFYING_1v1 = 1 --1v1排位赛榜单
Ds_RankType.RANKTYPE_QUALIFYING_2v2 = 2 --2v2排位赛榜单
Ds_RankType.RANKTYPE_FRIEND = 3 --好友榜单

Ds_GuideSkillType = {} --技巧类型
Ds_GuideSkillType.GUIDE_SKILL_BASICS = 1 --技巧类型_基础
Ds_GuideSkillType.GUIDE_SKILL_MIDDLE = 2 --技巧类型_进阶
Ds_GuideSkillType.GUIDE_SKILL_HIGH = 3 --技巧类型_高级

Ds_RaceSkillType = {} --种族技能类型
Ds_RaceSkillType.RACE_SKILL_TALENT = 1 --种族天赋技能
Ds_RaceSkillType.RACE_SKILL_SPY = 2 --种族侦查技能

Ds_MonthCardType = {} --月卡类型
Ds_MonthCardType.MONTH_CARD_SILVER = 1 --白银月卡
Ds_MonthCardType.MONTH_CARD_GOLD = 2 --黄金月卡

Ds_MatchOpenTimeType = {} --赛事开放时间类型
Ds_MatchOpenTimeType.MATCHOPENTIMETYPE_ALL = 0 --赛事开放时间_全开
Ds_MatchOpenTimeType.MATCHOPENTIMETYPE_DAY = 1 --赛事开放时间_天
Ds_MatchOpenTimeType.MATCHOPENTIMETYPE_WEEK = 2 --赛事开放时间_周

Ds_ShopSheet = {} --商城分页
Ds_ShopSheet.SHOPSHEET_HERO = 1 --商城分页_英雄
Ds_ShopSheet.SHOPSHEET_SKIN = 2 --商城分页_皮肤
Ds_ShopSheet.SHOPSHEET_ITEM = 3 --商城分页_道具
Ds_ShopSheet.SHOPSHEET_DISCOUNT = 4 --商城分页_折扣
Ds_ShopSheet.SHOPSHEET_NEWBIE = 5 --商城分页_新手礼包
Ds_ShopSheet.SHOPSHEET_HEROFARGMENT = 6 --商城分页_英雄碎片
Ds_ShopSheet.SHOPSHEET_SKINFARGMENT = 7 --商城分页_皮肤碎片
Ds_ShopSheet.SHOPSHEET_RAFFLEWARMEDAL = 8 --商城分页_战争勋章
Ds_ShopSheet.SHOPSHEET_RAFFLEROARMEDAL = 9 --商城分页_怒吼勋章

Ds_ShopLimitType = {} --商城限购周期
Ds_ShopLimitType.SHOPLIMITTYPE_NONE = 0 --商城限购周期_无
Ds_ShopLimitType.SHOPLIMITTYPE_DAILY = 1 --商城限购周期_每日
Ds_ShopLimitType.SHOPLIMITTYPE_WEEKLY = 2 --商城限购周期_每周
Ds_ShopLimitType.SHOPLIMITTYPE_FOREVER = 3 --商城限购周期_永久
Ds_ShopLimitType.SHOPLIMITTYPE_MONTH = 4 --商城限购周期_每月

Ds_SeasonReward = {} --赛季奖励
Ds_SeasonReward.S1_1V1 = 1 --S1赛季1v1奖励
Ds_SeasonReward.S2_1V1 = 2 --S2赛季1v1奖励
Ds_SeasonReward.S3_1V1 = 3 --S3赛季1v1奖励
Ds_SeasonReward.S4_1V1 = 4 --S4赛季1v1奖励
Ds_SeasonReward.S5_1V1 = 5 --S5赛季1v1奖励
Ds_SeasonReward.S6_1V1 = 6 --S6赛季1v1奖励
Ds_SeasonReward.S7_1V1 = 7 --S7赛季1v1奖励
Ds_SeasonReward.S8_1V1 = 8 --S8赛季1v1奖励
Ds_SeasonReward.S9_1V1 = 9 --S9赛季1v1奖励
Ds_SeasonReward.S10_1V1 = 10 --S10赛季1v1奖励
Ds_SeasonReward.S11_1V1 = 11 --S11赛季1v1奖励
Ds_SeasonReward.S12_1V1 = 12 --S12赛季1v1奖励
Ds_SeasonReward.S1_2V2 = 13 --S1赛季2v2奖励
Ds_SeasonReward.S2_2V2 = 14 --S2赛季2v2奖励
Ds_SeasonReward.S3_2V2 = 15 --S3赛季2v2奖励
Ds_SeasonReward.S4_2V2 = 16 --S4赛季2v2奖励
Ds_SeasonReward.S5_2V2 = 17 --S5赛季2v2奖励
Ds_SeasonReward.S6_2V2 = 18 --S6赛季2v2奖励
Ds_SeasonReward.S7_2V2 = 19 --S7赛季2v2奖励
Ds_SeasonReward.S8_2V2 = 20 --S8赛季2v2奖励
Ds_SeasonReward.S9_2V2 = 21 --S9赛季2v2奖励
Ds_SeasonReward.S10_2V2 = 22 --S10赛季2v2奖励
Ds_SeasonReward.S11_2V2 = 23 --S11赛季2v2奖励
Ds_SeasonReward.S12_2V2 = 24 --S12赛季2v2奖励
Ds_SeasonReward.First_Recharge = 25 --赛季首冲
Ds_SeasonReward.MEDAL_EXCHANGE = 26 --勋章兑换
Ds_SeasonReward.SkillTECHNIC_REWARD = 27 --技巧教学奖励
Ds_SeasonReward.HERO_FRAGMENT = 28 --英雄碎片兑换
Ds_SeasonReward.SKIN_FRAGMENT = 29 --皮肤碎片兑换

Ds_SystemLotteryType = {} --系统抽奖类型
Ds_SystemLotteryType.SYSTEMLOTTERYTYPE_DIAMONDFRIST = 1 --系统钻石首抽
Ds_SystemLotteryType.SYSTEMLOTTERYTYPE_DIAMONDSOLO = 2 --系统钻石单抽
Ds_SystemLotteryType.SYSTEMLOTTERYTYPE_DIAMONDFIVE = 3 --系统钻石连抽
Ds_SystemLotteryType.SYSTEMLOTTERYTYPE_DIAMONDSOLOGOD = 4 --系统钻石单抽保底
Ds_SystemLotteryType.SYSTEMLOTTERYTYPE_DIAMONDFIVEGOD = 5 --系统钻石连抽保底
Ds_SystemLotteryType.SYSTEMLOTTERYTYPE_COUPONFRIST = 6 --系统点券首抽
Ds_SystemLotteryType.SYSTEMLOTTERYTYPE_COUPONSOLO = 7 --系统点券单抽
Ds_SystemLotteryType.SYSTEMLOTTERYTYPE_COUPONFIVE = 8 --系统点券连抽
Ds_SystemLotteryType.SYSTEMLOTTERYTYPE_COUPONSOLOGOD = 9 --系统点券单抽保底
Ds_SystemLotteryType.SYSTEMLOTTERYTYPE_COUPONFIVEGOD = 10 --系统点券连抽保底
Ds_SystemLotteryType.SYSTEMLOTTERYTYPE_HERO_RUNE_DIAMONDFRIST = 11 --系统英雄符文钻石首抽
Ds_SystemLotteryType.SYSTEMLOTTERYTYPE_HERO_RUNE_DIAMONDSOLO = 12 --系统英雄符文钻石单抽
Ds_SystemLotteryType.SYSTEMLOTTERYTYPE_HERO_RUNE_DIAMONDFIVE = 13 --系统英雄符文钻石连抽
Ds_SystemLotteryType.SYSTEMLOTTERYTYPE_HERO_RUNE_DIAMONDSOLOGOD = 14 --系统英雄符文钻石单抽保底
Ds_SystemLotteryType.SYSTEMLOTTERYTYPE_HERO_RUNE_DIAMONDFIVEGOD = 15 --系统英雄符文钻石连抽保底
Ds_SystemLotteryType.SYSTEMLOTTERYTYPE_HERO_RUNE_GOLDFRIST = 16 --系统英雄符文金币首抽
Ds_SystemLotteryType.SYSTEMLOTTERYTYPE_HERO_RUNE_GOLDSOLO = 17 --系统英雄符文金币单抽
Ds_SystemLotteryType.SYSTEMLOTTERYTYPE_HERO_RUNE_GOLDFIVE = 18 --系统英雄符文金币连抽
Ds_SystemLotteryType.SYSTEMLOTTERYTYPE_HERO_RUNE_GOLDSOLOGOD = 19 --系统英雄符文金币单抽保底
Ds_SystemLotteryType.SYSTEMLOTTERYTYPE_HERO_RUNE_GOLDFIVEGOD = 20 --系统英雄符文金币连抽保底
Ds_SystemLotteryType.SYSTEMLOTTERYTYPE_RACE_RUNE_DIAMONDFRIST = 21 --系统种族符文钻石首抽
Ds_SystemLotteryType.SYSTEMLOTTERYTYPE_RACE_RUNE_DIAMONDSOLO = 22 --系统种族符文钻石单抽
Ds_SystemLotteryType.SYSTEMLOTTERYTYPE_RACE_RUNE_DIAMONDFIVE = 23 --系统种族符文钻石连抽
Ds_SystemLotteryType.SYSTEMLOTTERYTYPE_RACE_RUNE_DIAMONDSOLOGOD = 24 --系统种族符文钻石单抽保底
Ds_SystemLotteryType.SYSTEMLOTTERYTYPE_RACE_RUNE_DIAMONDFIVEGOD = 25 --系统种族符文钻石连抽保底
Ds_SystemLotteryType.SYSTEMLOTTERYTYPE_RACE_RUNE_GOLDFRIST = 26 --系统种族符文金币首抽
Ds_SystemLotteryType.SYSTEMLOTTERYTYPE_RACE_RUNE_GOLDSOLO = 27 --系统种族符文金币单抽
Ds_SystemLotteryType.SYSTEMLOTTERYTYPE_RACE_RUNE_GOLDFIVE = 28 --系统种族符文金币连抽
Ds_SystemLotteryType.SYSTEMLOTTERYTYPE_RACE_RUNE_GOLDSOLOGOD = 29 --系统种族符文金币单抽保底
Ds_SystemLotteryType.SYSTEMLOTTERYTYPE_RACE_RUNE_GOLDFIVEGOD = 30 --系统种族符文金币连抽保底

Ds_ShopDiscountType = {} --商城折扣类型
Ds_ShopDiscountType.SHOPDISCOUNTTYPE_NONE = 0 --商城折扣类型_无折扣
Ds_ShopDiscountType.SHOPDISCOUNTTYPE_LIMITTIME = 1 --商城折扣类型_限时折扣
Ds_ShopDiscountType.SHOPDISCOUNTTYPE_NEWBIE = 2 --商城折扣类型_新手折扣

Ds_TeamInviteFromType = {} --组队邀请类型
Ds_TeamInviteFromType.TEAMINVITEFROMTYPE_FRIEND = 0 --组队邀请类型_好友
Ds_TeamInviteFromType.TEAMINVITEFROMTYPE_RECENT = 1 --组队邀请类型_近期
Ds_TeamInviteFromType.TEAMINVITEFROMTYPE_CHAT = 2 --组队邀请类型_聊天

Ds_ActivityAcquireType = {} --活动获得类型
Ds_ActivityAcquireType.ACTIVITYACQUIRETYPE_FIRSTLOGIN = 0 --活动获得类型_首次登录
Ds_ActivityAcquireType.ACTIVITYACQUIRETYPE_LIMITTIME = 1 --活动获得类型_限时获得
Ds_ActivityAcquireType.ACTIVITYACQUIRETYPE_WEEKDAY = 2 --活动获得类型_每周获得
Ds_ActivityAcquireType.ACTIVITYACQUIRETYPE_MONTHDAY = 3 --活动获得类型_每月获得

Ds_ActivityDurationType = {} --活动时间类型
Ds_ActivityDurationType.ACTIVITYDURATIONTYPE_WEEKDAY = 0 --活动时间类型_每周时间段
Ds_ActivityDurationType.ACTIVITYDURATIONTYPE_NEWBIE = 1 --活动时间类型_新手期
Ds_ActivityDurationType.ACTIVITYDURATIONTYPE_PERIOD = 2 --活动时间类型_固定时间段
Ds_ActivityDurationType.ACTIVITYDURATIONTYPE_MONTHDAY = 3 --活动时间类型_每月时间段

Ds_ActivityCounterType = {} --活动计数器类型
Ds_ActivityCounterType.ACTIVITYCOUNTERTYPE_NONE = 0 --活动计数器类型_无
Ds_ActivityCounterType.ACTIVITYCOUNTERTYPE_LOGIN_INTIME = 1 --活动计数器类型_时间段登录
Ds_ActivityCounterType.ACTIVITYCOUNTERTYPE_LOGIN_TOTALDAY = 2 --活动计数器类型_每日登录
Ds_ActivityCounterType.ACTIVITYCOUNTERTYPE_PAY_TOTAL = 3 --活动计数器类型_充值
Ds_ActivityCounterType.ACTIVITYCOUNTERTYPE_NEWBIE_LOGIN = 4 --活动计数器类型_新手登录

Ds_ActivityCounterResetType = {} --活动计数器重置类型
Ds_ActivityCounterResetType.ACTIVITYCOUNTERRESETTYPE_NONE = 0 --活动计数器重置类型_不重置
Ds_ActivityCounterResetType.ACTIVITYCOUNTERRESETTYPE_EVERYDAY = 1 --活动计数器重置类型_每天重置
Ds_ActivityCounterResetType.ACTIVITYCOUNTERRESETTYPE_EVERYWEEK = 2 --活动计数器重置类型_每周重置
Ds_ActivityCounterResetType.ACTIVITYCOUNTERRESETTYPE_EVERYMONTH = 3 --活动计数器重置类型_每月重置

Ds_ActivityQuestState = {} --活动任务状态
Ds_ActivityQuestState.ACTIVITYQUESTSTATE_UNFINISH = 0 --活动任务状态_未完成
Ds_ActivityQuestState.ACTIVITYQUESTSTATE_FINISH = 1 --活动任务状态_已完成
Ds_ActivityQuestState.ACTIVITYQUESTSTATE_REWARDED = 2 --活动任务状态_已领奖

Ds_ResActorRuneAttrType = {} --单位符文属性类型(服务器存储,不可改动ID)
Ds_ResActorRuneAttrType.RUNE_ATTR_MIN = 0 --符文_属性最小值
Ds_ResActorRuneAttrType.RUNE_ATTR_MAX_HP = 2 --符文_最大生命值
Ds_ResActorRuneAttrType.RUNE_ATTR_HP_RECOVERY = 3 --符文_生命回复/5s
Ds_ResActorRuneAttrType.RUNE_ATTR_MAX_MP = 5 --符文_最大法术值
Ds_ResActorRuneAttrType.RUNE_ATTR_MP_RECOVER = 7 --符文_法术回复/5s
Ds_ResActorRuneAttrType.RUNE_ATTR_ATK = 8 --符文_攻击力
Ds_ResActorRuneAttrType.RUNE_ATTR_ARMOR = 9 --符文_护甲值
Ds_ResActorRuneAttrType.RUNE_ATTR_ARMOR_PIERCE = 10 --符文_护甲穿透
Ds_ResActorRuneAttrType.RUNE_ATTR_ATK_SPEED = 12 --符文_攻击速度(1万代表1s)
Ds_ResActorRuneAttrType.RUNE_ATTR_ATK_STEAL_RATE = 13 --符文_生命偷取率(万分比)
Ds_ResActorRuneAttrType.RUNE_ATTR_CRI_RATE = 14 --符文_暴击率(万分比)
Ds_ResActorRuneAttrType.RUNE_ATTR_CRI_DAM_RATE = 15 --符文_暴击伤害率(万分比)
Ds_ResActorRuneAttrType.RUNE_ATTR_MAGIC = 16 --符文_法术强度
Ds_ResActorRuneAttrType.RUNE_ATTR_MAGIC_DEF = 17 --符文_法术抗性
Ds_ResActorRuneAttrType.RUNE_ATTR_MD_PIERCE = 18 --符文_法术穿透
Ds_ResActorRuneAttrType.RUNE_ATTR_AP_STEAL_RATE = 20 --符文_法术吸血率(万分比)
Ds_ResActorRuneAttrType.RUNE_ATTR_TENACITY_RATE = 21 --符文_韧性率(万分比)
Ds_ResActorRuneAttrType.RUNE_ATTR_CD_REDUCTION = 22 --符文_冷却缩减(万分比)
Ds_ResActorRuneAttrType.RUNE_ATTR_EVASION_RATE = 24 --符文_闪避值(万分比)
Ds_ResActorRuneAttrType.RUNE_ATTR_MAX = 26 --符文_属性最大值

Ds_ResTeamRuneAttrType = {} --队伍符文属性类型(服务器存储,不可改动ID)
Ds_ResTeamRuneAttrType.TEAMRUNE_ATTR_MIN = 0 --符文_队伍属性最小值
Ds_ResTeamRuneAttrType.TEAMRUNE_ATTR_MFGOLD = 1 --符文_打野额外金钱(万分比)
Ds_ResTeamRuneAttrType.TEAMRUNE_ATTR_MFEXP = 2 --符文_打野额外经验(万分比)
Ds_ResTeamRuneAttrType.TEAMRUNE_ATTR_PKEXP = 3 --符文_击杀士兵额外经验(万分比)
Ds_ResTeamRuneAttrType.TEAMRUNE_ATTR_BUILDGOLDTIME = 4 --符文_分矿建造时间(毫秒)
Ds_ResTeamRuneAttrType.TEAMRUNE_ATTR_BUILDTOWERTIME = 5 --符文_防御塔建造时间(毫秒)
Ds_ResTeamRuneAttrType.TEAMRUNE_ATTR_UPBASETIME = 6 --符文_升级基地时间(万分比)
Ds_ResTeamRuneAttrType.TEAMRUNE_ATTR_CONSTRUCTARMYCOST = 7 --符文_训练士兵费用(万分比)
Ds_ResTeamRuneAttrType.TEAMRUNE_ATTR_REPARISPEED = 8 --符文_修理建筑速度(万分比)
Ds_ResTeamRuneAttrType.TEAMRUNE_ATTR_SPAWNGOLD = 9 --符文_出生携带金币
Ds_ResTeamRuneAttrType.TEAMRUNE_ATTR_TRANFERCD = 10 --符文_传送冷却时间(毫秒)
Ds_ResTeamRuneAttrType.TEAMRUNE_ATTR_GRASSHPRECOVER = 11 --符文_草丛生命回复(万分比)
Ds_ResTeamRuneAttrType.TEAMRUNE_ATTR_SPRINGHPRECOVER = 12 --符文_泉水生命回复(万分比)
Ds_ResTeamRuneAttrType.TEAMRUNE_ATTR_MAX = 13 --符文_队伍属性最大值

Ds_RuneMosaicType = {} --符文镶嵌类型
Ds_RuneMosaicType.RuneMosaicType_Attack = 0 --攻击向符文
Ds_RuneMosaicType.RuneMosaicType_Defense = 1 --防御向符文
Ds_RuneMosaicType.RuneMosaicType_Buff = 2 --辅助向符文
Ds_RuneMosaicType.RuneMosaicType_Specially = 3 --特殊向符文
Ds_RuneMosaicType.RuneMosaicType_AnyWhere = 4 --任意位置符文

Ds_RuneAttrType = {} --符文属性类型
Ds_RuneAttrType.RUNEATTRTYPE_ACTOR = 0 --单位属性符文
Ds_RuneAttrType.RUNEATTRTYPE_TEAM = 1 --队伍属性符文

Ds_RunePackageType = {} --符文类型
Ds_RunePackageType.RUNEPACKAGETYPE_HERO = 1 --英雄符文背包
Ds_RunePackageType.RUNEPACKAGETYPE_RACE = 2 --种族符文背包

Ds_GameShareType = {} --分享类型
Ds_GameShareType.SHARE_BATTLESETTLE = 0 --分享游戏战绩
Ds_GameShareType.SHARE_ACTIVITY = 1 --分享活动
