-- This file is generated by tdr. 

Ds_ResDataOperate_Str = {} --数据操作类型
Ds_ResDataOperate_Str["固定数值"] = 1 --固定数值
Ds_ResDataOperate_Str["万分比"] = 2 --万分比

Ds_ResDataSet_Str = {} --数据操作类型
Ds_ResDataSet_Str["数据覆盖"] = 0 --数据覆盖
Ds_ResDataSet_Str["数据加法"] = 1 --数据加法
Ds_ResDataSet_Str["数据减法"] = 2 --数据减法

Ds_ATTRADDTYPE_Str = {} --属性加成类型
Ds_ATTRADDTYPE_Str["基础属性"] = 1 --基础属性
Ds_ATTRADDTYPE_Str["加成属性"] = 2 --加成属性(固定数值)
Ds_ATTRADDTYPE_Str["基础属性乘法"] = 3 --基础属性乘法(万分比)
Ds_ATTRADDTYPE_Str["加成属性乘法"] = 4 --加成属性乘法(万分比)
Ds_ATTRADDTYPE_Str["所有属性乘法"] = 5 --所有属性乘法(万分比)

Ds_ATTRDATATYPE_Str = {} --属性数值类型
Ds_ATTRDATATYPE_Str["当前最大生命值"] = 0 --当前最大生命值
Ds_ATTRDATATYPE_Str["当前生命值"] = 1 --当前生命值
Ds_ATTRDATATYPE_Str["损失生命值"] = 2 --损失生命值
Ds_ATTRDATATYPE_Str["当前最大法术值"] = 3 --当前最大法术值
Ds_ATTRDATATYPE_Str["当前法术值"] = 4 --当前法术值
Ds_ATTRDATATYPE_Str["损失法术值"] = 5 --损失法术值

Ds_RaceType_Str = {} --种族
Ds_RaceType_Str["中立种族"] = 0 --中立种族
Ds_RaceType_Str["人族"] = 1 --人族
Ds_RaceType_Str["兽族"] = 2 --兽族
Ds_RaceType_Str["神族"] = 3 --神族
Ds_RaceType_Str["恶魔族"] = 4 --恶魔族
Ds_RaceType_Str["种族最大值"] = 5 --种族最大值

Ds_LegionType_Str = {} --军团类型
Ds_LegionType_Str["中立军团"] = 0 --中立军团
Ds_LegionType_Str["正义军团"] = 1 --正义军团
Ds_LegionType_Str["邪恶军团"] = 2 --邪恶军团
Ds_LegionType_Str["军团最大值"] = 3 --军团最大值

Ds_ResHeroCapacityType_Str = {} --英雄能力类别
Ds_ResHeroCapacityType_Str["战士"] = 1 --战士
Ds_ResHeroCapacityType_Str["法师"] = 2 --法师
Ds_ResHeroCapacityType_Str["肉盾"] = 3 --肉盾
Ds_ResHeroCapacityType_Str["刺客"] = 4 --刺客
Ds_ResHeroCapacityType_Str["射手"] = 5 --射手
Ds_ResHeroCapacityType_Str["能力类别Max"] = 6 --Max

Ds_ResWeaponType_Str = {} --武器类型
Ds_ResWeaponType_Str["近战"] = 0 --
Ds_ResWeaponType_Str["远程"] = 1 --

Ds_BattleTeamType_Str = {} --队伍类型
Ds_BattleTeamType_Str["白方队伍"] = 0 --白方队伍
Ds_BattleTeamType_Str["红方队伍"] = 1 --红方队伍
Ds_BattleTeamType_Str["蓝方队伍"] = 2 --蓝方队伍
Ds_BattleTeamType_Str["紫方队伍"] = 3 --紫方队伍
Ds_BattleTeamType_Str["绿方队伍"] = 4 --绿方队伍
Ds_BattleTeamType_Str["粉方队伍"] = 5 --粉方队伍
Ds_BattleTeamType_Str["黄方队伍"] = 6 --黄方队伍
Ds_BattleTeamType_Str["队伍数量"] = 7 --队伍数量

Ds_TeamLegionType_Str = {} --阵营类型
Ds_TeamLegionType_Str["阵营友军"] = 0 --阵营友军
Ds_TeamLegionType_Str["阵营敌军"] = 1 --阵营敌军
Ds_TeamLegionType_Str["所有阵营单位"] = 2 --所有阵营单位

Ds_BattleActorType_Str = {} --单位类型
Ds_BattleActorType_Str["无类型"] = 0 --无类型
Ds_BattleActorType_Str["英雄"] = 1 --英雄
Ds_BattleActorType_Str["士兵"] = 2 --士兵
Ds_BattleActorType_Str["野怪"] = 3 --野怪
Ds_BattleActorType_Str["BOSS"] = 4 --BOSS
Ds_BattleActorType_Str["防御塔"] = 5 --防御塔
Ds_BattleActorType_Str["金矿"] = 6 --金矿
Ds_BattleActorType_Str["基地"] = 7 --基地
Ds_BattleActorType_Str["召唤生物"] = 8 --召唤生物
Ds_BattleActorType_Str["副基地"] = 9 --副基地
Ds_BattleActorType_Str["泉水"] = 10 --泉水
Ds_BattleActorType_Str["场景物件"] = 11 --场景物件
Ds_BattleActorType_Str["单位类型MAX"] = 12 --MAX

Ds_BattleActorSubType_Str = {} --单位子类型
Ds_BattleActorSubType_Str["生物召唤物"] = 1 --生物召唤物
Ds_BattleActorSubType_Str["静止召唤物"] = 2 --静止召唤物
Ds_BattleActorSubType_Str["野外泉水"] = 3 --野外泉水
Ds_BattleActorSubType_Str["回血蓝符"] = 4 --回血蓝符

Ds_BattleRusult_Str = {} --战斗结果类型
Ds_BattleRusult_Str["无结果"] = 0 --无结果
Ds_BattleRusult_Str["正义胜利"] = 1 --正义胜利
Ds_BattleRusult_Str["邪恶胜利"] = 2 --邪恶胜利
Ds_BattleRusult_Str["平局"] = 3 --平局

Ds_AIAttackType_Str = {} --AI攻击类型
Ds_AIAttackType_Str["主动攻击AI"] = 0 --主动攻击AI
Ds_AIAttackType_Str["被动攻击AI"] = 1 --被动攻击AI

Ds_ActorDeadTrigEventType_Str = {} --死亡触发事件类型
Ds_ActorDeadTrigEventType_Str["死亡基地刷小兵"] = 1 --死亡基地刷小兵

Ds_ResActorMoveType_Str = {} --单位移动类型
Ds_ResActorMoveType_Str["地面移动单位"] = 0 --地面移动单位
Ds_ResActorMoveType_Str["空中移动单位"] = 1 --空中移动单位

Ds_ResActrorAITargetType_Str = {} --AI优先攻击目标类型
Ds_ResActrorAITargetType_Str["AI目标_任意单位"] = 0 --AI目标_任意单位
Ds_ResActrorAITargetType_Str["AI目标_敌方英雄"] = 1 --AI目标_敌方英雄
Ds_ResActrorAITargetType_Str["AI目标_敌方士兵"] = 2 --AI目标_敌方士兵
Ds_ResActrorAITargetType_Str["AI目标_敌方建筑"] = 3 --AI目标_敌方建筑,统称
Ds_ResActrorAITargetType_Str["AI目标_野怪"] = 4 --AI目标_野怪
Ds_ResActrorAITargetType_Str["AI目标_召唤生物"] = 5 --AI目标_召唤生物

Ds_ResAttrType_Str = {} --属性类型
Ds_ResAttrType_Str["属性最小值"] = 0 --
Ds_ResAttrType_Str["生命值"] = 1 --生命值(计算后)
Ds_ResAttrType_Str["最大生命值"] = 2 --最大生命值
Ds_ResAttrType_Str["生命回复/5s"] = 3 --生命回复/5s
Ds_ResAttrType_Str["生命回复率"] = 4 --生命回复率(万分比/5s)
Ds_ResAttrType_Str["最大法术值"] = 5 --最大法术值
Ds_ResAttrType_Str["法术值"] = 6 --法术值(计算后)
Ds_ResAttrType_Str["法术回复/5s"] = 7 --法术回复/5s
Ds_ResAttrType_Str["攻击力"] = 8 --攻击力
Ds_ResAttrType_Str["护甲值"] = 9 --护甲值
Ds_ResAttrType_Str["护甲穿透"] = 10 --护甲穿透
Ds_ResAttrType_Str["护甲穿透率"] = 11 --护甲穿透率(万分比)
Ds_ResAttrType_Str["攻击速度"] = 12 --攻击速度(1万代表1s)
Ds_ResAttrType_Str["生命偷取率"] = 13 --生命偷取率(万分比)
Ds_ResAttrType_Str["暴击率"] = 14 --暴击率(万分比)
Ds_ResAttrType_Str["暴击伤害率"] = 15 --暴击伤害率(万分比)
Ds_ResAttrType_Str["法术强度"] = 16 --法术强度
Ds_ResAttrType_Str["法术抗性"] = 17 --法术抗性
Ds_ResAttrType_Str["法术穿透"] = 18 --法术穿透
Ds_ResAttrType_Str["法术穿透率"] = 19 --法术穿透率(万分比)
Ds_ResAttrType_Str["法术吸血率"] = 20 --法术吸血率(万分比)
Ds_ResAttrType_Str["韧性率"] = 21 --韧性率(万分比)
Ds_ResAttrType_Str["冷却缩减"] = 22 --冷却缩减(万分比)
Ds_ResAttrType_Str["移动速度"] = 23 --移动速度(1万代表1M)
Ds_ResAttrType_Str["生命值成长"] = 24 --生命值成长
Ds_ResAttrType_Str["生命回复成长"] = 25 --生命回复成长(/5s)
Ds_ResAttrType_Str["攻击力成长"] = 26 --攻击力成长
Ds_ResAttrType_Str["法术强度成长"] = 27 --法术强度成长
Ds_ResAttrType_Str["护甲成长"] = 28 --护甲成长
Ds_ResAttrType_Str["法术抗性成长"] = 29 --法术抗性成长
Ds_ResAttrType_Str["法术值成长"] = 30 --法术值成长
Ds_ResAttrType_Str["法术值回复成长"] = 31 --法术值回复成长(/5s)
Ds_ResAttrType_Str["反伤值"] = 32 --反弹值
Ds_ResAttrType_Str["反伤率"] = 33 --反伤率(万分比)
Ds_ResAttrType_Str["碰撞体积"] = 34 --碰撞体积
Ds_ResAttrType_Str["视野半径"] = 35 --视野半径
Ds_ResAttrType_Str["警戒半径"] = 36 --警戒半径
Ds_ResAttrType_Str["物理伤害减免"] = 37 --物理伤害减免
Ds_ResAttrType_Str["法术伤害减免"] = 38 --法术伤害减免
Ds_ResAttrType_Str["物理伤害万分比"] = 39 --物理伤害百分比(万分比,计算完后)
Ds_ResAttrType_Str["法术伤害万分比"] = 40 --法术伤害百分比(万分比,计算完后)
Ds_ResAttrType_Str["受到物理伤害万分比"] = 41 --受到物理伤害率(万分比,计算完后)
Ds_ResAttrType_Str["受到法术伤害万分比"] = 42 --受到法术伤害率(万分比,计算完后)
Ds_ResAttrType_Str["被普通攻击伤害减免值"] = 43 --被普通攻击伤害减免值
Ds_ResAttrType_Str["被普通攻击伤害减免率"] = 44 --被普通攻击伤害减免率(万分比)
Ds_ResAttrType_Str["对野怪伤害加成值"] = 45 --对野怪伤害加成值
Ds_ResAttrType_Str["对野怪伤害加成系数"] = 46 --对野怪伤害加成系数(万分比)
Ds_ResAttrType_Str["AI攻击伤害系数"] = 47 --AI攻击伤害系数
Ds_ResAttrType_Str["AI防御伤害系数"] = 48 --AI防御伤害系数
Ds_ResAttrType_Str["BUFF回属性加成系数"] = 49 --BUFF回属性加成系数
Ds_ResAttrType_Str["基础回复加成系数"] = 50 --基础回复加成系数
Ds_ResAttrType_Str["击杀野怪经验加成系数"] = 51 --击杀野怪经验加成系数
Ds_ResAttrType_Str["最大值"] = 52 --

Ds_BuffPropertyType_Str = {} --BUFF属性类型
Ds_BuffPropertyType_Str["天赋BUFF"] = 1 --天赋BUFF
Ds_BuffPropertyType_Str["系统BUFF"] = 2 --系统BUFF
Ds_BuffPropertyType_Str["数值增益BUFF"] = 3 --数值增益BUFF
Ds_BuffPropertyType_Str["数值减益BUFF"] = 4 --数值减益BUFF
Ds_BuffPropertyType_Str["控制BUFF"] = 5 --控制BUFF
Ds_BuffPropertyType_Str["免疫控制BUFF"] = 6 --免疫控制BUFF
Ds_BuffPropertyType_Str["触发技能BUFF"] = 7 --触发技能BUFF
Ds_BuffPropertyType_Str["触发BUFF"] = 8 --触发BUFF

Ds_BuffPropertySubType_Str = {} --BUFF属性子类型
Ds_BuffPropertySubType_Str["眩晕类子类型"] = 1 --眩晕类子类型
Ds_BuffPropertySubType_Str["减速类子类型"] = 2 --减速类子类型
Ds_BuffPropertySubType_Str["沉默类子类型"] = 3 --沉默类子类型
Ds_BuffPropertySubType_Str["击飞击退类子类型"] = 4 --击飞击退类子类型
Ds_BuffPropertySubType_Str["X空间类子类型"] = 5 --X空间类子类型
Ds_BuffPropertySubType_Str["法术值增减益子类型"] = 6 --法术值增减益子类型

Ds_BuffDoType_Str = {} --BUFF执行类型
Ds_BuffDoType_Str["单次执行"] = 0 --单次执行
Ds_BuffDoType_Str["周期性执行"] = 1 --周期性执行

Ds_BuffMergeType_Str = {} --BUFF叠加规则
Ds_BuffMergeType_Str["无法合并"] = 0 --无法合并
Ds_BuffMergeType_Str["BUFF堆叠"] = 1 --BUFF堆叠
Ds_BuffMergeType_Str["替换旧的BUFF(施法者)"] = 2 --替换旧的BUFF（同一施法者，高等级替换低等级，同等级刷数据）
Ds_BuffMergeType_Str["新Buff被排斥"] = 3 --新Buff被排斥
Ds_BuffMergeType_Str["替换旧的BUFF(组ID)"] = 4 --替换旧的BUFF（只按组ID）

Ds_BuffOp_Str = {} --BUFF操作类型
Ds_BuffOp_Str[""] = 1 --添加buff操作
Ds_BuffOp_Str[""] = 2 --移除buff操作
Ds_BuffOp_Str[""] = 3 --覆盖buff操作
Ds_BuffOp_Str[""] = 4 --中断buff操作

Ds_BuffRemoveType_Str = {} --BUFF外部移除类型
Ds_BuffRemoveType_Str["任意移除Buff"] = 0 --任意移除Buff
Ds_BuffRemoveType_Str["死亡移除Buff"] = 1 --死亡移除Buff
Ds_BuffRemoveType_Str["上帝移除Buff"] = 2 --上帝移除Buff

Ds_BuffEndType_Str = {} --BUFF结束类型
Ds_BuffEndType_Str["Buff自然结束"] = 0 --Buff自然结束
Ds_BuffEndType_Str["Buff被动清除"] = 1 --Buff被动清除
Ds_BuffEndType_Str["Buff死亡清除"] = 2 --Buff死亡清除

Ds_BuffEffectType_Str = {} --Buff效果类型
Ds_BuffEffectType_Str["属性修改"] = 1 --属性修改
Ds_BuffEffectType_Str["触发释放技能"] = 2 --触发释放技能
Ds_BuffEffectType_Str["回属性"] = 3 --回属性
Ds_BuffEffectType_Str["吸收伤害"] = 4 --吸收伤害
Ds_BuffEffectType_Str["眩晕"] = 5 --眩晕
Ds_BuffEffectType_Str["沉默"] = 6 --沉默
Ds_BuffEffectType_Str["拉扯"] = 7 --拉扯
Ds_BuffEffectType_Str["击飞击退"] = 8 --击飞击退
Ds_BuffEffectType_Str["嘲讽"] = 9 --嘲讽
Ds_BuffEffectType_Str["物理免疫"] = 10 --物理免疫
Ds_BuffEffectType_Str["魔法免疫"] = 11 --魔法免疫
Ds_BuffEffectType_Str["无敌"] = 12 --无敌
Ds_BuffEffectType_Str["清除BUFF"] = 13 --清除BUFF
Ds_BuffEffectType_Str["免疫DEBUFF"] = 14 --免疫DEBUFF
Ds_BuffEffectType_Str["霸体BUFF"] = 15 --霸体BUFF
Ds_BuffEffectType_Str["进入X空间"] = 16 --进入X空间
Ds_BuffEffectType_Str["触发变体技能"] = 17 --触发变体技能
Ds_BuffEffectType_Str["解除变体技能"] = 18 --解除变体技能
Ds_BuffEffectType_Str["永久修改属性"] = 19 --永久修改属性
Ds_BuffEffectType_Str["清空技能释放次数"] = 20 --清空技能释放次数
Ds_BuffEffectType_Str["触发添加技能"] = 21 --触发添加技能
Ds_BuffEffectType_Str["触发技能阶段"] = 22 --触发技能阶段
Ds_BuffEffectType_Str["BUFF增加金钱"] = 23 --BUFF增加金钱
Ds_BuffEffectType_Str["BUFF增加经验"] = 24 --BUFF增加经验
Ds_BuffEffectType_Str["烟幕失明效果"] = 25 --烟幕失明效果
Ds_BuffEffectType_Str["修改召唤物存活时间"] = 26 --修改召唤物存活时间
Ds_BuffEffectType_Str["灵魂锁链"] = 27 --灵魂锁链
Ds_BuffEffectType_Str["撒网诱捕"] = 28 --撒网诱捕
Ds_BuffEffectType_Str["Buff效果最大值"] = 29 --Buff效果最大值

Ds_BuffEffectAddExpGoldType_Str = {} --BUFF增加经验金钱类型
Ds_BuffEffectAddExpGoldType_Str["BUFF固定数值增加"] = 0 --BUFF固定数值增加
Ds_BuffEffectAddExpGoldType_Str["BUFF游戏时间增加"] = 1 --BUFF游戏时间增加

Ds_BuffEffectRemoveBuffType_Str = {} --BUFF效果清除BUFF类型
Ds_BuffEffectRemoveBuffType_Str["根据BUFF组清除BUFF"] = 0 --根据BUFF组清除BUFF
Ds_BuffEffectRemoveBuffType_Str["根据BUFF类型清除BUFF"] = 1 --根据BUFF类型清除BUFF
Ds_BuffEffectRemoveBuffType_Str["根据BUFF子类型清除BUFF"] = 2 --根据BUFF子类型清除BUFF

Ds_BuffEftSetAttrType_Str = {} --BUFF回属性参数
Ds_BuffEftSetAttrType_Str["回属性HP"] = 1 --回属性HP
Ds_BuffEftSetAttrType_Str["回属性MP"] = 2 --回属性MP
Ds_BuffEftSetAttrType_Str["回属性怒气"] = 3 --回属性怒气

Ds_BuffEffectCoefType_Str = {} --BUFF效果作用系数类型
Ds_BuffEffectCoefType_Str["BUFF效默认效果系数"] = 0 --BUFF效默认效果系数
Ds_BuffEffectCoefType_Str["BUFF效果角色等级系数"] = 1 --BUFF效果角色等级系数

Ds_BuffEffectTrigType_Str = {} --BUFF效果生效条件
Ds_BuffEffectTrigType_Str["自动生效"] = 0 --自动生效
Ds_BuffEffectTrigType_Str["死亡生效"] = 1 --死亡生效
Ds_BuffEffectTrigType_Str["普通攻击命中单个生效"] = 2 --普通攻击命中单个生效
Ds_BuffEffectTrigType_Str["释放技能生效"] = 3 --释放技能生效
Ds_BuffEffectTrigType_Str["释放技能前摇结束生效"] = 4 --释放技能前摇结束生效
Ds_BuffEffectTrigType_Str["被伤害生效"] = 5 --被伤害生效
Ds_BuffEffectTrigType_Str["被伤害暴击生效"] = 6 --被伤害暴击生效
Ds_BuffEffectTrigType_Str["击杀单位生效"] = 7 --击杀单位生效
Ds_BuffEffectTrigType_Str["指定技能释放次数生效"] = 8 --指定技能释放次数生效(技能前摇完)
Ds_BuffEffectTrigType_Str["被致命一击生效"] = 9 --被致命一击生效
Ds_BuffEffectTrigType_Str["普通攻击命中生效"] = 10 --普通攻击命中生效

Ds_BuffEventType_Str = {} --BUFF事件类型
Ds_BuffEventType_Str["当前BUFF移除"] = 1 --当前BUFF移除
Ds_BuffEventType_Str["当前BUFF层级改变"] = 2 --当前BUFF层级改变

Ds_BuffEventTrigType_Str = {} --BUFF事件触发类型
Ds_BuffEventTrigType_Str["受到伤害触发BUFF事件"] = 1 --受到伤害触发BUFF事件
Ds_BuffEventTrigType_Str["技能释放次数触发BUFF事件"] = 2 --技能释放次数触发BUFF事件

Ds_SkillType_Str = {} --技能类型
Ds_SkillType_Str["普通攻击"] = 1 --普通攻击
Ds_SkillType_Str["主动技能"] = 2 --主动技能
Ds_SkillType_Str["主动二段技能"] = 3 --主动二段技能
Ds_SkillType_Str["主动三段技能"] = 4 --主动三段技能
Ds_SkillType_Str["被动技能"] = 5 --被动技能

Ds_SkillSubType_Str = {} --技能子类型
Ds_SkillSubType_Str["普通技能"] = 1 --普通技能
Ds_SkillSubType_Str["攻击技能"] = 2 --攻击技能
Ds_SkillSubType_Str["辅助BUFF技能"] = 3 --辅助BUFF技能
Ds_SkillSubType_Str["辅助回血技能"] = 4 --辅助回血技能
Ds_SkillSubType_Str["基础回血技能"] = 5 --基础回血技能
Ds_SkillSubType_Str["基础回程技能"] = 6 --基础回程技能
Ds_SkillSubType_Str["变体技能"] = 7 --变体技能
Ds_SkillSubType_Str["召唤师技能"] = 8 --召唤师技能
Ds_SkillSubType_Str["基础传送技能"] = 9 --基础传送技能
Ds_SkillSubType_Str["重生复活技能"] = 10 --重生复活技能，复活自身
Ds_SkillSubType_Str["召唤复活技能"] = 11 --召唤复活技能，复活他人

Ds_SkillBarType_Str = {} --技能栏位类型
Ds_SkillBarType_Str["技能栏无"] = 0 --技能栏无
Ds_SkillBarType_Str["技能栏Q"] = 1 --技能栏Q
Ds_SkillBarType_Str["技能栏W"] = 2 --技能栏W
Ds_SkillBarType_Str["技能栏E"] = 3 --技能栏E
Ds_SkillBarType_Str["技能栏R"] = 4 --技能栏R
Ds_SkillBarType_Str["技能栏A"] = 5 --技能栏A
Ds_SkillBarType_Str["技能栏F1"] = 6 --技能栏F1
Ds_SkillBarType_Str["技能栏F2"] = 7 --技能栏F2
Ds_SkillBarType_Str["技能栏F3"] = 8 --技能栏F3
Ds_SkillBarType_Str["技能栏F4"] = 9 --技能栏F4
Ds_SkillBarType_Str["技能栏普攻1"] = 10 --技能栏普攻1
Ds_SkillBarType_Str["技能栏普攻2"] = 11 --技能栏普攻2
Ds_SkillBarType_Str["技能栏最大值"] = 12 --技能栏最大值

Ds_SkillTrigCastType_Str = {} --技能触发释放类型
Ds_SkillTrigCastType_Str["主动释放触发"] = 0 --主动释放触发
Ds_SkillTrigCastType_Str["天赋触发"] = 1 --天赋触发
Ds_SkillTrigCastType_Str["死亡触发"] = 2 --死亡触发
Ds_SkillTrigCastType_Str["普通攻击命中触发"] = 3 --普通攻击命中触发
Ds_SkillTrigCastType_Str["释放技能触发"] = 4 --释放技能触发(只算QWER)
Ds_SkillTrigCastType_Str["释放技能前摇结束触发"] = 5 --释放技能前摇结束触发
Ds_SkillTrigCastType_Str["被伤害触发"] = 6 --被伤害触发
Ds_SkillTrigCastType_Str["被普攻伤害触发"] = 7 --被普攻伤害触发
Ds_SkillTrigCastType_Str["被主动技能伤害触发"] = 8 --被主动技能伤害触发
Ds_SkillTrigCastType_Str["时间周期触发"] = 9 --时间周期触发
Ds_SkillTrigCastType_Str["Buff效果触发"] = 10 --Buff效果触发
Ds_SkillTrigCastType_Str["非被动技能触发伤害生效"] = 11 --非被动技能触发伤害生效
Ds_SkillTrigCastType_Str["QWER技能触发伤害生效"] = 12 --QWER技能触发伤害生效
Ds_SkillTrigCastType_Str["角色等级提升触发"] = 13 --角色等级提升触发
Ds_SkillTrigCastType_Str["击杀目标触发"] = 14 --击杀目标触发
Ds_SkillTrigCastType_Str["普通攻击命中单个触发"] = 15 --普通攻击命中单个触发
Ds_SkillTrigCastType_Str["被物理攻击伤害触发"] = 16 --被物理攻击伤害触发
Ds_SkillTrigCastType_Str["被穿刺类攻击伤害触发"] = 17 --被穿刺类攻击伤害触发

Ds_SkillTrigCastParamType_Str = {} --技能触发释放参数类型
Ds_SkillTrigCastParamType_Str["一定时间内未受伤害"] = 1 --一定时间内未受伤害
Ds_SkillTrigCastParamType_Str["一定时间内未释放普攻"] = 2 --一定时间内未释放普攻(包括变体普攻)
Ds_SkillTrigCastParamType_Str["一定随机概率"] = 3 --一定随机概率
Ds_SkillTrigCastParamType_Str["生命值低于一定值"] = 4 --生命值低于一定值
Ds_SkillTrigCastParamType_Str["指定一个技能组ID"] = 5 --指定一个技能组ID
Ds_SkillTrigCastParamType_Str["指定一个目标类型"] = 6 --指定一个目标类型
Ds_SkillTrigCastParamType_Str["技能攻击范围内存在友军尸体"] = 7 --技能攻击范围内存在友军尸体

Ds_SkillTargetType_Str = {} --技能作用对象类型
Ds_SkillTargetType_Str["所有单位"] = 0 --所有单位
Ds_SkillTargetType_Str["自身"] = 1 --自身
Ds_SkillTargetType_Str["所有敌方"] = 2 --所有敌方
Ds_SkillTargetType_Str["所有己方"] = 3 --所有己方
Ds_SkillTargetType_Str["我方英雄"] = 4 --我方英雄
Ds_SkillTargetType_Str["我方士兵"] = 5 --我方士兵
Ds_SkillTargetType_Str["我方建筑"] = 6 --我方建筑
Ds_SkillTargetType_Str["敌方英雄"] = 7 --敌方英雄
Ds_SkillTargetType_Str["敌方士兵"] = 8 --敌方士兵
Ds_SkillTargetType_Str["敌方建筑"] = 9 --敌方建筑
Ds_SkillTargetType_Str["所有己方除建筑"] = 10 --所有己方除建筑
Ds_SkillTargetType_Str["所有敌方除建筑"] = 11 --所有敌方除建筑
Ds_SkillTargetType_Str["野怪"] = 14 --野怪

Ds_SkillDmgType_Str = {} --技能伤害类型
Ds_SkillDmgType_Str["物理伤害"] = 1 --物理伤害
Ds_SkillDmgType_Str["法术伤害"] = 2 --法术伤害
Ds_SkillDmgType_Str["全额伤害"] = 3 --全额伤害

Ds_SkillDistanceType_Str = {} --技能距离类型
Ds_SkillDistanceType_Str["近战技能"] = 0 --近战技能
Ds_SkillDistanceType_Str["远程技能"] = 1 --远程技能

Ds_SkillAtkActorType_Str = {} --技能攻击单位类型
Ds_SkillAtkActorType_Str["攻击地面单位"] = 0 --攻击地面单位
Ds_SkillAtkActorType_Str["攻击空中单位"] = 1 --攻击空中单位
Ds_SkillAtkActorType_Str["攻击空地单位"] = 2 --攻击空地单位

Ds_SkillBreakType_Str = {} --技能打断类型
Ds_SkillBreakType_Str["任意打断"] = 0 --任意打断，优先级最低
Ds_SkillBreakType_Str["软控Buff打断"] = 1 --软控Buff打断
Ds_SkillBreakType_Str["硬控Buff打断"] = 2 --硬控Buff打断
Ds_SkillBreakType_Str["死亡打断"] = 3 --死亡打断
Ds_SkillBreakType_Str["上帝打断"] = 4 --上帝模式，能够打断所有

Ds_SkillCooldownType_Str = {} --技能冷却类型
Ds_SkillCooldownType_Str["无冷却"] = 0 --无冷却
Ds_SkillCooldownType_Str["时间冷却"] = 1 --时间冷却

Ds_SkillCDStartType_Str = {} --技能CD启动类型
Ds_SkillCDStartType_Str["释放技能启动"] = 0 --释放技能启动
Ds_SkillCDStartType_Str["技能前摇结束启动"] = 1 --技能前摇结束启动
Ds_SkillCDStartType_Str["技能攻击状态结束启动"] = 2 --技能后摇结束启动

Ds_SkillCostType_Str = {} --技能消耗类型
Ds_SkillCostType_Str["无消耗"] = 0 --无消耗
Ds_SkillCostType_Str["法术值消耗"] = 1 --法术值消耗
Ds_SkillCostType_Str["技能充能点消耗"] = 2 --技能充能点
Ds_SkillCostType_Str["特殊技能点消耗"] = 3 --特殊技能点
Ds_SkillCostType_Str["道具消耗"] = 4 --道具

Ds_SkillPointType_Str = {} --技能指向类型
Ds_SkillPointType_Str["选择自身"] = 0 --自身
Ds_SkillPointType_Str["选择目标"] = 1 --选择目标
Ds_SkillPointType_Str["选择朝向"] = 2 --选择朝向
Ds_SkillPointType_Str["选择区域"] = 3 --选择区域
Ds_SkillPointType_Str["选择自身位置"] = 4 --自身位置

Ds_SkillPointAreaType_Str = {} --技能指向区域类型
Ds_SkillPointAreaType_Str["无区域"] = 0 --无区域
Ds_SkillPointAreaType_Str["矩形"] = 1 --矩形
Ds_SkillPointAreaType_Str["圆形"] = 2 --圆形
Ds_SkillPointAreaType_Str["扇形"] = 3 --扇形

Ds_SkillAttkRollBuffType_Str = {} --技能前摇效果类型
Ds_SkillAttkRollBuffType_Str["前摇效果_无"] = 0 --前摇效果_无
Ds_SkillAttkRollBuffType_Str["前摇效果_移动"] = 1 --前摇效果_移动
Ds_SkillAttkRollBuffType_Str["前摇效果_眩晕"] = 2 --前摇效果_眩晕
Ds_SkillAttkRollBuffType_Str["前摇效果_沉默"] = 3 --前摇效果_沉默
Ds_SkillAttkRollBuffType_Str["前摇效果_嘲讽"] = 4 --前摇效果_嘲讽
Ds_SkillAttkRollBuffType_Str["前摇效果_被动位移"] = 5 --前摇效果_被动位移
Ds_SkillAttkRollBuffType_Str["前摇效果_物理免疫"] = 6 --前摇效果_物理免疫
Ds_SkillAttkRollBuffType_Str["前摇效果_魔法免疫"] = 7 --前摇效果_魔法免疫
Ds_SkillAttkRollBuffType_Str["前摇效果_无敌"] = 8 --前摇效果_无敌
Ds_SkillAttkRollBuffType_Str["前摇效果_Max"] = 9 --前摇效果_Max

Ds_SkillCtrCastType_Str = {} --技能受控制释放类型
Ds_SkillCtrCastType_Str["有前摇通过AI释放"] = 0 --有前摇通过AI释放
Ds_SkillCtrCastType_Str["无前摇通过AI释放"] = 1 --无前摇通过AI释放
Ds_SkillCtrCastType_Str["无前摇不通过AI释放"] = 2 --无前摇不通过AI受控制释放
Ds_SkillCtrCastType_Str["上帝释放"] = 3 --上帝释放(不通过AI,任何状态可放，无前摇)
Ds_SkillCtrCastType_Str["被动技能直接释放"] = 4 --被动技能直接释放

Ds_SkillBeforeRollType_Str = {} --技能前摇类型
Ds_SkillBeforeRollType_Str["固定时间前摇"] = 0 --固定时间前摇
Ds_SkillBeforeRollType_Str["动态时间前摇"] = 1 --动态时间前摇

Ds_SkillBattleCastType_Str = {} --技能战斗释放类型
Ds_SkillBattleCastType_Str["战斗状态释放"] = 0 --战斗状态释放
Ds_SkillBattleCastType_Str["任意状态释放"] = 1 --任意状态释放

Ds_SkillLastTargetCondType_Str = {} --技能上次目标有效条件
Ds_SkillLastTargetCondType_Str["技能目标仍在技能范围内"] = 1 --技能目标仍在技能范围内

Ds_SkillTargetStatusCullType_Str = {} --技能目标状态排除条件
Ds_SkillTargetStatusCullType_Str["技能目标命中BUFF组ID"] = 1 --技能目标命中BUFF组ID
Ds_SkillTargetStatusCullType_Str["技能目标血量满"] = 2 --技能目标血量满

Ds_SkillTargetFilterType_Str = {} --技能目标筛选条件类型
Ds_SkillTargetFilterType_Str["技能目标筛选_目标类型"] = 1 --技能目标筛选_目标类型
Ds_SkillTargetFilterType_Str["技能目标筛选_血量"] = 2 --技能目标筛选_血量
Ds_SkillTargetFilterType_Str["技能目标筛选_距离"] = 3 --技能目标筛选_距离
Ds_SkillTargetFilterType_Str["技能目标筛选_魔法盗取"] = 4 --技能目标筛选_魔法盗取

Ds_SkillTargetFilterActorType_Str = {} --技能目标筛选目标类型
Ds_SkillTargetFilterActorType_Str["目标筛选_英雄"] = 1 --目标筛选_英雄
Ds_SkillTargetFilterActorType_Str["目标筛选_小兵"] = 2 --目标筛选_小兵
Ds_SkillTargetFilterActorType_Str["目标筛选_建筑"] = 3 --目标筛选_建筑
Ds_SkillTargetFilterActorType_Str["目标筛选_近战单位"] = 4 --目标筛选_近战单位
Ds_SkillTargetFilterActorType_Str["目标筛选_远程单位"] = 5 --目标筛选_远程单位

Ds_SkillEffectType_Str = {} --技能效果类型
Ds_SkillEffectType_Str["无特殊效果"] = 0 --无特殊效果
Ds_SkillEffectType_Str["添加buff"] = 1 --添加buff
Ds_SkillEffectType_Str["移除buff"] = 2 --移除buff
Ds_SkillEffectType_Str["造成伤害"] = 3 --造成伤害
Ds_SkillEffectType_Str["召唤法术场"] = 4 --召唤法术场
Ds_SkillEffectType_Str["召唤怪物"] = 5 --召唤怪物
Ds_SkillEffectType_Str["技能回城"] = 6 --技能回城
Ds_SkillEffectType_Str["造成反弹伤害"] = 7 --造成反弹伤害
Ds_SkillEffectType_Str["技能驱散"] = 8 --技能驱散
Ds_SkillEffectType_Str["魔法盗取阶段效果"] = 9 --魔法盗取阶段效果
Ds_SkillEffectType_Str["技能召唤复活"] = 10 --技能召唤复活
Ds_SkillEffectType_Str["技能阶段加血"] = 11 --技能阶段加血
Ds_SkillEffectType_Str["技能效果类型最大值"] = 12 --技能效果类型最大值

Ds_SkillEffectCondtionType_Str = {} --技能效果触发条件类型
Ds_SkillEffectCondtionType_Str["无条件"] = 0 --无条件

Ds_SkillEffectTargetType_Str = {} --技能效果目标类型
Ds_SkillEffectTargetType_Str["己方单位"] = 0 --己方单位
Ds_SkillEffectTargetType_Str["敌方单位"] = 1 --敌方单位

Ds_SkillEffectDamageType_Str = {} --技能阶段伤害系数类型
Ds_SkillEffectDamageType_Str["技能阶段默认效果系数"] = 0 --技能阶段默认效果系数
Ds_SkillEffectDamageType_Str["距离效果系数"] = 1 --距离效果系数
Ds_SkillEffectDamageType_Str["生命值效果固定值"] = 2 --生命值效果固定值
Ds_SkillEffectDamageType_Str["法术值效果固定值"] = 3 --法术值效果固定值
Ds_SkillEffectDamageType_Str["技能能量点系数"] = 4 --技能能量点系数
Ds_SkillEffectDamageType_Str["角色等级系数"] = 5 --角色等级系数
Ds_SkillEffectDamageType_Str["BUFF层级系数"] = 6 --BUFF层级系数
Ds_SkillEffectDamageType_Str["护甲数值系数"] = 7 --护甲数值系数
Ds_SkillEffectDamageType_Str["技能受击排序系数"] = 8 --技能受击排序系数
Ds_SkillEffectDamageType_Str["技能阶段效果系数最大值"] = 9 --技能阶段效果系数最大值

Ds_SkillEffectSummonedType_Str = {} --技能阶段召唤物召唤类型
Ds_SkillEffectSummonedType_Str["当前目标位置召唤"] = 0 --当前目标位置召唤
Ds_SkillEffectSummonedType_Str["当前目标朝向位置召唤"] = 1 --当前目标朝向位置召唤

Ds_SkillEffectAddBuffCondType_Str = {} --技能阶段BUFF添加条件
Ds_SkillEffectAddBuffCondType_Str["技能阶段所需技能充能点数目"] = 1 --技能阶段所需技能充能点数目

Ds_SkillEffectTPType_Str = {} --技能阶段回城类型
Ds_SkillEffectTPType_Str["回城到出生点"] = 0 --回城到出生点

Ds_SkillEffectRevivalType_Str = {} --技能阶段召唤复活类型
Ds_SkillEffectRevivalType_Str["召唤复活指定怪物ID"] = 0 --召唤复活指定怪物ID
Ds_SkillEffectRevivalType_Str["召唤复活随机怪物ID"] = 1 --召唤复活随机怪物ID

Ds_SkillEffectDoDamageType_Str = {} --技能造成伤害类型
Ds_SkillEffectDoDamageType_Str["直接造成伤害"] = 0 --直接造成伤害
Ds_SkillEffectDoDamageType_Str["反弹造成伤害"] = 1 --反弹造成伤害

Ds_ResExpType_Str = {} --经验类型
Ds_ResExpType_Str["系统经验"] = 0 --系统经验
Ds_ResExpType_Str["野怪经验"] = 1 --野怪经验
Ds_ResExpType_Str["英雄士兵经验"] = 2 --英雄士兵经验

Ds_ResMoneyAddType_Str = {} --金钱获取类型
Ds_ResMoneyAddType_Str["系统奖励金钱"] = 0 --系统奖励金钱
Ds_ResMoneyAddType_Str["金矿开采金钱"] = 1 --金矿开采金钱
Ds_ResMoneyAddType_Str["击杀单位金钱"] = 2 --击杀单位金钱

Ds_ResRepairCostType_Str = {} --维修费用类型
Ds_ResRepairCostType_Str["无维修费用"] = 0 --无维修费用
Ds_ResRepairCostType_Str["低维修费用"] = 1 --低维修费用
Ds_ResRepairCostType_Str["高维修费用"] = 2 --高维修费用

Ds_SkillFieldType_Str = {} --法术场类型
Ds_SkillFieldType_Str["触碰消失法术场"] = 0 --触碰消失放技能
Ds_SkillFieldType_Str["一般法术场"] = 1 --一般形式的法术场
Ds_SkillFieldType_Str["路径场"] = 2 --路径场
Ds_SkillFieldType_Str["塔buff生效检测场"] = 3 --特殊的塔buff检测场规则
Ds_SkillFieldType_Str["只加不减法术场"] = 4 --进加出不减法术场
Ds_SkillFieldType_Str["血瓶触碰法术场"] = 5 --血瓶触碰法术场
Ds_SkillFieldType_Str["法术场类型最大值"] = 6 --法术场类型最大值

Ds_SkillFieldShape_Str = {} --法术场形状
Ds_SkillFieldShape_Str["圆形场"] = 0 --圆形场
Ds_SkillFieldShape_Str["矩形场"] = 1 --矩形场

Ds_SkillFieldParamType_Str = {} --法术场触发参数类型
Ds_SkillFieldParamType_Str["buff"] = 1 --buff
Ds_SkillFieldParamType_Str["skill"] = 2 --skill
Ds_SkillFieldParamType_Str["skill_phase"] = 3 --skill_phase

Ds_SkillFieldTargetFilterType_Str = {} --法术场目标筛选类型
Ds_SkillFieldTargetFilterType_Str["一定时间内未受伤害筛选"] = 1 --一定时间内未受伤害筛选
Ds_SkillFieldTargetFilterType_Str["一定时间内未受到伤害或主动攻击筛选"] = 2 --一定时间内未受到伤害或主动攻击筛选
Ds_SkillFieldTargetFilterType_Str["最近距离的几个"] = 3 --最近距离的几个

Ds_EquipType_Str = {} --装备类型
Ds_EquipType_Str["装备无类型"] = 0 --装备无类型
Ds_EquipType_Str["攻击装备"] = 1 --攻击装备
Ds_EquipType_Str["法术装备"] = 2 --法术装备
Ds_EquipType_Str["防御装备"] = 3 --防御装备
Ds_EquipType_Str["移动装备"] = 4 --移动装备
Ds_EquipType_Str["打野装备"] = 5 --打野装备

Ds_BattleModeType_Str = {} --战场模式类型
Ds_BattleModeType_Str["默认模式战场局"] = 0 --默认模式战场局
Ds_BattleModeType_Str["新手模式战场局"] = 1 --新手模式战场局

Ds_AIModeType_Str = {} --电脑AI模式类型
Ds_AIModeType_Str["简单电脑AI"] = 0 --简单电脑AI
Ds_AIModeType_Str["中等电脑AI"] = 1 --中等电脑AI
Ds_AIModeType_Str["困难电脑AI"] = 2 --困难电脑AI

Ds_BaseTechLevelType_Str = {} --基地科技等级类型
Ds_BaseTechLevelType_Str["一本科技基地"] = 0 --一本科技基地
Ds_BaseTechLevelType_Str["二本科技基地"] = 1 --二本科技基地
Ds_BaseTechLevelType_Str["三本科技基地"] = 2 --三本科技基地

Ds_TechSpecialFunction_Str = {} --科技树特殊功能
Ds_TechSpecialFunction_Str["开采金币效率"] = 1 --开采金币效率
Ds_TechSpecialFunction_Str["升级人口"] = 2 --升级人口
Ds_TechSpecialFunction_Str["解锁建筑"] = 3 --解锁建筑
Ds_TechSpecialFunction_Str["解锁科技属性"] = 4 --解锁科技属性

Ds_SkillFieldRemoveType_Str = {} --法术场被移除类型
Ds_SkillFieldRemoveType_Str["不能被移除"] = 0 --不能被移除
Ds_SkillFieldRemoveType_Str["可被敌方移除"] = 1 --可被敌方移除
Ds_SkillFieldRemoveType_Str["法术场被移除类型最大值"] = 2 --法术场被移除类型最大值

Ds_BattleItemType_Str = {} --道具大类型
Ds_BattleItemType_Str["物品道具类型"] = 0 --物品道具类型
Ds_BattleItemType_Str["技能道具类型"] = 1 --技能道具类型

Ds_BattleGoodsItemType_Str = {} --物品道具类型
Ds_BattleGoodsItemType_Str["物品道具无类型"] = 0 --物品道具无类型
Ds_BattleGoodsItemType_Str["回程类物品道具"] = 1 --回程类物品道具
Ds_BattleGoodsItemType_Str["金币类物品道具"] = 2 --金币类物品道具
Ds_BattleGoodsItemType_Str["书籍类物品道具"] = 3 --书籍类物品道具
Ds_BattleGoodsItemType_Str["卷轴类物品道具"] = 4 --卷轴类物品道具
Ds_BattleGoodsItemType_Str["药剂类物品道具"] = 5 --药剂类物品道具
Ds_BattleGoodsItemType_Str["光环类物品道具"] = 6 --光环类物品道具
Ds_BattleGoodsItemType_Str["物品道具类型最大值"] = 7 --物品道具类型最大值

Ds_BattleSkillItemType_Str = {} --技能道具类型
Ds_BattleSkillItemType_Str["技能道具无类型"] = 0 --技能道具无类型
Ds_BattleSkillItemType_Str["技能道具类型最大值"] = 1 --技能道具类型最大值

Ds_SkillItemBarType_Str = {} --技能道具栏位类型
Ds_SkillItemBarType_Str["技能道具栏位1"] = 0 --技能道具栏位1
Ds_SkillItemBarType_Str["技能道具栏位2"] = 1 --技能道具栏位2
Ds_SkillItemBarType_Str["技能道具栏位3"] = 2 --技能道具栏位3
Ds_SkillItemBarType_Str["技能道具栏位最大值"] = 3 --技能道具栏位最大值

Ds_BattleItemEffectType_Str = {} --道具效果类型
Ds_BattleItemEffectType_Str["道具触发释放技能"] = 1 --道具触发释放技能
Ds_BattleItemEffectType_Str["道具侦查迷雾位置"] = 2 --道具侦查迷雾位置

Ds_ArmorType_Str = {} --护甲类型
Ds_ArmorType_Str["轻型护甲"] = 0 --轻型护甲
Ds_ArmorType_Str["中型护甲"] = 1 --中型护甲
Ds_ArmorType_Str["重型护甲"] = 2 --重型护甲
Ds_ArmorType_Str["城型护甲"] = 3 --城型护甲
Ds_ArmorType_Str["英雄护甲"] = 4 --英雄护甲
Ds_ArmorType_Str["建筑建造中护甲"] = 5 --建筑建造中护甲

Ds_SkillAttackType_Str = {} --攻击类型
Ds_SkillAttackType_Str["攻击类型_无"] = 0 --攻击类型_无
Ds_SkillAttackType_Str["攻击类型_普通"] = 1 --攻击类型_普通
Ds_SkillAttackType_Str["攻击类型_穿刺"] = 2 --攻击类型_穿刺
Ds_SkillAttackType_Str["攻击类型_能量"] = 3 --攻击类型_能量
Ds_SkillAttackType_Str["攻击类型_攻城"] = 4 --攻击类型_攻城
Ds_SkillAttackType_Str["攻击类型_英雄"] = 5 --攻击类型_英雄
Ds_SkillAttackType_Str["攻击类型_神圣"] = 6 --攻击类型_神圣
Ds_SkillAttackType_Str["攻击类型_max"] = 7 --攻击类型_max

Ds_SpeedType_Str = {} --速度类型
Ds_SpeedType_Str["无速度"] = 0 --无速度
Ds_SpeedType_Str["快"] = 1 --快
Ds_SpeedType_Str["中"] = 2 --中
Ds_SpeedType_Str["慢"] = 3 --慢

Ds_BattleCongfigType_Str = {} --战场设置表
Ds_BattleCongfigType_Str["建造塔最少满足距离"] = 1 --建造塔最少满足距离
Ds_BattleCongfigType_Str["灵魂锁链伤害计算最大范围"] = 2 --灵魂锁链伤害计算最大范围
Ds_BattleCongfigType_Str["灵魂锁链分摊伤害万分比"] = 3 --灵魂锁链分摊伤害万分比
Ds_BattleCongfigType_Str["单位死亡变成尸体时间"] = 4 --单位死亡变成尸体时间

Ds_SkillFieldEffectConditionType_Str = {} --法术场生效条件类型
Ds_SkillFieldEffectConditionType_Str["无生效条件"] = 0 --无生效条件
Ds_SkillFieldEffectConditionType_Str["没有某个buff触发生效"] = 1 --没有某个buff触发生效

Ds_SystemItemType_Str = {} --系统道具类型
Ds_SystemItemType_Str["隐藏道具"] = 0 --隐藏道具
Ds_SystemItemType_Str["系统道具_道具"] = 1 --系统道具_道具
Ds_SystemItemType_Str["系统道具_礼包"] = 2 --系统道具_礼包
Ds_SystemItemType_Str["系统道具_体验卡"] = 3 --系统道具_体验卡
Ds_SystemItemType_Str["系统道具_符文"] = 4 --系统道具_符文

Ds_SystemItemSubType_Str = {} --系统道具子类型
Ds_SystemItemSubType_Str["道具子类型_EXP"] = 1 --道具子类型_EXP
Ds_SystemItemSubType_Str["道具子类型_点券"] = 2 --道具子类型_点券
Ds_SystemItemSubType_Str["道具子类型_金币"] = 3 --道具子类型_金币
Ds_SystemItemSubType_Str["道具子类型_钻石"] = 4 --道具子类型_钻石
Ds_SystemItemSubType_Str["道具子类型_喇叭"] = 5 --道具子类型_喇叭
Ds_SystemItemSubType_Str["道具子类型_礼包"] = 6 --道具子类型_礼包
Ds_SystemItemSubType_Str["道具子类型_英雄体验卡"] = 7 --道具子类型_英雄体验卡
Ds_SystemItemSubType_Str["道具子类型_皮肤体验卡"] = 8 --道具子类型_皮肤体验卡
Ds_SystemItemSubType_Str["道具子类型_符文"] = 9 --道具子类型_符文
Ds_SystemItemSubType_Str["道具子类型_活跃"] = 10 --道具子类型_活跃

Ds_SystemItemEffectType_Str = {} --系统道具效果
Ds_SystemItemEffectType_Str["增加召唤师经验"] = 1 --增加召唤师经验
Ds_SystemItemEffectType_Str["增加召唤师点券"] = 2 --增加召唤师点券
Ds_SystemItemEffectType_Str["增加召唤师金币"] = 3 --增加召唤师金币
Ds_SystemItemEffectType_Str["增加召唤师钻石"] = 4 --增加召唤师钻石
Ds_SystemItemEffectType_Str["增加召唤师活跃"] = 5 --增加召唤师活跃

Ds_SystemTaskType_Str = {} --系统任务类型
Ds_SystemTaskType_Str["任务_每日任务"] = 1 --每日任务
Ds_SystemTaskType_Str["任务_成长任务"] = 2 --成长任务
Ds_SystemTaskType_Str["任务_每周任务"] = 3 --任务_每周任务

Ds_SystemTaskCountType_Str = {} --系统任务计数类型
Ds_SystemTaskCountType_Str["任务_单局"] = 1 --任务_单局
Ds_SystemTaskCountType_Str["任务_日累计"] = 2 --任务_日累计
Ds_SystemTaskCountType_Str["任务_周累计"] = 3 --任务_周累计
Ds_SystemTaskCountType_Str["任务_永久"] = 4 --任务_永久

Ds_SystemTaskNeedActType_Str = {} --系统任务行为需求类型
Ds_SystemTaskNeedActType_Str["任务_登陆游戏"] = 1 --登陆游戏
Ds_SystemTaskNeedActType_Str["任务_单局击杀英雄数量"] = 2 --单局击杀英雄数量
Ds_SystemTaskNeedActType_Str["任务_单局击杀野怪数量"] = 3 --单局击杀野怪数量
Ds_SystemTaskNeedActType_Str["任务_单局连杀小兵数量"] = 4 --单局连杀小兵数量
Ds_SystemTaskNeedActType_Str["任务_连续赢得积分赛场次"] = 5 --连续赢得积分赛场次
Ds_SystemTaskNeedActType_Str["任务_连续赢得对战比赛场次"] = 6 --连续赢得对战比赛场次
Ds_SystemTaskNeedActType_Str["任务_当日累计花费金币"] = 7 --当日累计花费金币
Ds_SystemTaskNeedActType_Str["任务_当日参加对战比赛场次"] = 8 --当日参加对战比赛场次
Ds_SystemTaskNeedActType_Str["任务_当日对战中累计造塔数量"] = 9 --当日对战中累计造塔数量
Ds_SystemTaskNeedActType_Str["任务_单局内开分矿次数"] = 10 --单局内开分矿次数
Ds_SystemTaskNeedActType_Str["任务_当日对战中杀龙次数"] = 11 --当日对战中杀龙次数
Ds_SystemTaskNeedActType_Str["任务_当日对战胜利场次"] = 12 --当日对战胜利场次
Ds_SystemTaskNeedActType_Str["任务_日活跃度点数"] = 13 --日活跃度点数
Ds_SystemTaskNeedActType_Str["任务_周活跃度点数"] = 14 --周活跃度点数
Ds_SystemTaskNeedActType_Str["任务_购买一个英雄"] = 15 --购买一个英雄
Ds_SystemTaskNeedActType_Str["任务_小兵升级一次"] = 16 --小兵升级一次
Ds_SystemTaskNeedActType_Str["任务_购买任意一个皮肤"] = 17 --购买任意一个皮肤
Ds_SystemTaskNeedActType_Str["任务_召唤师技能升级一次"] = 18 --召唤师技能升级一次

Ds_MoneyType_Str = {} --货币类型
Ds_MoneyType_Str["金币"] = 1 --
Ds_MoneyType_Str["钻石"] = 2 --
Ds_MoneyType_Str["点券"] = 3 --
Ds_MoneyType_Str["日活跃度"] = 4 --
Ds_MoneyType_Str["周活跃度"] = 5 --
