/* This file is generated by tdr. */
/* No manual modification is permitted. */

/* metalib version: 1 */
/* metalib md5sum: ffe11ec7494f03665e0edf5d1e817aec */

/* creation time: Fri Apr 28 09:43:20 2023 */
/* tdr version: 2.5.0, build at 20111124 */


using System;
using System.Diagnostics;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Text;
using tsf4g_tdr_csharp;

namespace MobaResDBMeta
{


public interface tsf4g_csharp_interface
{
        TdrError.ErrorType construct();
        TdrError.ErrorType pack(ref byte[] buffer, int size, ref int usedSize, uint cutVer);
        TdrError.ErrorType pack(ref TdrWriteBuf destBuf, uint cutVer);
        TdrError.ErrorType unpack(ref byte[] buffer, int size, ref int usedSize, uint cutVer);
        TdrError.ErrorType unpack(ref TdrReadBuf srcBuf, uint cutVer);
        TdrError.ErrorType load(ref byte[] buffer, int size, ref int usedSize, uint cutVer);
        TdrError.ErrorType load(ref TdrReadBuf srcBuf, uint cutVer);
        TdrError.ErrorType visualize(ref string buffer,int indent , char separator);
        TdrError.ErrorType visualize(ref TdrVisualBuf destBuf, int indent, char separator);
        TdrError.ErrorType getSizeInfo(byte[] buffer, int size, ref uint sizeInfo);
        TdrError.ErrorType getSizeInfo(TdrReadBuf srcBuf, ref uint sizeInfo);
}


public enum  ResDataOperate
{
        ResDataOperate_INT = 1, // 固定数值
        ResDataOperate_10K = 2, // 万分比
}
public enum  ResDataSet
{
        RESDATASET_SET = 0, // 数据覆盖
        RESDATASET_ADD = 1, // 数据加法
        RESDATASET_SUB = 2, // 数据减法
}
public enum  ATTRADDTYPE
{
        ATTRADD_BASE = 1, // 基础属性
        ATTRADD_UPADD = 2, // 加成属性(固定数值)
        ATTRADD_BASEMUL = 3, // 基础属性乘法(万分比)
        ATTRADD_UPADDMUL = 4, // 加成属性乘法(万分比)
        ATTRADD_ALLMUL = 5, // 所有属性乘法(万分比)
}
public enum  ATTRDATATYPE
{
        ATTRDATA_HPMAX = 1, // 当前最大生命值(固定值)
        ATTRHPDATA_HPCUR = 2, // 当前生命值(固定值)
        ATTRHPDATA_HPLOSE = 3, // 损失生命值(固定值)
        ATTRHPDATA_HPLOSEPRECENT = 4, // 损失生命值万分比
        ATTRDATA_MMAX = 5, // 当前最大法术值(固定值)
        ATTRHPDATA_MCUR = 6, // 当前法术值(固定值)
        ATTRHPDATA_MLOSE = 7, // 损失法术值(固定值)
}
public enum  LOGICOPTTYPE
{
        LOGICOPT_LESS = 0, // 小于
        LOGICOPT_LESS_EQ = 1, // 小于等于
        LOGICOPT_GREAT = 2, // 大于
        LOGICOPT_GREAT_EQ = 3, // 大于等于
        LOGICOPT_EQUAL = 4, // 等于
        LOGICOPT_NOT_EQUAL = 5, // 不等于
        LOGICOPT_AND = 6, // 逻辑与
        LOGICOPT_OR = 7, // 逻辑或
}
public enum  RaceType
{
        RACE_NEUTRAL = 0, // 中立种族
        RACE_HUMAN = 1, // 人族
        RACE_ORC = 2, // 兽族
        RACE_GHOST = 3, // 亡灵
        RACE_ELF = 4, // 精灵
        RACE_MAX = 5, // 种族最大值
}
public enum  LegionType
{
        LEGION_NEUTRAL = 0, // 中立军团
        LEGION_JUSTICE = 1, // 正义军团
        LEGION_EVIL = 2, // 邪恶军团
        LEGION_MAX = 3, // 军团最大值
}
public enum  ResHeroCapacityType
{
        ResHeroCapatyType_FIGHTER = 1, // 战士
        ResHeroAttrType_MAGE = 2, // 法师
        ResHeroAttrType_SUP = 3, // 辅助
        ResHeroAttrType_SHOOTER = 4, // 射手
        ResHeroAttrType_TANK = 5, // 坦克
        ResHeroAttrType_MAX = 6, // Max
}
public enum  ResWeaponType
{
        RESWEAPONTYPE_DISTANCE = 0,
        RESWEAPONTYPE_LONGDISTANCE = 1,
}
public enum  BattleTeamType
{
        WHITE = 0, // 白方队伍
        RED = 1, // 红方队伍
        BLUE = 2, // 蓝方队伍
        PURPLE = 3, // 紫方队伍
        GREEN = 4, // 绿方队伍
        PINK = 5, // 粉方队伍
        YELLOW = 6, // 黄方队伍
        TEAM_MAX = 7, // 队伍数量
}
public enum  TeamLegionType
{
        LEGION_FRIEND = 0, // 阵营友军
        LEGION_ENEMY = 1, // 阵营敌军
        LEGION_ALLL = 2, // 所有阵营单位
}
public enum  BattleActorType
{
        COMMON = 0, // 普通单位
        HERO = 1, // 英雄
        DOGFACE = 2, // 士兵
        MONSTER = 3, // 野怪
        TOWER = 4, // 防御塔
        GOLDMINE = 5, // 金矿
        BASE = 6, // 基地
        SUBBASE = 7, // 副基地
        STASISTRAP = 8, // 静止陷阱
        SCENEOBJECT = 9, // 场景物件
        ACTORPET = 10, // 跟宠
        MECHINE = 11, // 机械单位
        TRANSFERDOOR = 12, // 场景传送门
        ACTORTYPE_MAX = 13, // MAX
}
public enum  BattleActorSubType
{
        SUBTYPE_NONE = 0, // 无类型
        SUBTYPE_TECHDOGFACE = 1, // 科技建造士兵
        SUBTYPE_CHARMDOGFACE = 2, // 魅惑符咒士兵
        SUBTYPE_WILD_SPRING = 3, // 野外泉水
        SUBTYPE_HPMP_RUNE = 4, // 回血蓝符
        SUBTYPE_BIGDRAGON = 5, // 野怪精英_大龙
        SUBTYPE_SMALLDRAGON = 6, // 野怪精英_小龙
        SUBTYPE_WARD = 7, // 侦查守卫
        SUBTYPE_RELIFE = 8, // 治疗守卫
        SUBTYPE_SUMMONEDBIGDRAGON = 9, // 大龙召唤物
        SUBTYPE_HEROTRAP = 10, // 英雄技能陷阱
        SUBTYPE_TEAMGROUPGHOST = 11, // 队伍灵魂控制者
        SUBTYPE_BIGTITAN = 12, // 野怪精英_泰坦
        SUBTYPE_SMALLTITAN = 13, // 野怪精英_小泰坦
}
public enum  BattleActorSummonedType
{
        BATTLEACTORSUMMONEDTYPE_NONE = 0, // 非召唤物
        BATTLEACTORSUMMONEDTYPE_CREATURES = 1, // 生物召唤物
        BATTLEACTORSUMMONEDTYPE_STILL = 2, // 静止召唤物
        BATTLEACTORSUMMONEDTYPE_CHARM = 3, // 魅惑符咒召唤物(不可驱散)
}
public enum  BattleDeadBodyType
{
        BATTLEDEADBODYTYOE_ACTOR = 0, // 单位死亡尸体
        BATTLEDEADBODYTYOE_CARRY = 1, // 载具召唤尸体
        BATTLEDEADBODYTYOE_UDSPAWN = 2, // 腐地召唤尸体
}
public enum  BattleRusult
{
        RESULT_NONE = 0, // 无结果
        JUSTICE_WIN = 1, // 正义胜利
        EVIL_WIN = 2, // 邪恶胜利
        NO_WIN = 3, // 平局
}
public enum  ArmorType
{
        ARMORTYPE_LIGHT = 0, // 轻型护甲
        ARMORTYPE_MIDDLE = 1, // 中型护甲
        ARMORTYPE_HEAVY = 2, // 重型护甲
        ARMORTYPE_CITY = 3, // 城型护甲
        ARMORTYPE_HERO = 4, // 英雄护甲
        ARMORTYPE_BUILDING = 5, // 建筑建造中护甲
}
public enum  SkillAttackType
{
        ATTACK_TYPR_NONE = 0, // 攻击类型_无
        ATTACK_TYPR_NORMAL = 1, // 攻击类型_普通
        ATTACK_TYPR_INSERT = 2, // 攻击类型_穿刺
        ATTACK_TYPR_ENERGY = 3, // 攻击类型_能量
        ATTACK_TYPR_CITY = 4, // 攻击类型_攻城
        ATTACK_TYPR_HERO = 5, // 攻击类型_英雄
        ATTACK_TYPR_GOD = 6, // 攻击类型_神圣
        ATTACK_TYPR_MAX = 7, // 攻击类型_max
}
public enum  SpeedType
{
        SPEED_NONE = 0, // 无速度
        SPEED_FAST = 1, // 快
        SPEED_MIDDLE = 2, // 中
        SPEED_SLOW = 3, // 慢
}
public enum  ResFogViewType
{
        RESFOGVIEWTYPE_GROUND = 0, // 迷雾视野_地面
        RESFOGVIEWTYPE_AIR = 1, // 迷雾视野_高空
}
public enum  AIAttackType
{
        AIATKTYPE_AUTO = 0, // 主动攻击AI
        AIATKTYPE_PASSIVE = 1, // 被动攻击AI
        AIATKTYPE_STATICAUTO = 2, // 静止攻击AI,视野小半径，触发打开AI
}
public enum  ActorDeadTrigEventType
{
        ACTORDEADTRIGEVENT_SPAWNDOGFACE = 1, // 死亡基地刷小兵
        ACTORDEADTRIGEVENT_MAPSPAWNGROUP = 2, // 地图孵化一组怪物
        ACTORDEADTRIGEVENT_KILLERADDBUFF = 3, // 死亡给目标方增加BUFF
}
public enum  KillerTargetType
{
        SKILLERTARGETTYPE_SELF = 1, // 击杀者自身
        SKILLERTARGETTYPE_TEAMHERO = 2, // 击杀者队伍所有英雄
        SKILLERTARGETTYPE_LEGIONHERO = 3, // 击杀者阵营所有英雄
        SKILLERTARGETTYPE_LEGIONALL = 4, // 击杀者阵营所有英雄和士兵
}
public enum  ResActorMoveType
{
        ACTORMOVETYPE_GROUND = 0, // 地面移动单位
        ACTORMOVETYPE_AIR = 1, // 空中移动单位
}
public enum  ResActrorAITargetType
{
        ACTORAITARGETTYPE_ALL = 0, // AI目标_任意单位
        ACTORAITARGETTYPE_NONE = 1, // AI目标_无单位
        ACTORAITARGETTYPE_ENEMYHERO = 2, // AI目标_敌方英雄
        ACTORAITARGETTYPE_ENEMYDOGFACE = 3, // AI目标_敌方士兵
        ACTORAITARGETTYPE_ENEMYBUILD = 4, // AI目标_敌方建筑,统称
        ACTORAITARGETTYPE_MONSTER = 5, // AI目标_野怪
        ACTORAITARGETTYPE_SUMMONED = 6, // AI目标_召唤生物
        ACTORAITARGETTYPE_MAX = 7, // AI目标_最大值
}
public enum  ResAttrType
{
        EN_ATTR_MIN = 0, // 属性最小值
        EN_ATTR_HP = 1, // 生命值(计算后)
        EN_ATTR_MAX_HP = 2, // 最大生命值
        EN_ATTR_HP_RECOVERY = 3, // 生命回复/5s
        EN_ATTR_HP_RECOVERY_RATE = 4, // 生命回复率(万分比/5s)
        EN_ATTR_MAX_MP = 5, // 最大法术值
        EN_ATTR_MP = 6, // 法术值(计算后)
        EN_ATTR_MP_RECOVER = 7, // 法术回复/5s
        EN_ATTR_ATK = 8, // 攻击力
        EN_ATTR_ARMOR = 9, // 护甲值
        EN_ATTR_ARMOR_PIERCE = 10, // 护甲穿透
        EN_ATTR_ARMOR_PIERCE_RATE = 11, // 护甲穿透率(万分比)
        EN_ATTR_ATK_SPEED = 12, // 攻击速度(1万代表1s)
        EN_ATTR_ATK_STEAL_RATE = 13, // 生命偷取率(万分比)
        EN_ATTR_CRI_RATE = 14, // 暴击率(万分比)
        EN_ATTR_CRI_DAM_RATE = 15, // 暴击伤害率(万分比)
        EN_ATTR_MAGIC = 16, // 法术强度
        EN_ATTR_MAGIC_DEF = 17, // 法术抗性
        EN_ATTR_MD_PIERCE = 18, // 法术穿透
        EN_ATTR_MD_PIERCE_RATE = 19, // 法术穿透率(万分比)
        EN_ATTR_AP_STEAL_RATE = 20, // 法术吸血率(万分比)
        EN_ATTR_TENACITY_RATE = 21, // 韧性率(万分比)
        EN_ATTR_CD_REDUCTION = 22, // 冷却缩减(万分比)
        EN_ATTR_MOVE_SPEED = 23, // 移动速度(1万代表1M)
        EN_ATTR_EVASION_RATE = 24, // 闪避值(万分比)
        EN_ATTR_MAX_HP_LV = 25, // 生命值成长
        EN_ATTR_HP_RECOVER_LV = 26, // 生命回复成长(/5s)
        EN_ATTR_ATK_LV = 27, // 攻击力成长
        EN_ATTR_MAGIC_LV = 28, // 法术强度成长
        EN_ATTR_ARMOR_LV = 29, // 护甲成长
        EN_ATTR_MAGIC_DEF_LV = 30, // 法术抗性成长
        EN_ATTR_MAX_MP_LV = 31, // 法术值成长
        EN_ATTR_MP_RECOVER_LV = 32, // 法术值回复成长(/5s)
        EN_ATTR_REB_DAMAGE = 33, // 反弹值
        EN_ATTR_REB_DAMAGE_RATE = 34, // 反伤率(万分比)
        EN_ATTR_ATKMISS_RATE = 35, // 攻击丢失率(万分比)
        EN_ATTR_COLLIDERRADIUS = 36, // 碰撞体积
        EN_ATTR_VISIONRADIUS = 37, // 视野半径
        EN_ATTR_WARNRADIUS = 38, // 警戒半径
        EN_ATTR_FOWRADIUS = 39, // 迷雾半径
        EN_ATTR_MAGIC_ATK_IMM = 40, // 物理伤害减免
        EN_ATTR_MAGIC_MGIC_IMM = 41, // 法术伤害减免
        EN_ATTR_ATK_DMG_RATE = 42, // 物理伤害百分比(万分比,计算完后)
        EN_ATTR_AP_DMG_RATE = 43, // 法术伤害百分比(万分比,计算完后)
        EN_ATTR_ATK_GET_DMG_RATE = 44, // 受到物理伤害率(万分比,计算完后)
        EN_ATTR_AP_GET_DMG_RATE = 45, // 受到法术伤害率(万分比,计算完后)
        EN_ATTR_NORMALDMG_IMM = 46, // 被普通攻击伤害减免值
        EN_ATTR_NORMALDMG_IMM_RATE = 47, // 被普通攻击伤害减免率(万分比)
        EN_ATTR_FARNORMALDMG_IMM_RATE = 48, // 被远程普通攻击伤害减免率(万分比)
        EN_ATTR_MONSTERDMG_ADD = 49, // 对野怪伤害加成值
        EN_ATTR_MONSTERDMG_ADD_COE = 50, // 对野怪伤害加成系数(万分比)
        EN_ATTR_AI_ATKDMG_COE = 51, // AI攻击伤害系数
        EN_ATTR_AI_DEFDMG_COE = 52, // AI防御伤害系数
        EN_ATTR_BUILDING_COE = 53, // 对建筑伤害系数(万分比,计算完后)
        EN_ATTR_BUILDING_BECOE = 54, // 被建筑伤害系数(万分比,计算完后)
        EN_ATTR_BUFFRESTADD_CORE = 55, // BUFF回属性加成系数
        EN_ATTR_BASERECOVERYADD_CORE = 56, // 基础回复加成系数
        EN_ATTR_NSATKDIS_ADD = 57, // 普攻半径加成
        EN_ATTR_MAX = 58, // 最大值
}
public enum  BuffPropertyType
{
        BUFFPROPERTYTYPE_TALENT = 1, // 天赋BUFF
        BUFFPROPERTYTYPE_SYSTEM = 2, // 系统BUFF
        BUFFPROPERTYTYPE_USEFUL = 3, // 数值增益BUFF
        BUFFPROPERTYTYPE_UNUSEFUL = 4, // 数值减益BUFF
        BUFFPROPERTYTYPE_HARMFUL = 5, // 控制BUFF
        BUFFPROPERTYTYPE_UNHARMFUL = 6, // 免疫控制BUFF
        BUFFPROPERTYTYPE_TRIGSKILL = 7, // 触发技能BUFF
        BUFFPROPERTYTYPE_TRIGBUFF = 8, // 触发BUFF
        BUFFPROPERTYTYPE_GODBUFF = 9, // 上帝BUFF
}
public enum  BuffPropertySubType
{
        BUFFPROPERTYSUBTYPE_SWIM = 1, // 眩晕类子类型
        BUFFPROPERTYSUBTYPE_DELSPEED = 2, // 减速类子类型
        BUFFPROPERTYSUBTYPE_SILENT = 3, // 沉默类子类型
        BUFFPROPERTYSUBTYPE_BEATBACK = 4, // 击飞击退类子类型
        BUFFPROPERTYSUBTYPE_XSPACE = 5, // X空间类子类型
        BUFFPROPERTYSUBTYPE_MPOP = 6, // 法术值增减益子类型
}
public enum  BuffMergeType
{
        BUFFERMERGRES_NONE = 0, // 无法合并
        BUFFERMERGRES_CASTERSTACK = 1, // BUFF堆叠(施法者)
        BUFFERMERGRES_GROUPSTACK = 2, // BUFF堆叠(组ID)
        BUFFERMERGRES_CASTERREPLACE = 3, // 替换旧的BUFF（同一施法者，高等级替换低等级，同等级刷数据）
        BUFFERMERGRES_CASTERMUTEX = 4, // 新Buff被排斥(施法者)
        BUFFERMERGRES_GROUPIDMUTEX = 5, // 新Buff被排斥(组ID)
        BUFFERMERGRES_GROUPIDREPLACE = 6, // 替换旧的BUFF（只按组ID）
        BUFFERMERGRES_UNCASTERREPLACE = 7, // 不同施法者并行BUFF,同一施法者替换旧的BUFF,不同施法者无法合并但是生效
}
public enum  BuffOp
{
        BUFF_OP_ADD = 1, // 添加buff操作
        BUFF_OP_DEL = 2, // 移除buff操作
        BUFF_OP_OVERLAY = 3, // 覆盖buff操作
        BUFF_OP_INTERRUPT = 4, // 中断buff操作
}
public enum  BuffRemoveType
{
        BUFFREMOVETYPE_DEFUALT = 0, // 任意移除Buff
        BUFFREMOVETYPE_DEAD = 1, // 死亡移除Buff
        BUFFREMOVETYPE_GOD = 2, // 上帝移除Buff
}
public enum  BuffEndType
{
        BUFFENDTYPE_ENC = 0, // Buff自然结束
        BUFFENDTYPE_BECLEAR = 1, // Buff被动清除
        BUFFENDTYPE_DEADCLEAR = 2, // Buff死亡清除
}
public enum  BuffEffectType
{
        BUFFEFFECTTYPE_ATTROPE = 1, // 属性修改
        BUFFEFFECTTYPE_SETATTR = 2, // 回属性
        BUFFEFFECTTYPE_SPRINGSETATTR = 3, // 泉水回属性
        BUFFEFFECTTYPE_DMGABSORB = 4, // 吸收伤害
        BUFFEFFECTTYPE_SWIM = 5, // 眩晕
        BUFFEFFECTTYPE_SILENT = 6, // 沉默
        BUFFEFFECTTYPE_DRAG = 7, // 拉扯
        BUFFEFFECTTYPE_BEATBACK = 8, // 击飞击退
        BUFFEFFECTTYPE_SNEER = 9, // 嘲讽
        BUFFEFFECTTYPE_FEAR = 10, // 恐惧效果
        BUFFEFFECTTYPE_CYCLONE = 11, // 龙卷风效果
        BUFFEFFECTTYPE_PHYIMM = 12, // 物理免疫
        BUFFEFFECTTYPE_MGCIMM = 13, // 魔法免疫
        BUFFEFFECTTYPE_GOD = 14, // 无敌
        BUFFEFFECTTYPE_DELBUFF = 15, // 清除BUFF
        BUFFEFFECTTYPE_IMMDELBUFF = 16, // 免疫DEBUFF
        BUFFEFFECTTYPE_SUPERBODY = 17, // 霸体BUFF
        BUFFEFFECTTYPE_XSPACE = 18, // 进入X空间
        BUFFEFFECTTYPE_GOLDENBODY = 19, // BUFF金身
        BUFFEFFECTTYPE_ADDAVATARSKILL = 20, // 触发变体技能
        BUFFEFFECTTYPE_DELAVATARSKILL = 21, // 解除变体技能
        BUFFEFFECTTYPE_FOEVERATTROPE = 22, // 永久修改属性
        BUFFEFFECTTYPE_CLEARSKILCASTCNT = 23, // 清空技能释放次数
        BUFFEFFECTTYPE_ADDSKILL = 24, // 触发添加技能
        BUFFEFFECTTYPE_TRIGSKILLPHASE_EFFECT = 25, // 触发技能阶段效果
        BUFFEFFECTTYPE_TRIGSKILLPHASE_SERACHEFFECT = 26, // 触发技能阶段搜索和效果
        BUFFEFFECTTYPE_ADDGOLD = 27, // BUFF增加金钱
        BUFFEFFECTTYPE_ADDEXP = 28, // BUFF增加经验
        BUFFEFFECTTYPE_BLINDNESS = 29, // 烟幕失明效果
        BUFFEFFECTTYPE_SUMMONEDLIFETIME = 30, // BUFF修改召唤物存活时间
        BUFFEFFECTTYPE_SOULFETTER = 31, // 灵魂锁链
        BUFFEFFECTTYPE_NETTRAP = 32, // 撒网诱捕
        BUFFEFFECTTYPE_TPCHAT = 33, // 回城吟唱
        BUFFEFFECTTYPE_STEALTH = 34, // BUFF隐身
        BUFFEFFECTTYPE_ANTISTEALTH = 35, // BUFF反隐身
        BUFFEFFECTTYPE_TARGETVISION = 36, // BUFF目标视野
        BUFFEFFECTTYPE_CHANGEAVATAR = 37, // BUFF变身
        BUFFEFFECTTYPE_ATKCRI = 38, // BUFF普攻暴击
        BUFFEFFECTTYPE_FLIMSYBURYING = 39, // BUFF薄葬
        BUFFEFFECTTYPE_POLYMORPH = 40, // BUFF变形术
        BUFFEFFECTTYPE_IMPRISON = 41, // BUFF禁锢
        BUFFEFFECTTYPE_LIGHTGIRLFRIEND = 42, // BUFF光之女圈内友军(定制)
        BUFFEFFECTTYPE_LIGHTGIRLENEMY = 43, // BUFF光之女圈内敌军(定制)
        BUFFEFFECTTYPE_DMGTOTRANSFER = 44, // BUFF伤害转移
        BUFFEFFECTTYPE_DMGNUMB = 45, // BUFF伤害麻木(船长船游)
        BUFFEFFECTTYPE_DIVINESHIELD = 46, // 圣盾(无敌但能被选中)
        BUFFEFFECTTYPE_SPELLSHIELD = 47, // BUFF魔法护盾
        BUFFEFFECTTYPE_MAX = 48, // Buff效果最大值
}
public enum  BuffEffectAddExpGoldType
{
        BUFFEFFADDEXPMONEYTYPE_DEFAULT = 0, // BUFF固定数值增加
        BUFFEFFADDEXPMONEYTYPE_GAMETIME = 1, // BUFF游戏时间增加
}
public enum  BuffEffectRemoveBuffType
{
        BUFFEFFCTREMOVEBUFFTYPE_GROUPID = 0, // 根据BUFF组清除BUFF
        BUFFEFFCTREMOVEBUFFTYPE_BUFFTYPE = 1, // 根据BUFF类型清除BUFF
        BUFFEFFCTREMOVEBUFFTYPE_SUBBUFFTYPE = 2, // 根据BUFF子类型清除BUFF
}
public enum  BuffEftSetAttrType
{
        BUFFSETATTRPARAM_HP = 1, // 回属性HP
        BUFFSETATTRPARAM_MP = 2, // 回属性MP
        BUFFSETATTRPARAM_ENERGY = 3, // 回属性怒气
}
public enum  BuffEffectCoefType
{
        BUFFEFFECTCOEFTYPE_DEFAULT = 0, // BUFF效默认效果系数
        BUFFEFFECTCOEFTYPE_HEROLEVEL = 1, // BUFF效果施法者等级系数
}
public enum  BuffEftBeatBackType
{
        BUFFBEATBACKTYPE_CASTER = 0, // 击飞击退_施法者
        BUFFBEATBACKTYPE_SKILLPOS = 1, // 击飞击退_技能目标点(对点释放)
        BUFFBEATBACKTYPE_CASTERFIXEDDISTANCE = 2, // 击飞击退_施法者固定距离(动态计算VEC/ACC)
}
public enum  BuffEffectTrigType
{
        BUFFTRIGTYPE_TIME = 0, // BUFF效果时间周期生效
        BUFFTRIGTYPE_DEAD = 1, // 死亡生效
        BUFFTRIGTYPE_NORMALEACHHIT = 2, // 普通攻击命中单个生效
        BUFFTRIGTYPE_CASTSKILL = 3, // 释放技能生效
        BUFFTRIGTYPE_CASTNORMALSKILL = 4, // 释放普攻技能生效
        BUFFTRIGTYPE_CASTSKILLROLLEND = 5, // 释放技能前摇结束生效
        BUFFTRIGTYPE_BEHIT = 6, // 被伤害生效
        BUFFTRIGTYPE_BEHITCRI = 7, // 被伤害暴击生效
        BUFFTRIGTYPE_KILLACTOR = 8, // 击杀单位生效
        BUFFTRIGTYPE_CASTSKILLCNT = 9, // 指定技能释放次数生效(技能前摇完)
        BUFFTRIGTYPE_BECRITHIT = 10, // 被致命一击生效
        BUFFTRIGTYPE_NORMALHIT = 11, // 普通攻击命中生效
        BUFFTRIGTYPE_SPECQWERSKILLHIT = 12, // 被特定单位QWER伤害生效
        BUFFTRIGTYPE_SPECACTORNORMALSKILLHIT = 13, // 被特定单位普攻伤害生效
        BUFFTRIGTYPE_BUFFOVERLAY = 14, // 当前Buff堆叠生效
}
public enum  BuffEventType
{
        BUFFEVENTTYPE_REMOVESELF = 1, // 当前BUFF移除
        BUFFEVENTTYPE_LAYERCHANGE = 2, // 当前BUFF层级改变
        BUFFEVENTTYPE_LAYERRESET = 3, // 当前BUFF层级重置
        BUFFEVENTTYPE_CASTBUFF = 4, // 当前BUFF释放BUFF
        BUFFEVENTTYPE_REDAMAGE = 5, // 当前BUFF反弹伤害
        BUFFEVENTTYPE_DMGNUMBEND = 6, // 当前BUFF伤害麻木触发
        BUFFEVENTTYPE_FEEDBACKCASTER = 7, // 当前BUFF反馈施法者
}
public enum  BuffEventTrigType
{
        BUFFEVENTTRIGTYPE_BEDAMAGE = 1, // 受到伤害触发BUFF事件
        BUFFEVENTTRIGTYPE_DMGTARGET = 2, // 对目标造成伤害触发BUFF事件
        BUFFEVENTTRIGTYPE_SKILLCASTCNT = 3, // 技能释放次数触发BUFF事件
        BUFFEVENTTRIGTYPE_NORMALSKILLHIT = 4, // 普通攻击命中触发BUFF事件
        BUFFEVENTTRIGTYPE_ATTRHPCHANGE = 5, // 生命值改变触发BUFF事件
        BUFFEVENTTRIGTYPE_BENORMALSKILLDAMAGE = 6, // 受到普攻伤害触发BUFF事件
        BUFFEVENTTRIGTYPE_BENOPHYDAMAGE = 7, // 受到物理伤害触发BUFF事件
        BUFFEVENTTRIGTYPE_STEALUNIONS = 8, // 隐身移除事件集合事件,攻击,被伤害，建造，使用道具
        BUFFEVENTTRIGTYPE_BMSTEALUNIONS = 9, // 剑圣隐身移除事件集合事件,攻击,建造，使用道具
        BUFFEVENTTRIGTYPE_NORMALSKILLREDAMGE = 10, // 受普通攻击触发反弹BUFF事件
        BUFFEVENTTRIGTYPE_CHANGEDAY = 11, // 切换到白天触发BUFF事件
        BUFFEVENTTRIGTYPE_ELFTALENTBUFFREMOVE = 12, // 精灵族通用天赋BUFF移除事件
        BUFFEVENTTRIGTYPE_SPELLFIELDDO = 13, // 魔法护盾抵消触发BUFF事件
        BUFFEVENTTRIGTYPE_CASTQWERSKILL = 14, // 释放QWER技能触发BUFF事件
        BUFFEVENTTRIGTYPE_BUFFTRIG = 15, // 当前BUFF生效触发BUFF事件
        BUFFEVENTTRIGTYPE_BUFFEND = 16, // 当前BUFF结束触发BUFF事件
}
public enum  BuffEventEffectType
{
        BUFFEVENTEFFECTTYPE_HP = 1, // BUFF事件生命值效果系数
}
public enum  BuffEventFeedBackCaterType
{
        BUFFEVENTFEEDBACKCATERTYPE_MANAFLARE = 1, // BUFF事件反馈施法者_技能魔法闪耀
        BUFFEVENTFEEDBACKCATERTYPE_ADDBUFF = 2, // BUFF事件反馈施法者_添加BUFF
        BUFFEVENTFEEDBACKCATERTYPE_SKILL = 3, // BUFF事件反馈施法者_技能反馈
}
public enum  SkillType
{
        SKILLTYPE_NORMAL = 1, // 普通攻击
        SKILLTYPE_AUTO = 2, // 主动技能
        SKILLTYPE_AUTO2 = 3, // 主动二段技能
        SKILLTYPE_AUTO3 = 4, // 主动三段技能
        SKILLTYPE_SWITCH = 5, // 主动开关技能(一个需设置技能栏一个无)
        SKILLTYPE_PASSIVE = 6, // 被动技能
}
public enum  SkillSubType
{
        SKILLSUBTYPE_NORMALATTACK = 1, // 普通技能
        SKILLSUBTYPE_ATTACK = 2, // 攻击技能
        SKILLSUBTYPE_SUBBUFF = 3, // 辅助BUFF技能
        SKILLSUBTYPE_SUBRESHP = 4, // 辅助回血技能
        SKILLSUBTYPE_RESHP = 5, // 基础回血技能
        SKILLSUBTYPE_TP = 6, // 基础回程技能
        SKILLSUBTYPE_AVATAR = 7, // 变体技能
        SKILLSUBTYPE_SUMMONED = 8, // 召唤师技能
        SKILLSUBTYPE_POSTRANSFORM = 9, // 基础传送技能
        SKILLSUBTYPE_SELFREVIVAL = 10, // 重生复活技能，复活自身
        SKILLSUBTYPE_SUMMONREVIVAL = 11, // 召唤复活技能，复活他人
        SKILLSUBTYPE_ENERGY = 12, // 充能技能
}
public enum  SkillAICastType
{
        SKILLAICASTTYPE_REHP = 1, // AI技能类型_治疗
        SKILLSUBTYPE_CTR = 2, // AI技能类型_控制
        SKILLSUBTYPE_USEFUL = 3, // AI技能类型_增益
        SKILLSUBTYPE_UNUSEFUL = 4, // AI技能类型_减益
        SKILLSUBTYPE_DMG = 5, // AI技能类型_伤害
}
public enum  SkillBarType
{
        SKILLBARTYPE_NONE = 0, // 技能栏无
        SKILLBARTYPE_Q = 1, // 技能栏Q
        SKILLBARTYPE_W = 2, // 技能栏W
        SKILLBARTYPE_E = 3, // 技能栏E
        SKILLBARTYPE_R = 4, // 技能栏R
        SKILLBARTYPE_A = 5, // 技能栏A
        SKILLBARTYPE_F1 = 6, // 技能栏F1
        SKILLBARTYPE_F2 = 7, // 技能栏F2
        SKILLBARTYPE_F3 = 8, // 技能栏F3
        SKILLBARTYPE_F4 = 9, // 技能栏F4
        SKILLBARTYPE_NORMAL1 = 10, // 技能栏普攻1
        SKILLBARTYPE_NORMAL2 = 11, // 技能栏普攻2
        SKILLBARTYPE_TALENT = 12, // 技能栏天赋
        SKILLBARTYPE_RANCEEYE = 13, // 技能栏种族眼
        SKILLBARTYPE_MAX = 14, // 技能栏最大值
}
public enum  SkillTrigCastType
{
        SKILLTRIGTYPE_AUTOCAST = 0, // 主动释放触发
        SKILLTRIGTYPE_TALENT = 1, // 技能天赋触发
        SKILLTRIGTYPE_NOOTHER = 2, // 被动无触发
        SKILLTRIGTYPE_DEAD = 3, // 单位死亡触发
        SKILLTRIGTYPE_TIMEDURA = 4, // 时间周期触发
        SKILLTRIGTYPE_NORMALHIT = 5, // 普通攻击命中锁定目标触发(第一个目标)
        SKILLTRIGTYPE_BENORMALHIT = 6, // 被普通攻击命中触发
        SKILLTRIGTYPE_CASTNORMALSKILL = 7, // 释放普攻技能触发
        SKILLTRIGTYPE_CASTAUTOSKILL = 8, // 释放QWER技能触发
        SKILLTRIGTYPE_CASTSKILLROLLEND = 9, // 释放技能前摇结束触发
        SKILLTRIGTYPE_BEHIT = 10, // 被任意伤害触发
        SKILLTRIGTYPE_NORMALSKILLBEHIT = 11, // 被普攻伤害触发
        SKILLTRIGTYPE_AUTOSKILLBEHIT = 12, // 被主动技能伤害触发
        SKILLTRIGTYPE_PHYDMGHIT = 13, // 被物理攻击伤害触发
        SKILLTRIGTYPE_INSERTDMGHIT = 14, // 被穿刺类攻击伤害触发
        SKILLTRIGTYPE_BECRITHIT = 15, // 被致命一击伤害触发
        SKILLTRIGTYPE_UNPASSIVESKILLDAMAGE = 16, // 非被动技能造成伤害触发
        SKILLTRIGTYPE_QWERSKILLDAMAGE = 17, // QWER技能造成伤害触发
        SKILLTRIGTYPE_NORMALEACHHIT = 18, // 普通攻击伤害目标触发（AOE）
        SKILLTRIGTYPE_KILLTARGET = 19, // 击杀目标触发
        SKILLTRIGTYPE_BUFFEFFECTMANAFLARE = 20, // Buff效果魔法闪耀触发
        SKILLTRIGTYPE_LEVELUP = 21, // 角色等级提升触发
        SKILLTRIGTYPE_Day2NIGHT = 22, // 切换到夜晚触发
        SKILLTRIGTYPE_NIGHT2DAY = 23, // 切换到白天触发
        SKILLTRIGTYPE_CALLSUMMONED = 24, // 召唤召唤物触发
        SKILLTRIGTYPE_SUMMONEDDEAD = 25, // 召唤物死亡触发
}
public enum  SkillTrigCastCondType
{
        SKILLTRIGCONDTYPE_DURANOTDAMAGE = 1, // 一定时间内未受伤害
        SKILLTRIGCONDTYPE_DURANOTNORMALSKILL = 2, // 一定时间内未释放普攻(包括变体普攻)
        SKILLTRIGCONDTYPE_DURANOTBEDAMAGEANDNORMALSKILL = 3, // 一定时间内未受伤害和未释放普攻
        SKILLTRIGCONDTYPE_RANDOM = 4, // 一定随机概率
        SKILLTRIGCONDTYPE_LESSHP = 5, // 生命值低于一定值
        SKILLTRIGCONDTYPE_SELECTSKILLGROUPID = 6, // 指定一个技能组ID(主动技能不支持)
        SKILLTRIGCONDTYPE_SELECTACTORTYPE = 7, // 指定一个目标类型(主动技能不支持)
        SKILLTRIGCONDTYPE_RANGEEXITTEAMDEADBODY = 8, // 技能攻击范围内存在友军尸体
        SKILLTRIGCONDTYPE_RANGEEXITANYDEADBODY = 9, // 技能攻击范围内存在任意尸体(被动技能不支持)
        SKILLTRIGCONDTYPE_RANGEEXITANYDEADBODYANDACTORNUMLIMIT = 10, // 技能攻击范围内存在尸体且召唤数目限制(被动技能不支持)
        SKILLTRIGCONDTYPE_TEAMACTORNUMMAXLIMIT = 11, // 队伍指定单位数量上限限制(被动技能不支持)
        SKILLTRIGCONDTYPE_NIGHT = 12, // 技能条件所需夜晚
        SKILLTRIGCONDTYPE_NOREVIVAL = 13, // 无复活技能或道具
        SKILLTRIGCONDTYPE_ELFNIGHTTALENTTIRG = 14, // 精灵族夜晚天赋效果触发条件
        SKILLTRIGCONDTYPE_SKILLXPOSMARKDIS = 15, // 技能X标记点距离条件
        SKILLTRIGCONDTYPE_SELECTSUMMONRESID = 16, // 指定召唤召唤物怪物ID条件
        SKILLTRIGCONDTYPE_UDDEADBODYNOTFULL = 17, // 不死灵魂战车尸体未满条件
}
public enum  SkillTrigRevivalParamType
{
        SKILLTRIGREVIVALTYPE_INT = 0, // 技能复活血蓝固定值
        SKILLTRIGPARAMTYPE_10K = 1, // 技能复活血蓝万分比
        SKILLTRIGPARAMTYPE_LEVEL = 2, // 技能复活血蓝等级系数
}
public enum  SkillTargetType
{
        SKILL_TARGETTYPE_ALL = 0, // 所有单位
        SKILL_TARGETTYPE_SELF = 1, // 自身
        SKILL_TARGETTYPE_ALLENEMY = 2, // 所有敌方
        SKILL_TARGETTYPE_ALLSELF = 3, // 所有己方
        SKILL_TARGETTYPE_MYHERO = 4, // 我方英雄
        SKILL_TARGETTYPE_MYDOGFACE = 5, // 我方士兵
        SKILL_TARGETTYPE_MYBUILD = 6, // 我方建筑
        SKILL_TARGETTYPE_ENEMYHERO = 7, // 敌方英雄
        SKILL_TARGETTYPE_ENEMYDOGFACE = 8, // 敌方士兵
        SKILL_TARGETTYPE_ENEMYBUILD = 9, // 敌方建筑
        SKILL_TARGETTYPE_MYTEAMCALLER = 10, // 自身队伍召唤物
        SKILL_TARGETTYPE_ENEMYCALLER = 11, // 敌方召唤物
        SKILL_TARGETTYPE_MYALLNOTBUILD = 12, // 所有己方除建筑
        SKILL_TARGETTYPE_MYALLNOTBUILDANDME = 13, // 所有己方除建筑除施法者
        SKILL_TARGETTYPE_ALLENEMTNOTBUILD = 14, // 所有敌方除建筑
        SKILL_TARGETTYPE_ALLENEMTNOTHEROANDBUILD = 15, // 所有敌方除英雄和建筑
        SKILL_TARGETTYPE_MYLONGACTORNOTBUILD = 16, // 所有己方远程除建筑
        SKILL_TARGETTYPE_MYNEARACTORNOTBUILD = 17, // 所有己方近战除建筑
        SKILL_TARGETTYPE_ALLENEMTNOTBUILDANDMONSTER = 18, // 所有敌方除建筑和野怪
        SKILL_TARGETTYPE_MYTEAMALLNOTBUILD = 19, // 所有己方队伍除建筑
        SKILL_TARGETTYPE_MYTEAMLONGACTORNOTBUILD = 20, // 所有己方队伍远程除建筑
        SKILL_TARGETTYPE_ALLDOGFACEANDMONSTRENOTSUMM = 21, // 所有士兵及野怪除召唤物
        SKILL_TARGETTYPE_ALLTARGETLEGIONACTOR = 22, // 目标阵营单位
        SKILL_TARGETTYPE_ALLTARGETLEGIONHERO = 23, // 目标阵营所有英雄(无范围搜索)
        SKILL_TARGETTYPE_ALLTARGETLEGIONHERODOGFACE = 24, // 目标阵营所有英雄和士兵(无范围搜索)
        SKILL_TARGETTYPE_ALLTARGETTEAMHERO = 25, // 目标队伍所有英雄(无范围搜索)
        SKILL_TARGETTYPE_CASTERHOLEGIONALLHERO = 26, // 施法者敌对阵营所有英雄(无范围搜索)
        SKILL_TARGETTYPE_ALLMONSTER = 27, // 所有野怪
        SKILL_TARGETTYPE_MYTEAMHERO = 28, // 我方队伍英雄
}
public enum  SkillDeadbodyTargetType
{
        SKILLDEADBODYTARGETTYPE_ALLACTOR = 0, // 所有单位尸体
        SKILLDEADBODYTARGETTYPE_MYTEAM = 1, // 所有己方队伍尸体
        SKILLDEADBODYTARGETTYPE_MYLEGION = 2, // 所有己方阵营尸体
        SKILLDEADBODYTARGETTYPE_ALLACTORADNCARRDY = 3, // 所有单位和载具尸体
}
public enum  SkillDmgType
{
        SKILLDMGTYPE_PHY = 1, // 物理伤害
        SKILLDMGTYPE_MGC = 2, // 法术伤害
        SKILLDMGTYPE_ALL = 3, // 全额伤害
}
public enum  SkillDistanceType
{
        SKILLDISTANCETYPE_NEARA = 0, // 近战技能
        SKILLDISTANCETYPE_FAR = 1, // 远程技能
}
public enum  SkillAtkActorType
{
        SKILLATKACTORTYPE_GROUND = 0, // 攻击地面单位
        SKILLATKACTORTYPE_AIR = 1, // 攻击空中单位
        SKILLATKACTORTYPE_AIRANDGROUND = 2, // 攻击空地单位
}
public enum  SkillPassiveBreakType
{
        SKILLPASSIVEBREAKTYPE_ALL = 1, // 任意打断(1.受攻击)
        SKILLPASSIVEBREAKTYPE_SOFTBUFF = 2, // 软控Buff打断
        SKILLPASSIVEBREAKTYPE_DEBUFF = 3, // 硬控Buff打断
        SKILLPASSIVEBREAKTYPE_DEAD = 4, // 死亡打断
        SKILLPASSIVEBREAKTYPE_GOD = 5, // 上帝模式，能够打断所有(程序保护用)
}
public enum  SkillAutoBreakBehaviType
{
        SKILLAUTOBREAKBEHAVITYPE_SKILLBEFOREROLL = 1, // 技能前摇打断
        SKILLAUTOBREAKBEHAVITYPE_AUTOCASTSKILL = 2, // 主动释放技能打断
        SKILLAUTOBREAKBEHAVITYPE_USEITEM = 3, // 使用道具打断
        SKILLAUTOBREAKBEHAVITYPE_BUILD = 4, // 建造打断
        SKILLAUTOBREAKBEHAVITYPE_MOVE = 5, // 移动打断
}
public enum  SkillAutoBreakType
{
        SKILLAUTOBREAKTYPE_LV1 = 1, // 技能前摇打断
        SKILLAUTOBREAKTYPE_LV2 = 2, // 建造和使用道具打断
        SKILLAUTOBREAKTYPE_LV3 = 3, // 技能前摇和移动打断
        SKILLAUTOBREAKTYPE_LV4 = 4, // 建造和使用道具和移动打断
        SKILLAUTOBREAKTYPE_LV5 = 5, // 主动使用技能打断
        SKILLAUTOBREAKTYPE_LV6 = 6, // 主动使用技能和使用道具和移动打断
}
public enum  SkillInputOpType
{
        SKILLINPUTOPTYPE_NONE = 0, // 操控类型_无
        SKILLINPUTOPTYPE_DIR = 1, // 操控类型_控制朝向
}
public enum  SkillCooldownType
{
        SKILLCOOLDOWNTYPE_NONE = 0, // 无冷却
        SKILLCOOLDOWNTYPE_TIME = 1, // 时间冷却
}
public enum  SkillCDStartType
{
        SKILLCDSTARTTYPE_CASTSKILL = 0, // 释放技能启动
        SKILLCDSTARTTYPE_SKILLROLLEND = 1, // 技能前摇结束启动
        SKILLCDSTARTTYPE_SKILATKEND = 2, // 技能后摇结束启动
}
public enum  SkillCostType
{
        SKILLCOSTYPE_NONE = 0, // 无消耗
        SKILLCOSTYPE_MP = 1, // 法术值消耗
        SKILLCOSTYPE_ENERGY = 2, // 计数能量点
        SKILLCOSTYPE_SKILLPT = 3, // 技能充能点
        SKILLCOSTYPE_ITEM = 4, // 道具
}
public enum  SkillPointType
{
        SKILLPOINTTYPE_SLFE = 0, // 自身
        SKILLPOINTTYPE_SLFEPOS = 1, // 自身位置
        SKILLPOINTTYPE_TARGET = 2, // 选择目标
        SKILLPOINTTYPE_DIRECTION = 3, // 选择朝向
        SKILLPOINTTYPE_AREA = 4, // 选择区域
        SKILLPOINTTYPE_AREATARGET = 5, // 选择区域目标
        SKILLPOINTTYPE_MAPAREA = 6, // 选择地图区域
        SKILLPOINTTYPE_MAPTARGET = 7, // 选择地图目标
        SKILLPOINTTYPE_AREACAMERAFOLLOW = 8, // 选择区域并镜头跟随
}
public enum  SkillPointAreaType
{
        SKILLPOINTAREA_NONE = 0, // 无区域
        ASKILLPOINTAREA_RECTANGLE = 1, // 矩形
        SKILLPOINTAREA_CIRCLE = 2, // 圆形
        SKILLPOINTAREA_CIRCULAR = 3, // 扇形
}
public enum  SkillAttkRollBuffType
{
        SKILLATKROLLBUFFTYPE_NONE = 0, // 前摇效果_无
        SKILLATKROLLBUFFTYPE_MOVE = 1, // 前摇效果_移动
        SKILLATKROLLBUFFTYPE_SWIM = 2, // 前摇效果_眩晕
        SKILLATKROLLBUFFTYPE_SILENT = 3, // 前摇效果_沉默
        SKILLATKROLLBUFFTYPE_SNEER = 4, // 前摇效果_嘲讽
        SKILLATKROLLBUFFTYPE_PASSIVEMOVE = 5, // 前摇效果_被动位移
        SKILLATKROLLBUFFTYPE_PHYIMM = 6, // 前摇效果_物理免疫
        SKILLATKROLLBUFFTYPE_MGCIMM = 7, // 前摇效果_魔法免疫
        SKILLATKROLLBUFFTYPE_GOD = 8, // 前摇效果_无敌
        SKILLATKROLLBUFFTYPE_TYPEMAX = 9, // 前摇效果_Max
}
public enum  SkillCtrCastType
{
        SKILLCTRCASTTYPE_AIATKROLLCAST = 0, // 有前摇通过AI释放
        SKILLCTRCASTTYPE_AINOTATKCASTCAST = 1, // 无前摇通过AI释放
        SKILLCTRCASTTYPE_DIRECT = 2, // 无前摇不通过AI受控制释放
        SKILLCTRCASTTYPE_GOD = 3, // 上帝释放(不通过AI,任何状态可放，无前摇)
        SKILLCTRCASTTYPE_PASSIVECAST = 4, // 被动技能直接释放
}
public enum  SkillBeforeRollType
{
        SKILLBEFOREROLLTYPE_FIXTIME = 0, // 固定时间前摇
        SKILLBEFOREROLLTYPE_DYNTIME = 1, // 动态时间前摇
}
public enum  SkillBeforeRollMoveFaceType
{
        SKILLBEFOREROLLMOVEFACETYPE_NONE = 0, // 技能前摇移动任意朝向
        SKILLBEFOREROLLMOVEFACETYPE_CAST = 1, // 技能前摇移动释放朝向
}
public enum  SkillBattleCastType
{
        SKILLBATTLECASTTYPE_IN = 0, // 战斗状态释放
        SKILLBATTLECASTTYPE_ALL = 1, // 任意状态释放
}
public enum  SkillCastMutexType
{
        SKILLCASTMUTEX_NONE = 0, // 无目标互斥
        SKILLCASTMUTEX_SAMETARGET = 1, // 对同一目标互斥
        SKILLCASTMUTEX_SAMETEAM = 2, // 对同一队伍排斥
}
public enum  SkillLastTargetCondType
{
        SKILLLASTTARGETCONDTYPE_SKLLAREA = 1, // 技能目标仍在技能范围内
}
public enum  SkillTargetStatusCullType
{
        SKILLTTARGETSTATUSCULLYPE_BUFFGROUP = 1, // 技能目标命中BUFF组ID
        SKILLTTARGETSTATUSCULLYPE_FULLHP = 2, // 技能目标血量满
        SKILLTTARGETSTATUSCULLYPE_SKILLFIELD = 3, // 技能目标命中法术场组ID
}
public enum  SkillTargetFilterType
{
        SKILLTARGETFILTERTYPE_ACTORTYPE = 1, // 技能目标筛选_目标类型
        SKILLTARGETFILTERTYPE_HP = 2, // 技能目标筛选_血量
        SKILLTARGETFILTERTYPE_DISTANCE = 3, // 技能目标筛选_距离
        SKILLTARGETFILTERTYPE_SPELLSTEAL = 4, // 技能目标筛选_魔法盗取
        SKILLTARGETFILTERTYPE_DISPELMAGIC = 5, // 技能目标筛选_驱散魔法
        SKILLTARGETFILTERTYPE_CYCLONE = 6, // 技能目标筛选_龙卷风
}
public enum  SkillTargetFilterActorType
{
        SKILLTARGETFILTERACTORTYPE_HERO = 1, // 目标筛选_英雄
        SKILLTARGETFILTERACTORTYPE_DOGFACE = 2, // 目标筛选_小兵
        SKILLTARGETFILTERACTORTYPE_BUILD = 3, // 目标筛选_建筑
        SKILLTARGETFILTERACTORTYPE_WEAPONTYPENEAR = 4, // 目标筛选_近战单位
        SKILLTARGETFILTERACTORTYPE_WEAPONTYPEFAR = 5, // 目标筛选_远程单位
}
public enum  SkillTargetFilterDispelMagicType
{
        SKILLTARGETFILTERDISPELMAGICTYPE_ENEMYUSEFULBUFF = 0, // 驱散优先_敌方增益BUFF
        SKILLTARGETFILTERDISPELMAGICTYPE_MYUNUSEFUL = 1, // 驱散优先_我方减益BUFF
        SKILLTARGETFILTERDISPELMAGICTYPE_SUMMONED = 2, // 驱散优先_召唤物
}
public enum  SkillEffectType
{
        SKILLEFFECT_NONE = 0, // 无特殊效果
        SET_ADD_BUFF = 1, // 添加buff
        REMOVE_BUFF = 2, // 移除buff
        CHANGE_BUFFLAYER = 3, // 修改buff层数
        SET_HURT = 4, // 造成伤害
        SET_KILLHURT = 5, // 造成致命伤害
        SKILL_ADDFIELD = 6, // 召唤法术场
        SKILL_REMOVEFIELD = 7, // 技能移除法术场
        SPAWN_SUMMONED = 8, // 召唤怪物
        SKILL_TP = 9, // 技能回城
        SET_REBHURT = 10, // 造成反弹伤害
        SKILL_DISPEL = 11, // 技能驱散
        SpellSteal = 12, // 魔法盗取阶段效果
        RESETHP = 13, // 技能阶段加血
        OPDEADBODY = 14, // 技能操控尸体
        CHANGESKILLENERGY = 15, // 修改计数能量点
        BREAKSKILL = 16, // 中断释放中技能
        SKILLSPAWNDEADBODY = 17, // 技能产生尸体
        SKILLMANABREAK = 18, // 技能法力损毁
        OPCASTSKILLCD = 19, // 修改当前释放技能CD
        EXORCISMSUCKHP = 20, // 驱使恶灵吸血
        SUMMONEDLIFETIME = 21, // 技能修改召唤物存活时间
        DEVOUR_MAGIC = 22, // 吞噬魔法
        SKILL_CHARM = 23, // 魅惑符咒
        SKILL_XPOSMARK = 24, // 技能X位置标记
        SKILLBACK_XPOSMARK = 25, // 技能X标记返回
        SPYFOWPOSITION = 26, // 技能侦查迷雾位置
        RESETITEMCD = 27, // 重置道具CD
        UDGROUNDSPAWNDEADBODY = 28, // 腐地生成尸体
        NETREESTANDBY = 29, // 精灵树坐地
        ATKPLUNDERGOLD = 30, // 攻击掠夺金钱
        SET_MAX = 31, // 技能效果类型最大值
}
public enum  SkillEffectTargetType
{
        SKILLEFFECTTARGET_SELFTEAM = 0, // 己方单位
        SKILLEFFECTTARGET_OPPTEAM = 1, // 敌方单位
}
public enum  SkillEffectDamageType
{
        SKILLEFFECTDAMGETYPE_DEFAULT = 0, // 技能阶段默认效果系数
        SKILLEFFECTDAMGETYPE_DISTANCE = 1, // 距离效果系数
        SKILLEFFECTDAMGETYPE_HP = 2, // 生命值效果固定值
        SKILLEFFECTDAMGETYPE_MP = 3, // 法术值效果固定值
        SKILLEFFECTDAMGETYPE_SKILLENERGY = 4, // 计数能量点系数
        SKILLEFFECTDAMGETYPE_HEROLEVEL = 5, // 角色等级系数
        SKILLEFFECTDAMGETYPE_BUFFLAYER = 6, // BUFF层级系数
        SKILLEFFECTDAMGETYPE_ATTRARMOR = 7, // 护甲数值系数
        SKILLEFFECTDAMGETYPE_HITINDEX = 8, // 技能受击排序系数
        SKILLEFFECTDAMGETYPE_HITTARGETCNT_OP = 9, // 技能击中目标数目操作数系数
        SKILLEFFECTDAMGETYPE_HITTARGETCNT_ATTR = 10, // 技能击中目标数目属性系数
        SKILLEFFECTDAMGETYPE_HPANDBLOOM = 11, // 生命值效果固定值附带吸血效果
        SKILLEFFECTDAMGETYPE_MAX = 12, // 技能阶段效果系数最大值
}
public enum  SkillEffectSummonedType
{
        SKILLEFFECTSUMMON_TARGETPOS = 0, // 当前目标位置召唤
        SKILLEFFECTSUMMON_FRONTPOS = 1, // 当前目标朝向位置召唤
}
public enum  SkillEffectAddBuffCondType
{
        SKILLEFFECTADDBUFFCOND_SKILLENGRGYCNT = 1, // 技能阶段所需计数能量点数目,条件
        SKILLEFFECTADDBUFFCOND_HITTARGETCNTBUFFLAYER = 2, // 技能阶段击中目标数添加BUFF层,添加层级
        SKILLEFFECTADDBUFFCOND_GIVERLEVELBUFFLAYER = 3, // 技能阶段施法者等级添加BUFF层,添加层级
        SKILLEFFECTADDBUFFCOND_REGIONFREINDACTORCNTBUFFLAYER = 4, // 技能阶段范围内特定友军单位数目添加BUFF层,添加层级
}
public enum  SkillEffectTPType
{
        SKILLEFFECTTPTYPE_MAPTPPOS = 0, // 回城到地图传送点
        SKILLEFFECTTPTYPE_TEAM = 1, // 群体传送到单位位置
}
public enum  SkillEffectOpDeadBodyType
{
        SKILLEFFECTOPDEADBODYTYPE_REVIVAL = 0, // 操控尸体复活
        SKILLEFFECTOPDEADBODYTYPE_CALLER = 1, // 操控尸体召唤
}
public enum  SkillEffectDispelType
{
        SKILLEFFECTDISPELTYPE_ALL = 0, // 技能驱散_所有
        SKILLEFFECTDISPELTYPE_LEGION = 1, // 技能驱散_阵营优先
}
public enum  SkillEffectDoDamageType
{
        SKILLEFFECTDODAMAGE_DIRECT = 0, // 直接造成伤害
        SKILLEFFECTDODAMAGE_REBORT = 1, // 反弹造成伤害
}
public enum  SkillEffectSkillCdOpType
{
        SKILLEFFECTSKILLCDOPTYPE_SKILLCD = 0, // 技能阶段效果_修改技能CD,分子时间
        SKILLEFFECTSKILLCDOPTYPE_INSKILLCD = 1, // 技能阶段效果_技能进入CD
}
public enum  SkillEffectHitLimitType
{
        SKILLEFFECTHITLIMITTYPE_ALL = 0, // 累计受击数目上限
        SKILLEFFECTHITLIMITTYPE_ONCE = 1, // 单次受击数目上限
}
public enum  ResExpType
{
        RESEXPTYPE_SYSTEM = 0, // 系统经验
        RESEXPTYPE_MONSTER = 1, // 野怪经验
        RESEXPTYPE_LEGION = 2, // 英雄士兵经验
}
public enum  ResMoneyAddType
{
        RESMONEYADDTYPE_SYSTEM = 0, // 系统奖励金钱
        RESMONEYADDTYPE_GOLDMINE = 1, // 金矿开采金钱
        RESMONEYADDTYPE_KILLACTOR = 2, // 击杀战斗单位金钱
        RESMONEYADDTYPE_KILLMONSTER = 3, // 击杀野怪金钱
        RESMONEYADDTYPE_REPLAIRCOST = 4, // 维修费消耗
        RESMONEYADDTYPE_BUILDACTORCOST = 5, // 造兵消耗
        RESMONEYADDTYPE_BUILDOTHERCOST = 6, // 造塔或金矿消耗
        RESMONEYADDTYPE_TECHUPCOST = 7, // 科技升级消耗
        RESMONEYADDTYPE_SELLEQUIP = 8, // 出售装备
        RESMONEYADDTYPE_GM = 10, // GM命令
}
public enum  ResRepairCostType
{
        RESREPAIRCOSTTYPE_NONE = 0, // 无维修费用
        RESREPAIRCOSTTYPE_LOW = 1, // 低维修费用
        RESREPAIRCOSTTYPE_HIGHT = 2, // 高维修费用
}
public enum  SkillFieldType
{
        SKILLFIELD_TYPE_TRIGGER_ONCE = 0, // 触碰消失放技能
        SKILLFIELD_TYPE_COMMON_FIELD = 1, // 进加出减法术场
        SKILLFIELD_ONLY_ADD = 2, // 进加出不减法术场
        SKILLFIELD_TRIGGER_HP = 3, // 血瓶触碰法术场
        SKILLFIELD_TYPE_MAX = 4, // 法术场类型最大值
}
public enum  SkillFieldShape
{
        SKILLFIELD_SHAPE_CIRCLE = 0, // 圆形场
        SKILLFIELD_SHAPE_RECT = 1, // 矩形场
}
public enum  SkillFieldShapeChangeType
{
        SKILLFIELDSHAPECHANGETYPE_NONE = 0, // 范围内法术场无变化
        SKILLFIELDSHAPECHANGETYPE_RECTWIDTH = 1, // 范围内矩形长度变化
        SKILLFIELDSHAPECHANGETYPE_RECTHEIGHT = 2, // 范围内矩形宽度变化
        SKILLFIELDSHAPECHANGETYPE_CIRCLE = 3, // 范围内圆形半径变化
}
public enum  SkillFieldParamType
{
        SKILLFIELD_PARAM_TYPE_BUFF = 1, // 法术场触发Buff
        SKILLFIELD_PARAM_TYPE_SKILL_PHASE = 2, // 法术场触发技能阶段
}
public enum  SkillFieldTargetFilterType
{
        SKILLFIELD_FILTER_DURADAMAGE = 1, // 法术场_一定时间内未受伤害筛选
        SKILLFIELD_FILTER_DURADAMAGEORATTACK = 2, // 法术场_一定时间内未受到伤害或主动攻击筛选
        SKILLFIELD_FILTER_NEAR = 3, // 法术场_最近距离的几个
        SKILLFIELD_FILTER_NOBUFF = 4, // 法术场_无指定BUFF组ID
        SKILLFIELD_FILTER_TRIGERRECTACTOR = 5, // 法术场_触发者范围内搜寻
}
public enum  SkillFieldRemoveEventType
{
        SKILLFIELDREMOVEEVENTTYPE_NONE = 0, // 法术场移除事件_NONE
        SKILLFIELDREMOVEEVENTTYPE_CASTERCASTSKILL = 1, // 法术场施法者使用技能移除
        SKILLFIELDREMOVEEVENTTYPE_CASTERBEHIT = 2, // 法术场施法者受到伤害移除
        SKILLFIELDREMOVEEVENTTYPE_BESKILLNODEHIT = 3, // 法术场被技能子弹碰撞移除
}
public enum  BattleModeType
{
        BATTLEMODETYPE_DEFUALT = 0, // 默认模式战场局
        BATTLEMODETYPE_GUIDE = 1, // 新手模式战场局
}
public enum  BuildAIType
{
        BUILDAI_ACTOR = 1, // 建造AI_建造单位
        BUILDAI_ACTOR_TECH = 2, // 建造AI_升级单位科技
        BUILDAI_TEAM_TECH = 3, // 建造AI_升级队伍科技
        BUILDAI_BUILDGOLDMINEGOLD = 4, // 建造AI_建造分矿攒钱
        BUILDAI_CANCELGOLDMINEGOLD = 5, // 建造AI_取消分矿攒钱
}
public enum  BuildAITargetType
{
        BUILDAITARGET_NONE = 0, // 建造AI_无目标
        BUILDAITARGET_CONST = 1, // 建造AI_常量
        BUILDAITARGET_VAR = 2, // 建造AI_条件变量
        BUILDAITARGET_SUB_COND = 3, // 建造AI_子条件
        BUILDAITARGET_ACTOR_CNT = 4, // 建造AI_单位数量
        BUILDAITARGET_BUILDING_ACTOR_CNT = 5, // 建造AI_建造中单位数量
        BUILDAITARGET_BASE_LVL = 6, // 建造AI_基地等级
        BUILDAITARGET_FOOD_CNT = 7, // 建造AI_人口数量
        BUILDAITARGET_MAX_FOOD_CNT = 8, // 建造AI_最大人口数量
        BUILDAITARGET_NEED_GOLD_MINE_CNT = 9, // 建造AI_待开采金矿数
        BUILDAITARGET_NEED_TOWER_CNT = 10, // 建造AI_待建造防御塔数
        BUILDAITARGET_TECH_LVL = 11, // 建造AI_科技等级
        BUILDAITARGET_MAX = 12, // 建造AI目标类型最大值
}
public enum  BaseTechLevelType
{
        BASETECHLEVEL_LEVEL0 = 0, // 无科技基地
        BASETECHLEVEL_LEVEL1 = 1, // 一本科技基地
        BASETECHLEVEL_LEVEL2 = 2, // 二本科技基地
        BASETECHLEVEL_LEVEL3 = 3, // 三本科技基地
}
public enum  TechLevelType
{
        TECHTYPE_ACTOR = 0, // 单位科技
        TECHTYPE_TEAM = 1, // 团队科技
}
public enum  TechLevelSubType
{
        TECHSUBTYPE_NONE = 0, // 科技子类型_NONE
        TECHSUBTYPE_BASEUP = 1, // 单位基地升级科技
        TECHSUBTYPE_ACTORAVATAR = 2, // 单位变身科技
        TECHSUBTYPE_BUILDGOLDMINE = 3, // 单位金矿建造科技
        TECHSUBTYPE_BUILDTOWER = 4, // 单位防御塔建造科技
        TECHSUBTYPE_CONSTRUCTARMY = 5, // 单位训练科技
        TECHSUBTYPE_ATKUP = 6, // 团队攻击升级科技
        TECHSUBTYPE_DEFENCEUP = 7, // 团队防御升级科技
        TECHSUBTYPE_FOODUP = 8, // 团队人口升级科技
}
public enum  TechEffectType
{
        TECHEFFECTTYPE_UNLOCKUNITSKILL = 1, // 科技效果_解锁单位技能
        TECHEFFECTTYPE_UPDATEMAXFOOD = 2, // 科技效果_提升最大人口
        TECHEFFECTTYPE_UPDATEUNITATTR = 3, // 科技效果_提升单位攻防属性
        TECHEFFECTTYPE_UPDATEBASE = 4, // 科技效果_基地科技升级
        TECHEFFECTTYPE_SPAWNACTOR = 5, // 科技效果_孵化单位
        TECHEFFECTTYPE_ADDHEROSKILL = 6, // 科技效果_增加英雄技能
}
public enum  TechStatusType
{
        TECHSTATUSTYPE_INVALID = 0, // 科技状态_不可用
        TECHSTATUSTYPE_LOCK = 1, // 科技状态_不可用
        TECHSTATUSTYPE_READY = 2, // 科技状态_可研究
        TECHSTATUSTYPE_RESEARCHING = 3, // 科技状态_研究中
        TECHSTATUSTYPE_FINISH = 4, // 科技状态_研究完成
}
public enum  TechTreeType
{
        TECHTREETYPE_LEVEL1 = 1, // 科技树类型1
        TECHTREETYPE_LEVEL2 = 2, // 科技树类型2
        TECHTREETYPE_LEVEL3 = 3, // 科技树类型3
        TECHTREETYPE_LEVEL4 = 4, // 科技树类型3
        TECHTREETYPE_LEVEL5 = 5, // 科技树类型4
        TECHTREETYPE_MAX = 10, // 科技树类型MAX
}
public enum  BattleGoodsItemType
{
        BATTLEGOODSITEMTYPE_NONE = 0, // 物品道具无类型
        BATTLEGOODSITEMTYPE_RETURNTOBASE = 1, // 回程类物品道具
        BATTLEGOODSITEMTYPE_GOLD = 2, // 金币类物品道具
        BATTLEGOODSITEMTYPE_ATTRBOOK = 3, // 书籍类物品道具
        BATTLEGOODSITEMTYPE_SCROLLS = 4, // 卷轴类物品道具
        BATTLEGOODSITEMTYPE_POTION = 5, // 药剂类物品道具
        BATTLEGOODSITEMTYPE_RUNE = 6, // 神符类物品道具
        BATTLEGOODSITEMTYPE_WARD = 7, // 侦查类物品道具
        BATTLEGOODSITEMTYPE_EQUIP = 8, // 装备类物品道具
        BATTLEGOODSITEMTYPE_SUMMONEDACTOR = 9, // 召唤单位类物品道具
        BATTLEGOODSITEMTYPE_MAX = 10, // 物品道具类型最大值
}
public enum  ItemQualityType
{
        ITEMQUALITYTYPE_WHITE = 0, // 道具品质_白
        ITEMQUALITYTYPE_GREEN = 1, // 道具品质_绿
        ITEMQUALITYTYPE_BLUE = 2, // 道具品质_蓝
        ITEMQUALITYTYPE_PURPLE = 3, // 道具品质_紫
        ITEMQUALITYTYPE_ORANGE = 4, // 道具品质_橙
}
public enum  ItemPickType
{
        ITEMPICKTYPE_AUTO = 0, // 道具自动拾取
        ITEMPICKTYPE_MANUAL = 1, // 道具点击拾取
        ITEMPICKTYPE_CHAT = 2, // 道具吟唱拾取
}
public enum  ItemUseType
{
        ITEMUSETYPE_NONE = 0, // 道具不可使用
        ITEMUSETYPE_MANUAL = 1, // 道具点击使用
        ITEMUSETYPE_AUTO = 2, // 道具自动使用
}
public enum  ItemCostType
{
        ITEMCOSTTYPE_IMM = 0, // 道具使用立即消耗
        ITEMCOSTTYPE_SKILLROLL = 1, // 道具技能前摇结束消耗，技能必须配置前摇和道具消耗
}
public enum  EquipBarType
{
        EQUIPBARTYPE_1 = 0, // 装备栏位1
        EQUIPBARTYPE_2 = 1, // 装备栏位2
        EQUIPBARTYPE_3 = 2, // 装备栏位3
        EQUIPBARTYPE_4 = 3, // 装备栏位4
        EQUIPBARTYPE_5 = 4, // 装备栏位5
        EQUIPBARTYPE_6 = 5, // 装备栏位6
        EQUIPBARTYPE_MAX = 6, // 装备栏位最大值
}
public enum  BattleItemEffectType
{
        BATTLEITEMEFFECTTYPE_CASTSKILL = 1, // 道具触发释放技能
        BATTLEITEMEFFECTTYPE_ADDBUFF = 2, // 道具触发添加BUFF
        BATTLEITEMEFFECTTYPE_ADDGOLD = 3, // 道具使用增加金币
        BATTLEITEMEFFECTTYPE_ADDEQUIP = 4, // 道具使用穿戴装备
}
public enum  ItemMapTpPosType
{
        ITEMMAPTPPOSTYPE_MYLEGION = 0, // 我方阵营所有回城点
        ITEMMAPTPPOSTYPE_MYBASE = 1, // 我方队伍基地回城点
}
public enum  BaseProtectType
{
        BASEPROTECTTYPE_LEGION = 0, // 主基地团队保护
        BASEPROTECTTYPE_TEAM = 1, // 主基地队伍保护
}
public enum  BattleEndJudgeType
{
        BATTLEENDJUDGETYPE_KILLALLBASE = 0, // 摧毁所有主基地定战斗胜负
        BATTLEENDJUDGETYPE_OTHERCMD = 1, // 外部判定定战斗胜负
}
public enum  BattleCongfigType
{
        BATTLECONFIGTYPE_BUILDTOWERDIS = 1, // 建造塔最少满足距离
        BATTLECONFIGTYPE_ACTORDEADBODY_TIME = 2, // 单位死亡变成尸体时间
        BATTLECONFIGTYPE_OP_TIME = 3, // 队伍操作时间集
        BATTLECONFIGTYPE_TEAM_REGION = 4, // 队伍区域距离范围
        BATTLECONFIGTYPE_TEAMLOCKOPTIME = 5, // 队伍英雄死亡锁定操作时间
        BATTLECONFIGTYPE_HEROFOLLOWTEAMGOURO = 6, // 队伍英雄复活归队距离
        BATTLECONFIGTYPE_BACKTEAM_MOVEBUFF = 7, // 单位归队加速BUFF
        BATTLECONFIGTYPE_DROPPICKUP_RANGE = 8, // 掉落拾取半径范围
        BATTLECONFIGTYPE_REPATRI_RANGE = 9, // 遣散士兵有效范围
        BATTLECONFIGTYPE_STEALWARN_RANGE = 10, // 隐身提示检测范围
        BATTLECONFIGTYPE_GRASSPARAM = 11, // 草丛渐隐参数
        BATTLECONFIGTYPE_EQUIPPICKUP = 12, // 装备拾取参数
        BATTLECONFIGTYPE_AIFLLOWPARAM = 13, // AI跟随参数
        BATTLECONFIGTYPE_GANKKILLEVENTPARAM = 14, // Gank击杀事件参数
        BATTLECONFIGTYPE_KILLDOGFACEEVENTPARAM = 15, // 击杀小兵事件参数
        BATTLECONFIGTYPE_HOSTPARAM = 16, // 挂机托管参数
        BATTLECONFIGTYPE_NETPARAM = 17, // 网络延迟参数
}
public enum  NightDayType
{
        NIGHTDAYTYPE_DAYTIME = 0, // 昼夜_白天
        NIGHTDAYTYPE_NIGHT = 1, // 昼夜_晚上
}
public enum  AiConfigType
{
        AICONFIGTYPE_ASSIT = 0, // AI难度_托管
        AICONFIGTYPE_PASSIVE = 1, // AI难度_消极
        AICONFIGTYPE_EASY = 2, // AI难度_简单
        AICONFIGTYPE_NORMAL = 3, // AI难度_中等
        AICONFIGTYPE_HARD = 4, // AI难度_困难
        AICONFIGTYPE_CRAZY = 5, // AI难度_疯狂
        AICONFIGTYPE_GUIDE = 6, // AI难度_弱引导
        AICONFIGTYPE_NEWBEE = 7, // AI难度_新手
        AICONFIGTYPE_MAX = 8, // AI难度_MAX
}
public enum  BattleSceneType
{
        BATTLESCENETYPE_COMMON = 0, // 战斗场景_通用
        BATTLESCENETYPE_COMMON1V1 = 1, // 战斗场景_通用1V1
        BATTLESCENETYPE_COMMON2V2 = 2, // 战斗场景_通用2V2
        BATTLESCENETYPE_COMMON3V3 = 3, // 战斗场景_通用3V3
        BATTLESCENETYPE_GUIDEPVE1 = 4, // 战斗场景_新手PVE1
        BATTLESCENETYPE_GUIDEPVE2 = 5, // 战斗场景_新手PVE2
        BATTLESCENETYPE_GUIDEPVE3 = 6, // 战斗场景_新手PVE3
        BATTLESCENETYPE_GUIDEPVE4 = 7, // 战斗场景_新手PVE4
}
public enum  LODType
{
        LODTYPE_LOW = 0, // LOD低配
        LODTYPE_MID = 1, // LOD中配
        LODTYPE_HIGHT = 2, // LOD高配
        LODTYPE_MAX = 3, // LOD_MAX
}
public enum  LODTargetType
{
        LODTARGETTYPE_SELF = 0, // LOD对象_自身
        LODTARGETTYPE_FRIENDD = 1, // LOD对象_友军
        LODTARGETTYPE_ENEMY = 2, // LOD对象_敌军
        LODTARGETTYPE_MAX = 3, // LOD对象_MAX
}
public enum  LODEffectType
{
        LODEFFECTTYPE_ATTACKEFFECT_NEAR = 0, // LOD近战攻击特效
        LODEFFECTTYPE_ATTACKEFFECT_FLY = 1, // LOD飞行攻击特效
        LODEFFECTTYPE_HITEFFECT = 2, // LOD受击特效
        LODEFFECTTYPE_SKILLHITRING = 3, // LOD技能识别圈特效
        LODEFFECTTYPE_SKILLOTHER = 4, // LOD技能辅助特效
        LODEFFECTTYPE_BUFF = 5, // LODBUFF特效
        LODEFFECTTYPE_ITEM = 6, // LOD道具特效
        LODEFFECTTYPE_SKILLFIELD = 7, // LOD法术场特效
        LODEFFECTTYPE_ACTOR = 8, // LOD角色特效
        LODEFFECTTYPE_SCENE = 9, // LOD场景特效
        LODEFFECTTYPE_MAX = 10, // LOD特效MAX
}
public enum  LODEffectSetType
{
        LODEFFECTSETTYPE_ENEMYCNT = 1, // 敌方单位LOD数目
        LODEFFECTSETTYPE_FRIENDCNT = 2, // 友方单位LOD数目
}
public enum  LanguageDefine
{
        NONE = 0, // 无
        SIM_CHINESE = 1, // 简体中文
        FON_CHINESE = 2, // 繁体中文
        ENGLISH = 3, // 英文
}
public enum  SystemItemType
{
        SYSYTEMITEMTYPE_HIDDES = 0, // 隐藏道具
        SYSYTEMITEMTYPE_ITEM = 1, // 系统道具_道具
        SYSYTEMITEMTYPE_EXPERIENCE = 2, // 系统道具_体验卡
        SYSYTEMITEMTYPE_RUNE = 3, // 系统道具_符文
}
public enum  SystemItemSubType
{
        SYSYTEMITEMSUBTYPE_EXP = 1, // 道具子类型_EXP
        SYSYTEMITEMSUBTYPE_RMB = 2, // 道具子类型_点券
        SYSYTEMITEMSUBTYPE_GOLD = 3, // 道具子类型_金币
        SYSYTEMITEMSUBTYPE_DIAM = 4, // 道具子类型_钻石
        SYSYTEMITEMSUBTYPE_SPEAK = 5, // 道具子类型_喇叭
        SYSYTEMITEMSUBTYPE_PACKAGE = 6, // 道具子类型_礼包
        SYSYTEMITEMSUBTYPE_EXPCARD = 7, // 道具子类型_经验卡
        SYSYTEMITEMSUBTYPE_GOLDCARD = 8, // 道具子类型_金币卡
        SYSYTEMITEMSUBTYPE_NAMECARD = 9, // 道具子类型_改名卡
        SYSYTEMITEMSUBTYPE_HEROPIECE = 10, // 道具子类型_英雄碎片
        SYSYTEMITEMSUBTYPE_SKINPIECE = 11, // 道具子类型_皮肤碎片
        SYSYTEMITEMSUBTYPE_HEROEXP = 12, // 道具子类型_英雄体验卡
        SYSYTEMITEMSUBTYPE_SKINEXP = 13, // 道具子类型_皮肤体验卡
        SYSYTEMITEMSUBTYPE_RUNE = 14, // 道具子类型_符文
        SYSYTEMITEMSUBTYPE_ACTIVE = 15, // 道具子类型_活跃
        SYSYTEMITEMSUBTYPE_RUNES = 16, // 道具子类型_纹章
        SYSYTEMITEMSUBTYPE_HERO = 17, // 道具子类型_英雄
        SYSYTEMITEMSUBTYPE_SKIN = 18, // 道具子类型_皮肤
        SYSYTEMITEMSUBTYPE_ACHPOINT = 19, // 道具子类型_成就点数
        SYSYTEMITEMSUBTYPE_HEAD = 20, // 道具子类型_头像
        SYSYTEMITEMSUBTYPE_HEADFRAME = 21, // 道具子类型_头像框
        SYSYTEMITEMSUBTYPE_RAFFLE = 22, // 道具子类型_抽奖
        SYSYTEMITEMSUBTYPE_MEDAL = 23, // 道具子类型_勋章商店
        SYSYTEMITEMSUBTYPE_ARENA = 24, // 道具子类型_竞技场积分
        SYSYTEMITEMSUBTYPE_ACTIVITY = 25, // 道具子类型_活动道具
        SYSYTEMITEMSUBTYPE_HERO_RUNE_FRAGMENT = 26, // 道具子类型_英雄符文碎片
        SYSYTEMITEMSUBTYPE_RACE_RUNE_FRAGMENT = 27, // 道具子类型_种族符文碎片
}
public enum  SystemItemEffectType
{
        SYSYTEFFECTTYPE_ADDEXP = 1, // 增加召唤师经验
        SYSYTEFFECTTYPE_ADDCOUPON = 2, // 增加召唤师点券
        SYSYTEFFECTTYPE_ADDGOLD = 3, // 增加召唤师金币
        SYSYTEFFECTTYPE_ADDDIAM = 4, // 增加召唤师钻石
        SYSYTEFFECTTYPE_ACTIVE = 5, // 增加召唤师活跃
        SYSYTEFFECTTYPE_HERO = 6, // 增加英雄
        SYSYTEFFECTTYPE_SKIN = 7, // 增加皮肤
        SYSYTEFFECTTYPE_ADDACHPOINT = 8, // 增加召唤师成就点数
        SYSYTEFFECTTYPE_ADD_DOUBLEEXP_TIME = 9, // 增加双倍经验时间
        SYSYTEFFECTTYPE_ADD_DOUBLEGOLD_TIME = 10, // 增加双倍金币时间
        SYSYTEFFECTTYPE_EXPER_HERO = 11, // 增加体验英雄
        SYSYTEFFECTTYPE_EXPER_SKIN = 12, // 增加体验皮肤
        SYSYTEFFECTTYPE_ADD_DOUBLEEXP_WIN_NUM = 13, // 增加胜利获得双倍经验次数
        SYSYTEFFECTTYPE_ADD_DOUBLEGOLD_WIN_NUM = 14, // 增加胜利获得双倍金币次数
        SYSYTEFFECTTYPE_UNLOCKHEAD = 15, // 解锁系统头像
        SYSYTEFFECTTYPE_UNLOCKHEADFRAME = 16, // 解锁系统头像框
        SYSYTEFFECTTYPE_ADD_RACE_RUNE_FRAGMENT = 17, // 增加召唤师种族符文碎片
        SYSYTEFFECTTYPE_ADD_HERO_RUNE_FRAGMENT = 18, // 增加召唤师英雄符文碎片
}
public enum  SystemTaskType
{
        SYSYTEMTASKTYPE_DAY = 1, // 每日任务
        SYSYTEMTASKTYPE_LEVEL = 2, // 成长任务
        SYSYTEMTASKTYPE_WEEK = 3, // 任务_每周任务
        SYSYTEMTASKTYPE_NEWGUIDE = 4, // 任务_新手引导任务
        SYSYTEMTASKTYPE_BASIC = 5, // 任务_基础任务
        SYSYTEMTASKTYPE_CONDITION = 6, // 任务_条件任务
}
public enum  SystemTaskCountType
{
        SYSYTEMTASKCOUNTTYPE_SINGLE = 1, // 任务_单局
        SYSYTEMTASKCOUNTTYPE_DAY = 2, // 任务_日累计
        SYSYTEMTASKCOUNTTYPE_WEEK = 3, // 任务_周累计
        SYSYTEMTASKCOUNTTYPE_FOREVER = 4, // 任务_永久
}
public enum  SystemTaskNeedActType
{
        SYSTEMTASKNEEDACTTYPE_LOGIN = 1, // 登陆游戏
        SYSTEMTASKNEEDACTTYPE_KILLHERO = 2, // 单局击杀英雄数量
        SYSTEMTASKNEEDACTTYPE_KILLMOS = 3, // 单局击杀野怪数量
        SYSTEMTASKNEEDACTTYPE_KILLSOLDIER = 4, // 单局击杀小兵数量
        SYSTEMTASKNEEDACTTYPE_CONTINWININT = 5, // 连续赢得积分赛场次
        SYSTEMTASKNEEDACTTYPE_CONTINWIN = 6, // 连续赢得对战比赛场次
        SYSTEMTASKNEEDACTTYPE_GOLD = 7, // 当日累计花费金币
        SYSTEMTASKNEEDACTTYPE_JOINBATTLE = 8, // 当日参加对战比赛场次
        SYSTEMTASKNEEDACTTYPE_TOWER = 9, // 当日对战中累计造塔数量
        SYSTEMTASKNEEDACTTYPE_MINE = 10, // 单局内开分矿次数
        SYSTEMTASKNEEDACTTYPE_KILLDRAGEON = 11, // 当日对战中杀龙次数
        SYSTEMTASKNEEDACTTYPE_WINNUM = 12, // 当日对战胜利场次
        SYSTEMTASKNEEDACTTYPE_DAY = 13, // 日活跃度点数
        SYSTEMTASKNEEDACTTYPE_WEEK = 14, // 周活跃度点数
        SYSTEMTASKNEEDACTTYPE_BUYHERO = 15, // 购买一个英雄
        SYSTEMTASKNEEDACTTYPE_SOLDIERLEVELUP = 16, // 小兵升级一次
        SYSTEMTASKNEEDACTTYPE_BUYSKIN = 17, // 购买任意一个皮肤
        SYSTEMTASKNEEDACTTYPE_SKILLLEVELUP = 18, // 召唤师技能升级一次
        SYSTEMTASKNEEDACTTYPE_NEWGUIDEBASICS = 19, // 任务_新手通关基础教学
        SYSTEMTASKNEEDACTTYPE_BUILD_INFANTRY_NUM = 20, // 任务_单局建造步兵数量
        SYSTEMTASKNEEDACTTYPE_BUILD_CROSSBOWMAN = 21, // 任务_单局建造弩兵数量
        SYSTEMTASKNEEDACTTYPE_LEVEL_UP_FARM = 22, // 任务_单局升级人口次数
        SYSTEMTASKNEEDACTTYPE_LEVEL_UP_BASE = 23, // 任务_单局升级基地次数
        SYSTEMTASKNEEDACTTYPE_USE_SUMMON_SKILL = 24, // 任务_单局使用召唤师技能次数
        SYSTEMTASKNEEDACTTYPE_DESTORY_TOWER = 25, // 任务_单局摧毁防御塔数量
        SYSTEMTASKNEEDACTTYPE_MOVE_TARGET = 26, // 任务_单局移动目标
        SYSTEMTASKNEEDACTTYPE_BUILD_NUN_NUM = 27, // 任务_单局建造修女数量
        SYSTEMTASKNEEDACTTYPE_WATCHANYVIDEO = 28, // 任务_观看任意技巧教学
        SYSTEMTASKNEEDACTTYPE_COMPLETE_GUIDESKILL = 51, // 任务_完成单个技能教学
        SYSTEMTASKNEEDACTTYPE_COMPLETE_ALL_GUIDESKILL = 52, // 任务_完成全部技能教学
        SYSTEMTASKNEEDACTTYPE_PLAY_RANK = 53, // 任务_参加排位赛
        SYSTEMTASKNEEDACTTYPE_INVITE_FRIEND_START_GAME = 54, // 任务_邀请好友上线
        SYSTEMTASKNEEDACTTYPE_DAILY_SHARE_GAME = 55, // 任务_每日分享
        SYSTEMTASKNEEDACTTYPE_KILL_BOSS = 56, // 任务_击杀黑暗泰坦或烈焰战神
        SYSTEMTASKNEEDACTTYPE_ARENA_LEVEL_UP = 57, // 任务_竞技场升级
        SYSTEMTASKNEEDACTTYPE_PAY = 58, // 任务_充值
        SYSTEMTASKNEEDACTTYPE_DIAMOND_LOTTERY = 59, // 任务_抽钻石宝箱
        SYSTEMTASKNEEDACTTYPE_TICKET_LOTTERY = 60, // 任务_抽点券宝箱
        SYSTEMTASKNEEDACTTYPE_KILL_SMALL_BOSS = 61, // 任务_击杀烈焰战神
        SYSTEMTASKNEEDACTTYPE_KILL_BIG_BOSS = 62, // 任务_击杀黑暗泰坦
        SYSTEMTASKNEEDACTTYPE_JOINBATTLE_BYHERO = 63, // 任务_当日使用某英雄参加对战比赛场次
        SYSTEMTASKNEEDACTTYPE_BUY_APPOINT_ITEM = 64, // 任务_购买指定物品
        SYSTEMTASKNEEDACTTYPE_BUY_APPOINT_HERO = 65, // 任务_购买指定英雄
        SYSTEMTASKNEEDACTTYPE_SHARE_GAME = 66, // 任务_分享游戏
        SYSTEMTASKNEEDACTTYPE_PLAYER_LEVEL = 101, // 成就_玩家等级
        SYSTEMTASKNEEDACTTYPE_MVP = 102, // 成就_MVP
        SYSTEMTASKNEEDACTTYPE_RACE_TYPE = 103, // 成就_种族
        SYSTEMTASKNEEDACTTYPE_MULTI_MODE = 104, // 成就_多人模式
        SYSTEMTASKNEEDACTTYPE_DOGFACE_STAT = 105, // 成就_训练小兵
        SYSTEMTASKNEEDACTTYPE_RANK_LEVEL = 106, // 成就_段位
        SYSTEMTASKNEEDACTTYPE_ICON_EDGE = 107, // 成就_头像框
        SYSTEMTASKNEEDACTTYPE_ADD_HERO = 108, // 成就_获得英雄
        SYSTEMTASKNEEDACTTYPE_ADD_SKIN = 109, // 成就_获得皮肤
        SYSTEMTASKNEEDACTTYPE_ADD_MONEY = 110, // 成就_获得货币
        SYSTEMTASKNEEDACTTYPE_HERO_LEGEND = 111, // 成就_英雄传说
        SYSTEMTASKNEEDACTTYPE_TEAM_GAME = 112, // 成就_组队游戏
        SYSTEMTASKNEEDACTTYPE_KILL_BIG_DRAGON = 113, // 成就_击杀大龙
        SYSTEMTASKNEEDACTTYPE_KILL_SMALL_DRAGON = 114, // 成就_击杀小龙
        SYSTEMTASKNEEDACTTYPE_ACH_CONTINWIN = 115, // 连续赢得对战比赛场次
        SYSTEMTASKNEEDACTTYPE_ACH_KILLHERO = 116, // 单局击杀英雄数量
        SYSTEMTASKNEEDACTTYPE_ACH_KILLSOLDIER = 117, // 单局击杀小兵数量
        SYSTEMTASKNEEDACTTYPE_MAX_RANK_LEVEL = 118, // 成就_最高段位
}
public enum  AchievementCounterType
{
        ACHCOUNTERTYPE_INC = 0, // 成就计数类型_累加
        ACHCOUNTERTYPE_MAXUPDATE = 1, // 成就计数类型_最大更新
}
public enum  UIInterfaceSkipType
{
        UIINTERFACESKIPTYPE_NONE = 0, // 界面跳转_无
        UIINTERFACESKIPTYPE_RACE = 1, // 界面跳转_种族
        UIINTERFACESKIPTYPE_RACE_HUMAN_PROFILE = 2, // 界面跳转_人族概况
        UIINTERFACESKIPTYPE_RACE_HUMAN_DOGFACE = 3, // 界面跳转_人族小兵
        UIINTERFACESKIPTYPE_RACE_HUMAN_TALENT = 4, // 界面跳转_人族天赋
        UIINTERFACESKIPTYPE_RACE_ORC_PROFILE = 5, // 界面跳转_兽族概况
        UIINTERFACESKIPTYPE_RACE_ORC_DOGFACE = 6, // 界面跳转_兽族小兵
        UIINTERFACESKIPTYPE_RACE_ORC_TALENT = 7, // 界面跳转_兽族天赋
        UIINTERFACESKIPTYPE_RACE_GHOST_PROFILE = 8, // 界面跳转_亡灵概况
        UIINTERFACESKIPTYPE_RACE_GHOST_DOGFACE = 9, // 界面跳转_亡灵小兵
        UIINTERFACESKIPTYPE_RACE_GHOST_TALENT = 10, // 界面跳转_亡灵天赋
        UIINTERFACESKIPTYPE_RACE_ELF_PROFILE = 11, // 界面跳转_精灵概况
        UIINTERFACESKIPTYPE_RACE_ELF_DOGFACE = 12, // 界面跳转_精灵小兵
        UIINTERFACESKIPTYPE_RACE_ELF_TALENT = 13, // 界面跳转_精灵天赋
        UIINTERFACESKIPTYPE_STRATEGY = 14, // 界面跳转_种族攻略
        UIINTERFACESKIPTYPE_HERO = 20, // 界面跳转_英雄
        UIINTERFACESKIPTYPE_HERO_FIGHTER = 21, // 界面跳转_英雄战士
        UIINTERFACESKIPTYPE_HERO_TANK = 22, // 界面跳转_英雄坦克
        UIINTERFACESKIPTYPE_HERO_MASTER = 23, // 界面跳转_英雄法师
        UIINTERFACESKIPTYPE_HERO_SHOOTER = 24, // 界面跳转_英雄射手
        UIINTERFACESKIPTYPE_HERO_SUPPORTER = 25, // 界面跳转_英雄辅助
        UIINTERFACESKIPTYPE_DOGFACESETTING = 31, // 界面跳转_快捷出兵
        UIINTERFACESKIPTYPE_MESSAGESETTING = 32, // 界面跳转_快捷消息
        UIINTERFACESKIPTYPE_ACHIEVE = 40, // 界面跳转_成就
        UIINTERFACESKIPTYPE_ACHIEVE_UNREACHED = 41, // 界面跳转_成就未达成
        UIINTERFACESKIPTYPE_BAG = 50, // 界面跳转_背包
        UIINTERFACESKIPTYPE_BAG_PROP = 51, // 界面跳转_背包道具
        UIINTERFACESKIPTYPE_BAG_CARD = 52, // 界面跳转_背包体验卡
        UIINTERFACESKIPTYPE_TASK = 60, // 界面跳转_任务
        UIINTERFACESKIPTYPE_TASK_GROWUP = 61, // 界面跳转_成长任务
        UIINTERFACESKIPTYPE_TASK_STRONGER = 62, // 界面跳转_我要变强
        UIINTERFACESKIPTYPE_BATTLE = 70, // 界面跳转_对战
        UIINTERFACESKIPTYPE_FORFUN = 71, // 界面跳转_娱乐模式
        UIINTERFACESKIPTYPE_PVC = 72, // 界面跳转_人机练习
        UIINTERFACESKIPTYPE_CUSTOM = 73, // 界面跳转_开房间
        UIINTERFACESKIPTYPE_RANK1V1 = 80, // 界面跳转_排位1V1
        UIINTERFACESKIPTYPE_RANK2V2 = 81, // 界面跳转_排位2V2
        UIINTERFACESKIPTYPE_TRAINING = 90, // 界面跳转_训练营
        UIINTERFACESKIPTYPE_TECHNIC = 91, // 界面跳转_技巧教学
        UIINTERFACESKIPTYPE_SHOP = 100, // 界面跳转_商城
        UIINTERFACESKIPTYPE_SHOPSKIN = 101, // 界面跳转_皮肤商城
        UIINTERFACESKIPTYPE_SHOPSKINFARGMENT = 102, // 界面跳转_皮肤碎片商城
        UIINTERFACESKIPTYPE_SHOPPROP = 103, // 界面跳转_道具商城
        UIINTERFACESKIPTYPE_SHOPCARD = 104, // 界面跳转_特权卡
        UIINTERFACESKIPTYPE_SHOPRAFFLE = 105, // 界面跳转_战争祭坛
        UIINTERFACESKIPTYPE_SHOPMEDALWAR = 106, // 界面跳转_战争勋章商店
        UIINTERFACESKIPTYPE_SHOPMEDALROAR = 107, // 界面跳转_怒吼勋章商店
        UIINTERFACESKIPTYPE_SHOPHEROFARGMENT = 108, // 界面跳转_英雄碎片商城
        UIINTERFACESKIPTYPE_LIVE = 110, // 界面跳转_直播
        UIINTERFACESKIPTYPE_REPLAY = 120, // 界面跳转_回看录像
        UIINTERFACESKIPTYPE_GREATREPLAY = 121, // 界面跳转_高手观战
        UIINTERFACESKIPTYPE_ACTIVITY = 130, // 界面跳转_活动
        UIINTERFACESKIPTYPE_SEVENDAYLOGIN = 131, // 界面跳转_七日登录
        UIINTERFACESKIPTYPE_SETTING = 140, // 界面跳转_设置
        UIINTERFACESKIPTYPE_OPERATESETTING = 141, // 界面跳转_操做设置
        UIINTERFACESKIPTYPE_VOICESETTING = 142, // 界面跳转_声音设置
        UIINTERFACESKIPTYPE_NETWORKSETTING = 143, // 界面跳转_网络诊断
        UIINTERFACESKIPTYPE_FRIEND = 150, // 界面跳转_好友
        UIINTERFACESKIPTYPE_ADDFRIEND = 151, // 界面跳转_添加好友
        UIINTERFACESKIPTYPE_FRIENDAPPLY = 152, // 界面跳转_好友申请
        UIINTERFACESKIPTYPE_RECHARGE = 160, // 界面跳转_充值
        UIINTERFACESKIPTYPE_FIRSTRECHARGE = 161, // 界面跳转_首冲
        UIINTERFACESKIPTYPE_RUNE = 162, // 界面跳转_战旗
}
public enum  SystemGrowthGuidanceType
{
        SYSTEMGROWTHGUID_GOLD = 1, // 指导_获取金币
        SYSTEMGROWTHGUID_HERO = 2, // 指导_获取英雄
        SYSTEMGROWTHGUID_STRONG = 3, // 指导_我要变强
}
public enum  MainGuideID
{
        MAINGUIDEID_PVE1 = 1, // 新手_PVE关卡1
        MAINGUIDEID_PVE2 = 2, // 新手_PVE关卡2
        MAINGUIDEID_PVE3 = 3, // 新手_PVE关卡3
        MAINGUIDEID_PVE4 = 4, // 新手_PVE关卡4
        MAINGUIDEID_MATCH = 5, // 新手_解锁匹配
        MAINGUIDEID_TEACH_MATCH = 6, // 新手_匹配教学
        MAINGUIDEID_SEVENDAYLOGIN = 7, // 新手_解锁七日登录
        MAINGUIDEID_FIRSTRECHARGE = 8, // 新手_解锁首冲
        MAINGUIDEID_ACTIVITY = 9, // 新手_解锁活动
        MAINGUIDEID_TASK = 10, // 新手_解锁任务
        MAINGUIDEID_TRAIN = 11, // 新手_解锁训练营
        MAINGUIDEID_SHOP = 12, // 新手_解锁商城
        MAINGUIDEID_ACHIEVE = 13, // 新手_解锁成就
        MAINGUIDEID_ARMYSETTING = 14, // 新手_解锁快捷出兵
        MAINGUIDEID_RUNE = 15, // 新手_解锁战旗
        MAINGUIDEID_MAX = 18, // 新手_最大值
}
public enum  NewGuideEventType
{
        NEWGUIDE_CLICK_NONE = 0,
        NEWGUIDE_MOVE_JOYSTICK = 1, // 新手教学转动转盘
        NEWGUIDE_CLICK_CONVERGE = 2, // 新手教学点击集火
        NEWGUIDE_CLICK_RETREAT = 3, // 新手教学点击撤退
        NEWGUIDE_CLICK_NORMALSKILL = 4, // 新手教学点击攻击
        NEWGUIDE_COVER = 5, // 新手教学透明蒙板
        NEWGUIDE_SHOW_CONVERGE_EFFECT = 6, // 显示集火特效
        NEWGUIDE_SHOW_RETREAT_EFFECT = 7, // 显示撤退特效
        NEWGUIDE_RETREAT_INTRODUCE = 8, // 撤退说明
        NEWGUIDE_MOVE_JOYSTICK_RETREAT = 9, // 转动轮盘撤退
        NEWGUIDE_RETREAT_NOTICE = 10, // 撤退提示
        NEWGUIDE_CLICK_TECH_VIEW = 11, // 点击科技界面
        NEWGUIDE_CLICK_ARM = 12, // 点击士兵头像
        NEWGUIDE_CLICK_TRAIN_DWARFINFANTRY = 13, // 点击训练矮人步兵
        NEWGUIDE_SHOW_TRAIN_PROGRESS = 14, // 显示训练进度
        NEWGUIDE_CLICK_TECH_TOGGLE = 15, // 点击科技页签
        NEWGUIDE_CLICK_FOOD_ICON = 16, // 点击人口图标
        NEWGUIDE_CLICK_LEVEL_UP_BTN = 17, // 点击升级按钮
        NEWGUIDE_SHOW_FOOD_CHANGE = 18, // 显示人口变化
        NEWGUIDE_CLICK_TRAIN_TOGGLE = 19, // 点击训练页签
        NEWGUIDE_CLICK_TRAIN_CROSSBOWMAN = 20, // 点击训练弩手
        NEWGUIDE_CLICK_CLOSE_TRAIN_VIEW = 21, // 点击关闭训练界面
        NEWGUIDE_CLICK_NORMAL_ATTACK = 31, // 点击普攻(弱引导)
        NEWGUIDE_BUILD_GOLD_MINE = 32, // 点击金矿建造
        NEWGUIDE_GOLD_MINE_STATE = 33, // 金矿建造状态
        NEWGUIDE_CLICK_TOWER_BAR = 34, // 点击防御塔栏
        NEWGUIDE_CLICK_BUILD_TOWER = 35, // 点击建造防御塔
        NEWGUIDE_CLICK_REPAIR_BTN = 36, // 点击维修按钮
        NEWGUIDE_CLICK_CASTLE = 41, // 点击城堡图标
        NEWGUIDE_CLICK_CASTLE_LEVELUP = 42, // 点击城堡升级按钮
        NEWGUIDE_CLICK_TRAIN_CURE = 43, // 点击修女训练图标
        NEWGUIDE_CLICK_CURE_TRAIN_BTN = 44, // 点击训练修女
        NEWGUIDE_SHOW_SMALL_DRAGON = 45, // 标注小龙位置
        NEWGUIDE_CLICK_EQUIP = 46, // 点击装备拾取栏
        NEWGUIDE_SHOW_ENEMY_BASE = 47, // 标注敌方基地
        NEWGUIDE_GET_BIG_DRAGON_NOTIFY = 48, // 获取统帅之刃提示
        NEWGUIDE_GET_BIG_DRAGON = 49, // 获取统帅之刃
        NEWGUIDE_SHOW_MATCH_DESC = 120, // 显示匹配描述
        NEWGUIDE_CLICK_MATCH_BUTTON = 121, // 点击匹配按钮
        NEWGUIDE_SHOW_ARENA_DESC = 122, // 显示竞技场描述
        NEWGUIDE_CLICK_ARENA_BUTTON = 123, // 点击竞技场按钮
        NEWGUIDE_CLICK_TASK_BUTTON = 130, // 点击任务按钮
        NEWGUIDE_SHOW_LEVEL_UNLOCK = 131, // 标注等级解锁新功能
        NEWGUIDE_CLICK_LEVEL_REWARD_BUTTON = 132, // 点击等级奖励领取按钮
        NEWGUIDE_CLICK_TRAINCAMP_BUTTON = 140, // 点击训练营按钮
        NEWGUIDE_CLICK_GUIDE_SKILL_BUTTON = 141, // 点击技巧教学按钮
        NEWGUIDE_CLICK_GUIDE_SKILL_PLAY_BUTTON = 142, // 点击开始播放按钮
        NEWGUIDE_CLICK_SHOP_BUTTON = 150, // 点击商城按钮
        NEWGUIDE_SHOW_SHOP_DESC = 151, // 显示商城描述
        NEWGUIDE_SHOW_ACHIEVE_DESC = 160, // 显示成就描述
        NEWGUIDE_CLICK_ACHIEVE_BUTTON = 161, // 点击成就按钮
        NEWGUIDE_CLICK_ACHIEVE_REWARD_BUTTON = 162, // 点击成就奖励领取按钮
        NEWGUIDE_CLICK_PREPAREFORWAR_BUTTON = 170, // 点击备战按钮
        NEWGUIDE_CLICK_ARMYSETTING_BUTTON = 171, // 点击快捷出兵按钮
        NEWGUIDE_PLAY_ARMYSETTING_VIDEO = 172, // 播放快捷出兵视频
        NEWGUIDE_SHOW_SEVENDAYLOGIN = 180, // 显示七日登录界面
        NEWGUIDE_HIDE_SEVENDAYLOGIN = 181, // 关闭七日登录界面
        NEWGUIDE_SHOW_FIRSTRECHARGE = 190, // 显示首冲界面
        NEWGUIDE_HIDE_FIRSTRECHARGE = 191, // 关闭首冲界面
        NEWGUIDE_SHOW_ACTIVITY = 200, // 显示活动界面
        NEWGUIDE_HIDE_ACTIVITY = 201, // 关闭活动界面
        NEWGUIDE_CLICK_BEGIN_BUTTON = 210, // 点击开始匹配按钮
        NEWGUIDE_CLICK_READY_BUTTON = 211, // 点击准备按钮
        NEWGUIDE_CLICK_RACE_BUTTON = 212, // 点击种族
        NEWGUIDE_CLICK_RACE_SKILL = 213, // 点击种族技能
        NEWGUIDE_SELECT_HERO_NOTIFY = 214, // 英雄选择提示
        NEWGUIDE_CLICK_HERO_BUTTON = 215, // 点击英雄
        NEWGUIDE_CLICK_HERO_SKILL = 216, // 点击英雄技能
        NEWGUIDE_HERO_SURE_NOTIFY = 217, // 英雄确定提示
        NEWGUIDE_CLICK_HERO_SURE = 218, // 确定英雄
        NEWGUIDE_VICTORY_CONDITION = 219, // 胜利条件提示
        NEWGUIDE_MAP_INTRODUCE = 220, // 地图介绍
        NEWGUIDE_FIGHT_WILD_NOTIFY = 221, // 打野路线提示
        NEWGUIDE_PICK_EQUIPMENT = 222, // 拾取装备提示
        NEWGUIDE_ATTACK_GOLDMINE = 223, // 进攻金矿提示
        NEWGUIDE_TRAIN_DOGFACE = 224, // 训练小兵提示
        NEWGUIDE_CLICK_OPEN_TECH_BUTTON = 225, // 点击打开科技界面按钮
        NEWGUIDE_CLICK_DOGFACE = 226, // 点击小兵
        NEWGUIDE_CLICK_TRAIN_BUTTON = 227, // 点击训练按钮
        NEWGUIDE_REPAIR_COST_NOTIFY = 228, // 高维修费用通知
        NEWGUIDE_GOLDMINE_INTRODUCE = 229, // 金矿介绍
        NEWGUIDE_CLICK_GOLDMINE_BUTTON = 230, // 点击金矿建造按钮
        NEWGUIDE_CLICK_TOWERBAR_BUTTON = 231, // 点击防御塔栏
        NEWGUIDE_BIG_DRAGON_SPAWN = 232, // 大龙出生提示
        NEWGUIDE_BIG_DRAGON_INTRODUCE = 233, // 大龙介绍
        NEWGUIDE_USE_BIG_DRAGON = 234, // 召唤大龙
        NEWGUIDE_CLICK_TP_BUTTON = 235, // 点击回城按钮
        NEWGUIDE_SMALL_DRAGON_SPAWN = 236, // 小龙出生提示
        NEWGUIDE_SMALL_DRAGON_INTRODUCE = 237, // 小龙介绍
        NEWGUIDE_ATTACK_BASE_NOTIFY = 238, // 进攻敌方基地
        NEWGUIDE_PICK_DRAGON_EGG = 239, // 拾取统帅之刃
        NEWGUIDE_CAST_DRAGON_EGG = 240, // 使用统帅之刃
        NEWGUIDE_UPGRADE_FOOD = 241, // 升级人口提示
        NEWGUIDE_UPGRADE_BASE = 242, // 升级基地提示
        NEWGUIDE_WELCOME_TO_GAME = 243, // 欢迎来到战争怒吼
        NEWGUIDE_MONSTER_INTRODUCE = 244, // 野怪介绍
        NEWGUIDE_BASE_PROTECT = 245, // 主基地保护机制
        NEWGUIDE_CLICK_RUNE = 260, // 点击战旗按钮
        NEWGUIDE_CLICK_RUNE_SHOP = 261, // 点击战旗室按钮
        NEWGUIDE_CLICK_RUNE_ICON = 262, // 点击战旗图标
        NEWGUIDE_CLICK_RUNE_BUY = 263, // 点击战旗购买按钮
        NEWGUIDE_CLICK_RUNE_SURE = 264, // 点击战旗确定按钮
        NEWGUIDE_CLICK_RUNE_FIT = 265, // 点击战旗装配按钮
        NEWGUIDE_CLICK_RUNE_SLOT = 266, // 点击战旗插槽
        NEWGUIDE_CLICK_RUNE_SET = 267, // 点击镶嵌战旗
        NEWGUIDE_SHOW_RUNE_DESC = 268, // 展示战旗描述
}
public enum  SystemVoicer
{
        SystemVoicer_HERO = 0, // 播报者_英雄
        SystemVoicer_ACTOR = 1, // 播报者_声优
}
public enum  ResTastType
{
        RESTASKTYPE_BRANCH = 0, // 支线任务
        RESTASKTYPE_TRUNK = 1, // 主线任务
}
public enum  ResGuideBattleTastActiveType
{
        RESGUIDEBATTLETASTACTIVETYPE_ENTERBATTLE = 1, // 新手战斗任务激活类型_进入战斗
        RESGUIDEBATTLETASTACTIVETYPE_BFTASKCOMPLETE = 2, // 新手战斗任务激活类型_前置任务完成
        RESGUIDEBATTLETASTACTIVETYPE_GOD = 10, // 新手战斗任务激活类型_GOD,默认激活
}
public enum  ResGuideBattleTastCompleteType
{
        RESGUIDEBATTLETASTCOMPLETETYPE_KILLACTOR = 1, // 新手战斗任务完成类型_击杀指定怪物
        RESGUIDEBATTLETASTCOMPLETETYPE_TRAINACTOR = 2, // 新手战斗任务完成类型_训练指定单位
        RESGUIDEBATTLETASTCOMPLETETYPE_KILLACTORGROUP = 3, // 新手战斗任务完成类型_击杀指定怪物组
        RESGUIDEBATTLETASTCOMPLETETYPE_STUDYACTORTECH = 4, // 新手战斗任务完成类型_研究指定科技
        RESGUIDEBATTLETASTCOMPLETETYPE_BUILDCOMPLETE = 5, // 新手战斗任务完成类型_建筑建造完成
        RESGUIDEBATTLETASTCOMPLETETYPE_REPAIR = 6, // 新手战斗任务完成类型_维修指定单位
        RESGUIDEBATTLETASTCOMPLETETYPE_MISSKILATK = 7, // 新手战斗任务完成类型_躲避技能攻击
        RESGUIDEBATTLETASTCOMPLETETYPE_BUILD_ORE_GOLDNUM = 8, // 新手战斗任务完成类型_金矿开采数量
        RESGUIDEBATTLETASTCOMPLETETYPE_GOLD = 10, // 新手战斗任务完成类型_GOD,默认激活
}
public enum  StoryBreakType
{
        RESSTORYBREAKTYPE_NOTSKIP = 0, // 不可跳过
        RESSTORYBREAKTYPE_SKIPGROUP = 1, // 跳过剧情组
}
public enum  ResGuideUnLockSystemType
{
        RESGUIDEUNLOCKSYSTEMTYPE_NONE = 0, // 新手解锁系统_无
        RESGUIDEUNLOCKSYSTEMTYPE_TASK = 1, // 新手解锁系统_任务
        RESGUIDEUNLOCKSYSTEMTYPE_TRAIN = 2, // 新手解锁系统_训练营
        RESGUIDEUNLOCKSYSTEMTYPE_SHOP = 3, // 新手解锁系统_商城
        RESGUIDEUNLOCKSYSTEMTYPE_ACHIEVE = 4, // 新手解锁系统_成就
        RESGUIDEUNLOCKSYSTEMTYPE_ARMYSETTING = 5, // 新手解锁系统_快捷出兵
        RESGUIDEUNLOCKSYSTEMTYPE_RANK = 6, // 新手解锁系统_排位
        RESGUIDEUNLOCKSYSTEMTYPE_RANK1V1 = 7, // 新手解锁系统_排位1V1
        RESGUIDEUNLOCKSYSTEMTYPE_RANK2V2 = 8, // 新手解锁系统_排位2V2
        RESGUIDEUNLOCKSYSTEMTYPE_MATCH = 9, // 新手解锁系统_匹配
        RESGUIDEUNLOCKSYSTEMTYPE_MATCH1V1 = 10, // 新手解锁系统_匹配1V1
        RESGUIDEUNLOCKSYSTEMTYPE_MATCH2V2 = 11, // 新手解锁系统_匹配2V2
        RESGUIDEUNLOCKSYSTEMTYPE_PVC = 12, // 新手解锁系统_人机
        RESGUIDEUNLOCKSYSTEMTYPE_PVC1V1 = 13, // 新手解锁系统_人机1V1
        RESGUIDEUNLOCKSYSTEMTYPE_PVC2V2 = 14, // 新手解锁系统_人机2V2
        RESGUIDEUNLOCKSYSTEMTYPE_FORFUN = 15, // 新手解锁系统_娱乐
        RESGUIDEUNLOCKSYSTEMTYPE_FORFUN1V1 = 16, // 新手解锁系统_娱乐1V1
        RESGUIDEUNLOCKSYSTEMTYPE_FORFUN2V2 = 17, // 新手解锁系统_娱乐2V2
        RESGUIDEUNLOCKSYSTEMTYPE_FORFUN3V3 = 18, // 新手解锁系统_娱乐2V2
        RESGUIDEUNLOCKSYSTEMTYPE_CUSTOM = 19, // 新手解锁系统_开房间
        RESGUIDEUNLOCKSYSTEMTYPE_CUSTOM1V1 = 20, // 新手解锁系统_开房间1V1
        RESGUIDEUNLOCKSYSTEMTYPE_CUSTOM2V2 = 21, // 新手解锁系统_开房间2V2
        RESGUIDEUNLOCKSYSTEMTYPE_SEVENDAYLOGIN = 22, // 新手解锁系统_七日登录
        RESGUIDEUNLOCKSYSTEMTYPE_FIRSTRECHARGE = 23, // 新手解锁系统_首冲
        RESGUIDEUNLOCKSYSTEMTYPE_ACTIVITY = 24, // 新手解锁系统_活动
        RESGUIDEUNLOCKSYSTEMTYPE_FALLRUINS = 25, // 新手解锁系统_陨落遗迹
        RESGUIDEUNLOCKSYSTEMTYPE_LOSTDESERT = 26, // 新手解锁系统_迷失沙漠
        RESGUIDEUNLOCKSYSTEMTYPE_RUNE = 27, // 新手解锁系统_战旗
        RESGUIDEUNLOCKSYSTEMTYPE_VIDEO = 28, // 新手解锁系统_观战
        RESGUIDEUNLOCKSYSTEMTYPE_LIVE = 29, // 新手解锁系统_直播
}
public enum  GiftOpenWay
{
        GiftOpenWay_OnlyItem = 1, // 礼包_道具
        GiftOpenWay_IncludeHero = 2, // 礼包_英雄
        GiftOpenWay_Other = 3, // 礼包_其他
}
public enum  MoneyType
{
        MONEYTYPE_GOLD = 1, // 金币
        MONEYTYPE_DIAMOND = 2, // 钻石
        MONEYTYPE_TICKET = 3, // 点券
        MONEYTYPE_DAY_ACTIVE_POINT = 4, // 日活跃度
        MONEYTYPE_WEEK_ACTIVE_POINT = 5, // 周活跃度
        MONEYTYPE_SIGNET_FRAGMENT = 6, // 纹章碎片
        MONEYTYPE_HERO_FRAGMENT = 7, // 英雄碎片(道具)
        MONEYTYPE_SKIN_FRAGMENT = 8, // 皮肤碎片(道具)
        MONEYTYPE_WAR_MEDAL = 9, // 战争勋章
        MONEYTYPE_ROAR_MEDAL = 10, // 怒吼勋章
        MONEYTYPE_HERO_RUNE_FRAGMENT = 11, // 英雄符文碎片
        MONEYTYPE_RACE_RUNE_FRAGMENT = 12, // 种族符文碎片
}
public enum  ChatChannelType
{
        CHATCHANNEL_BIG_HORN = 1, // 聊天频道_大喇叭
        CHATCHANNEL_SMALL_HORN = 2, // 聊天频道_小喇叭
        CHATCHANNEL_HALL = 3, // 聊天频道_大厅频道
        CHATCHANNEL_FRIENDS = 4, // 聊天频道_好友频道
        CHATCHANNEL_TONG = 5, // 聊天频道_公会频道
        CHATCHANNEL_BATTLE_TEAM = 6, // 聊天频道_战斗队伍频道
        CHATCHANNEL_BATTLE_ALL = 7, // 聊天频道_战斗全局频道
        CHATCHANNEL_SYSTEM = 8, // 聊天频道_系统公告
        CHATCHANNEL_MATCH_TEAM = 9, // 聊天频道_匹配队伍频道
        CHATCHANNEL_CUSTOM_ROOM = 10, // 聊天频道_开房间频道
}
public enum  GlobalParameterType
{
        GLOBALPARAMETERE_WEEK_BATTLE_GOLD_TOPLIMIT = 1, // 每周通过对战获得金币初始上限
        GLOBALPARAMETERE_WEEK_ALL_GOLD_TOPLIMIT = 2, // 每周金币绝对上限
        GLOBALPARAMETERE_WEEK_ALL_EXP_TOPLIMIT = 3, // 每周经验绝对上限
        GLOBALPARAMETERE_CREDIT_ADD_WEEK_BATTLE_GOLD_TOPLIMIT = 4, // 对战信用奖励对战获得金币上限
        GLOBALPARAMETERE_CREDIT_REDUCE_WEEK_BATTLE_GOLD_TOPLIMIT = 5, // 对战信用降低对战获得金币上限
        GLOBALPARAMETERE_BIG_HORN = 6, // 大喇叭
        GLOBALPARAMETERE_SMALL_HORN = 7, // 小喇叭
        GLOBALPARAMETERE_CHAT_HALL_CD = 8, // 大厅聊天冷却CD
        GLOBALPARAMETERE_HERO_MASTERY_TOPLIMIT = 9, // 英雄熟练度上限
        GLOBALPARAMETERE_REAL_AUTH_REWARD = 10, // 英雄熟练度上限
        GLOBALPARAMETERE_FIRST_PAY = 11, // 首充奖励
        GLOBALPARAMETERE_NEWBIE_TIME = 12, // 新手活动时间
        GLOBALPARAMETERE_WARMGAME_1ST = 13, // 新号第一把温暖局
        GLOBALPARAMETERE_WARMGAME_2ND = 14, // 新号第二把温暖局
        GLOBALPARAMETERE_RUNE_PRICE = 15, // 购买战旗价格
}
public enum  ServerParameterType
{
        SERVERPARAMETERE_IOS_CLIENT_VERSION = 1, // 客户端苹果版本号
        SERVERPARAMETERE_ANDROID_CLIENT_VERSION = 2, // 客户端安卓版本号
}
public enum  BasicState
{
        BASICSTATE_LOBBY = 0, // 大厅中
        BASICSTATE_QUEUE = 1, // 组队中
        BASICSTATE_ROOM = 2, // 选人中
        BASICSTATE_BATTLE = 3, // 游戏中
        BASICSTATE_BATTLE_AWARD = 4, // 游戏结算中
        BASICSTATE_NEW_GUIDE = 5, // 新手教学中
        BASICSTATE_NONET_BATTLE = 6, // 无网络游戏中
        BASICSTATE_WATCH_RECORD = 7, // 观看录像中
        BASICSTATE_BATTLE_GROUPING = 8, // 开黑中
}
public enum  GameType
{
        GAMETYPE_MATCH = 0, // 匹配比赛
        GAMETYPE_RANK = 1, // 排位比赛
}
public enum  SystemVsMode
{
        SYSTEMVSMODE_ALL = 0, // 对战模式_所有
        SYSTEMVSMODE_RANK = 1, // 对战模式_排位
        SYSTEMVSMODE_MATCH = 2, // 对战模式_匹配
        SYSTEMVSMODE_PVC = 3, // 对战模式_人机
        SYSTEMVSMODE_CUSTOM = 4, // 对战模式_自定义
        SYSTEMVSMODE_FORFUN = 5, // 对战模式_娱乐模式
}
public enum  SystemMutiPlayMode
{
        SYTEMVSMUTIPLAYMODE_ALL = 0, // 对战人数模式_所有
        SYTEMVSMUTIPLAYMODE_1V1 = 1, // 对战人数模式_1V1
        SYTEMVSMUTIPLAYMODE_2V2 = 2, // 对战人数模式_2V2
        SYTEMVSMUTIPLAYMODE_3V3 = 3, // 对战人数模式_3V3
}
public enum  CustomRoomMode
{
        CUSTOMROOMMODE_1v1 = 1, // 1v1
        CUSTOMROOMMODE_2v2 = 2, // 2v2
        CUSTOMROOMMODE_3v3 = 3, // 3v3
}
public enum  FriendSyncType
{
        FRIENDSYNCTYPE_ONLINE = 1, // 在线状态
        FRIENDSYNCTYPE_STATE = 2, // 游戏状态
        FRIENDSYNCTYPE_ICON = 3, // 头像
        FRIENDSYNCTYPE_ICON_EDGE = 4, // 头像框
        FRIENDSYNCTYPE_COUNTRY = 5, // 国籍
        FRIENDSYNCTYPE_RANK_LEVEL = 6, // 段位
        FRIENDSYNCTYPE_LOGOUT_TIME = 7, // 登出时间
        FRIENDSYNCTYPE_LEVEL = 8, // 等级
}
public enum  RoleType
{
        ROLETYPE_PLAYER = 1, // 角色类型_玩家
        ROLETYPE_COMPUTER = 2, // 角色类型_电脑
        ROLETYPE_VIRTUAL = 3, // 角色类型_虚拟人
}
public enum  SystemPackageUseType
{
        SYSTEMPACKAGE_MANUALUSE = 0, // 手动使用
        SYSTEMPACKAGE_AUTOUSE = 1, // 自动使用
}
public enum  SystemPackageRandomType
{
        SYSTEMPACKAGE_RANDOM_ALL = 0, // 全概率抽取
        SYSTEMPACKAGE_RANDOM_SINGLE = 1, // 独立概率抽取
}
public enum  CreditReportType
{
        CREDITREPORTTYPE_HANGUP = 1, // 信用投票类型_恶意挂机
        CREDITREPORTTYPE_PASSIVE = 2, // 信用投票类型_消极游戏
        CREDITREPORTTYPE_ABUSE = 4, // 信用投票类型_言语辱骂
        CREDITREPORTTYPE_CHEAT = 8, // 信用投票类型_使用外挂
}
public enum  MailMainType
{
        MAILMAINTYPE_SYSTEM = 1, // 邮件主类型_系统
        MAILMAINTYPE_SOCIATY = 2, // 邮件主类型_公会
        MAILMAINTYPE_FRIEND = 3, // 邮件主类型_好友
        MAILMAINTYPE_QUALIFIER = 4, // 邮件主类型_排位赛
        MAILMAINTYPE_MESSAGE = 5, // 邮件主类型_消息
}
public enum  MailSubType
{
        MAILSUBTYPE_SERVERNOTIFY = 1, // 邮件子类型_服务器通知
        MAILSUBTYPE_FESTIVALAWARDS = 2, // 邮件子类型_节日奖励
        MAILSUBTYPE_VIPRITESPACKAGE = 3, // 邮件子类型_VIP周礼包
        MAILSUBTYPE_VIPONETIMEREWARD = 4, // 邮件子类型_VIP一次性奖励
        MAILSUBTYPE_HEROCARDFAILS = 5, // 邮件子类型_英雄体验卡失效
        MAILSUBTYPE_SKINCARDFAILS = 6, // 邮件子类型_皮肤体验卡失效
        MAILSUBTYPE_CREDITSCORE = 7, // 邮件子类型_对战信用扣分
        MAILSUBTYPE_SUSPENDNOTICE = 8, // 邮件子类型_禁赛通知
        MAILSUBTYPE_REPORTSUCCESS = 9, // 邮件子类型_成功举报
        MAILSUBTYPE_REPORTFEEDBACK = 10, // 邮件子类型_举报反馈
        MAILSUBTYPE_GUILDREWARD = 11, // 邮件子类型_公会奖励
        MAILSUBTYPE_GUILDWEEKLY = 12, // 邮件子类型_公会周报
        MAILSUBTYPE_FRIENDSGIVEGOLD = 13, // 邮件子类型_好友赠送金币
        MAILSUBTYPE_RECEIVEQUALIFIERAWARD = 14, // 邮件子类型_排位赛奖励领取
        MAILSUBTYPE_SQUADINVITE = 15, // 邮件子类型_邀请组队
}
public enum  RankType
{
        RANKTYPE_QUALIFYING_1v1 = 1, // 1v1排位赛榜单
        RANKTYPE_QUALIFYING_2v2 = 2, // 2v2排位赛榜单
        RANKTYPE_FRIEND = 3, // 好友榜单
}
public enum  GuideSkillType
{
        GUIDE_SKILL_BASICS = 1, // 技巧类型_基础
        GUIDE_SKILL_MIDDLE = 2, // 技巧类型_进阶
        GUIDE_SKILL_HIGH = 3, // 技巧类型_高级
}
public enum  RaceSkillType
{
        RACE_SKILL_TALENT = 1, // 种族天赋技能
        RACE_SKILL_SPY = 2, // 种族侦查技能
}
public enum  MonthCardType
{
        MONTH_CARD_SILVER = 1, // 白银月卡
        MONTH_CARD_GOLD = 2, // 黄金月卡
}
public enum  MatchOpenTimeType
{
        MATCHOPENTIMETYPE_ALL = 0, // 赛事开放时间_全开
        MATCHOPENTIMETYPE_DAY = 1, // 赛事开放时间_天
        MATCHOPENTIMETYPE_WEEK = 2, // 赛事开放时间_周
}
public enum  ShopSheet
{
        SHOPSHEET_HERO = 1, // 商城分页_英雄
        SHOPSHEET_SKIN = 2, // 商城分页_皮肤
        SHOPSHEET_ITEM = 3, // 商城分页_道具
        SHOPSHEET_DISCOUNT = 4, // 商城分页_折扣
        SHOPSHEET_NEWBIE = 5, // 商城分页_新手礼包
        SHOPSHEET_HEROFARGMENT = 6, // 商城分页_英雄碎片
        SHOPSHEET_SKINFARGMENT = 7, // 商城分页_皮肤碎片
        SHOPSHEET_RAFFLEWARMEDAL = 8, // 商城分页_战争勋章
        SHOPSHEET_RAFFLEROARMEDAL = 9, // 商城分页_怒吼勋章
}
public enum  ShopLimitType
{
        SHOPLIMITTYPE_NONE = 0, // 商城限购周期_无
        SHOPLIMITTYPE_DAILY = 1, // 商城限购周期_每日
        SHOPLIMITTYPE_WEEKLY = 2, // 商城限购周期_每周
        SHOPLIMITTYPE_FOREVER = 3, // 商城限购周期_永久
        SHOPLIMITTYPE_MONTH = 4, // 商城限购周期_每月
}
public enum  SeasonReward
{
        S1_1V1 = 1, // S1赛季1v1奖励
        S2_1V1 = 2, // S2赛季1v1奖励
        S3_1V1 = 3, // S3赛季1v1奖励
        S4_1V1 = 4, // S4赛季1v1奖励
        S5_1V1 = 5, // S5赛季1v1奖励
        S6_1V1 = 6, // S6赛季1v1奖励
        S7_1V1 = 7, // S7赛季1v1奖励
        S8_1V1 = 8, // S8赛季1v1奖励
        S9_1V1 = 9, // S9赛季1v1奖励
        S10_1V1 = 10, // S10赛季1v1奖励
        S11_1V1 = 11, // S11赛季1v1奖励
        S12_1V1 = 12, // S12赛季1v1奖励
        S1_2V2 = 13, // S1赛季2v2奖励
        S2_2V2 = 14, // S2赛季2v2奖励
        S3_2V2 = 15, // S3赛季2v2奖励
        S4_2V2 = 16, // S4赛季2v2奖励
        S5_2V2 = 17, // S5赛季2v2奖励
        S6_2V2 = 18, // S6赛季2v2奖励
        S7_2V2 = 19, // S7赛季2v2奖励
        S8_2V2 = 20, // S8赛季2v2奖励
        S9_2V2 = 21, // S9赛季2v2奖励
        S10_2V2 = 22, // S10赛季2v2奖励
        S11_2V2 = 23, // S11赛季2v2奖励
        S12_2V2 = 24, // S12赛季2v2奖励
        First_Recharge = 25, // 赛季首冲
        MEDAL_EXCHANGE = 26, // 勋章兑换
        SkillTECHNIC_REWARD = 27, // 技巧教学奖励
        HERO_FRAGMENT = 28, // 英雄碎片兑换
        SKIN_FRAGMENT = 29, // 皮肤碎片兑换
}
public enum  SystemLotteryType
{
        SYSTEMLOTTERYTYPE_DIAMONDFRIST = 1, // 系统钻石首抽
        SYSTEMLOTTERYTYPE_DIAMONDSOLO = 2, // 系统钻石单抽
        SYSTEMLOTTERYTYPE_DIAMONDFIVE = 3, // 系统钻石连抽
        SYSTEMLOTTERYTYPE_DIAMONDSOLOGOD = 4, // 系统钻石单抽保底
        SYSTEMLOTTERYTYPE_DIAMONDFIVEGOD = 5, // 系统钻石连抽保底
        SYSTEMLOTTERYTYPE_COUPONFRIST = 6, // 系统点券首抽
        SYSTEMLOTTERYTYPE_COUPONSOLO = 7, // 系统点券单抽
        SYSTEMLOTTERYTYPE_COUPONFIVE = 8, // 系统点券连抽
        SYSTEMLOTTERYTYPE_COUPONSOLOGOD = 9, // 系统点券单抽保底
        SYSTEMLOTTERYTYPE_COUPONFIVEGOD = 10, // 系统点券连抽保底
        SYSTEMLOTTERYTYPE_HERO_RUNE_DIAMONDFRIST = 11, // 系统英雄符文钻石首抽
        SYSTEMLOTTERYTYPE_HERO_RUNE_DIAMONDSOLO = 12, // 系统英雄符文钻石单抽
        SYSTEMLOTTERYTYPE_HERO_RUNE_DIAMONDFIVE = 13, // 系统英雄符文钻石连抽
        SYSTEMLOTTERYTYPE_HERO_RUNE_DIAMONDSOLOGOD = 14, // 系统英雄符文钻石单抽保底
        SYSTEMLOTTERYTYPE_HERO_RUNE_DIAMONDFIVEGOD = 15, // 系统英雄符文钻石连抽保底
        SYSTEMLOTTERYTYPE_HERO_RUNE_GOLDFRIST = 16, // 系统英雄符文金币首抽
        SYSTEMLOTTERYTYPE_HERO_RUNE_GOLDSOLO = 17, // 系统英雄符文金币单抽
        SYSTEMLOTTERYTYPE_HERO_RUNE_GOLDFIVE = 18, // 系统英雄符文金币连抽
        SYSTEMLOTTERYTYPE_HERO_RUNE_GOLDSOLOGOD = 19, // 系统英雄符文金币单抽保底
        SYSTEMLOTTERYTYPE_HERO_RUNE_GOLDFIVEGOD = 20, // 系统英雄符文金币连抽保底
        SYSTEMLOTTERYTYPE_RACE_RUNE_DIAMONDFRIST = 21, // 系统种族符文钻石首抽
        SYSTEMLOTTERYTYPE_RACE_RUNE_DIAMONDSOLO = 22, // 系统种族符文钻石单抽
        SYSTEMLOTTERYTYPE_RACE_RUNE_DIAMONDFIVE = 23, // 系统种族符文钻石连抽
        SYSTEMLOTTERYTYPE_RACE_RUNE_DIAMONDSOLOGOD = 24, // 系统种族符文钻石单抽保底
        SYSTEMLOTTERYTYPE_RACE_RUNE_DIAMONDFIVEGOD = 25, // 系统种族符文钻石连抽保底
        SYSTEMLOTTERYTYPE_RACE_RUNE_GOLDFRIST = 26, // 系统种族符文金币首抽
        SYSTEMLOTTERYTYPE_RACE_RUNE_GOLDSOLO = 27, // 系统种族符文金币单抽
        SYSTEMLOTTERYTYPE_RACE_RUNE_GOLDFIVE = 28, // 系统种族符文金币连抽
        SYSTEMLOTTERYTYPE_RACE_RUNE_GOLDSOLOGOD = 29, // 系统种族符文金币单抽保底
        SYSTEMLOTTERYTYPE_RACE_RUNE_GOLDFIVEGOD = 30, // 系统种族符文金币连抽保底
}
public enum  ShopDiscountType
{
        SHOPDISCOUNTTYPE_NONE = 0, // 商城折扣类型_无折扣
        SHOPDISCOUNTTYPE_LIMITTIME = 1, // 商城折扣类型_限时折扣
        SHOPDISCOUNTTYPE_NEWBIE = 2, // 商城折扣类型_新手折扣
}
public enum  TeamInviteFromType
{
        TEAMINVITEFROMTYPE_FRIEND = 0, // 组队邀请类型_好友
        TEAMINVITEFROMTYPE_RECENT = 1, // 组队邀请类型_近期
        TEAMINVITEFROMTYPE_CHAT = 2, // 组队邀请类型_聊天
}
public enum  ActivityAcquireType
{
        ACTIVITYACQUIRETYPE_FIRSTLOGIN = 0, // 活动获得类型_首次登录
        ACTIVITYACQUIRETYPE_LIMITTIME = 1, // 活动获得类型_限时获得
        ACTIVITYACQUIRETYPE_WEEKDAY = 2, // 活动获得类型_每周获得
        ACTIVITYACQUIRETYPE_MONTHDAY = 3, // 活动获得类型_每月获得
}
public enum  ActivityDurationType
{
        ACTIVITYDURATIONTYPE_WEEKDAY = 0, // 活动时间类型_每周时间段
        ACTIVITYDURATIONTYPE_NEWBIE = 1, // 活动时间类型_新手期
        ACTIVITYDURATIONTYPE_PERIOD = 2, // 活动时间类型_固定时间段
        ACTIVITYDURATIONTYPE_MONTHDAY = 3, // 活动时间类型_每月时间段
}
public enum  ActivityCounterType
{
        ACTIVITYCOUNTERTYPE_NONE = 0, // 活动计数器类型_无
        ACTIVITYCOUNTERTYPE_LOGIN_INTIME = 1, // 活动计数器类型_时间段登录
        ACTIVITYCOUNTERTYPE_LOGIN_TOTALDAY = 2, // 活动计数器类型_每日登录
        ACTIVITYCOUNTERTYPE_PAY_TOTAL = 3, // 活动计数器类型_充值
        ACTIVITYCOUNTERTYPE_NEWBIE_LOGIN = 4, // 活动计数器类型_新手登录
}
public enum  ActivityCounterResetType
{
        ACTIVITYCOUNTERRESETTYPE_NONE = 0, // 活动计数器重置类型_不重置
        ACTIVITYCOUNTERRESETTYPE_EVERYDAY = 1, // 活动计数器重置类型_每天重置
        ACTIVITYCOUNTERRESETTYPE_EVERYWEEK = 2, // 活动计数器重置类型_每周重置
        ACTIVITYCOUNTERRESETTYPE_EVERYMONTH = 3, // 活动计数器重置类型_每月重置
}
public enum  ActivityQuestState
{
        ACTIVITYQUESTSTATE_UNFINISH = 0, // 活动任务状态_未完成
        ACTIVITYQUESTSTATE_FINISH = 1, // 活动任务状态_已完成
        ACTIVITYQUESTSTATE_REWARDED = 2, // 活动任务状态_已领奖
}
public enum  ResActorRuneAttrType
{
        RUNE_ATTR_MIN = 0, // 符文_属性最小值
        RUNE_ATTR_MAX_HP = 2, // 符文_最大生命值
        RUNE_ATTR_HP_RECOVERY = 3, // 符文_生命回复/5s
        RUNE_ATTR_MAX_MP = 5, // 符文_最大法术值
        RUNE_ATTR_MP_RECOVER = 7, // 符文_法术回复/5s
        RUNE_ATTR_ATK = 8, // 符文_攻击力
        RUNE_ATTR_ARMOR = 9, // 符文_护甲值
        RUNE_ATTR_ARMOR_PIERCE = 10, // 符文_护甲穿透
        RUNE_ATTR_ATK_SPEED = 12, // 符文_攻击速度(1万代表1s)
        RUNE_ATTR_ATK_STEAL_RATE = 13, // 符文_生命偷取率(万分比)
        RUNE_ATTR_CRI_RATE = 14, // 符文_暴击率(万分比)
        RUNE_ATTR_CRI_DAM_RATE = 15, // 符文_暴击伤害率(万分比)
        RUNE_ATTR_MAGIC = 16, // 符文_法术强度
        RUNE_ATTR_MAGIC_DEF = 17, // 符文_法术抗性
        RUNE_ATTR_MD_PIERCE = 18, // 符文_法术穿透
        RUNE_ATTR_AP_STEAL_RATE = 20, // 符文_法术吸血率(万分比)
        RUNE_ATTR_TENACITY_RATE = 21, // 符文_韧性率(万分比)
        RUNE_ATTR_CD_REDUCTION = 22, // 符文_冷却缩减(万分比)
        RUNE_ATTR_EVASION_RATE = 24, // 符文_闪避值(万分比)
        RUNE_ATTR_MAX = 26, // 符文_属性最大值
}
public enum  ResTeamRuneAttrType
{
        TEAMRUNE_ATTR_MIN = 0, // 符文_队伍属性最小值
        TEAMRUNE_ATTR_MFGOLD = 1, // 符文_打野额外金钱(万分比)
        TEAMRUNE_ATTR_MFEXP = 2, // 符文_打野额外经验(万分比)
        TEAMRUNE_ATTR_PKEXP = 3, // 符文_击杀士兵额外经验(万分比)
        TEAMRUNE_ATTR_BUILDGOLDTIME = 4, // 符文_分矿建造时间(毫秒)
        TEAMRUNE_ATTR_BUILDTOWERTIME = 5, // 符文_防御塔建造时间(毫秒)
        TEAMRUNE_ATTR_UPBASETIME = 6, // 符文_升级基地时间(万分比)
        TEAMRUNE_ATTR_CONSTRUCTARMYCOST = 7, // 符文_训练士兵费用(万分比)
        TEAMRUNE_ATTR_REPARISPEED = 8, // 符文_修理建筑速度(万分比)
        TEAMRUNE_ATTR_SPAWNGOLD = 9, // 符文_出生携带金币
        TEAMRUNE_ATTR_TRANFERCD = 10, // 符文_传送冷却时间(毫秒)
        TEAMRUNE_ATTR_GRASSHPRECOVER = 11, // 符文_草丛生命回复(万分比)
        TEAMRUNE_ATTR_SPRINGHPRECOVER = 12, // 符文_泉水生命回复(万分比)
        TEAMRUNE_ATTR_MAX = 13, // 符文_队伍属性最大值
}
public enum  RuneMosaicType
{
        RuneMosaicType_Attack = 0, // 攻击向符文
        RuneMosaicType_Defense = 1, // 防御向符文
        RuneMosaicType_Buff = 2, // 辅助向符文
        RuneMosaicType_Specially = 3, // 特殊向符文
        RuneMosaicType_AnyWhere = 4, // 任意位置符文
}
public enum  RuneAttrType
{
        RUNEATTRTYPE_ACTOR = 0, // 单位属性符文
        RUNEATTRTYPE_TEAM = 1, // 队伍属性符文
}
public enum  RunePackageType
{
        RUNEPACKAGETYPE_HERO = 1, // 英雄符文背包
        RUNEPACKAGETYPE_RACE = 2, // 种族符文背包
}
public enum  GameShareType
{
        SHARE_BATTLESETTLE = 0, // 分享游戏战绩
        SHARE_ACTIVITY = 1, // 分享活动
}


}
