/* This file is generated by tdr. */
/* No manual modification is permitted. */

/* metalib version: 1 */
/* metalib md5sum: 65d0301c457c17200214e2e089e79aee */

/* creation time: Fri Apr 28 11:11:00 2023 */
/* tdr version: 2.5.0, build at 20111124 */

#ifndef _BattleProtocol_metalib_h_
#define _BattleProtocol_metalib_h_

namespace BattleProtocol
{


class MetaLib
{
    public:
        static int getVersion()
        {
            return 1;
        }

        static const char* getName()
        {
            return "BattleProtocol";
        }

        static const char* getMd5Sum()
        {
            return "65d0301c457c17200214e2e089e79aee";
        }

        static const char* getTdrVersion()
        {
            return "2.5.0, build at 20111124";
        }
};


}
#endif
