/* This file is generated by tdr. */
/* No manual modification is permitted. */

/* metalib version: 1 */
/* metalib md5sum: 65d0301c457c17200214e2e089e79aee */

/* creation time: Fri Apr 28 11:11:00 2023 */
/* tdr version: 2.5.0, build at 20111124 */

#ifndef _CSBattleComm_h_
#define _CSBattleComm_h_

#include "TdrBuf.h"
#include "TdrError.h"
#include "TdrBufUtil.h"
#include "TdrTypeUtil.h"


using tsf4g_tdr::TdrError;
using tsf4g_tdr::TdrReadBuf;
using tsf4g_tdr::TdrWriteBuf;

namespace BattleProtocol
{


enum
{
    CLIENT_FRONT_LEN = 2, // 服务器头字节
    CLIENT_FLUSH_FRONT_LEN = 4, // 压缩格式头字节
    MSGID_FRONT_LEN = 6, // 服务器头结构字节
    RET_CODE_OK = 0, // 正常
    MAX_NAME_LEN = 64, // 名称最大长度
    MAX_MD5_LEN = 64, // md5最大长度
    MAX_TOKEN_LEN = 256, // token长度
    MAX_GM_LEN = 256, // gm长度
    MAX_DUMP_LEN = 17, // dump
    MAX_FRAME_CMD_LEN = 128, // 帧通用指令长度
    MAX_BATTLEFRAMECMD_LEN = 256, // 帧指令最大数组长度
    MAX_BATTLEFRAMECMD_MAXCNT = 60, // 帧指令最大指令长度
    MAX_BATTLEFRAMECMDARRAY_MAXSIZE = 8096, // 重连帧指令数组最大长度
    MAX_ROLENAME_LEN = 128, // 名字最大长度
    MAX_BATTLEPLAYER_COUNT = 10, // 战场对阵玩家最大数目
    MAX_BATTLESYSTEM_COUNT = 12, // 游戏系统设置最大数目
    MAX_RACESKILL_COUNT = 4, // 种族技能最大个数
    MAX_ACTORRUNEATTR_COUNT = 26, // 创建单位符文属性最大个数
    MAX_TEAMRUNEATTR_COUNT = 12, // 创建队伍符文属性最大个数
    MAX_BATTLTEDUMPATTR_MAX_COUNT = 60, // Dump属性最大个数
    MAX_BATTLTEBUFF_MAX_COUNT = 16, // Dump BUFF最大个数
    MAX_BATTLTACTOR_MAX_COUNT = 256, // Dump Actor最大个数
    MAX_BATTLTEAM_MAX_COUNT = 8, // 队伍最大个数
    MAX_BATTLSTATISSTICD_TECHSKILLS_MAX_COUNT = 16, // 战斗统计科技技能最大个数
    MAX_BATTLSTATISSTICD_TECHDOGFACE_MAX_COUNT = 32, // 战斗统计科技兵种最大个数
    MAX_BATTLSTATISSTIC_SKILLBARDMG_MAX_COUNT = 4, // 统计技能伤害个数
    MAX_BATTLSTATISSTIC_GOLDMINE_MAX_COUNT = 3, // 统计分矿个数
    MAX_BATTLSTATISSTIC_GOLDGET_MAX_COUNT = 6, // 统计金币信息
    MAX_BATTLSTATISSTIC_EQUIP_MAX_COUNT = 6, // 最大装备数目信息
    MAX_BATTLSTATISSTIC_MONSTER_GROUP_KILL_MAX_COUNT = 32, // 最大野怪组击杀个数
    MAX_BATTLSTATISSTIC_DROP_ITEM_MAX_COUNT = 12, // 最大掉落道具数目信息
};


enum CS_MAIN_MSGID // CS消息编号
{
    CS_MSG_MAIN_LOGIN = 0, // 登录服务器
    CS_MSG_MAIN_LOGIC = 1, // 逻辑服务器
    CS_MSG_MAIN_BATTLE = 2, // 战斗服务器
};
enum CS_SUB_MSGID_BATTLESVR // Battlesvr子消息
{
    CS_SUB_MSGID_BATTLESVR_LOGIN_REQ = 1, // 登陆请求
    CS_SUB_MSGID_BATTLESVR_LOGIN_RSP = 2, // 登陆回包
    CS_SUB_MSGID_MAPLOAD_PROGRESS_REQ = 4, // 地图加载进度上报
    CS_SUB_MSGID_MAPLOAD_PROGRESS_NOTIFY = 5, // 地图加载进度通知
    CS_SUB_MSGID_BATTLESVR_FINISH_LOADMAP_REQ = 6, // 完成地图加载消息上报
    CS_SUB_MSGID_BATTLESVR_GAMESTART_NOTIFY = 7, // 开始游戏通知消广播
    CS_SUB_MSGID_BATTLESVR_GAMEEND_REQ = 8, // 游戏结束通知上报
    CS_SUB_MSGID_BATTLESVR_GAMEEND_NOTIFY = 9, // 游戏结束通知通知
    CS_SUB_MSGID_BATTLESVR_GAMERESTART_REQ = 10, // 重连请求服务器数据
    CS_SUB_MSGID_BATTLESVR_GAMERESTART_RSP = 11, // 重连请求服务器数据完成
    CS_SUB_MSGID_BATTLE_HEARTBEAT_REQ = 12, // 心跳包请求
    CS_SUB_MSGID_BATTLE_HEARTBEAT_RSP = 13, // 心跳包请求回复
    CS_SUB_MSGID_BATTLE_MAPEVENT_REQ = 15, // 战斗地图信息号请求
    CS_SUB_MSGID_BATTLE_MAPEVENT_RSP = 16, // 战斗地图信息号请求回包
    CS_SUB_MSGID_BATTLE_MAPEVENT_NOTIFY = 17, // 战斗地图信息号广播
    CS_SUB_MSGID_BATTLESVR_FRAME_REQ = 30, // 1帧指令请求
    CS_SUB_MSGID_BATTLESVR_FRAME_NOTIFY = 31, // 1帧指令通知
    CS_SUB_MSGID_MINIMAP_EVENT_REQ = 32, // 小地图事件请求
    CS_SUB_MSGID_MINIMAP_EVENT_NOTIFY = 33, // 小地图事件通知
    CS_SUB_MSGID_SURRENDER_REQ = 34, // 投降请求
    CS_SUB_MSGID_SURRENDER_AGREE = 36, // 同意投降
    CS_SUB_MSGID_SURRENDER_REFUSE = 37, // 拒绝投降
    CS_SUB_MSGID_SURRENDER_AGREE_NOTIFY = 38, // 同意投降通知
    CS_SUB_MSGID_SURRENDER_REFUSE_NOTIFY = 39, // 拒绝投降通知
    CS_SUB_MSGID_SURRENDER_NOTIFY = 40, // 投降请求通知
    CS_SUB_MSGID_SURRENDER_RESULT_NOTIFY = 41, // 投降结果通知
    CS_SUB_MSGID_FETCH_FRAME_DATA_REQ = 42, // 请求重连数据
    CS_SUB_MSGID_PLAYER_CONNECT_NOTIFY = 43, // 玩家上下线通知
    CS_SUB_MSGID_NEW_PLAYER_INFO = 50, // 新玩家加入
    CS_SUB_MSGID_GM_COMMAND = 900, // gm指令
    CS_SUB_MSGID_DUMP_INFO = 901, // 客户端dumpinfo
    CS_SUB_MSGID_DUMP_INFO_RET = 902, // 客户端dumpinfo校验结果
    CS_SUB_MSGID_REPLAY_SVR_NEW_BATTLE_REQ = 910, // 新的战斗
    CS_SUB_MSGID_REPLAY_SVR_FRAME_MD5_REQ = 911, // 帧md5
    CS_SUB_MSGID_REPLAY_SVR_BATTLE_RESULT_NOTIFY = 912, // 结果通知
    CS_SUB_MSGID_REPLAY_SVR_SURRENDER_RESULT_NOTIFY = 913, // 投降结果通知
    CS_SUB_MSGID_BATTLESVR_MAX = 1000, // MAX
};
enum ErrCodeDefine // 通用错误码
{
    ERR_SUCCESS = 0, // 成功
    ERR_PARAM_INV = 1, // 参数错误
    ERR_POINTER_NULL = 2, // 指针为空
    ERR_BATTLESVR_MONEYNOTENUGH = 10, // 金钱不够
    ERR_BATTLESVR_LOGIN_FAILED_BATTLEFINISHED = 100, // 登录服务器，战斗已经结束
    ERR_BATTLESVR_CASTSKILL_COMMONERRO = 200, // 技能参数错误
    ERR_BATTLESVR_CASTSKILL_PARAMERROR = 201, // 技能参数错误
    ERR_BATTLESVR_CASTSKILL_SKILLLOCK = 202, // 技能未解锁
    ERR_BATTLESVR_CASTSKILL_COLINGDOWN = 203, // 技能CD冷却中
    ERR_BATTLESVR_CASTSKILL_DISTANCE_NOTENOUGH = 204, // 不满足释放距离
    ERR_BATTLESVR_CASTSKILL_CONSUME_NOTENOUGH = 205, // 技能消耗不足
    ERR_BATTLESVR_CASTSKILL_TARGET_INAVALID = 206, // 当前目标非法
    ERR_BATTLESVR_CASTSKILL_SELFSTATE_INAVALIABLE = 207, // 自身状态非法
    ERR_BATTLESVR_CASTSKILL_SELFSTATE_HPISFULL = 208, // 使用基础加血技能,当前自身血量已满
    ERR_BATTLESVR_CASTSKILL_AICLOSE = 209, // 服务器AI关闭
    ERR_BATTLESVR_CASTSKILL_SKILLBEFOREROLL = 210, // 技能处于前摇中
    ERR_BATTLESVR_CASTSKILL_INDEBUFF = 211, // 处于DEBUFF中无法释放
    ERR_BATTLESVR_CASTSKILL_AVATARSKILLNOTEQUIP = 212, // 变体技能未挂载
    ERR_BATTLESVR_CASTSKILL_MOVINGNOTCAST = 213, // 移动中普攻技能无法释放
    ERR_BATTLESVR_OPEQUIP_NOTFINDEQUIP = 300, // 找不到对应装备
    ERR_BATTLESVR_OPEQUIP_EQUIPBARFULL = 301, // 装备栏位不足
    ERR_SYSTEM_SERVER_OBJ_NULL = 10001, // 系统错误,服务器发现空指针
};
enum PlatformType // 平台类型
{
    EN_PLATFORMTYPE_NONE = 0, // 未知
    EN_PLATFORMTYPE_QQ = 1, // QQ
    EN_PLATFORMTYPE_WX = 2, // 微信
    EN_PLATFORMTYPE_GUEST = 3, // 游客模式
};
enum OSType // 客户端系统类型
{
    OSTYPE_IOS = 1, // IOS
    OSTYPE_ANDROID = 2, // Android
    OSTYPE_WINDOWS = 3, // PC
};
enum LoginConnectType // 登录连接返回类型
{
    EN_LOGINRECONNECT_NONE = 0, // 正常登录
    EN_LOGINRECONNECT_FLASH = 1, // 闪断重连
    EN_LOGINRECONNECT_BREAK = 2, // 长断重连
};
enum BattleMode // 战场类型
{
    EN_BT_PVP = 1, // PVP
    EN_BT_PVE = 2, // PVE
    EN_BT_ALL = 3, // 所有战场
};
enum BattleVSMode // 比赛类型
{
    BT_QUALIFYING_1V1 = 1, // BT_QUALIFYING_1V1
    BT_QUALIFYING_3V3 = 2, // BT_QUALIFYING_3V3
    BT_MATCH_1V1 = 3, // BT_MATCH_1V1
    BT_MATCH_3V3 = 4, // BT_MATCH_3V3
    BT_ROOM = 5, // BT_ROOM
    BT_PVC = 6, // BT_PVC
    BT_QUALIFYING_2V2 = 7, // BT_QUALIFYING_2V2
    BT_MATCH_2V2 = 8, // BT_MATCH_2V2
    BT_ALL = 9, // 所有战场
};
enum BattleEvilMatchTeamType // 邪恶方队伍颜色分配
{
    TEAMTYPE_RED = 1, // 红方队伍
    TEAMTYPE_PURPLE = 3, // 紫方队伍
    TEAMTYPE_PINK = 5, // 粉方队伍
};
enum BattleJusticeMatchTeamType // 正义方队伍颜色分配
{
    TEAMTYPE_BLUE = 2, // 蓝方队伍
    TEAMTYPE_GREEN = 4, // 绿方队伍
    TEAMTYPE_YELLOW = 6, // 黄方队伍
};
enum CSClientOpenFlag // 客户端功能开关
{
    CS_CLENTOPENFLAG_SHOP = 0, // 商城
    CS_CLENTOPENFLAG_CHAT = 1, // 聊天
    CS_CLENTOPENFLAG_MAIL = 2, // 邮件
    CS_CLENTOPENFLAG_LIVE = 3, // 直播
    CS_CLENTOPENFLAG_REPLAYS = 4, // 录像回看
    CS_CLENTOPENFLAG_FRIEND = 5, // 好友
    CS_CLENTOPENFLAG_ACHIEVE = 6, // 成就
    CS_CLENTOPENFLAG_TASK = 7, // 任务
    CS_CLENTOPENFLAG_ACTIVITY = 8, // 活动
    CS_CLENTOPENFLAG_MAX = 9, // MAX
};
enum CSBattleGankKillEvent // 战场击杀玩家事件类型
{
    CS_GANK_KILLEVENT_NONE = 0, // 无
    CS_GANK_KILLEVENT_FIRST_BLOOD = 1, // 首杀
    CS_GANK_KILLEVENT_DOMINATING = 2, // 主宰战场
    CS_GANK_KILLEVENT_UNSTOPPABLE = 3, // 无人能挡
    CS_GANK_KILLEVENT_LEGENDARY = 4, // 王者再临
    CS_GANK_KILLEVENT_KILLENEMYHERO = 5, // 击杀英雄
};
enum CSBattleKillDogfaceEvent // 战场击杀小兵事件类型
{
    CS_KILLDOGFACEEVENT_NONE = 0, // 无
    CS_KILLDOGFACEEVENT_GODLIKE = 1, // 杀小兵超神(连续击杀)
};
enum BattleActorState // 单位状态
{
    EN_ACTORSTATE_FREEZE = 0, // 冻结状态
    EN_ACTORSTATE_ALIVE = 1, // 活着
    EN_ACTORSTATE_DEATH = 2, // 死亡
    EN_ACTORSTATE_RECYCLE = 3, // 死亡回收中，用于清理
};
enum BattleActorRevivalType // 单位复活类型
{
    EN_ACTORREVIVALTYPE_DEAD = 0, // 死亡复活
    EN_ACTORREVIVALTYPE_SKILL = 1, // 技能重生复活
};
enum SkillCastInputMode // 技能释放输入模式
{
    EN_SKILLINPUT_ACTOR = 0, // 朝着目标
    EN_SKILLINPUT_POS = 1, // 朝点
};
enum BattleStatisticsEventType // 战斗统计事件类型
{
    BATTLEEVENTTYPE_KILLHERO = 1, // 击杀英雄 
    BATTLEEVENTTYPE_KILLMONSTER = 2, // 击杀野怪
    BATTLEEVENTTYPE_KILLDOGFACE = 3, // 击杀士兵
    BATTLEEVENTTYPE_BUILDMINE = 4, // 造矿
    BATTLEEVENTTYPE_KILLDRAGON = 5, // 杀大龙
    BATTLEEVENTTYPE_BUILDTOWER = 6, // 造塔
};
enum RoomStepType // 房间所处的步骤
{
    ROOM_STEP_BATTLEREADY = 1, // 战斗准备中
    ROOM_STEP_SELECTHERO = 2, // 选择英雄中
    ROOM_STEP_LOADINGMAP = 3, // 等待地图加载中
    ROOM_STEP_WAITING = 4, // 等待战斗开始
    ROOM_STEP_BATTLESTART = 5, // 战场已经开始
    ROOM_STEP_BATTLEEND = 6, // 战斗已经结束
    ROOM_STEP_NOTEXIST = 7, // 房间不存在
};
enum RoomPlayerrStepType // 玩家在房间所处的步骤
{
    ROOMPLAYER_STEP_MATCH_OK = 1, // 匹配到队伍
    ROOMPLAYER_STEP_BATTLEREADY = 2, // 点了战斗准备
    ROOMPLAYER_STEP_SELECTHEROEND = 3, // 已经选好英雄
    ROOMPLAYER_STEP_LOADINGMAP = 4, // 正在加载地图
    ROOMPLAYER_STEP_ENDLOADINGMAP = 5, // 加载地图完成
    ROOMPLAYER_STEP_BATTLESTART = 6, // 战场已经开始
    ROOMPLAYER_STEP_BATTLEEND = 7, // 战斗已经结束
};
enum EquipOpType // 装备操作类型
{
    EQUIPOPTYPE_ADD = 0, // 添加装备
    EQUIPOPTYPE_REMOVE = 1, // 移除装备
    EQUIPOPTYPE_SELL = 2, // 出售装备
};
enum CSBattleSystemType // 游戏系统设置类型
{
    CSBATTLESYTEMTYPE_HEROFORMATIONPOS = 1, // 队伍英雄站位,0=居中,1=队伍前,默认=0
    CSBATTLESYTEMTYPE_NEARASSISTED = 2, // 普攻近战集火开关,0=关,1=开,默认=0
    CSBATTLESYTEMTYPE_FARASSISTED = 3, // 普攻远程集火开关,0=关,1=开,默认=0
    CSBATTLESYTEMTYPE_MUTEXTREATTYPE = 4, // 治疗目标方式,0=互斥治疗,1=不互斥治疗,默认=0
    CSBATTLESYTEMTYPE_KEEPDIS = 5, // 最小首次攻击距离,0=关,1=开,默认=1
    CSBATTLESYTEMTYPE_CTRSKILLTOMONSTER = 6, // 控制技能对野怪施放,0=关,1=开,默认=0
    CSBATTLESYTEMTYPE_TEAMGROUPREGIONMAX = 7, // 队伍区域距离最大范围,距离
    CSBATTLESYTEMTYPE_ESCAPEHPPRECENT = 8, // 士兵受攻击时主动后撤血量,距离
    CSBATTLESYTEMTYPE_MAX = 9, // 最大值
};
enum CSBattleEventType // 游戏事件通知类型
{
    CSBATTLEEVENTTYPE_HOST_CTRL = 1, // 进入托管模式
};
enum CSBattleFrameEventType // 帧同步指令类型
{
    BATTLEFRAMEEVENT_ACTOR_CASTSKILL = 1, // 单位释放技能
    BATTLEFRAMEEVENT_ACTOR_SKILLEVENT = 2, // 单位技能释放事件
    BATTLEFRAMEEVENT_ACTOR_ADDSKILLPOINIT = 3, // 单位技能加点
    BATTLEFRAMEEVENT_ACTOR_EQUIPOP = 4, // 单位装备操作
    BATTLEFRAMEEVENT_BATTLE_STARTMOVE = 10, // 开始移动
    BATTLEFRAMEEVENT_BATTLE_STOPMOVE = 11, // 停止移动
    BATTLEFRAMEEVENT_BATTLE_JUMP = 12, // 跳跃
    BATTLEFRAMEEVENT_BATTLE_WALK = 13, // 设置走路状态
    BATTLEFRAMEEVENT_BATTLE_FACE_DIR = 14, // 玩家转向
    BATTLEFRAMEEVENT_BATTLE_TEAMCONFIG = 30, // 同步玩家游戏设置
    BATTLEFRAMEEVENT_BATTLE_EVENTNOTIFY = 31, // 游戏通用事件通知
    BATTLEFRAMEEVENT_BATTLE_SET_HOTBAR_INDEX = 32, // 切换快捷栏
    BATTLEFRAMEEVENT_BATTLE_SWAP_ITEM_SLOT = 33, // 物品栏交换
    BATTLEFRAMEEVENT_BATTLE_GM_CMD = 100, // gm指令
    BATTLEFRAMEEVENT_BATTLE_GM_SCALE_TIME_CMD = 101, // gm指令修改服务器时间缩放
    BATTLEFRAMEEVENT_BATTLE_GAME_END_NOTIFY = 102, // 服务器主动结束战斗通知
};
enum CSMiniMapEvent // 
{
    MINIMAPEVENT_NONE = 0, // 
    MINIMAPEVENT_STICKTOGETHER = 1, // 集合
    MINIMAPEVENT_WITHDRAW = 2, // 撤退
    MINIMAPEVENT_ATTACK = 3, // 进攻
};
enum GameReStartState // 玩家重连服务器状态
{
    GAMERESTARTSTATE_NONE = 0, // 未重连
    GAMERESTARTSTATE_SYNC = 1, // 同步中
    GAMERESTARTSTATE_QUEUED = 2, // 排队中
};


#pragma pack(1)


class CSFlushMsgHead
{
    public: /* members */
        uint16_t DataLen; // 数据长度
        uint16_t LzoLen; // 压缩后的长度，为0表示未压缩

    public: /* methods */
        TdrError::ErrorType construct();

        TdrError::ErrorType pack(TdrWriteBuf& destBuf, unsigned cutVer = 0) const;
        TdrError::ErrorType pack(char* buffer, size_t size, size_t* usedSize = NULL, unsigned cutVer = 0) const;

        TdrError::ErrorType unpack(TdrReadBuf& srcBuf, unsigned cutVer = 0);
        TdrError::ErrorType unpack(const char* buffer, size_t size, size_t* usedSize = NULL, unsigned cutVer = 0);

        /* set indent = -1 to disable indent */
        TdrError::ErrorType visualize(TdrWriteBuf& destBuf, int indent = 0, char separator = '\n') const;
        TdrError::ErrorType visualize(char* buffer, size_t size, size_t* usedSize = NULL,
                                      int indent = 0, char separator = '\n') const;
        const char* visualize_ex(TdrWriteBuf& destBuf, int indent = 0, char separator = '\n') const;
        const char* visualize_ex(char* buffer, size_t size, size_t* usedSize = NULL,
                                 int indent = 0, char separator = '\n') const;


    public: /* version infomation */
        enum
        {
            BASEVERSION = 1,
            CURRVERSION = 1,
        };
};

typedef       CSFlushMsgHead          tagCSFlushMsgHead;
typedef       CSFlushMsgHead             CSFLUSHMSGHEAD;
typedef       CSFlushMsgHead*          LPCSFLUSHMSGHEAD;
typedef const CSFlushMsgHead*         LCPCSFLUSHMSGHEAD;


class CSMsgHead
{
    public: /* members */
        int32_t Frame; // 帧号
        uint16_t SubMsgID; // 子协议编号

    public: /* methods */
        TdrError::ErrorType construct();

        TdrError::ErrorType pack(TdrWriteBuf& destBuf, unsigned cutVer = 0) const;
        TdrError::ErrorType pack(char* buffer, size_t size, size_t* usedSize = NULL, unsigned cutVer = 0) const;

        TdrError::ErrorType unpack(TdrReadBuf& srcBuf, unsigned cutVer = 0);
        TdrError::ErrorType unpack(const char* buffer, size_t size, size_t* usedSize = NULL, unsigned cutVer = 0);

        /* set indent = -1 to disable indent */
        TdrError::ErrorType visualize(TdrWriteBuf& destBuf, int indent = 0, char separator = '\n') const;
        TdrError::ErrorType visualize(char* buffer, size_t size, size_t* usedSize = NULL,
                                      int indent = 0, char separator = '\n') const;
        const char* visualize_ex(TdrWriteBuf& destBuf, int indent = 0, char separator = '\n') const;
        const char* visualize_ex(char* buffer, size_t size, size_t* usedSize = NULL,
                                 int indent = 0, char separator = '\n') const;


    public: /* version infomation */
        enum
        {
            BASEVERSION = 1,
            CURRVERSION = 1,
        };
};

typedef       CSMsgHead          tagCSMsgHead;
typedef       CSMsgHead             CSMSGHEAD;
typedef       CSMsgHead*          LPCSMSGHEAD;
typedef const CSMsgHead*         LCPCSMSGHEAD;


class CSUpMsgHead
{
    public: /* members */
        uint16_t SubMsgID; // 子协议编号

    public: /* methods */
        TdrError::ErrorType construct();

        TdrError::ErrorType pack(TdrWriteBuf& destBuf, unsigned cutVer = 0) const;
        TdrError::ErrorType pack(char* buffer, size_t size, size_t* usedSize = NULL, unsigned cutVer = 0) const;

        TdrError::ErrorType unpack(TdrReadBuf& srcBuf, unsigned cutVer = 0);
        TdrError::ErrorType unpack(const char* buffer, size_t size, size_t* usedSize = NULL, unsigned cutVer = 0);

        /* set indent = -1 to disable indent */
        TdrError::ErrorType visualize(TdrWriteBuf& destBuf, int indent = 0, char separator = '\n') const;
        TdrError::ErrorType visualize(char* buffer, size_t size, size_t* usedSize = NULL,
                                      int indent = 0, char separator = '\n') const;
        const char* visualize_ex(TdrWriteBuf& destBuf, int indent = 0, char separator = '\n') const;
        const char* visualize_ex(char* buffer, size_t size, size_t* usedSize = NULL,
                                 int indent = 0, char separator = '\n') const;


    public: /* version infomation */
        enum
        {
            BASEVERSION = 1,
            CURRVERSION = 1,
        };
};

typedef       CSUpMsgHead          tagCSUpMsgHead;
typedef       CSUpMsgHead             CSUPMSGHEAD;
typedef       CSUpMsgHead*          LPCSUPMSGHEAD;
typedef const CSUpMsgHead*         LCPCSUPMSGHEAD;


#pragma pack()

}
#endif
