#! /usr/bin/env python
#coding=utf-8
import __future__
import tokenize
import os
import sys
import xml.dom.minidom

def get_attrvalue(node, attrname):
     return node.getAttribute(attrname) if node else ''

def get_nodevalue(node, index = 0):
    return node.childNodes[index].nodeValue if node else ''

def get_xmlnode(node, name):
    return node.getElementsByTagName(name) if node else []
	
def decode_keywords_Res():
    file_xml = open('../xml/keywords_Res.xml',"r").read()
    file_xml = file_xml.replace('<?xml version="1.0" encoding="GBK" standalone="yes" ?>','<?xml version="1.0" encoding="utf-8" standalone="yes" ?>')
    file_xml = unicode(file_xml,encoding='gbk').encode('utf-8')
    xmldoc = xml.dom.minidom.parseString(file_xml)
    root = xmldoc.documentElement
	
    user_nodes = get_xmlnode(root, 'macrosgroup')
    #print "user_nodes:", user_nodes
	
    data_str ='-- This file is generated by tdr. \n'
    for node in user_nodes: 
		sub_cname = get_attrvalue(node, 'name')
		sub_desc = get_attrvalue(node, 'desc')
		data_str= data_str+ '\nDs_%s = {} --%s\n' % (sub_cname,sub_desc)
        
		sub_nodes = get_xmlnode(node, 'macro')
		for subnode in sub_nodes: 
		    attr_cname = get_attrvalue(subnode, 'cname') 
		    attr_value = get_attrvalue(subnode, 'value')
		    attr_name = get_attrvalue(subnode, 'name')
		    attr_desc = get_attrvalue(subnode, 'desc')

		    data_str= data_str+'Ds_%s.%s = %s --%s\n' % (sub_cname,attr_name,attr_value,attr_desc)

    file_object = open('../xml/Ds_keywords.lua','w')
    file_object.write(data_str.encode('utf-8'))
    file_object.close( )
	
def decode_keywords_Res_Str():
    file_xml = open('../xml/keywords_Res.xml',"r").read()
    file_xml = file_xml.replace('<?xml version="1.0" encoding="GBK" standalone="yes" ?>','<?xml version="1.0" encoding="utf-8" standalone="yes" ?>')
    file_xml = unicode(file_xml,encoding='gbk').encode('utf-8')
    xmldoc = xml.dom.minidom.parseString(file_xml)
    root = xmldoc.documentElement
	
    user_nodes = get_xmlnode(root, 'macrosgroup')
    #print "user_nodes:", user_nodes
	
    data_str ='-- This file is generated by tdr. \n'
    for node in user_nodes: 
		sub_cname = get_attrvalue(node, 'name')
		sub_desc = get_attrvalue(node, 'desc')
		data_str= data_str+ '\nDs_%s_Str = {} --%s\n' % (sub_cname,sub_desc)
        
		sub_nodes = get_xmlnode(node, 'macro')
		for subnode in sub_nodes: 
		    attr_cname = get_attrvalue(subnode, 'cname') 
		    attr_value = get_attrvalue(subnode, 'value')
		    attr_name = get_attrvalue(subnode, 'name')
		    attr_desc = get_attrvalue(subnode, 'desc')

		    data_str= data_str+'Ds_%s_Str["%s"] = %d --%s\n' % (sub_cname,attr_cname,int(attr_value),attr_desc)

    file_object = open('../xml/Ds_keywords_str.lua','w')
    file_object.write(data_str.encode('utf-8'))
    file_object.close( )
	
def decode_ErrorCode():
    file_xml = open('../xml/CSBattleComm.xml',"r").read()
    xmldoc = xml.dom.minidom.parseString(file_xml)
    root = xmldoc.documentElement
	
    user_nodes = get_xmlnode(root, 'macrosgroup')
    #print "user_nodes:", user_nodes
	
    data_str ='-- This file is generated by tdr. \n'
    for node in user_nodes: 
		sub_cname = get_attrvalue(node, 'name')
		sub_desc = get_attrvalue(node, 'desc')
		
		
		if sub_cname == 'CSBattleFrameEventType':
		    continue
		
		
		data_str= data_str+ '\nDs_%s = {} --%s\n' % (sub_cname,sub_desc)
        
		sub_nodes = get_xmlnode(node, 'macro')
		for subnode in sub_nodes: 
		    attr_value = get_attrvalue(subnode, 'value')
		    attr_name = get_attrvalue(subnode, 'name')
		    attr_desc = get_attrvalue(subnode, 'desc')

		    data_str= data_str+'Ds_%s.%s = %s --%s\n' % (sub_cname,attr_name,attr_value,attr_desc)

    file_object = open('../xml/Ds_CSBattleComm.lua','w')
    file_object.write(data_str.encode('utf-8'))
    file_object.close( )
	
def decode_DsConfig():
    file_xml = open('../xml/Ds_Res.xml',"r").read()
    file_xml = file_xml.replace('<?xml version="1.0" encoding="GBK" standalone="yes" ?>','<?xml version="1.0" encoding="utf-8" standalone="yes" ?>')
    file_xml = unicode(file_xml,encoding='gbk').encode('utf-8')
    xmldoc = xml.dom.minidom.parseString(file_xml)
    root = xmldoc.documentElement
	
	#定义
    all_keyList = {}
    keys_nodes = get_xmlnode(root, 'macro')
    for node in keys_nodes: 
	    sub_cname = get_attrvalue(node, 'name')
	    sub_value = get_attrvalue(node, 'value')
	    keyList={};
	    keyList['name'] = sub_cname
	    keyList['value'] = sub_value
	    all_keyList[len(all_keyList)] = keyList;
	    #print "keys_nodes:%s==>%s"%(sub_cname,sub_value)
	
	
	#结构体
    user_nodes = get_xmlnode(root, 'struct')
    #print "user_nodes:", user_nodes
	
	
    data_str ='-- This file is generated by tdr. \n'
    all_list={}
    all_index=0
    for node in user_nodes: 
		sub_cname = get_attrvalue(node, 'name')
		sub_desc = get_attrvalue(node, 'desc')
		#data_str= data_str+ '\nDs_%s = {} --%s\n' % (sub_cname,sub_desc)
		
		all_index=all_index+1
		data_list= {}
		data_list['name'] = sub_cname;
		data_list['desc'] = sub_desc;
		data_list['entry'] = {};
		all_list[all_index] = data_list
        
		sub_nodes = get_xmlnode(node, 'entry')
		index = 0;
		for subnode in sub_nodes: 
		    attr_cname = get_attrvalue(subnode, 'cname') 
		    attr_name = get_attrvalue(subnode, 'name')
		    attr_desc = get_attrvalue(subnode, 'desc')
		    attr_countVal = get_attrvalue(subnode, 'count')
		    attr_type = get_attrvalue(subnode, 'type')
			
		    index=index+1
		    sub_data_list = {}
		    sub_data_list['cname'] = attr_cname
		    sub_data_list['name'] = attr_name
		    sub_data_list['desc'] = attr_desc
		    sub_data_list['type'] = attr_type
			
		    if attr_countVal!='':
			    sub_data_list['count'] = attr_countVal
		    else:
			    sub_data_list['count'] = 'none'
		
		    data_list['entry'][index] = sub_data_list;

		    #data_str= data_str+'Ds_%s.%s = "%s" --%s\n' % (sub_cname,attr_name,attr_cname,attr_desc)
	
    for d in all_list:
	    struct_name=all_list[d]['name']
	    data_str= data_str+ '\nDs_%s = {} --%s\n' % (struct_name,all_list[d]['desc'])
	    for d2 in all_list[d]['entry']:  
		    entry_name = all_list[d]['entry'][d2]['name'];
		    entry_cname = all_list[d]['entry'][d2]['cname'];
		    entry_desc = all_list[d]['entry'][d2]['desc'];
		    entry_classtype = all_list[d]['entry'][d2]['type'];
		    entry_count = all_list[d]['entry'][d2]['count'];
			
		    data_str = data_str + decode_DsConfig_Entry(all_list,all_keyList,struct_name, entry_name, 
		    entry_cname,entry_desc, entry_classtype, entry_count)  
    
    file_object = open('../xml/Ds_Res.lua','w')
    file_object.write(data_str.encode('utf-8'))
    file_object.close( )	
	
def decode_DsConfig_Entry(all_list,all_keyList,struct_name, entry_name, entry_cname,entry_desc, entry_classtype, entry_count):
    data_str=""
    if entry_count == 'none':
	    data_str= data_str+'Ds_%s.%s = "%s" --%s\n' % (struct_name,
		       entry_name, entry_cname,entry_desc)
    else:
	    data_str= data_str+'Ds_%s.%s = {} --%s\n' % (struct_name,entry_name,entry_desc)
		   
		    #计算出数组的长度
	    array_Len = 5
	    for key_index in all_keyList:
		   if all_keyList[key_index]['name']==entry_count:
			    array_Len = int(all_keyList[key_index]['value'])
			    break
			   
		   
		    #如果是基础类型
	    if entry_classtype=='int' or entry_classtype=='int8' or entry_classtype=='int16' or entry_classtype=='char':
		    for i2 in range(array_Len):
			    data_str= data_str+'Ds_%s.%s[%d] = "%s%d"\n' % (struct_name,
			    entry_name,i2+1,
			    entry_cname,i2+1)
	    else:
		    for i in all_list:
			    if all_list[i]['name'] != entry_classtype:
				    continue;
					 
			    for i2 in range(array_Len):
				    data_str= data_str+'Ds_%s.%s[%d] = {}\n' % (struct_name,
						    entry_name,i2+1)
							
				    for i3 in all_list[i]['entry']:  
					    sub_entry_name = all_list[i]['entry'][i3]['name']
					    sub_entry_cname = all_list[i]['entry'][i3]['cname']
					    sub_entry_count = all_list[i]['entry'][i3]['count'];
					    sub_entry_type = all_list[i]['entry'][i3]['type'];
						
					    if sub_entry_count == 'none':
						    data_str= data_str+'Ds_%s.%s[%d].%s = "%s%d%s"\n' % (struct_name,
						    entry_name,i2+1, sub_entry_name,
						    entry_cname,i2+1,sub_entry_cname)
					    else: #数组类型
						    data_str= data_str+'Ds_%s.%s[%d].%s = {}\n' % (struct_name,
						    entry_name,i2+1, sub_entry_name)
							
							 #计算出数组的长度
						    sub_array_Len = 5
						    for key_index in all_keyList:
							   if all_keyList[key_index]['name']==sub_entry_count:
								    sub_array_Len = int(all_keyList[key_index]['value'])
								    break
									
							    #如果是基础类型
						    if sub_entry_type=='int' or sub_entry_type=='int8' or sub_entry_type=='int16' or sub_entry_type=='char':
							    for i4 in range(sub_array_Len):
								    data_str= data_str+'Ds_%s.%s[%d].%s[%d] = "%s%d%s%d"\n' % (struct_name,
								    entry_name,i2+1,
								    sub_entry_name,i4+1,
								    entry_cname,i2+1,
								    sub_entry_cname, i4+1)
						    else:
								    print "error not supoort 3layer:%s,%s" %(struct_name, sub_entry_cname)
									
    return data_str
	
def main():
    decode_keywords_Res()
    #decode_keywords_Res_Str()
    decode_ErrorCode()
    #decode_DsConfig()
if __name__ == '__main__':
    main()
