/* This file is generated by tdr. */
/* No manual modification is permitted. */

/* metalib version: 1 */
/* metalib md5sum: 65d0301c457c17200214e2e089e79aee */

/* creation time: Fri Apr 28 09:43:21 2023 */
/* tdr version: 2.5.0, build at 20111124 */


namespace BattleProtocol
{


public class MetaLib
{
        public static int getVersion()
        {
                return 1;
        }

        public static string getName()
        {
                return "BattleProtocol";
        }

        public static string getMd5Sum()
        {
                return "65d0301c457c17200214e2e089e79aee";
        }

        public static string getTdrVersion()
        {
                return "2.5.0, build at 20111124";
        }
}


}
