/* This file is generated by tdr. */
/* No manual modification is permitted. */

/* metalib version: 1 */
/* metalib md5sum: 65d0301c457c17200214e2e089e79aee */

/* creation time: Fri Apr 28 09:43:21 2023 */
/* tdr version: 2.5.0, build at 20111124 */

namespace BattleProtocol
{

public class  BattleProtocolMacros
{
        public const int CLIENT_FRONT_LEN = 2; // 服务器头字节
        public const int CLIENT_FLUSH_FRONT_LEN = 4; // 压缩格式头字节
        public const int MSGID_FRONT_LEN = 6; // 服务器头结构字节
        public const int RET_CODE_OK = 0; // 正常
        public const int MAX_NAME_LEN = 64; // 名称最大长度
        public const int MAX_MD5_LEN = 64; // md5最大长度
        public const int MAX_TOKEN_LEN = 256; // token长度
        public const int MAX_GM_LEN = 256; // gm长度
        public const int MAX_DUMP_LEN = 17; // dump
        public const int MAX_FRAME_CMD_LEN = 128; // 帧通用指令长度
        public const int MAX_BATTLEFRAMECMD_LEN = 256; // 帧指令最大数组长度
        public const int MAX_BATTLEFRAMECMD_MAXCNT = 60; // 帧指令最大指令长度
        public const int MAX_BATTLEFRAMECMDARRAY_MAXSIZE = 8096; // 重连帧指令数组最大长度
        public const int MAX_ROLENAME_LEN = 128; // 名字最大长度
        public const int MAX_BATTLEPLAYER_COUNT = 10; // 战场对阵玩家最大数目
        public const int MAX_BATTLESYSTEM_COUNT = 12; // 游戏系统设置最大数目
        public const int MAX_RACESKILL_COUNT = 4; // 种族技能最大个数
        public const int MAX_ACTORRUNEATTR_COUNT = 26; // 创建单位符文属性最大个数
        public const int MAX_TEAMRUNEATTR_COUNT = 12; // 创建队伍符文属性最大个数
        public const int MAX_BATTLTEDUMPATTR_MAX_COUNT = 60; // Dump属性最大个数
        public const int MAX_BATTLTEBUFF_MAX_COUNT = 16; // Dump BUFF最大个数
        public const int MAX_BATTLTACTOR_MAX_COUNT = 256; // Dump Actor最大个数
        public const int MAX_BATTLTEAM_MAX_COUNT = 8; // 队伍最大个数
        public const int MAX_BATTLSTATISSTICD_TECHSKILLS_MAX_COUNT = 16; // 战斗统计科技技能最大个数
        public const int MAX_BATTLSTATISSTICD_TECHDOGFACE_MAX_COUNT = 32; // 战斗统计科技兵种最大个数
        public const int MAX_BATTLSTATISSTIC_SKILLBARDMG_MAX_COUNT = 4; // 统计技能伤害个数
        public const int MAX_BATTLSTATISSTIC_GOLDMINE_MAX_COUNT = 3; // 统计分矿个数
        public const int MAX_BATTLSTATISSTIC_GOLDGET_MAX_COUNT = 6; // 统计金币信息
        public const int MAX_BATTLSTATISSTIC_EQUIP_MAX_COUNT = 6; // 最大装备数目信息
        public const int MAX_BATTLSTATISSTIC_MONSTER_GROUP_KILL_MAX_COUNT = 32; // 最大野怪组击杀个数
        public const int MAX_BATTLSTATISSTIC_DROP_ITEM_MAX_COUNT = 12; // 最大掉落道具数目信息

        /* macros in macrogroup CS_MAIN_MSGID */
        public const int CS_MSG_MAIN_LOGIN = 0; // 登录服务器
        public const int CS_MSG_MAIN_LOGIC = 1; // 逻辑服务器
        public const int CS_MSG_MAIN_BATTLE = 2; // 战斗服务器

        /* macros in macrogroup CS_SUB_MSGID_BATTLESVR */
        public const int CS_SUB_MSGID_BATTLESVR_LOGIN_REQ = 1; // 登陆请求
        public const int CS_SUB_MSGID_BATTLESVR_LOGIN_RSP = 2; // 登陆回包
        public const int CS_SUB_MSGID_MAPLOAD_PROGRESS_REQ = 4; // 地图加载进度上报
        public const int CS_SUB_MSGID_MAPLOAD_PROGRESS_NOTIFY = 5; // 地图加载进度通知
        public const int CS_SUB_MSGID_BATTLESVR_FINISH_LOADMAP_REQ = 6; // 完成地图加载消息上报
        public const int CS_SUB_MSGID_BATTLESVR_GAMESTART_NOTIFY = 7; // 开始游戏通知消广播
        public const int CS_SUB_MSGID_BATTLESVR_GAMEEND_REQ = 8; // 游戏结束通知上报
        public const int CS_SUB_MSGID_BATTLESVR_GAMEEND_NOTIFY = 9; // 游戏结束通知通知
        public const int CS_SUB_MSGID_BATTLESVR_GAMERESTART_REQ = 10; // 重连请求服务器数据
        public const int CS_SUB_MSGID_BATTLESVR_GAMERESTART_RSP = 11; // 重连请求服务器数据完成
        public const int CS_SUB_MSGID_BATTLE_HEARTBEAT_REQ = 12; // 心跳包请求
        public const int CS_SUB_MSGID_BATTLE_HEARTBEAT_RSP = 13; // 心跳包请求回复
        public const int CS_SUB_MSGID_BATTLE_MAPEVENT_REQ = 15; // 战斗地图信息号请求
        public const int CS_SUB_MSGID_BATTLE_MAPEVENT_RSP = 16; // 战斗地图信息号请求回包
        public const int CS_SUB_MSGID_BATTLE_MAPEVENT_NOTIFY = 17; // 战斗地图信息号广播
        public const int CS_SUB_MSGID_BATTLESVR_FRAME_REQ = 30; // 1帧指令请求
        public const int CS_SUB_MSGID_BATTLESVR_FRAME_NOTIFY = 31; // 1帧指令通知
        public const int CS_SUB_MSGID_MINIMAP_EVENT_REQ = 32; // 小地图事件请求
        public const int CS_SUB_MSGID_MINIMAP_EVENT_NOTIFY = 33; // 小地图事件通知
        public const int CS_SUB_MSGID_SURRENDER_REQ = 34; // 投降请求
        public const int CS_SUB_MSGID_SURRENDER_AGREE = 36; // 同意投降
        public const int CS_SUB_MSGID_SURRENDER_REFUSE = 37; // 拒绝投降
        public const int CS_SUB_MSGID_SURRENDER_AGREE_NOTIFY = 38; // 同意投降通知
        public const int CS_SUB_MSGID_SURRENDER_REFUSE_NOTIFY = 39; // 拒绝投降通知
        public const int CS_SUB_MSGID_SURRENDER_NOTIFY = 40; // 投降请求通知
        public const int CS_SUB_MSGID_SURRENDER_RESULT_NOTIFY = 41; // 投降结果通知
        public const int CS_SUB_MSGID_FETCH_FRAME_DATA_REQ = 42; // 请求重连数据
        public const int CS_SUB_MSGID_PLAYER_CONNECT_NOTIFY = 43; // 玩家上下线通知
        public const int CS_SUB_MSGID_NEW_PLAYER_INFO = 50; // 新玩家加入
        public const int CS_SUB_MSGID_GM_COMMAND = 900; // gm指令
        public const int CS_SUB_MSGID_DUMP_INFO = 901; // 客户端dumpinfo
        public const int CS_SUB_MSGID_DUMP_INFO_RET = 902; // 客户端dumpinfo校验结果
        public const int CS_SUB_MSGID_REPLAY_SVR_NEW_BATTLE_REQ = 910; // 新的战斗
        public const int CS_SUB_MSGID_REPLAY_SVR_FRAME_MD5_REQ = 911; // 帧md5
        public const int CS_SUB_MSGID_REPLAY_SVR_BATTLE_RESULT_NOTIFY = 912; // 结果通知
        public const int CS_SUB_MSGID_REPLAY_SVR_SURRENDER_RESULT_NOTIFY = 913; // 投降结果通知
        public const int CS_SUB_MSGID_BATTLESVR_MAX = 1000; // MAX

        /* macros in macrogroup ErrCodeDefine */
        public const int ERR_SUCCESS = 0; // 成功
        public const int ERR_PARAM_INV = 1; // 参数错误
        public const int ERR_POINTER_NULL = 2; // 指针为空
        public const int ERR_BATTLESVR_MONEYNOTENUGH = 10; // 金钱不够
        public const int ERR_BATTLESVR_LOGIN_FAILED_BATTLEFINISHED = 100; // 登录服务器，战斗已经结束
        public const int ERR_BATTLESVR_CASTSKILL_COMMONERRO = 200; // 技能参数错误
        public const int ERR_BATTLESVR_CASTSKILL_PARAMERROR = 201; // 技能参数错误
        public const int ERR_BATTLESVR_CASTSKILL_SKILLLOCK = 202; // 技能未解锁
        public const int ERR_BATTLESVR_CASTSKILL_COLINGDOWN = 203; // 技能CD冷却中
        public const int ERR_BATTLESVR_CASTSKILL_DISTANCE_NOTENOUGH = 204; // 不满足释放距离
        public const int ERR_BATTLESVR_CASTSKILL_CONSUME_NOTENOUGH = 205; // 技能消耗不足
        public const int ERR_BATTLESVR_CASTSKILL_TARGET_INAVALID = 206; // 当前目标非法
        public const int ERR_BATTLESVR_CASTSKILL_SELFSTATE_INAVALIABLE = 207; // 自身状态非法
        public const int ERR_BATTLESVR_CASTSKILL_SELFSTATE_HPISFULL = 208; // 使用基础加血技能,当前自身血量已满
        public const int ERR_BATTLESVR_CASTSKILL_AICLOSE = 209; // 服务器AI关闭
        public const int ERR_BATTLESVR_CASTSKILL_SKILLBEFOREROLL = 210; // 技能处于前摇中
        public const int ERR_BATTLESVR_CASTSKILL_INDEBUFF = 211; // 处于DEBUFF中无法释放
        public const int ERR_BATTLESVR_CASTSKILL_AVATARSKILLNOTEQUIP = 212; // 变体技能未挂载
        public const int ERR_BATTLESVR_CASTSKILL_MOVINGNOTCAST = 213; // 移动中普攻技能无法释放
        public const int ERR_BATTLESVR_OPEQUIP_NOTFINDEQUIP = 300; // 找不到对应装备
        public const int ERR_BATTLESVR_OPEQUIP_EQUIPBARFULL = 301; // 装备栏位不足
        public const int ERR_SYSTEM_SERVER_OBJ_NULL = 10001; // 系统错误,服务器发现空指针

        /* macros in macrogroup PlatformType */
        public const int EN_PLATFORMTYPE_NONE = 0; // 未知
        public const int EN_PLATFORMTYPE_QQ = 1; // QQ
        public const int EN_PLATFORMTYPE_WX = 2; // 微信
        public const int EN_PLATFORMTYPE_GUEST = 3; // 游客模式

        /* macros in macrogroup OSType */
        public const int OSTYPE_IOS = 1; // IOS
        public const int OSTYPE_ANDROID = 2; // Android
        public const int OSTYPE_WINDOWS = 3; // PC

        /* macros in macrogroup LoginConnectType */
        public const int EN_LOGINRECONNECT_NONE = 0; // 正常登录
        public const int EN_LOGINRECONNECT_FLASH = 1; // 闪断重连
        public const int EN_LOGINRECONNECT_BREAK = 2; // 长断重连

        /* macros in macrogroup BattleMode */
        public const int EN_BT_PVP = 1; // PVP
        public const int EN_BT_PVE = 2; // PVE
        public const int EN_BT_ALL = 3; // 所有战场

        /* macros in macrogroup BattleVSMode */
        public const int BT_QUALIFYING_1V1 = 1; // BT_QUALIFYING_1V1
        public const int BT_QUALIFYING_3V3 = 2; // BT_QUALIFYING_3V3
        public const int BT_MATCH_1V1 = 3; // BT_MATCH_1V1
        public const int BT_MATCH_3V3 = 4; // BT_MATCH_3V3
        public const int BT_ROOM = 5; // BT_ROOM
        public const int BT_PVC = 6; // BT_PVC
        public const int BT_QUALIFYING_2V2 = 7; // BT_QUALIFYING_2V2
        public const int BT_MATCH_2V2 = 8; // BT_MATCH_2V2
        public const int BT_ALL = 9; // 所有战场

        /* macros in macrogroup BattleEvilMatchTeamType */
        public const int TEAMTYPE_RED = 1; // 红方队伍
        public const int TEAMTYPE_PURPLE = 3; // 紫方队伍
        public const int TEAMTYPE_PINK = 5; // 粉方队伍

        /* macros in macrogroup BattleJusticeMatchTeamType */
        public const int TEAMTYPE_BLUE = 2; // 蓝方队伍
        public const int TEAMTYPE_GREEN = 4; // 绿方队伍
        public const int TEAMTYPE_YELLOW = 6; // 黄方队伍

        /* macros in macrogroup CSClientOpenFlag */
        public const int CS_CLENTOPENFLAG_SHOP = 0; // 商城
        public const int CS_CLENTOPENFLAG_CHAT = 1; // 聊天
        public const int CS_CLENTOPENFLAG_MAIL = 2; // 邮件
        public const int CS_CLENTOPENFLAG_LIVE = 3; // 直播
        public const int CS_CLENTOPENFLAG_REPLAYS = 4; // 录像回看
        public const int CS_CLENTOPENFLAG_FRIEND = 5; // 好友
        public const int CS_CLENTOPENFLAG_ACHIEVE = 6; // 成就
        public const int CS_CLENTOPENFLAG_TASK = 7; // 任务
        public const int CS_CLENTOPENFLAG_ACTIVITY = 8; // 活动
        public const int CS_CLENTOPENFLAG_MAX = 9; // MAX

        /* macros in macrogroup CSBattleGankKillEvent */
        public const int CS_GANK_KILLEVENT_NONE = 0; // 无
        public const int CS_GANK_KILLEVENT_FIRST_BLOOD = 1; // 首杀
        public const int CS_GANK_KILLEVENT_DOMINATING = 2; // 主宰战场
        public const int CS_GANK_KILLEVENT_UNSTOPPABLE = 3; // 无人能挡
        public const int CS_GANK_KILLEVENT_LEGENDARY = 4; // 王者再临
        public const int CS_GANK_KILLEVENT_KILLENEMYHERO = 5; // 击杀英雄

        /* macros in macrogroup CSBattleKillDogfaceEvent */
        public const int CS_KILLDOGFACEEVENT_NONE = 0; // 无
        public const int CS_KILLDOGFACEEVENT_GODLIKE = 1; // 杀小兵超神(连续击杀)

        /* macros in macrogroup BattleActorState */
        public const int EN_ACTORSTATE_FREEZE = 0; // 冻结状态
        public const int EN_ACTORSTATE_ALIVE = 1; // 活着
        public const int EN_ACTORSTATE_DEATH = 2; // 死亡
        public const int EN_ACTORSTATE_RECYCLE = 3; // 死亡回收中，用于清理

        /* macros in macrogroup BattleActorRevivalType */
        public const int EN_ACTORREVIVALTYPE_DEAD = 0; // 死亡复活
        public const int EN_ACTORREVIVALTYPE_SKILL = 1; // 技能重生复活

        /* macros in macrogroup SkillCastInputMode */
        public const int EN_SKILLINPUT_ACTOR = 0; // 朝着目标
        public const int EN_SKILLINPUT_POS = 1; // 朝点

        /* macros in macrogroup BattleStatisticsEventType */
        public const int BATTLEEVENTTYPE_KILLHERO = 1; // 击杀英雄 
        public const int BATTLEEVENTTYPE_KILLMONSTER = 2; // 击杀野怪
        public const int BATTLEEVENTTYPE_KILLDOGFACE = 3; // 击杀士兵
        public const int BATTLEEVENTTYPE_BUILDMINE = 4; // 造矿
        public const int BATTLEEVENTTYPE_KILLDRAGON = 5; // 杀大龙
        public const int BATTLEEVENTTYPE_BUILDTOWER = 6; // 造塔

        /* macros in macrogroup RoomStepType */
        public const int ROOM_STEP_BATTLEREADY = 1; // 战斗准备中
        public const int ROOM_STEP_SELECTHERO = 2; // 选择英雄中
        public const int ROOM_STEP_LOADINGMAP = 3; // 等待地图加载中
        public const int ROOM_STEP_WAITING = 4; // 等待战斗开始
        public const int ROOM_STEP_BATTLESTART = 5; // 战场已经开始
        public const int ROOM_STEP_BATTLEEND = 6; // 战斗已经结束
        public const int ROOM_STEP_NOTEXIST = 7; // 房间不存在

        /* macros in macrogroup RoomPlayerrStepType */
        public const int ROOMPLAYER_STEP_MATCH_OK = 1; // 匹配到队伍
        public const int ROOMPLAYER_STEP_BATTLEREADY = 2; // 点了战斗准备
        public const int ROOMPLAYER_STEP_SELECTHEROEND = 3; // 已经选好英雄
        public const int ROOMPLAYER_STEP_LOADINGMAP = 4; // 正在加载地图
        public const int ROOMPLAYER_STEP_ENDLOADINGMAP = 5; // 加载地图完成
        public const int ROOMPLAYER_STEP_BATTLESTART = 6; // 战场已经开始
        public const int ROOMPLAYER_STEP_BATTLEEND = 7; // 战斗已经结束

        /* macros in macrogroup EquipOpType */
        public const int EQUIPOPTYPE_ADD = 0; // 添加装备
        public const int EQUIPOPTYPE_REMOVE = 1; // 移除装备
        public const int EQUIPOPTYPE_SELL = 2; // 出售装备

        /* macros in macrogroup CSBattleSystemType */
        public const int CSBATTLESYTEMTYPE_HEROFORMATIONPOS = 1; // 队伍英雄站位,0=居中,1=队伍前,默认=0
        public const int CSBATTLESYTEMTYPE_NEARASSISTED = 2; // 普攻近战集火开关,0=关,1=开,默认=0
        public const int CSBATTLESYTEMTYPE_FARASSISTED = 3; // 普攻远程集火开关,0=关,1=开,默认=0
        public const int CSBATTLESYTEMTYPE_MUTEXTREATTYPE = 4; // 治疗目标方式,0=互斥治疗,1=不互斥治疗,默认=0
        public const int CSBATTLESYTEMTYPE_KEEPDIS = 5; // 最小首次攻击距离,0=关,1=开,默认=1
        public const int CSBATTLESYTEMTYPE_CTRSKILLTOMONSTER = 6; // 控制技能对野怪施放,0=关,1=开,默认=0
        public const int CSBATTLESYTEMTYPE_TEAMGROUPREGIONMAX = 7; // 队伍区域距离最大范围,距离
        public const int CSBATTLESYTEMTYPE_ESCAPEHPPRECENT = 8; // 士兵受攻击时主动后撤血量,距离
        public const int CSBATTLESYTEMTYPE_MAX = 9; // 最大值

        /* macros in macrogroup CSBattleEventType */
        public const int CSBATTLEEVENTTYPE_HOST_CTRL = 1; // 进入托管模式

        /* macros in macrogroup CSBattleFrameEventType */
        public const int BATTLEFRAMEEVENT_ACTOR_CASTSKILL = 1; // 单位释放技能
        public const int BATTLEFRAMEEVENT_ACTOR_SKILLEVENT = 2; // 单位技能释放事件
        public const int BATTLEFRAMEEVENT_ACTOR_ADDSKILLPOINIT = 3; // 单位技能加点
        public const int BATTLEFRAMEEVENT_ACTOR_EQUIPOP = 4; // 单位装备操作
        public const int BATTLEFRAMEEVENT_BATTLE_STARTMOVE = 10; // 开始移动
        public const int BATTLEFRAMEEVENT_BATTLE_STOPMOVE = 11; // 停止移动
        public const int BATTLEFRAMEEVENT_BATTLE_JUMP = 12; // 跳跃
        public const int BATTLEFRAMEEVENT_BATTLE_WALK = 13; // 设置走路状态
        public const int BATTLEFRAMEEVENT_BATTLE_FACE_DIR = 14; // 玩家转向
        public const int BATTLEFRAMEEVENT_BATTLE_TEAMCONFIG = 30; // 同步玩家游戏设置
        public const int BATTLEFRAMEEVENT_BATTLE_EVENTNOTIFY = 31; // 游戏通用事件通知
        public const int BATTLEFRAMEEVENT_BATTLE_SET_HOTBAR_INDEX = 32; // 切换快捷栏
        public const int BATTLEFRAMEEVENT_BATTLE_SWAP_ITEM_SLOT = 33; // 物品栏交换
        public const int BATTLEFRAMEEVENT_BATTLE_GM_CMD = 100; // gm指令
        public const int BATTLEFRAMEEVENT_BATTLE_GM_SCALE_TIME_CMD = 101; // gm指令修改服务器时间缩放
        public const int BATTLEFRAMEEVENT_BATTLE_GAME_END_NOTIFY = 102; // 服务器主动结束战斗通知

        /* macros in macrogroup CSMiniMapEvent */
        public const int MINIMAPEVENT_NONE = 0;
        public const int MINIMAPEVENT_STICKTOGETHER = 1; // 集合
        public const int MINIMAPEVENT_WITHDRAW = 2; // 撤退
        public const int MINIMAPEVENT_ATTACK = 3; // 进攻

        /* macros in macrogroup GameReStartState */
        public const int GAMERESTARTSTATE_NONE = 0; // 未重连
        public const int GAMERESTARTSTATE_SYNC = 1; // 同步中
        public const int GAMERESTARTSTATE_QUEUED = 2; // 排队中

}

}
