/* This file is generated by tdr. */
/* No manual modification is permitted. */

/* metalib version: 1 */
/* metalib md5sum: 531d5b4a397ad5b3c0fbfb5cc8059e55 */

/* creation time: Fri Apr 28 09:43:20 2023 */
/* tdr version: 2.5.0, build at 20111124 */


namespace MobaResDBMeta
{


public class MetaLib
{
        public static int getVersion()
        {
                return 1;
        }

        public static string getName()
        {
                return "MobaResDBMeta";
        }

        public static string getMd5Sum()
        {
                return "531d5b4a397ad5b3c0fbfb5cc8059e55";
        }

        public static string getTdrVersion()
        {
                return "2.5.0, build at 20111124";
        }
}


}
