/* This file is generated by tdr. */
/* No manual modification is permitted. */

/* metalib version: 1 */
/* metalib md5sum: 0fb322fb7d0670d0d2485340276272fa */

/* creation time: Fri Apr 28 09:43:21 2023 */
/* tdr version: 2.5.0, build at 20111124 */

namespace MobaConfigDBMeta
{

public class  MobaConfigDBMetaMacros
{
        public const int RES_PVPCONFIG_MAX_PATHPOINT_LEN = 18; // 最大路径点
        public const int RES_PVPCONFIG_MAX_PATHLIST_LEN = 12; // 最大路径个数
        public const int RES_PVPCONFIG_MAX_GROUP_LEN = 36; // 中立最大怪物组长度
        public const int RES_PVPCONFIG_MAX_PLAYERGROUP_LEN = 12; // 玩家最大怪物组长度
        public const int RES_PVPCONFIG_MAX_BATCH_LEN = 8; // 最大批长度
        public const int RES_PVPCONFIG_MAX_RACE_LEN = 6; // 种族最大长度
        public const int RES_PVPCONFIG_MAX_RACERITH_LEN = 8; // 最大玩家出生点数目
        public const int RES_PVPCONFIG_MAX_EVENT_LEN = 4; // 刷怪事件最大长度
        public const int RES_PVPCONFIG_GOLDMINE_MAX_NUM = 16; // 金矿最大长度
        public const int RES_PVPCONFIG_MAX_BUILDTOWERPOS_LEN = 2; // 分矿造塔点最大长度
        public const int RES_PVPCONFIG_MAX_MAPAREA_LEN = 6; // 区域最大长度
        public const int RES_PVPCONFIG_MAX_ARETRANSFER_LEN = 4; // 区域传送点最大长度
        public const int RES_PVPCONFIG_DROPITEMCONDTION_NUM = 5; // 掉落栏最大条件个数
        public const int RES_PVPCONFIG_DROPITEM_NUM = 3; // 掉落栏最大个数

        /* macros in macrogroup MobaSpawnType */
        public const int SPAWN_TYPE_ONCE = 0;
        public const int SPAWN_TYPE_TIME = 1;
        public const int SPAWN_TYPE_DEAD = 2;
        public const int SPAWN_TYPE_EVENTTRIG = 3;

        /* macros in macrogroup GroupDescType */
        public const int GROUPDESCTYPE_MONSTER = 1; // 野怪描述类型
        public const int GROUPDESCTYPE_GOLDMINE = 2; // 金矿描述类型
        public const int GROUPDESCTYPE_BASE = 3; // 基地描述类型
        public const int GROUPDESCTYPE_SUBBASE = 4; // 副基地描述类型
        public const int GROUPDESCTYPE_SPRING = 5; // 中立泉水描述类型
        public const int GROUPDESCTYPE_BASEREHP = 6; // 基地恢复符描述类型

        /* macros in macrogroup GroupMonsterHardLevel */
        public const int GROUPMONSTERHARDLEVEL_LEVEL0 = 0; // 1级难度
        public const int GROUPMONSTERHARDLEVEL_LEVEL1 = 1; // 2级难度
        public const int GROUPMONSTERHARDLEVEL_LEVEL2 = 2; // 3级难度
        public const int GROUPMONSTERHARDLEVEL_LEVEL3 = 3; // 4级难度,小龙
        public const int GROUPMONSTERHARDLEVEL_LEVEL4 = 4; // 5级难度,大龙

        /* macros in macrogroup GoldMineType */
        public const int GOLDMINETYPE_BASE = 0; // 基地金矿
        public const int GOLDMINETYPE_NEUTRALMAINLAND = 1; // 中立金矿
        public const int GOLDMINETYPE_NEUTRALISLAND = 2; // 中立岛矿

        /* macros in macrogroup SpawnItemDropsType */
        public const int ITEMDROPSTYPE_NONE = 0; // 无掉落
        public const int ITEMDROPSTYPE_FIXEDONE = 1; // 固定掉落
        public const int ITEMDROPSTYPE_RANDOM = 2; // 随机掉落

        /* macros in macrogroup MapPlayerControlType */
        public const int MAPPLAYERCONTROLTYPE_NONE = 0; // 无
        public const int MAPPLAYERCONTROLTYPE_PLAYER = 1; // 玩家
        public const int MAPPLAYERCONTROLTYPE_AI = 2; // 电脑
        public const int MAPPLAYERCONTROLTYPE_NEUTRAL = 3; // 中立

        /* macros in macrogroup MapAreaType */
        public const int ARAETYPE_MAIN = 0; // 主区域
        public const int ARAETYPE_ISLAND = 1; // 子区域

        /* macros in macrogroup PvpSpawnEventType */
        public const int PVP_SPAWN_ONE_GROUP_DIE = 1; // 指定的一组怪死亡
        public const int PVP_SPAWN_SELF_GROUP_DIE = 2; // 本组怪全部死亡
        public const int PVE_SPAWN_SKILSEQ_DIE = 3; // 指定的序号怪死亡
        public const int PVE_SPAWN_TIMEDIFF = 4; // 固定时间比较
        public const int PVE_SPAWN_TIMELOOPDIFF = 5; // 循环时间比较
        public const int PVP_SPAWN_ONE_GROUP_NOTDIE = 6; // 指定一组怪未全部死亡
        public const int PVP_SPAWN_ACTOR_SPAWN = 7; // 单位出生
        public const int PVP_SPAWN_ACTOR_DEAD = 8; // 单位死亡

        /* macros in macrogroup PvPSpawnTrigEventType */
        public const int PVE_SPAWN_TRIG_CGDIALOG = 1;
        public const int PVE_SPAWN_TRIG_SAYAWORD = 2;
        public const int PVE_SPAWN_TRIG_SHOW_SCENEEFFECT = 3;
        public const int PVE_SPAWN_TRIG_HIDE_SCENEEFFECT = 4;
        public const int PVE_SPAWN_TRIG_MOVECAMERA = 5;

}

}
