/* This file is generated by tdr. */
/* No manual modification is permitted. */

/* metalib version: 1 */
/* metalib md5sum: 531d5b4a397ad5b3c0fbfb5cc8059e55 */

/* creation time: Fri Apr 28 09:43:20 2023 */
/* tdr version: 2.5.0, build at 20111124 */

namespace MobaResDBMeta
{

public class  MobaResDBMetaMacros
{
        public const int MAX_NAME_LEN = 64; // 名称最大长度
        public const int MAX_ICON_NAME_LEN = 64; // 图标最大长度
        public const int MAX_DESC_LEN = 256; // 描述最大长度
        public const int MAX_DESC_LONGLEN = 512; // 描述最大长度
        public const int MAX_RES_PATH_LEN = 128; // 资源路径长度
        public const int MAX_RES_PATH_SHORTLEN = 64; // 资源路径短长度
        public const int MAX_DATE_LEN = 32; // 日期时间长度
        public const int MAX_MAIL_TITLE_LEN = 64; // 邮件标题最大长度
        public const int MAX_MAIL_BODY_LEN = 256; // 邮件正文最大长度
        public const int MAX_SERVER_PARAM_LEN = 512; // 服务器参数最大长度
        public const int RES_GENS_NORMALSKILL_CNT = 3; // 英雄普通攻击技能数
        public const int RES_GENS_SKILL_CNT = 8; // 英雄初始技能数
        public const int RES_GENS_TALENTSKILL_CNT = 3; // 英雄天赋技能个数
        public const int RES_GENS_SUMMONERSKILL_CNT = 3; // 英雄召唤师技能个数
        public const int RES_GENS_AVATARSKILL_CNT = 4; // 英雄变体技能个数
        public const int RES_GENS_HIDDENSKILL_CNT = 4; // 英雄隐藏技能个数
        public const int RES_GENS_DYNASKILL_CNT = 2; // 英雄动态技能个数
        public const int RES_GENS_SKILLLEVELUP_CNT = 4; // 英雄技能升级附带关系个数
        public const int BATTLE_GRASS_AREA_NUM = 32; // 战场中草丛的个数
        public const int RES_GENS_HEROSKIN_CNT = 6; // 英雄皮肤的个数
        public const int RES_MONSTERAITARGET_CNT = 3; // AI优先目标类型最大个数
        public const int BATTLE_ACTOR_EQUIP_NUM = 6; // 角色身上的装备最大数目
        public const int RANK_SEASON_AWARD_COUNT = 2; // 排位赛赛季奖励道具最大数目
        public const int RES_MONSTERDEADEENT_PARAM_CNT = 4; // 怪物死亡事件最大参数个数
        public const int RES_MONSTERDEADEENT_CNT = 2; // 怪物死亡事件最大个数
        public const int RES_MONSTESKINMAX_CNT = 2; // 怪物皮肤最大个数
        public const int RES_MAX_MOVESPEED_CONSTVAL = 80000; // 移动速度参考值
        public const int RES_MAX_BUFFATTR_CNT = 8; // BUFF属性最大个数
        public const int RES_MAX_INHERITED_PARENTATTR_CNT = 4; // 最大继承父属性个数
        public const int RES_MAX_INHERITED_PARENTATTRADD_CNT = 4; // 最大继承父属性转换属性个数
        public const int RES_MAX_INHERITED_PARENTLVATTRADD_CNT = 4; // 等级继承属性个数
        public const int RES_MAX_AVATAR_SKIN_CNT = 4; // 变身皮肤组最大个数
        public const int RES_MAX_SKILLPOINTAREA_LEN = 4; // 技能指向区域参数最大个数
        public const int RES_MAX_SKILLATTACKROLLBUFF_LEN = 4; // 技能前摇效果参数最大个数
        public const int RES_MAX_SKILLPHASEMAX_LEN = 6; // 技能阶段最大个数
        public const int RES_MAX_SKILLTRIGCAST_LEN = 4; // 技能触发释放参数最大个数
        public const int RES_MAX_SKILLCOST_LEN = 2; // 技能消耗最大个数
        public const int RES_MAX_SKILLPASSIVEBUFF_LEN = 3; // 技能被动Buff最大个数
        public const int RES_MAX_SKILLTARGETFILTER_LEN = 2; // 技能目标筛选条件最大个数
        public const int RES_MAX_SKILLTARGETCULLPARAM_LEN = 2; // 技能目标状态排除条件参数最大个数
        public const int RES_MAX_SKILLEFFECTCONDTIONPARAM_LEN = 4; // 技能效果触发条件参数最大个数
        public const int RES_MAX_SKILLEFFECTAREAPARAM_LEN = 4; // 技能效果区域参数最大个数
        public const int RES_MAX_SKILLEFFECTPARAM_LEN = 5; // 技能效果附加参数最大个数
        public const int RES_MAX_SKILLEFFECTDAMAGEPARAM_LEN = 5; // 技能伤害系统最大参数个数
        public const int RES_MAX_SKILLPHASESKILLEFFECT_LEN = 3; // 技能阶段技能效果最大参数
        public const int RES_BUFFEFFECT_LEN = 4; // BUFFEFFECT效果个数
        public const int RES_BUFF_EFFECTPARAM_CNT = 5; // BUFF效果最大参数
        public const int RES_BUFF_TRIGCONDPARAM_CNT = 4; // BUFF生效条件参数个数
        public const int RES_BUFF_EVENTP_CNT = 2; // BUFF事件个数
        public const int RES_BUFF_EVENTPARAM_CNT = 4; // BUFF事件参数个数
        public const int RES_MAX_BUFFEFFECTCOREPARAM_LEN = 4; // BUFF效果作用参数个数
        public const int RES_MOBALEVELUP_LEVEL_MAX = 10; // 英雄最大等级
        public const int RES_KILLHERO_CNT_MAX = 5; // 击杀英雄连杀计数
        public const int RES_LEGIONHERO_CNT_MAX = 3; // 最大盟军英雄个数
        public const int RES_MOBAPROFIT_CNT = 5; // Moba战斗经验经验金钱奖励个数
        public const int RES_MOBAATTRUP_TYPE_CNT = 4; // Moba属性成长最大属性个数
        public const int RES_MOBAATTRUP_TYPEPARAM_CNT = 2; // Moba属性成长最大属性参数个数
        public const int RES_REPAIR_TYPE_CNT = 2; // 维修费类型最大个数
        public const int RES_REPAIR_TYPE_PARAM_CNT = 2; // 维修费类型最大参数个数
        public const int RES_MOBASKILLLEVEL_Q_MAX = 4; // 技能栏Q技能最大等级
        public const int RES_MOBASKILLLEVEL_W_MAX = 4; // 技能栏W技能最大等级
        public const int RES_MOBASKILLLEVEL_E_MAX = 4; // 技能栏E技能最大等级
        public const int RES_MOBASKILLLEVEL_R_MAX = 2; // 技能栏R技能最大等级
        public const int RES_MOBASKILLLEVEL_TALENT_MAX = 4; // 技能栏天赋技能最大等级
        public const int RES_MOBASKILLFIELD_SHAPEPARAM_CNT = 2; // 法术场形状参数个数
        public const int RES_MOBASKILLFIELD_OFFSET_CNT = 2; // 法术场偏移参数个数
        public const int RES_MOBASKILLFIELD_TRIGGERPARAM_CNT = 3; // 法术场触发参数个数
        public const int RES_MOBASKILLFIELD_TRIGGEREFFECT_CNT = 2; // 法术场触发效果个数
        public const int RES_MOBASKILLFIELD_TARGETFILTER_CNT = 2; // 法术场作用对象筛选参数个数
        public const int RES_MOBASKILLFIELD_SHAPECHANGEPARAM_CNT = 2; // 法术场形状变化参数个数
        public const int RES_SKILLFIELD_REMOVEEVENT_CNT = 2; // 法术场形被移除事件个数
        public const int RES_SKILLFIELD_REMOVEEVENTPARAM_CNT = 2; // 法术场形被移除参数个数
        public const int RES_AUDIO_EFFECT_MAX = 11; // 音效数目
        public const int RES_BATTLESETTING_PARAM_MAX = 4; // 战场设置表参数最大长度
        public const int RES_CONSTURCTACTOR_LISTCNT_MAX = 10; // 建造单位队列最大长度
        public const int TECH_LEVEL_REC_MAX = 2; // 推荐建造最大个数
        public const int TECH_REC_SCENE_MAX = 6; // 推荐人口科技场景最大个数
        public const int TECH_UNLOCK_ATTR_NUM = 2; // 解锁属性效果数量
        public const int TECH_MAX_EFFECT_COUNT = 2; // 科技效果最大数量
        public const int TECH_MAX_EFFECT_PARAM_COUNT = 4; // 科技效果参数最大数量
        public const int TECH_MAX_TEAM_EFFECT_COUNT = 2; // 团队科技效果最大数量
        public const int TECH_MAX_BASELEVUP_FINISHEDEFFECT_COUNT = 20; // 基地升级科技完成效果最大数量
        public const int TECH_MAX_BASELEVUP_UNLOCKEFFECT_COUNT = 8; // 基地升级科技解锁效果最大数量
        public const int RES_GOODSITEMBAG_NUM_MAX = 99; // 物品道具背包最大个数
        public const int RES_GOODSAUTOPICK_PARAMNUM_MAX = 2; // 道具拾取类型参数个数
        public const int RES_ITEMEFFECT_NUM_MAX = 2; // 道具效果最大个数
        public const int RES_ITEMEFFECT_PARAMNUM_MAX = 2; // 道具效果类型参数最大个数
        public const int RES_RACESKILL_TALENT_MAX = 4; // 种族天赋技能最大个数
        public const int RES_RACESKILL_SPY_MAX = 2; // 种族扎侦查技能最大个数
        public const int EQUIP_ATTREFFECT_NUM = 4; // 装备属性效果数量
        public const int EQUIP_SKILLEFFECT_NUM = 2; // 装备被动技能数量
        public const int EQUIP_BUFF_NUM = 3; // 装备被动buff数量
        public const int RES_BUILDAI_PARAM_CNT = 2; // 建造AI参数个数
        public const int RES_BUILDAI_COND_CNT = 4; // 建造AI条件个数
        public const int RES_BUILDAI_COND_PARAM_CNT = 6; // 建造AI条件参数个数
        public const int RES_BUILDAI_TARGET_CNT = 2; // 建造AI条件目标个数
        public const int RES_TEAMAI_RETREATCOND_CNT = 4; // 战斗AI撤退条件个数
        public const int RES_SYSTEMITEMEFFECT_NUM_MAX = 2; // 道具效果最大个数
        public const int RES_SYSTEMITEMEFFECT_PARAMNUM_MAX = 6; // 道具效果类型参数最大个数
        public const int RES_SYSTEMTASKREWARD_NUM_MAX = 3; // 任务奖励最大数目
        public const int RES_SYSTEMNEEDPARAM_NUM_MAX = 3; // 行为需求最大参数
        public const int RES_SYSTEMTASKNUM_NUM_MAX = 8; // 任务随机组ID最大数目
        public const int RES_SYSTEMSUMMONREWARD_NUM_MAX = 3; // 召唤师等级经验奖励个数
        public const int RES_SYSTEMLEVELUNLOCK_NUM_MAX = 3; // 召唤师等级解锁内容个数
        public const int RES_SYSTEMARENALOCKDOGFACE_NUM_MAX = 16; // 竞技场解锁兵种个数
        public const int RES_SYSTEMHEROSKINDESC_NUM_MAX = 2; // 皮肤描述最大数目
        public const int RES_SYSTEMHEROSKINLINKMONSTERSKIN_NUM_MAX = 4; // 英雄皮肤映射怪物皮肤最大数目
        public const int RES_GUIDEBATTLETASKPARAM_NUM_MAX = 2; // 新手战斗任务激活和完成最大参数
        public const int RES_GUIDEBATTLETASKCOMPLETE_NUM_MAX = 2; // 新手战斗任务完成最大个数
        public const int RES_GUIDEBATTLESTORYPAGE_NUM_MAX = 3; // 新手剧情对话页最大个数
        public const int RES_SYSTEMPARAMTERVALUENUM_NUM_MAX = 5; // 参数值最大数目
        public const int RES_SYSTEMVSMODEMAP_NUM_MAX = 4; // 对战地图分配最大数目
        public const int RES_SYSTEMMATCHOPENTIME_NUM_MAX = 4; // 赛事开放时间表最大数目
        public const int RES_SYSTEMRANKSCORESEQ_NUM_MAX = 3; // 排位赛积分排名个数
        public const int RES_SYSTEMRANKSCOREWINSTREAT_NUM_MAX = 5; // 排位赛积分连胜个数
        public const int RES_SYSTEWARGAMETIMEOUTQUEUE_NUM_MAX = 2; // 温暖局排队列队数目
        public const int RES_SYSTEACTIVECODEPACKAGEITEM_NUM_MAX = 4; // 激活码礼包表物品数目
        public const int RES_SYSTEMPACKAGEITEM_NUM_MAX = 10; // 系统礼包表奖励数目
        public const int RES_SYSTEMPACKAGEITEM_RANDOM_GROUP_MAX = 4; // 系统礼包表随机组数目
        public const int RES_SYSTEACHIEVEMENTLEVEL_NUM_MAX = 2; // 成就等级奖励数目
        public const int RES_MONTHCARD_REWARD_NUM_MAX = 3; // 任务奖励最大数目
        public const int RES_SYSTEMWARGAMEQUEUE_TIMEOUT_NUM_MAX = 2; // 温暖局队列配置超时数目
        public const int RES_MAX_AICANUSERACEMAX_LEN = 4; // AI可选种族最大数
        public const int RES_SYSTEMACHIVEMENTPHASE_REWARD_NUM_MAX = 2; // 成就阶段奖励最大数目
        public const int RES_SYSTEMACHIVEMENTPHASE_PHASE_NUM_MAX = 5; // 成就列表阶段最大数目
        public const int RES_WEEK_FREE_HERO_MAX = 8; // 限免英雄最大数量
        public const int RES_SHOP_BUY_WAY_MAX = 2; // 商城购买方式最大数量
        public const int RES_HOTREPLAYS_VIEW_MAX = 5; // 观看与点赞最大最大数量
        public const int RES_SYSTEMLOTTERY_VIEWITEMCNT = 10; // 系统抽奖奖励显示数目
        public const int RES_SYSTEMLOTTERY_GROUPCNT = 5; // 系统抽奖奖品组数目
        public const int RES_SYSTEMLOTTERY_GROUPITEMCNT = 20; // 系统抽奖奖品组奖品数目
        public const int RES_ACTIVITY_DURATION_PARAMCNT = 3; // 活动时间参数个数
        public const int RES_ACTIVITY_QUEST_REWARDCNT = 4; // 活动任务奖励个数
        public const int RES_ACTIVITY_COUNTER_PARAMCNT = 2; // 活动任务目标参数个数
        public const int RES_RANDOM_ATTRIBUTE_COUNT = 7; // 随机属性数组长度
        public const int RES_CONSUME_MONNEY_COUNT = 2; // 消耗货币数组长度
        public const int RES_HERO_RUNE_RECOMMEND_COUNT = 15; // 英雄战旗推荐长度
        public const int RES_RACE_RUNE_RECOMMEND_COUNT = 15; // 种族战旗推荐长度
        public const int RES_UNLOCK_RUNE_PAGE_MONNEY_COUNT = 1; // 消耗货币数组长度
        public const int RES_SKIN_ITEM_COUNT = 6; // 大厅宝箱皮肤体验数量

}

}
