/* This file is generated by tdr. */
/* No manual modification is permitted. */

/* metalib version: 1 */
/* metalib md5sum: 0fb322fb7d0670d0d2485340276272fa */

/* creation time: Fri Apr 28 09:43:21 2023 */
/* tdr version: 2.5.0, build at 20111124 */


namespace MobaConfigDBMeta
{


public class MetaLib
{
        public static int getVersion()
        {
                return 1;
        }

        public static string getName()
        {
                return "MobaConfigDBMeta";
        }

        public static string getMd5Sum()
        {
                return "0fb322fb7d0670d0d2485340276272fa";
        }

        public static string getTdrVersion()
        {
                return "2.5.0, build at 20111124";
        }
}


}
