/* This file is generated by tdr. */
/* No manual modification is permitted. */

/* metalib version: 1 */
/* metalib md5sum: 0fb322fb7d0670d0d2485340276272fa */

/* creation time: Fri Apr 28 11:11:00 2023 */
/* tdr version: 2.5.0, build at 20111124 */

#ifndef _Ds_Config_h_
#define _Ds_Config_h_

#include "TdrBuf.h"
#include "TdrError.h"
#include "TdrBufUtil.h"
#include "TdrTypeUtil.h"


using tsf4g_tdr::TdrError;
using tsf4g_tdr::TdrReadBuf;
using tsf4g_tdr::TdrWriteBuf;

namespace MobaConfigDBMeta
{


enum
{
    RES_PVPCONFIG_MAX_PATHPOINT_LEN = 18, // 最大路径点
    RES_PVPCONFIG_MAX_PATHLIST_LEN = 12, // 最大路径个数
    RES_PVPCONFIG_MAX_GROUP_LEN = 36, // 中立最大怪物组长度
    RES_PVPCONFIG_MAX_PLAYERGROUP_LEN = 12, // 玩家最大怪物组长度
    RES_PVPCONFIG_MAX_BATCH_LEN = 8, // 最大批长度
    RES_PVPCONFIG_MAX_RACE_LEN = 6, // 种族最大长度
    RES_PVPCONFIG_MAX_RACERITH_LEN = 8, // 最大玩家出生点数目
    RES_PVPCONFIG_MAX_EVENT_LEN = 4, // 刷怪事件最大长度
    RES_PVPCONFIG_GOLDMINE_MAX_NUM = 16, // 金矿最大长度
    RES_PVPCONFIG_MAX_BUILDTOWERPOS_LEN = 2, // 分矿造塔点最大长度
    RES_PVPCONFIG_MAX_MAPAREA_LEN = 6, // 区域最大长度
    RES_PVPCONFIG_MAX_ARETRANSFER_LEN = 4, // 区域传送点最大长度
    RES_PVPCONFIG_DROPITEMCONDTION_NUM = 5, // 掉落栏最大条件个数
    RES_PVPCONFIG_DROPITEM_NUM = 3, // 掉落栏最大个数
};


enum MobaSpawnType // 刷新类型
{
    SPAWN_TYPE_ONCE = 0,
    SPAWN_TYPE_TIME = 1,
    SPAWN_TYPE_DEAD = 2,
    SPAWN_TYPE_EVENTTRIG = 3,
};
enum GroupDescType // 怪物组描述类型
{
    GROUPDESCTYPE_MONSTER = 1, // 野怪描述类型
    GROUPDESCTYPE_GOLDMINE = 2, // 金矿描述类型
    GROUPDESCTYPE_BASE = 3, // 基地描述类型
    GROUPDESCTYPE_SUBBASE = 4, // 副基地描述类型
    GROUPDESCTYPE_SPRING = 5, // 中立泉水描述类型
    GROUPDESCTYPE_BASEREHP = 6, // 基地恢复符描述类型
};
enum GroupMonsterHardLevel // 怪物组难度等级
{
    GROUPMONSTERHARDLEVEL_LEVEL0 = 0, // 1级难度
    GROUPMONSTERHARDLEVEL_LEVEL1 = 1, // 2级难度
    GROUPMONSTERHARDLEVEL_LEVEL2 = 2, // 3级难度
    GROUPMONSTERHARDLEVEL_LEVEL3 = 3, // 4级难度,小龙
    GROUPMONSTERHARDLEVEL_LEVEL4 = 4, // 5级难度,大龙
};
enum GoldMineType // 金矿类型
{
    GOLDMINETYPE_BASE = 0, // 基地金矿
    GOLDMINETYPE_NEUTRALMAINLAND = 1, // 中立金矿
    GOLDMINETYPE_NEUTRALISLAND = 2, // 中立岛矿
};
enum SpawnItemDropsType // 怪物掉落类型
{
    ITEMDROPSTYPE_NONE = 0, // 无掉落
    ITEMDROPSTYPE_FIXEDONE = 1, // 固定掉落
    ITEMDROPSTYPE_RANDOM = 2, // 随机掉落
};
enum MapPlayerControlType // 玩家控制者类型
{
    MAPPLAYERCONTROLTYPE_NONE = 0, // 无
    MAPPLAYERCONTROLTYPE_PLAYER = 1, // 玩家
    MAPPLAYERCONTROLTYPE_AI = 2, // 电脑
    MAPPLAYERCONTROLTYPE_NEUTRAL = 3, // 中立
};
enum MapAreaType // 地图区域类型
{
    ARAETYPE_MAIN = 0, // 主区域
    ARAETYPE_ISLAND = 1, // 子区域
};
enum PvpSpawnEventType // PVP触发事件类型
{
    PVP_SPAWN_ONE_GROUP_DIE = 1, // 指定的一组怪死亡
    PVP_SPAWN_SELF_GROUP_DIE = 2, // 本组怪全部死亡
    PVE_SPAWN_SKILSEQ_DIE = 3, // 指定的序号怪死亡
    PVE_SPAWN_TIMEDIFF = 4, // 固定时间比较
    PVE_SPAWN_TIMELOOPDIFF = 5, // 循环时间比较
    PVP_SPAWN_ONE_GROUP_NOTDIE = 6, // 指定一组怪未全部死亡
    PVP_SPAWN_ACTOR_SPAWN = 7, // 单位出生
    PVP_SPAWN_ACTOR_DEAD = 8, // 单位死亡
};
enum PvPSpawnTrigEventType // PVP处理事件类型
{
    PVE_SPAWN_TRIG_CGDIALOG = 1,
    PVE_SPAWN_TRIG_SAYAWORD = 2,
    PVE_SPAWN_TRIG_SHOW_SCENEEFFECT = 3,
    PVE_SPAWN_TRIG_HIDE_SCENEEFFECT = 4,
    PVE_SPAWN_TRIG_MOVECAMERA = 5,
};


#pragma pack(1)


class PvpSpawnEventCfg
{
    public: /* members */
        int32_t EventID; // 事件ID
        int32_t Param1; // 参数1
        int32_t Param2; // 参数2
        int32_t Param3; // 参数3
        int32_t Param4; // 参数4

    public: /* methods */
        TdrError::ErrorType construct();

        TdrError::ErrorType pack(TdrWriteBuf& destBuf, unsigned cutVer = 0) const;
        TdrError::ErrorType pack(char* buffer, size_t size, size_t* usedSize = NULL, unsigned cutVer = 0) const;

        TdrError::ErrorType unpack(TdrReadBuf& srcBuf, unsigned cutVer = 0);
        TdrError::ErrorType unpack(const char* buffer, size_t size, size_t* usedSize = NULL, unsigned cutVer = 0);

        /* set indent = -1 to disable indent */
        TdrError::ErrorType visualize(TdrWriteBuf& destBuf, int indent = 0, char separator = '\n') const;
        TdrError::ErrorType visualize(char* buffer, size_t size, size_t* usedSize = NULL,
                                      int indent = 0, char separator = '\n') const;
        const char* visualize_ex(TdrWriteBuf& destBuf, int indent = 0, char separator = '\n') const;
        const char* visualize_ex(char* buffer, size_t size, size_t* usedSize = NULL,
                                 int indent = 0, char separator = '\n') const;


    public: /* version infomation */
        enum
        {
            BASEVERSION = 1,
            CURRVERSION = 1,
        };
};

typedef       PvpSpawnEventCfg          tagPvpSpawnEventCfg;
typedef       PvpSpawnEventCfg             PVPSPAWNEVENTCFG;
typedef       PvpSpawnEventCfg*          LPPVPSPAWNEVENTCFG;
typedef const PvpSpawnEventCfg*         LCPPVPSPAWNEVENTCFG;


class MobaVector3
{
    public: /* members */
        int32_t X; // X分量
        int32_t Y; // Y分量
        int32_t Z; // Z分量

    public: /* methods */
        TdrError::ErrorType construct();

        TdrError::ErrorType pack(TdrWriteBuf& destBuf, unsigned cutVer = 0) const;
        TdrError::ErrorType pack(char* buffer, size_t size, size_t* usedSize = NULL, unsigned cutVer = 0) const;

        TdrError::ErrorType unpack(TdrReadBuf& srcBuf, unsigned cutVer = 0);
        TdrError::ErrorType unpack(const char* buffer, size_t size, size_t* usedSize = NULL, unsigned cutVer = 0);

        /* set indent = -1 to disable indent */
        TdrError::ErrorType visualize(TdrWriteBuf& destBuf, int indent = 0, char separator = '\n') const;
        TdrError::ErrorType visualize(char* buffer, size_t size, size_t* usedSize = NULL,
                                      int indent = 0, char separator = '\n') const;
        const char* visualize_ex(TdrWriteBuf& destBuf, int indent = 0, char separator = '\n') const;
        const char* visualize_ex(char* buffer, size_t size, size_t* usedSize = NULL,
                                 int indent = 0, char separator = '\n') const;


    public: /* version infomation */
        enum
        {
            BASEVERSION = 1,
            CURRVERSION = 1,
        };
};

typedef       MobaVector3          tagMobaVector3;
typedef       MobaVector3             MOBAVECTOR3;
typedef       MobaVector3*          LPMOBAVECTOR3;
typedef const MobaVector3*         LCPMOBAVECTOR3;


class PathConfig
{
    public: /* members */
        int32_t ID; // ID
        int32_t PositionCnt; // 路径点数目
        MobaVector3 PositionList[RES_PVPCONFIG_MAX_PATHPOINT_LEN]; // 路径点列表

    public: /* methods */
        TdrError::ErrorType construct();

        TdrError::ErrorType pack(TdrWriteBuf& destBuf, unsigned cutVer = 0) const;
        TdrError::ErrorType pack(char* buffer, size_t size, size_t* usedSize = NULL, unsigned cutVer = 0) const;

        TdrError::ErrorType unpack(TdrReadBuf& srcBuf, unsigned cutVer = 0);
        TdrError::ErrorType unpack(const char* buffer, size_t size, size_t* usedSize = NULL, unsigned cutVer = 0);

        /* set indent = -1 to disable indent */
        TdrError::ErrorType visualize(TdrWriteBuf& destBuf, int indent = 0, char separator = '\n') const;
        TdrError::ErrorType visualize(char* buffer, size_t size, size_t* usedSize = NULL,
                                      int indent = 0, char separator = '\n') const;
        const char* visualize_ex(TdrWriteBuf& destBuf, int indent = 0, char separator = '\n') const;
        const char* visualize_ex(char* buffer, size_t size, size_t* usedSize = NULL,
                                 int indent = 0, char separator = '\n') const;


    public: /* version infomation */
        enum
        {
            BASEVERSION = 1,
            CURRVERSION = 1,
        };
};

typedef       PathConfig          tagPathConfig;
typedef       PathConfig             PATHCONFIG;
typedef       PathConfig*          LPPATHCONFIG;
typedef const PathConfig*         LCPPATHCONFIG;


class ItemDropsOneCond // 掉落条件
{
    public: /* members */
        int32_t Random; // 掉落概率
        int8_t DropType; // 掉落类型
        int32_t FixedItemResID; // 固定掉落物品ID
        int8_t RandomItemLv; // 随机掉落物品等级,0表示任意
        int8_t RandomItemType; // 随机掉落物品类型

    public: /* methods */
        TdrError::ErrorType construct();

        TdrError::ErrorType pack(TdrWriteBuf& destBuf, unsigned cutVer = 0) const;
        TdrError::ErrorType pack(char* buffer, size_t size, size_t* usedSize = NULL, unsigned cutVer = 0) const;

        TdrError::ErrorType unpack(TdrReadBuf& srcBuf, unsigned cutVer = 0);
        TdrError::ErrorType unpack(const char* buffer, size_t size, size_t* usedSize = NULL, unsigned cutVer = 0);

        /* set indent = -1 to disable indent */
        TdrError::ErrorType visualize(TdrWriteBuf& destBuf, int indent = 0, char separator = '\n') const;
        TdrError::ErrorType visualize(char* buffer, size_t size, size_t* usedSize = NULL,
                                      int indent = 0, char separator = '\n') const;
        const char* visualize_ex(TdrWriteBuf& destBuf, int indent = 0, char separator = '\n') const;
        const char* visualize_ex(char* buffer, size_t size, size_t* usedSize = NULL,
                                 int indent = 0, char separator = '\n') const;


    public: /* version infomation */
        enum
        {
            BASEVERSION = 1,
            CURRVERSION = 1,
        };
};

typedef       ItemDropsOneCond          tagItemDropsOneCond;
typedef       ItemDropsOneCond             ITEMDROPSONECOND;
typedef       ItemDropsOneCond*          LPITEMDROPSONECOND;
typedef const ItemDropsOneCond*         LCPITEMDROPSONECOND;


class ItemDropsOneConfig // 单1物品掉落
{
    public: /* members */
        int32_t CondsCnt; // 掉落条件个数
        ItemDropsOneCond ItemDropsConds[RES_PVPCONFIG_DROPITEMCONDTION_NUM]; // 掉落条件

    public: /* methods */
        TdrError::ErrorType construct();

        TdrError::ErrorType pack(TdrWriteBuf& destBuf, unsigned cutVer = 0) const;
        TdrError::ErrorType pack(char* buffer, size_t size, size_t* usedSize = NULL, unsigned cutVer = 0) const;

        TdrError::ErrorType unpack(TdrReadBuf& srcBuf, unsigned cutVer = 0);
        TdrError::ErrorType unpack(const char* buffer, size_t size, size_t* usedSize = NULL, unsigned cutVer = 0);

        /* set indent = -1 to disable indent */
        TdrError::ErrorType visualize(TdrWriteBuf& destBuf, int indent = 0, char separator = '\n') const;
        TdrError::ErrorType visualize(char* buffer, size_t size, size_t* usedSize = NULL,
                                      int indent = 0, char separator = '\n') const;
        const char* visualize_ex(TdrWriteBuf& destBuf, int indent = 0, char separator = '\n') const;
        const char* visualize_ex(char* buffer, size_t size, size_t* usedSize = NULL,
                                 int indent = 0, char separator = '\n') const;


    public: /* version infomation */
        enum
        {
            BASEVERSION = 1,
            CURRVERSION = 1,
        };
};

typedef       ItemDropsOneConfig          tagItemDropsOneConfig;
typedef       ItemDropsOneConfig             ITEMDROPSONECONFIG;
typedef       ItemDropsOneConfig*          LPITEMDROPSONECONFIG;
typedef const ItemDropsOneConfig*         LCPITEMDROPSONECONFIG;


class BatchConfig
{
    public: /* members */
        int32_t DelayTime; // 延迟刷新时间(ms)
        int32_t ResID; // 资源ID
        int8_t UseRaceResID; // 使用种族资源ID 1：是
        int32_t RaceResID[RES_PVPCONFIG_MAX_RACE_LEN]; // 种族资源ID
        MobaVector3 Position; // 刷新位置
        MobaVector3 Rotation; // 旋转角度
        int32_t SpawnPathID; // 出生路径ID
        int32_t ItemDropsCnt; // 掉落栏数目
        ItemDropsOneConfig ItemDropsList[RES_PVPCONFIG_DROPITEM_NUM]; // 掉落栏列表

    public: /* methods */
        TdrError::ErrorType construct();

        TdrError::ErrorType pack(TdrWriteBuf& destBuf, unsigned cutVer = 0) const;
        TdrError::ErrorType pack(char* buffer, size_t size, size_t* usedSize = NULL, unsigned cutVer = 0) const;

        TdrError::ErrorType unpack(TdrReadBuf& srcBuf, unsigned cutVer = 0);
        TdrError::ErrorType unpack(const char* buffer, size_t size, size_t* usedSize = NULL, unsigned cutVer = 0);

        /* set indent = -1 to disable indent */
        TdrError::ErrorType visualize(TdrWriteBuf& destBuf, int indent = 0, char separator = '\n') const;
        TdrError::ErrorType visualize(char* buffer, size_t size, size_t* usedSize = NULL,
                                      int indent = 0, char separator = '\n') const;
        const char* visualize_ex(TdrWriteBuf& destBuf, int indent = 0, char separator = '\n') const;
        const char* visualize_ex(char* buffer, size_t size, size_t* usedSize = NULL,
                                 int indent = 0, char separator = '\n') const;


    public: /* version infomation */
        enum
        {
            BASEVERSION = 1,
            CURRVERSION = 1,
        };
};

typedef       BatchConfig          tagBatchConfig;
typedef       BatchConfig             BATCHCONFIG;
typedef       BatchConfig*          LPBATCHCONFIG;
typedef const BatchConfig*         LCPBATCHCONFIG;


class GroupConfig
{
    public: /* members */
        int8_t GroupType; // 怪物组类型
        int8_t MonsterHardLevel; // 野怪难度
        int32_t BrithTime; // 出生时间（ms）
        MobaVector3 CenterPos; // 中心位置
        int32_t SpawnType; // 刷新类型
        int32_t RefreshInterval; // 刷新间隔(ms,只有循环刷新有效)
        int8_t EventNum; // 刷新条件数量
        PvpSpawnEventCfg EventList[RES_PVPCONFIG_MAX_EVENT_LEN]; // 刷新条件列表
        int8_t BatchCnt; // 批次数目
        BatchConfig BatchList[RES_PVPCONFIG_MAX_BATCH_LEN]; // 批次列表

    public: /* methods */
        TdrError::ErrorType construct();

        TdrError::ErrorType pack(TdrWriteBuf& destBuf, unsigned cutVer = 0) const;
        TdrError::ErrorType pack(char* buffer, size_t size, size_t* usedSize = NULL, unsigned cutVer = 0) const;

        TdrError::ErrorType unpack(TdrReadBuf& srcBuf, unsigned cutVer = 0);
        TdrError::ErrorType unpack(const char* buffer, size_t size, size_t* usedSize = NULL, unsigned cutVer = 0);

        /* set indent = -1 to disable indent */
        TdrError::ErrorType visualize(TdrWriteBuf& destBuf, int indent = 0, char separator = '\n') const;
        TdrError::ErrorType visualize(char* buffer, size_t size, size_t* usedSize = NULL,
                                      int indent = 0, char separator = '\n') const;
        const char* visualize_ex(TdrWriteBuf& destBuf, int indent = 0, char separator = '\n') const;
        const char* visualize_ex(char* buffer, size_t size, size_t* usedSize = NULL,
                                 int indent = 0, char separator = '\n') const;


    public: /* version infomation */
        enum
        {
            BASEVERSION = 1,
            CURRVERSION = 1,
        };
};

typedef       GroupConfig          tagGroupConfig;
typedef       GroupConfig             GROUPCONFIG;
typedef       GroupConfig*          LPGROUPCONFIG;
typedef const GroupConfig*         LCPGROUPCONFIG;


class SpawnTransform
{
    public: /* members */
        MobaVector3 Position; // 位置
        MobaVector3 Rotation; // 旋转角度

    public: /* methods */
        TdrError::ErrorType construct();

        TdrError::ErrorType pack(TdrWriteBuf& destBuf, unsigned cutVer = 0) const;
        TdrError::ErrorType pack(char* buffer, size_t size, size_t* usedSize = NULL, unsigned cutVer = 0) const;

        TdrError::ErrorType unpack(TdrReadBuf& srcBuf, unsigned cutVer = 0);
        TdrError::ErrorType unpack(const char* buffer, size_t size, size_t* usedSize = NULL, unsigned cutVer = 0);

        /* set indent = -1 to disable indent */
        TdrError::ErrorType visualize(TdrWriteBuf& destBuf, int indent = 0, char separator = '\n') const;
        TdrError::ErrorType visualize(char* buffer, size_t size, size_t* usedSize = NULL,
                                      int indent = 0, char separator = '\n') const;
        const char* visualize_ex(TdrWriteBuf& destBuf, int indent = 0, char separator = '\n') const;
        const char* visualize_ex(char* buffer, size_t size, size_t* usedSize = NULL,
                                 int indent = 0, char separator = '\n') const;


    public: /* version infomation */
        enum
        {
            BASEVERSION = 1,
            CURRVERSION = 1,
        };
};

typedef       SpawnTransform          tagSpawnTransform;
typedef       SpawnTransform             SPAWNTRANSFORM;
typedef       SpawnTransform*          LPSPAWNTRANSFORM;
typedef const SpawnTransform*         LCPSPAWNTRANSFORM;


class SpawnTpConfig
{
    public: /* members */
        MobaVector3 MapTPPos; // 回城点
        int32_t RangeRadius; // 随机半径范围

    public: /* methods */
        TdrError::ErrorType construct();

        TdrError::ErrorType pack(TdrWriteBuf& destBuf, unsigned cutVer = 0) const;
        TdrError::ErrorType pack(char* buffer, size_t size, size_t* usedSize = NULL, unsigned cutVer = 0) const;

        TdrError::ErrorType unpack(TdrReadBuf& srcBuf, unsigned cutVer = 0);
        TdrError::ErrorType unpack(const char* buffer, size_t size, size_t* usedSize = NULL, unsigned cutVer = 0);

        /* set indent = -1 to disable indent */
        TdrError::ErrorType visualize(TdrWriteBuf& destBuf, int indent = 0, char separator = '\n') const;
        TdrError::ErrorType visualize(char* buffer, size_t size, size_t* usedSize = NULL,
                                      int indent = 0, char separator = '\n') const;
        const char* visualize_ex(TdrWriteBuf& destBuf, int indent = 0, char separator = '\n') const;
        const char* visualize_ex(char* buffer, size_t size, size_t* usedSize = NULL,
                                 int indent = 0, char separator = '\n') const;


    public: /* version infomation */
        enum
        {
            BASEVERSION = 1,
            CURRVERSION = 1,
        };
};

typedef       SpawnTpConfig          tagSpawnTpConfig;
typedef       SpawnTpConfig             SPAWNTPCONFIG;
typedef       SpawnTpConfig*          LPSPAWNTPCONFIG;
typedef const SpawnTpConfig*         LCPSPAWNTPCONFIG;


class SpawnBuildTowerConfig
{
    public: /* members */
        MobaVector3 BuildTowerPos[RES_PVPCONFIG_MAX_BUILDTOWERPOS_LEN]; // 造塔点

    public: /* methods */
        TdrError::ErrorType construct();

        TdrError::ErrorType pack(TdrWriteBuf& destBuf, unsigned cutVer = 0) const;
        TdrError::ErrorType pack(char* buffer, size_t size, size_t* usedSize = NULL, unsigned cutVer = 0) const;

        TdrError::ErrorType unpack(TdrReadBuf& srcBuf, unsigned cutVer = 0);
        TdrError::ErrorType unpack(const char* buffer, size_t size, size_t* usedSize = NULL, unsigned cutVer = 0);

        /* set indent = -1 to disable indent */
        TdrError::ErrorType visualize(TdrWriteBuf& destBuf, int indent = 0, char separator = '\n') const;
        TdrError::ErrorType visualize(char* buffer, size_t size, size_t* usedSize = NULL,
                                      int indent = 0, char separator = '\n') const;
        const char* visualize_ex(TdrWriteBuf& destBuf, int indent = 0, char separator = '\n') const;
        const char* visualize_ex(char* buffer, size_t size, size_t* usedSize = NULL,
                                 int indent = 0, char separator = '\n') const;


    public: /* version infomation */
        enum
        {
            BASEVERSION = 1,
            CURRVERSION = 1,
        };
};

typedef       SpawnBuildTowerConfig          tagSpawnBuildTowerConfig;
typedef       SpawnBuildTowerConfig             SPAWNBUILDTOWERCONFIG;
typedef       SpawnBuildTowerConfig*          LPSPAWNBUILDTOWERCONFIG;
typedef const SpawnBuildTowerConfig*         LCPSPAWNBUILDTOWERCONFIG;


class GoldMineConfig
{
    public: /* members */
        int8_t Type; // 金矿类型
        int8_t TeamType; // 基地金矿占领方
        int32_t RaceResID[RES_PVPCONFIG_MAX_RACE_LEN]; // 金矿种族资源ID
        SpawnTransform GodMineSpawnTransform; // 金矿出生点
        SpawnTpConfig TpConfig; // 金矿回城点
        SpawnBuildTowerConfig BuildTowerConfig; // 金矿造塔配置
        int32_t GuardGroupID; // 守矿野怪组
        int32_t GoldMineGroupID; // 金矿组ID
        int32_t Interval; // addgold间隔
        int32_t AddGold; // 每次增加的gold
        int32_t MaxGold; // 金币上限

    public: /* methods */
        TdrError::ErrorType construct();

        TdrError::ErrorType pack(TdrWriteBuf& destBuf, unsigned cutVer = 0) const;
        TdrError::ErrorType pack(char* buffer, size_t size, size_t* usedSize = NULL, unsigned cutVer = 0) const;

        TdrError::ErrorType unpack(TdrReadBuf& srcBuf, unsigned cutVer = 0);
        TdrError::ErrorType unpack(const char* buffer, size_t size, size_t* usedSize = NULL, unsigned cutVer = 0);

        /* set indent = -1 to disable indent */
        TdrError::ErrorType visualize(TdrWriteBuf& destBuf, int indent = 0, char separator = '\n') const;
        TdrError::ErrorType visualize(char* buffer, size_t size, size_t* usedSize = NULL,
                                      int indent = 0, char separator = '\n') const;
        const char* visualize_ex(TdrWriteBuf& destBuf, int indent = 0, char separator = '\n') const;
        const char* visualize_ex(char* buffer, size_t size, size_t* usedSize = NULL,
                                 int indent = 0, char separator = '\n') const;


    public: /* version infomation */
        enum
        {
            BASEVERSION = 1,
            CURRVERSION = 1,
        };
};

typedef       GoldMineConfig          tagGoldMineConfig;
typedef       GoldMineConfig             GOLDMINECONFIG;
typedef       GoldMineConfig*          LPGOLDMINECONFIG;
typedef const GoldMineConfig*         LCPGOLDMINECONFIG;


class PlayerBaseRegConfig // 基地区域范围
{
    public: /* members */
        MobaVector3 Position; // 中心点
        int32_t Radius; // 半径

    public: /* methods */
        TdrError::ErrorType construct();

        TdrError::ErrorType pack(TdrWriteBuf& destBuf, unsigned cutVer = 0) const;
        TdrError::ErrorType pack(char* buffer, size_t size, size_t* usedSize = NULL, unsigned cutVer = 0) const;

        TdrError::ErrorType unpack(TdrReadBuf& srcBuf, unsigned cutVer = 0);
        TdrError::ErrorType unpack(const char* buffer, size_t size, size_t* usedSize = NULL, unsigned cutVer = 0);

        /* set indent = -1 to disable indent */
        TdrError::ErrorType visualize(TdrWriteBuf& destBuf, int indent = 0, char separator = '\n') const;
        TdrError::ErrorType visualize(char* buffer, size_t size, size_t* usedSize = NULL,
                                      int indent = 0, char separator = '\n') const;
        const char* visualize_ex(TdrWriteBuf& destBuf, int indent = 0, char separator = '\n') const;
        const char* visualize_ex(char* buffer, size_t size, size_t* usedSize = NULL,
                                 int indent = 0, char separator = '\n') const;


    public: /* version infomation */
        enum
        {
            BASEVERSION = 1,
            CURRVERSION = 1,
        };
};

typedef       PlayerBaseRegConfig          tagPlayerBaseRegConfig;
typedef       PlayerBaseRegConfig             PLAYERBASEREGCONFIG;
typedef       PlayerBaseRegConfig*          LPPLAYERBASEREGCONFIG;
typedef const PlayerBaseRegConfig*         LCPPLAYERBASEREGCONFIG;


class MapPlayerConfig // 玩家属性
{
    public: /* members */
        int8_t TeamType; // 队伍颜色类型
        int8_t IsFixedStartPos; // 是否固定开始点
        int8_t CtrType; // 玩家控制者类型
        SpawnTpConfig TpConfig; // 回城点
        SpawnTransform ActorSpawnTransform; // 单位出生点
        int8_t GoldMineIndex; // 出生占矿索引
        int8_t GourpCnt; // 怪物组数目
        GroupConfig GourpList[RES_PVPCONFIG_MAX_PLAYERGROUP_LEN]; // 怪物组数目
        PlayerBaseRegConfig BaseRegConfig; // 基地区域范围

    public: /* methods */
        TdrError::ErrorType construct();

        TdrError::ErrorType pack(TdrWriteBuf& destBuf, unsigned cutVer = 0) const;
        TdrError::ErrorType pack(char* buffer, size_t size, size_t* usedSize = NULL, unsigned cutVer = 0) const;

        TdrError::ErrorType unpack(TdrReadBuf& srcBuf, unsigned cutVer = 0);
        TdrError::ErrorType unpack(const char* buffer, size_t size, size_t* usedSize = NULL, unsigned cutVer = 0);

        /* set indent = -1 to disable indent */
        TdrError::ErrorType visualize(TdrWriteBuf& destBuf, int indent = 0, char separator = '\n') const;
        TdrError::ErrorType visualize(char* buffer, size_t size, size_t* usedSize = NULL,
                                      int indent = 0, char separator = '\n') const;
        const char* visualize_ex(TdrWriteBuf& destBuf, int indent = 0, char separator = '\n') const;
        const char* visualize_ex(char* buffer, size_t size, size_t* usedSize = NULL,
                                 int indent = 0, char separator = '\n') const;


    public: /* version infomation */
        enum
        {
            BASEVERSION = 1,
            CURRVERSION = 1,
        };
};

typedef       MapPlayerConfig          tagMapPlayerConfig;
typedef       MapPlayerConfig             MAPPLAYERCONFIG;
typedef       MapPlayerConfig*          LPMAPPLAYERCONFIG;
typedef const MapPlayerConfig*         LCPMAPPLAYERCONFIG;


class MapAreaTransferConfig // 地图区域传送门设置
{
    public: /* members */
        int8_t TransferOutAreaID; // 传送目标区域ID
        MobaVector3 TransferInPos; // 传送点入口
        MobaVector3 TransferOutPos; // 传送点出口
        int32_t TransferGroupID; // 传送关联怪物组ID
        int32_t Radius; // 传送区域半径
        int32_t CheckTime; // 传送延迟时间

    public: /* methods */
        TdrError::ErrorType construct();

        TdrError::ErrorType pack(TdrWriteBuf& destBuf, unsigned cutVer = 0) const;
        TdrError::ErrorType pack(char* buffer, size_t size, size_t* usedSize = NULL, unsigned cutVer = 0) const;

        TdrError::ErrorType unpack(TdrReadBuf& srcBuf, unsigned cutVer = 0);
        TdrError::ErrorType unpack(const char* buffer, size_t size, size_t* usedSize = NULL, unsigned cutVer = 0);

        /* set indent = -1 to disable indent */
        TdrError::ErrorType visualize(TdrWriteBuf& destBuf, int indent = 0, char separator = '\n') const;
        TdrError::ErrorType visualize(char* buffer, size_t size, size_t* usedSize = NULL,
                                      int indent = 0, char separator = '\n') const;
        const char* visualize_ex(TdrWriteBuf& destBuf, int indent = 0, char separator = '\n') const;
        const char* visualize_ex(char* buffer, size_t size, size_t* usedSize = NULL,
                                 int indent = 0, char separator = '\n') const;


    public: /* version infomation */
        enum
        {
            BASEVERSION = 1,
            CURRVERSION = 1,
        };
};

typedef       MapAreaTransferConfig          tagMapAreaTransferConfig;
typedef       MapAreaTransferConfig             MAPAREATRANSFERCONFIG;
typedef       MapAreaTransferConfig*          LPMAPAREATRANSFERCONFIG;
typedef const MapAreaTransferConfig*         LCPMAPAREATRANSFERCONFIG;


class MapAreaConfig // 地图区域设置
{
    public: /* members */
        int8_t MapAreaType; // 区域类型
        int8_t AreaID; // 区域ID,0默认主区域
        MobaVector3 CenterPos; // 中心点
        int32_t Radius; // 半径
        int8_t TransferCnt; // 出口传送点数目
        MapAreaTransferConfig Transfers[RES_PVPCONFIG_MAX_ARETRANSFER_LEN]; // 传送点

    public: /* methods */
        TdrError::ErrorType construct();

        TdrError::ErrorType pack(TdrWriteBuf& destBuf, unsigned cutVer = 0) const;
        TdrError::ErrorType pack(char* buffer, size_t size, size_t* usedSize = NULL, unsigned cutVer = 0) const;

        TdrError::ErrorType unpack(TdrReadBuf& srcBuf, unsigned cutVer = 0);
        TdrError::ErrorType unpack(const char* buffer, size_t size, size_t* usedSize = NULL, unsigned cutVer = 0);

        /* set indent = -1 to disable indent */
        TdrError::ErrorType visualize(TdrWriteBuf& destBuf, int indent = 0, char separator = '\n') const;
        TdrError::ErrorType visualize(char* buffer, size_t size, size_t* usedSize = NULL,
                                      int indent = 0, char separator = '\n') const;
        const char* visualize_ex(TdrWriteBuf& destBuf, int indent = 0, char separator = '\n') const;
        const char* visualize_ex(char* buffer, size_t size, size_t* usedSize = NULL,
                                 int indent = 0, char separator = '\n') const;


    public: /* version infomation */
        enum
        {
            BASEVERSION = 1,
            CURRVERSION = 1,
        };
};

typedef       MapAreaConfig          tagMapAreaConfig;
typedef       MapAreaConfig             MAPAREACONFIG;
typedef       MapAreaConfig*          LPMAPAREACONFIG;
typedef const MapAreaConfig*         LCPMAPAREACONFIG;


class MapNeutralConfig // 地图中立配置
{
    public: /* members */
        int8_t GourpCnt; // 怪物组数目
        GroupConfig GourpList[RES_PVPCONFIG_MAX_GROUP_LEN]; // 怪物组数目
        int8_t GoldMineCnt; // 金矿数目
        GoldMineConfig GoldMineList[RES_PVPCONFIG_GOLDMINE_MAX_NUM]; // 金矿列表
        int8_t AreaCnt; // 地图区域个数
        MapAreaConfig AreaConfigs[RES_PVPCONFIG_MAX_MAPAREA_LEN]; // 地图区域个数

    public: /* methods */
        TdrError::ErrorType construct();

        TdrError::ErrorType pack(TdrWriteBuf& destBuf, unsigned cutVer = 0) const;
        TdrError::ErrorType pack(char* buffer, size_t size, size_t* usedSize = NULL, unsigned cutVer = 0) const;

        TdrError::ErrorType unpack(TdrReadBuf& srcBuf, unsigned cutVer = 0);
        TdrError::ErrorType unpack(const char* buffer, size_t size, size_t* usedSize = NULL, unsigned cutVer = 0);

        /* set indent = -1 to disable indent */
        TdrError::ErrorType visualize(TdrWriteBuf& destBuf, int indent = 0, char separator = '\n') const;
        TdrError::ErrorType visualize(char* buffer, size_t size, size_t* usedSize = NULL,
                                      int indent = 0, char separator = '\n') const;
        const char* visualize_ex(TdrWriteBuf& destBuf, int indent = 0, char separator = '\n') const;
        const char* visualize_ex(char* buffer, size_t size, size_t* usedSize = NULL,
                                 int indent = 0, char separator = '\n') const;


    public: /* version infomation */
        enum
        {
            BASEVERSION = 1,
            CURRVERSION = 1,
        };
};

typedef       MapNeutralConfig          tagMapNeutralConfig;
typedef       MapNeutralConfig             MAPNEUTRALCONFIG;
typedef       MapNeutralConfig*          LPMAPNEUTRALCONFIG;
typedef const MapNeutralConfig*         LCPMAPNEUTRALCONFIG;


class MobaPvpConfig
{
    public: /* members */
        int32_t ResID; // ID
        int8_t PathCnt; // 路径数目
        PathConfig PathList[RES_PVPCONFIG_MAX_PATHLIST_LEN]; // 路径列表
        MapNeutralConfig NeutralConfig; // 地图中立配置
        int8_t PlayerNum; // 玩家个数
        MapPlayerConfig PlayerConfigs[RES_PVPCONFIG_MAX_RACERITH_LEN]; // 玩家列表

    public: /* methods */
        TdrError::ErrorType construct();

        TdrError::ErrorType pack(TdrWriteBuf& destBuf, unsigned cutVer = 0) const;
        TdrError::ErrorType pack(char* buffer, size_t size, size_t* usedSize = NULL, unsigned cutVer = 0) const;

        TdrError::ErrorType unpack(TdrReadBuf& srcBuf, unsigned cutVer = 0);
        TdrError::ErrorType unpack(const char* buffer, size_t size, size_t* usedSize = NULL, unsigned cutVer = 0);

        /* set indent = -1 to disable indent */
        TdrError::ErrorType visualize(TdrWriteBuf& destBuf, int indent = 0, char separator = '\n') const;
        TdrError::ErrorType visualize(char* buffer, size_t size, size_t* usedSize = NULL,
                                      int indent = 0, char separator = '\n') const;
        const char* visualize_ex(TdrWriteBuf& destBuf, int indent = 0, char separator = '\n') const;
        const char* visualize_ex(char* buffer, size_t size, size_t* usedSize = NULL,
                                 int indent = 0, char separator = '\n') const;


    public: /* version infomation */
        enum
        {
            BASEVERSION = 1,
            CURRVERSION = 1,
        };
};

typedef       MobaPvpConfig          tagMobaPvpConfig;
typedef       MobaPvpConfig             MOBAPVPCONFIG;
typedef       MobaPvpConfig*          LPMOBAPVPCONFIG;
typedef const MobaPvpConfig*         LCPMOBAPVPCONFIG;


#pragma pack()

}
#endif
