/* This file is generated by tdr. */
/* No manual modification is permitted. */

/* metalib version: 1 */
/* metalib md5sum: 0fb322fb7d0670d0d2485340276272fa */

/* creation time: Fri Apr 28 11:11:00 2023 */
/* tdr version: 2.5.0, build at 20111124 */

#ifndef _MobaConfigDBMeta_metalib_h_
#define _MobaConfigDBMeta_metalib_h_

namespace MobaConfigDBMeta
{


class MetaLib
{
    public:
        static int getVersion()
        {
            return 1;
        }

        static const char* getName()
        {
            return "MobaConfigDBMeta";
        }

        static const char* getMd5Sum()
        {
            return "0fb322fb7d0670d0d2485340276272fa";
        }

        static const char* getTdrVersion()
        {
            return "2.5.0, build at 20111124";
        }
};


}
#endif
